In [ ]:
%pip install numba -q
%pip install engineering-notation -q
%pip install opencv-contrib-python -q
%pip install argcomplete -q
%pip install dv-processing -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.2/24.2 MB 83.5 MB/s eta 0:00:00

In [ ]:
!git clone https://github.com/SensorsINI/v2e
%cd /content/v2e
#!python setup.py develop
%pip install .
!mkdir input
%cd /content/
%pwd

Cloning into 'v2e'...
remote: Enumerating objects: 3227, done.
remote: Counting objects: 100% (1201/1201), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 3227 (delta 1156), reused 1102 (delta 1102), pack-reused 2026 (from 1)
Receiving objects: 100% (3227/3227), 34.25 MiB | 14.15 MiB/s, done.
Resolving deltas: 100% (2385/2385), done.
/content/v2e
Processing /content/v2e
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.12/dist-packages (from v2e==1.5.1) (2.0.2)
Requirement already satisfied: argcomplete in /usr/local/lib/python3.12/dist-packages (from v2e==1.5.1) (3.6.3)
Requirement already satisfied: engineering-notation in /usr/local/lib/python3.12/dist-packages (from v2e==1.5.1) (0.13.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from v2e==1.5.1) (4.67.3)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.12/dist-packages (from v2e==1.5.1) (4.13.0.92)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from v2e==1.5.1) (3.16.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from v2e==1.5.1) (2.10.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from v2e==1.5.1) (0.25.0+cu128)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from v2e==1.5.1) (0.60.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from v2e==1.5.1) (3.10.0)
Collecting plyer (from v2e==1.5.1)
  Downloading plyer-2.1.0-py2.py3-none-any.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 2.1 MB/s eta 0:00:00
Collecting screeninfo (from v2e==1.5.1)
  Downloading screeninfo-0.8.1-py3-none-any.whl.metadata (2.9 kB)
Collecting easygui (from v2e==1.5.1)
  Downloading easygui-0.98.3-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.12/dist-packages (from v2e==1.5.1) (0.25.2)
Requirement already satisfied: dv_processing in /usr/local/lib/python3.12/dist-packages (from v2e==1.5.1) (2.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->v2e==1.5.1) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->v2e==1.5.1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->v2e==1.5.1) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->v2e==1.5.1) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->v2e==1.5.1) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->v2e==1.5.1) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->v2e==1.5.1) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->v2e==1.5.1) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba->v2e==1.5.1) (0.43.0)
Requirement already satisfied: scipy>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image->v2e==1.5.1) (1.16.3)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-image->v2e==1.5.1) (3.6.1)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.12/dist-packages (from scikit-image->v2e==1.5.1) (2.37.3)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image->v2e==1.5.1) (2026.3.3)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image->v2e==1.5.1) (0.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->v2e==1.5.1) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->v2e==1.5.1) (1.5.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->v2e==1.5.1) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->v2e==1.5.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->v2e==1.5.1) (3.0.3)
Downloading easygui-0.98.3-py2.py3-none-any.whl (92 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.7/92.7 kB 5.4 MB/s eta 0:00:00
Downloading plyer-2.1.0-py2.py3-none-any.whl (142 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.3/142.3 kB 8.7 MB/s eta 0:00:00
Downloading screeninfo-0.8.1-py3-none-any.whl (12 kB)
Building wheels for collected packages: v2e
  Building wheel for v2e (setup.py) ... done
  Created wheel for v2e: filename=v2e-1.5.1-py3-none-any.whl size=116998 sha256=a44f4ef2750dfe4c208b86c912190ffa702ad09e42697c91c34dca2787b2ab5a
  Stored in directory: /tmp/pip-ephem-wheel-cache-cd4wyhd_/wheels/f4/f3/51/80837a929df608ceb06a5ecdb5f272f60a25522cfd8be8913d
Successfully built v2e
Installing collected packages: plyer, easygui, screeninfo, v2e
Successfully installed easygui-0.98.3 plyer-2.1.0 screeninfo-0.8.1 v2e-1.5.1
/content

'/content'

In [ ]:
import gdown
import os
from tqdm.notebook import tqdm
import shutil
import cv2
import pandas as pd
import numpy as np
from PIL import Image
import h5py
import pandas as pd
import subprocess


os.makedirs('/content/v2e/input/', exist_ok=True)

url = 'https://drive.google.com/uc?id=1ETID_4xqLpRBrRo1aOT7Yphs3QqWR_fx'
output = '/content/v2e/input/SuperSloMo39.ckpt'
gdown.download(url, output, quiet=False)

Downloading...
From (original): https://drive.google.com/uc?id=1ETID_4xqLpRBrRo1aOT7Yphs3QqWR_fx
From (redirected): https://drive.google.com/uc?id=1ETID_4xqLpRBrRo1aOT7Yphs3QqWR_fx&confirm=t&uuid=d4d7cc8a-97bf-46d9-995e-2709a728998c
To: /content/v2e/input/SuperSloMo39.ckpt
100%|██████████| 158M/158M [00:07<00:00, 20.0MB/s]

'/content/v2e/input/SuperSloMo39.ckpt'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Single video

In [ ]:
seq = 'bolt_1s'
initials = 'vlra'

In [ ]:
os.makedirs('/content/video', exist_ok=True)
shutil.copy(f'/content/drive/MyDrive/Diploma_project/own_videos/{initials}/28.03.2026/mp4/{seq}.mp4', '/content/video')

In [ ]:
#@title In the file explorer, right click the video file, and then click "Copy Path". Then, paste the path here: { run: "auto", vertical-output: true }
video_path = f"/content/video/{seq}.mp4" #@param {type:"string"}

import os
if video_path != "" and os.path.isfile(video_path):
    display("The chosen video file: {}".format(video_path))
else:
    print("The file path is empty or invalid, choose a file")

In [ ]:
# play the sample video, you can ignore it, support both AVI and MP4
# you can ignore this if you don't need
if ".avi" in video_path:
    !ffmpeg -y -i $video_path /tmp/output.mp4 -loglevel quiet
else:
    !cp $video_path /tmp/output.mp4

from IPython.display import HTML
from base64 import b64encode
mp4 = open("/tmp/output.mp4",'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML("<video controls src={} width=50%/>".format(data_url))

In [ ]:
cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    raise ValueError(f"Cannot open video: {video_path}")

fps = cap.get(cv2.CAP_PROP_FPS)
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
duration_sec = frame_count / fps if fps > 0 else 0

print(f"FPS: {fps}")
print(f"Frame count: {frame_count}")
print(f"Duration: {duration_sec:.2f} sec")

cap.release()

In [ ]:
#@title **Configure V2E Options** { run: "auto", vertical-output: true, display-mode: "both" }
#@markdown The full documentation is here: https://github.com/SensorsINI/v2e#render-emulated-dvs-events-from-conventional-video

#@markdown This GUI supports only common use configs, for finer control, please check the v2e documentation and edit the code below.

#@markdown ---
#@markdown ## Output Options

output_folder = "/content/v2e-output" #@param {type:"string"}
#@markdown - folder to store outputs. (default: v2e-output)
overwrite = True #@param {type:"boolean"}
#@markdown - overwrites files in existing folder (checks existence of non-empty output_folder). (default: True)
unique_output_folder = False #@param {type:"boolean"}
#@markdown - makes unique output folder based on output_folder, e.g. output1 (if non-empty output_folder already exists) (default: False)
out_filename = "events.h5" #@param {type:"string"}
#@markdown - Output DVS events as hdf5 event database.
davis_output = True #@param {type:"boolean"}
#@markdown - If also save frames in HDF5. (default: False)

#@markdown ### Output DVS Video Options
skip_video_output = False #@param {type:"boolean"}
#@markdown - Skip producing video outputs, including the original video, SloMo video, and DVS video (default: False)
dvs_exposure = f"duration {1/fps:.3f}" #@param {type:"string"}
#@markdown - Mode to finish DVS frame event integration: duration time: Use fixed accumulation time in seconds, e.g. --dvs_exposure duration .005; count n: Count n events per frame, -dvs_exposure count 5000; area_event N M: frame ends when any area of M x M pixels fills with N events, -dvs_exposure area_count 500 64 (default: duration 0.01)
output_mode = "dvs346" #@param ["dvs128", "dvs240", "dvs346", "dvs640", "dvs1024"]
#@markdown - This option sets the output size of the v2e. Supported models: "dvs128" (128x128), "dvs240" (240x180), "dvs346" (346x260), "dvs640" (640x480), "dvs1024" (1024x768).

#@markdown ---

#@markdown ## Input Options
input_frame_rate = 30 #@param {type:"number"}
#@markdown - Manually define the video frame rate when the video is presented as a list of image files. When the input video is a video file, this option will be ignored.
input_slowmotion_factor =  1#@param {type:"number"}
#@markdown - Sets the known slow-motion factor of the input video, i.e. how much the video is slowed down, i.e., the ratio of shooting frame rate to playback frame rate. input_slowmotion_factor<1 for sped-up video and input_slowmotion_factor>1 for slowmotion video.If an input video is shot at 120fps yet is presented as a 30fps video (has specified playback frame rate of 30Hz, according to file's FPS setting), then set --input_slowdown_factor=4.It means that each input frame represents (1/30)/4 s=(1/120)s.If input is video with intended frame intervals of 1ms that is in AVI file with default 30 FPS playback spec, then use ((1/30)s)*(1000Hz)=33.33333. (default: 1.0)

#@markdown ---

#@markdown ## DVS Time Resolution Options
disable_slomo = False #@param {type:"boolean"}
#@markdown - Disables slomo interpolation; the output DVS events will have exactly the timestamp resolution of the source video (which is perhaps modified by --input_slowmotion_factor). (default: False)
timestamp_resolution = 0.001 #@param {type:"number"}
#@markdown - (Ignored by --disable_slomo.) Desired DVS timestamp resolution in seconds; determines slow motion upsampling factor; the video will be upsampled from source fps to achieve the at least this timestamp resolution.I.e. slowdown_factor = (1/fps)/timestamp_resolution; using a high resolution e.g. of 1ms will result in slow rendering since it will force high upsampling ratio. Can be combind with --auto_timestamp_resolution to limit upsampling to a maximum limit value. (default: None)
auto_timestamp_resolution = True #@param {type:"boolean"}
#@markdown - (Ignored by --disable_slomo.) If True (default), upsampling_factor is automatically determined to limit maximum movement between frames to 1 pixel. If False, --timestamp_resolution sets the upsampling factor for input video. Can be combined with --timestamp_resolution to ensure DVS events have at most some resolution. (default: False)

# This is the SloMo model path
slomo_model = "/content/v2e/input/SuperSloMo39.ckpt"

#@markdown ---

#@markdown ## DVS Model Options
condition = "Clean" #@param ["Custom", "Clean", "Noisy"]
#@markdown - Custom: Use following slidebar to adjust your DVS model.
#@markdown - Clean: a preset DVS model, generate clean events, without non-idealities.
#@markdown - Noisy: a preset DVS model, generate noisy events.

thres = 0.2 #@param {type:"slider", min:0.05, max:1, step:0.01}
#@markdown - threshold in log_e intensity change to trigger a positive/negative event. (default: 0.2)
sigma = 0.03 #@param {type:"slider", min:0.01, max:0.25, step:0.001}
#@markdown - 1-std deviation threshold variation in log_e intensity change. (default: 0.03)
cutoff_hz = 200 #@param {type:"slider", min:0, max:300, step:1}
#@markdown - photoreceptor first-order IIR lowpass filter cutoff-off 3dB frequency in Hz - see https://ieeexplore.ieee.org/document/4444573 (default: 300)
leak_rate_hz = 5.18 #@param {type:"slider", min:0, max:100, step:0.01}
#@markdown - leak event rate per pixel in Hz - see https://ieeexplore.ieee.org/abstract/document/7962235 (default: 0.01)
shot_noise_rate_hz = 2.716 #@param {type:"slider", min:0, max:100, step:0.001}
#@markdown - Temporal noise rate of ON+OFF events in darkest parts of scene; reduced in brightest parts. (default: 0.001)

if condition == "Clean":
    thres = 0.2
    sigma = 0.02
    cutoff_hz = 0
    leak_rate_hz = 0
    shot_noise_rate_hz = 0
elif condition == "Noisy":
    thres = 0.2
    sigma_thres = 0.05
    cutoff_hz = 30
    leak_rate_hz = 0.1
    shot_noise_rate_hz = 5

#@markdown ---

v2e_command = ["v2e"]

# set the input folder
# the video_path can be a video file or a folder of images
v2e_command += ["-i", video_path]

# set the output folder
v2e_command += ["-o", output_folder]

# if the output will rewrite the previous output
if overwrite:
    v2e_command.append("--overwrite")

# if there the output folder is unique
v2e_command += ["--unique_output_folder", "{}".format(unique_output_folder).lower()]

# set output configs, for the sake of this tutorial, let's just output HDF5 record
if davis_output:
    v2e_command += ["--davis_output"]
v2e_command += ["--dvs_h5", out_filename]
v2e_command += ["--dvs_aedat2", "None"]
v2e_command += ["--dvs_text", "None"]

# in Colab, let's say no preview
v2e_command += ["--no_preview"]

# if skip video output
if skip_video_output:
    v2e_command += ["--skip_video_output"]
else:
    # set DVS video rendering params
    dvs_exposure = f"duration {1/input_frame_rate:.6f}"
    v2e_command += ["--dvs_exposure", dvs_exposure]

# set slomo related options
v2e_command += ["--input_frame_rate", "{}".format(input_frame_rate)]
v2e_command += ["--input_slowmotion_factor", "{}".format(input_slowmotion_factor)]

# set slomo data
if disable_slomo:
    v2e_command += ["--disable_slomo"]
    v2e_command += ["--auto_timestamp_resolution", "false"]
else:
    v2e_command += ["--slomo_model", slomo_model]
    if auto_timestamp_resolution:
        v2e_command += ["--auto_timestamp_resolution", "{}".format(auto_timestamp_resolution).lower()]
    else:
        v2e_command += ["--timestamp_resolution", "{}".format(timestamp_resolution)]

# threshold
v2e_command += ["--pos_thres", "{}".format(thres)]
v2e_command += ["--neg_thres", "{}".format(thres)]

# sigma
v2e_command += ["--sigma_thres", "{}".format(sigma)]

# DVS non-idealities
v2e_command += ["--cutoff_hz", "{}".format(cutoff_hz)]
v2e_command += ["--leak_rate_hz", "{}".format(leak_rate_hz)]
v2e_command += ["--shot_noise_rate_hz", "{}".format(shot_noise_rate_hz)]

# append output mode
v2e_command += [f"--{output_mode}"]

# Final v2e command

final_v2e_command = " ".join(v2e_command)

print("The Final v2e command:")
display(final_v2e_command)

In [ ]:
!$final_v2e_command

In [ ]:
#Make csv

h5_path = "/content/v2e-output/events.h5"
csv_path = "/content/v2e-output/events.csv"

with h5py.File(h5_path, "r") as f:
    events = f["events"][:]

df = pd.DataFrame(events, columns=["t", "x", "y", "p"])
df.to_csv(csv_path, index=False)

print(f"Saved: {csv_path}")

In [ ]:
video_path = "/content/v2e-output/video_orig.avi"
output_dir = "/content/v2e-output/aps"

os.makedirs(output_dir, exist_ok=True)

cap = cv2.VideoCapture(video_path)
if not cap.isOpened():
    raise ValueError(f"Cannot open video: {video_path}")

fps = cap.get(cv2.CAP_PROP_FPS)
frame_count = 0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_path = os.path.join(output_dir, f"{frame_count + 1:04d}.png")
    cv2.imwrite(frame_path, frame)
    frame_count += 1

cap.release()

print("Detected FPS:", fps)
print("Saved frames:", frame_count)
print("Output folder:", output_dir)

In [ ]:
def create_frames_from_csv(csv_path, output_dir, aps_dir, width=346, height=260):
    os.makedirs(output_dir, exist_ok=True)

    # Determine the number of frames from the APS folder
    aps_frames = sorted([
        f for f in os.listdir(aps_dir)
        if f.lower().endswith(('.png', '.jpg', '.jpeg'))
    ])
    num_frames = len(aps_frames)
    if num_frames == 0:
        raise ValueError(f"No frames found in '{aps_dir}'.")
    print(f"APS frames found: {num_frames}")

    # Read events from CSV
    df = pd.read_csv(csv_path)
    t_all = df['t'].to_numpy()
    x_all = df['x'].to_numpy()
    y_all = df['y'].to_numpy()
    p_all = df['p'].to_numpy()

    # Divide the time range evenly into num_frames intervals
    t_start = t_all[0]
    t_end   = t_all[-1]
    frame_boundaries = np.linspace(t_start, t_end, num_frames + 1)

    # Find the event end index for each frame boundary
    event_end_idxs = np.searchsorted(t_all, frame_boundaries[1:], side="right")

    start_idx = 0

    for frame_idx, end_idx in enumerate(tqdm(event_end_idxs, desc="Saving DVS frames")):
        xs = x_all[start_idx:end_idx]
        ys = y_all[start_idx:end_idx]
        ps = p_all[start_idx:end_idx]

        frame = np.zeros((height, width), dtype=np.int16)

        # Filter out events outside image bounds
        valid = (xs >= 0) & (xs < width) & (ys >= 0) & (ys < height)
        xs = xs[valid]
        ys = ys[valid]
        ps = ps[valid]

        vals = np.where(ps, 1, -1).astype(np.int16, copy=False)
        np.add.at(frame, (ys, xs), vals)

        # Visualize ON/OFF events as red/blue on a white background
        img = np.full((height, width, 3), 255, dtype=np.uint8)
        img[frame > 0] = (220, 30, 30)   # ON  → red
        img[frame < 0] = (30, 30, 200)   # OFF → blue

        # Name the output file to match the corresponding APS frame
        file_name = aps_frames[frame_idx]
        Image.fromarray(img).save(os.path.join(output_dir, file_name))

        start_idx = end_idx




# Run
create_frames_from_csv(
    csv_path="/content/v2e-output/events.csv",
    output_dir="/content/v2e-output/dvs",
    aps_dir="/content/v2e-output/aps",
    width=346,
    height=260
)

In [ ]:
!ffmpeg -y -framerate 30 -i /content/v2e-output/aps/%04d.png -framerate 30 -i /content/v2e-output/dvs/%04d.png -filter_complex hstack -c:v libx264 -pix_fmt yuv420p /content/v2e-output/aps_dvs.mp4

In [ ]:
!rm -rf '/content/v2e-output/dvs-video-frame_times.txt'
!rm -rf '/content/v2e-output/dvs-video.avi'
!rm -rf '/content/v2e-output/events.h5'
!rm -rf '/content/v2e-output/v2e-args.txt'
!rm -rf '/content/v2e-output/video_orig.avi'
!rm -rf '/content/v2e-output/video_slomo.avi'

In [ ]:
%cd /content/v2e-output
!zip -r /content/{seq}.zip .

import shutil
shutil.copy(
    f"/content/{seq}.zip",
    f"/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/{initials}/{seq}.zip"
)

In [ ]:
base = f"/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/{initials}"
os.environ['SEQ'] = seq
os.environ['BASE'] = base

!unzip "$BASE/$SEQ.zip" -d "$BASE/$SEQ"

# Cycle

In [ ]:
initials = 'seya'

In [ ]:
sequences = ['key_1:2hz', 'key_1hz', 'key_2hz', 'lamp_1:2hz', 'lamp_1hz', 'lamp_2hz',
             'repeater_1:2hz', 'repeater_1hz', 'repeater_2hz', 'soap_1:2hz',
             'soap_1hz', 'soap_2hz', 'white_1:2hz', 'white_1hz', 'white_2hz']

In [ ]:
def create_frames_from_csv(csv_path, output_dir, aps_dir, width=346, height=260):
        os.makedirs(output_dir, exist_ok=True)

        aps_frames = sorted([
            f for f in os.listdir(aps_dir)
            if f.lower().endswith(('.png', '.jpg', '.jpeg'))
        ])
        num_frames = len(aps_frames)
        if num_frames == 0:
            raise ValueError(f"No frames found in '{aps_dir}'.")
        print(f"APS frames found: {num_frames}")

        df = pd.read_csv(csv_path)
        t_all = df['t'].to_numpy()
        x_all = df['x'].to_numpy()
        y_all = df['y'].to_numpy()
        p_all = df['p'].to_numpy()

        t_start = t_all[0]
        t_end   = t_all[-1]
        frame_boundaries = np.linspace(t_start, t_end, num_frames + 1)

        event_end_idxs = np.searchsorted(t_all, frame_boundaries[1:], side="right")

        start_idx = 0

        for frame_idx, end_idx in enumerate(tqdm(event_end_idxs, desc="Saving DVS frames")):
            xs = x_all[start_idx:end_idx]
            ys = y_all[start_idx:end_idx]
            ps = p_all[start_idx:end_idx]

            frame = np.zeros((height, width), dtype=np.int16)

            valid = (xs >= 0) & (xs < width) & (ys >= 0) & (ys < height)
            xs = xs[valid]
            ys = ys[valid]
            ps = ps[valid]

            vals = np.where(ps, 1, -1).astype(np.int16, copy=False)
            np.add.at(frame, (ys, xs), vals)

            img = np.full((height, width, 3), 255, dtype=np.uint8)
            img[frame > 0] = (220, 30, 30)
            img[frame < 0] = (30, 30, 200)

            file_name = aps_frames[frame_idx]
            Image.fromarray(img).save(os.path.join(output_dir, file_name))

            start_idx = end_idx

In [ ]:
for seq in tqdm(sequences):
    %cd /content
    !rm -rf '/content/v2e-output'

    os.makedirs('/content/video', exist_ok=True)
    shutil.copy(f'/content/drive/MyDrive/Diploma_project/own_videos/{initials}/{seq}.mp4', '/content/video')

    video_path = f"/content/video/{seq}.mp4"

    if video_path != "" and os.path.isfile(video_path):
        display("The chosen video file: {}".format(video_path))
    else:
        print("The file path is empty or invalid, choose a file")

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise ValueError(f"Cannot open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    duration_sec = frame_count / fps if fps > 0 else 0

    print(f"FPS: {fps}")
    print(f"Frame count: {frame_count}")
    print(f"Duration: {duration_sec:.2f} sec")

    cap.release()

    output_folder = "/content/v2e-output"
    overwrite = True
    unique_output_folder = False
    out_filename = "events.h5"
    davis_output = True
    skip_video_output = False
    dvs_exposure = f"duration {1/fps:.3f}"
    output_mode = "dvs346"
    input_frame_rate = 30
    input_slowmotion_factor = 1
    disable_slomo = False
    timestamp_resolution = 0.001
    auto_timestamp_resolution = True
    slomo_model = "/content/v2e/input/SuperSloMo39.ckpt"
    condition = "Clean"
    thres = 0.2
    sigma = 0.03
    cutoff_hz = 200
    leak_rate_hz = 5.18
    shot_noise_rate_hz = 2.716

    if condition == "Clean":
        thres = 0.2
        sigma = 0.02
        cutoff_hz = 0
        leak_rate_hz = 0
        shot_noise_rate_hz = 0
    elif condition == "Noisy":
        thres = 0.2
        sigma_thres = 0.05
        cutoff_hz = 30
        leak_rate_hz = 0.1
        shot_noise_rate_hz = 5

    v2e_command = ["v2e"]
    v2e_command += ["-i", video_path]
    v2e_command += ["-o", output_folder]

    if overwrite:
        v2e_command.append("--overwrite")

    v2e_command += ["--unique_output_folder", "{}".format(unique_output_folder).lower()]

    if davis_output:
        v2e_command += ["--davis_output"]
    v2e_command += ["--dvs_h5", out_filename]
    v2e_command += ["--dvs_aedat2", "None"]
    v2e_command += ["--dvs_text", "None"]
    v2e_command += ["--no_preview"]

    if skip_video_output:
        v2e_command += ["--skip_video_output"]
    else:
        dvs_exposure = f"duration {1/input_frame_rate:.6f}"
        v2e_command += ["--dvs_exposure", dvs_exposure]

    v2e_command += ["--input_frame_rate", "{}".format(input_frame_rate)]
    v2e_command += ["--input_slowmotion_factor", "{}".format(input_slowmotion_factor)]

    if disable_slomo:
        v2e_command += ["--disable_slomo"]
        v2e_command += ["--auto_timestamp_resolution", "false"]
    else:
        v2e_command += ["--slomo_model", slomo_model]
        if auto_timestamp_resolution:
            v2e_command += ["--auto_timestamp_resolution", "{}".format(auto_timestamp_resolution).lower()]
        else:
            v2e_command += ["--timestamp_resolution", "{}".format(timestamp_resolution)]

    v2e_command += ["--pos_thres", "{}".format(thres)]
    v2e_command += ["--neg_thres", "{}".format(thres)]
    v2e_command += ["--sigma_thres", "{}".format(sigma)]
    v2e_command += ["--cutoff_hz", "{}".format(cutoff_hz)]
    v2e_command += ["--leak_rate_hz", "{}".format(leak_rate_hz)]
    v2e_command += ["--shot_noise_rate_hz", "{}".format(shot_noise_rate_hz)]
    v2e_command += [f"--{output_mode}"]

    final_v2e_command = " ".join(v2e_command)
    print("The Final v2e command:")
    display(final_v2e_command)

    !$final_v2e_command

    # Convert h5 events to csv
    h5_path  = "/content/v2e-output/events.h5"
    csv_path = "/content/v2e-output/events.csv"

    with h5py.File(h5_path, "r") as f:
        events = f["events"][:]

    df = pd.DataFrame(events, columns=["t", "x", "y", "p"])
    df.to_csv(csv_path, index=False)
    print(f"Saved: {csv_path}")

    # Extract APS frames
    video_path = "/content/v2e-output/video_orig.avi"
    output_dir = "/content/v2e-output/aps"
    os.makedirs(output_dir, exist_ok=True)

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise ValueError(f"Cannot open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_count = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break
        frame_path = os.path.join(output_dir, f"{frame_count + 1:04d}.png")
        cv2.imwrite(frame_path, frame)
        frame_count += 1

    cap.release()
    print("Detected FPS:", fps)
    print("Saved frames:", frame_count)
    print("Output folder:", output_dir)

    # Generate DVS frames
    create_frames_from_csv(
        csv_path="/content/v2e-output/events.csv",
        output_dir="/content/v2e-output/dvs",
        aps_dir="/content/v2e-output/aps",
        width=346,
        height=260
    )

    !ffmpeg -y -framerate 30 -i /content/v2e-output/aps/%04d.png -framerate 30 -i /content/v2e-output/dvs/%04d.png -filter_complex hstack -c:v libx264 -pix_fmt yuv420p /content/v2e-output/aps_dvs.mp4

    !rm -rf '/content/v2e-output/dvs-video-frame_times.txt'
    !rm -rf '/content/v2e-output/dvs-video.avi'
    !rm -rf '/content/v2e-output/events.h5'
    !rm -rf '/content/v2e-output/v2e-args.txt'
    !rm -rf '/content/v2e-output/video_orig.avi'
    !rm -rf '/content/v2e-output/video_slomo.avi'

    %cd /content/v2e-output
    !zip -r /content/{seq}.zip .

    shutil.copy(
        f"/content/{seq}.zip",
        f"/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/{initials}/{seq}.zip"
    )

    base = f"/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/{initials}"
    os.environ['SEQ'] = seq
    os.environ['BASE'] = base
    !unzip "$BASE/$SEQ.zip" -d "$BASE/$SEQ"

    print(f"✓ Done: {seq}")

  0%|          | 0/2 [00:00<?, ?it/s]

/content

'The chosen video file: /content/video/spring_3s.MOV'

FPS: 30.005102908657936
Frame count: 294
Duration: 9.80 sec
The Final v2e command:

'v2e -i /content/video/spring_3s.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/spring_3s.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/spring_3s.MOV
INFO:v2e:Input video frame rate 30.005102908657936Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/spring_3s.MOV has total 294 frames with total duration 9.77s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 294 frames 0 to 293
(From 0.0s to 9.766666666666667s, duration 9.766666666666667s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 293.0 frames with duration 9.77s and playback duration 9.77s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 293 from video input
INFO:v2e:Input video /content/video/spring_3s.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 294 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/294 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 294/294 [00:10<00:00, 28.98fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpjiqpacqn
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 37 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/37 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 12
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   3% 1/37 [00:02<01:44,  2.91s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 11
slomo-interp:   5% 2/37 [00:05<01:34,  2.70s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 8
slomo-interp: 100% 37/37 [04:43<00:00,  7.66s/ batch of 8 fr]
write-orig-avi: 100% 294/294 [00:00<00:00, 613.69fr/s]
write-slomo-vid: 100% 10400/10400 [00:21<00:00, 479.51fr/s]
INFO:v2ecore.slomo:Wrote 10400 frames and returning 10400 frame times.
Average upsampling factor= 35.2
INFO:v2e:SloMo average upsampling factor=35.22; average DVS timestamp resolution=946.53us
INFO:v2e:*** Stage 3/3: emulating DVS events from 10400 frames
dvs:   0% 6/10400 [00:00<02:57, 58.43fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs: 100% 10400/10400 [03:40<00:00, 47.19fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 292 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 294 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 10400 frames
INFO:v2e:generated total 19.77M events (9.60M on, 10.17M off)
INFO:v2e:Avg event rate for N=89960 px and total time =9.767 s
	Total: 2.02MHz (983.07kHz on, 1.04MHz off)
	Per pixel:  22.50Hz (10.93Hz on, 11.58Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 588 frames in 537.76s (1.09fr/s)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 292 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 294 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 10400 frames
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 294
Output folder: /content/v2e-output/aps
APS frames found: 294

Saving DVS frames:   0%|          | 0/294 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:09.80, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:09.80, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x5c7ea9368840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x5c7ea9371300] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x5c7ea9733600] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5c7ea9733600] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5c7ea9733600] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  294 fps= 37 q=-1.0 Lsize=    6463kB time=00:00:09.70 bitrate=5458.4kbits/s speed=1.23x
video:6459kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.066905%
[libx264 @ 0x5c7ea9733600] frame I:6     Avg QP:24.81  size: 24795
[libx264 @ 0x5c7ea9733600] frame P:79    Avg QP:28.92  size: 24955
[libx264 @ 0x5c7ea9733600] frame B:209   Avg QP:31.86  size: 21497
[libx264 @ 0x5c7ea9733600] consecutive B-frames:  4.8%  0.7%  2.0% 92.5%
[libx264 @ 0x5c7ea9733600] mb I  I16..4:  7.6% 56.8% 35.5%
[libx264 @ 0x5c7ea9733600] mb P  I16..4:  4.2% 13.3% 36.2%  P16..4: 22.5% 11.4%  6.4%  0.0%  0.0%    skip: 6.1%
[libx264 @ 0x5c7ea9733600] mb B  I16..4:  5.4%  2.2% 19.2%  B16..8: 27.9% 10.4%  6.5%  direct: 2.5%  skip:25.8%  L0:43.2% L1:42.3% BI:14.5%
[libx264 @ 0x5c7ea9733600] 8x8 transform intra:17.7% inter:41.2%
[libx264 @ 0x5c7ea9733600] coded y,uvDC,uvAC intra: 74.4% 75.8% 73.4% inter: 27.0% 16.9% 13.1%
[libx264 @ 0x5c7ea9733600] i16 v,h,dc,p: 28% 12% 54%  5%
[libx264 @ 0x5c7ea9733600] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 43% 11% 30%  3%  2%  3%  2%  4%  2%
[libx264 @ 0x5c7ea9733600] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 26% 14% 30%  6%  4%  6%  4%  6%  4%
[libx264 @ 0x5c7ea9733600] i8c dc,h,v,p: 62%  9% 23%  5%
[libx264 @ 0x5c7ea9733600] Weighted P-Frames: Y:21.5% UV:16.5%
[libx264 @ 0x5c7ea9733600] ref P L0: 44.5% 29.8% 17.2%  7.6%  0.9%
[libx264 @ 0x5c7ea9733600] ref B L0: 80.5% 14.9%  4.6%
[libx264 @ 0x5c7ea9733600] ref B L1: 91.1%  8.9%
[libx264 @ 0x5c7ea9733600] kb/s:5398.52
/content/v2e-output
  adding: aps/ (stored 0%)
  adding: aps/0146.png (deflated 16%)
  adding: aps/0204.png (deflated 15%)
  adding: aps/0275.png (deflated 15%)
  adding: aps/0081.png (deflated 15%)
  adding: aps/0025.png (deflated 17%)
  adding: aps/0179.png (deflated 16%)
  adding: aps/0231.png (deflated 16%)
  adding: aps/0134.png (deflated 16%)
  adding: aps/0106.png (deflated 16%)
  adding: aps/0042.png (deflated 17%)
  adding: aps/0004.png (deflated 15%)
  adding: aps/0142.png (deflated 15%)
  adding: aps/0018.png (deflated 15%)
  adding: aps/0057.png (deflated 16%)
  adding: aps/0039.png (deflated 17%)
  adding: aps/0150.png (deflated 16%)
  adding: aps/0016.png (deflated 15%)
  adding: aps/0092.png (deflated 16%)
  adding: aps/0046.png (deflated 16%)
  adding: aps/0087.png (deflated 18%)
  adding: aps/0014.png (deflated 16%)
  adding: aps/0226.png (deflated 16%)
  adding: aps/0105.png (deflated 16%)
  adding: aps/0170.png (deflated 19%)
  adding: aps/0256.png (deflated 15%)
  adding: aps/0010.png (deflated 15%)
  adding: aps/0200.png (deflated 15%)
  adding: aps/0164.png (deflated 17%)
  adding: aps/0125.png (deflated 15%)
  adding: aps/0082.png (deflated 15%)
  adding: aps/0183.png (deflated 17%)
  adding: aps/0119.png (deflated 16%)
  adding: aps/0274.png (deflated 15%)
  adding: aps/0041.png (deflated 17%)
  adding: aps/0286.png (deflated 16%)
  adding: aps/0137.png (deflated 16%)
  adding: aps/0270.png (deflated 16%)
  adding: aps/0277.png (deflated 17%)
  adding: aps/0167.png (deflated 16%)
  adding: aps/0130.png (deflated 15%)
  adding: aps/0251.png (deflated 15%)
  adding: aps/0189.png (deflated 15%)
  adding: aps/0213.png (deflated 16%)
  adding: aps/0198.png (deflated 16%)
  adding: aps/0223.png (deflated 17%)
  adding: aps/0168.png (deflated 16%)
  adding: aps/0050.png (deflated 18%)
  adding: aps/0235.png (deflated 15%)
  adding: aps/0158.png (deflated 18%)
  adding: aps/0218.png (deflated 20%)
  adding: aps/0242.png (deflated 17%)
  adding: aps/0239.png (deflated 16%)
  adding: aps/0215.png (deflated 15%)
  adding: aps/0281.png (deflated 16%)
  adding: aps/0224.png (deflated 17%)
  adding: aps/0157.png (deflated 18%)
  adding: aps/0110.png (deflated 16%)
  adding: aps/0253.png (deflated 16%)
  adding: aps/0120.png (deflated 16%)
  adding: aps/0108.png (deflated 16%)
  adding: aps/0043.png (deflated 16%)
  adding: aps/0085.png (deflated 22%)
  adding: aps/0245.png (deflated 16%)
  adding: aps/0094.png (deflated 15%)
  adding: aps/0240.png (deflated 18%)
  adding: aps/0027.png (deflated 15%)
  adding: aps/0069.png (deflated 16%)
  adding: aps/0186.png (deflated 15%)
  adding: aps/0214.png (deflated 15%)
  adding: aps/0263.png (deflated 15%)
  adding: aps/0260.png (deflated 16%)
  adding: aps/0266.png (deflated 18%)
  adding: aps/0064.png (deflated 17%)
  adding: aps/0174.png (deflated 16%)
  adding: aps/0261.png (deflated 16%)
  adding: aps/0072.png (deflated 16%)
  adding: aps/0003.png (deflated 16%)
  adding: aps/0141.png (deflated 15%)
  adding: aps/0123.png (deflated 16%)
  adding: aps/0293.png (deflated 17%)
  adding: aps/0090.png (deflated 16%)
  adding: aps/0221.png (deflated 17%)
  adding: aps/0088.png (deflated 16%)
  adding: aps/0153.png (deflated 15%)
  adding: aps/0232.png (deflated 17%)
  adding: aps/0145.png (deflated 17%)
  adding: aps/0203.png (deflated 15%)
  adding: aps/0051.png (deflated 17%)
  adding: aps/0019.png (deflated 15%)
  adding: aps/0209.png (deflated 16%)
  adding: aps/0001.png (deflated 16%)
  adding: aps/0068.png (deflated 16%)
  adding: aps/0097.png (deflated 19%)
  adding: aps/0250.png (deflated 15%)
  adding: aps/0259.png (deflated 16%)
  adding: aps/0208.png (deflated 17%)
  adding: aps/0161.png (deflated 17%)
  adding: aps/0104.png (deflated 17%)
  adding: aps/0100.png (deflated 17%)
  adding: aps/0011.png (deflated 14%)
  adding: aps/0032.png (deflated 16%)
  adding: aps/0191.png (deflated 15%)
  adding: aps/0062.png (deflated 19%)
  adding: aps/0192.png (deflated 15%)
  adding: aps/0067.png (deflated 16%)
  adding: aps/0184.png (deflated 17%)
  adding: aps/0013.png (deflated 16%)
  adding: aps/0172.png (deflated 17%)
  adding: aps/0140.png (deflated 16%)
  adding: aps/0197.png (deflated 16%)
  adding: aps/0219.png (deflated 19%)
  adding: aps/0169.png (deflated 20%)
  adding: aps/0193.png (deflated 18%)
  adding: aps/0022.png (deflated 16%)
  adding: aps/0084.png (deflated 17%)
  adding: aps/0074.png (deflated 19%)
  adding: aps/0054.png (deflated 17%)
  adding: aps/0229.png (deflated 18%)
  adding: aps/0083.png (deflated 16%)
  adding: aps/0147.png (deflated 16%)
  adding: aps/0171.png (deflated 18%)
  adding: aps/0070.png (deflated 16%)
  adding: aps/0199.png (deflated 16%)
  adding: aps/0071.png (deflated 16%)
  adding: aps/0063.png (deflated 18%)
  adding: aps/0058.png (deflated 16%)
  adding: aps/0265.png (deflated 17%)
  adding: aps/0075.png (deflated 18%)
  adding: aps/0272.png (deflated 16%)
  adding: aps/0139.png (deflated 15%)
  adding: aps/0052.png (deflated 16%)
  adding: aps/0029.png (deflated 15%)
  adding: aps/0095.png (deflated 15%)
  adding: aps/0247.png (deflated 16%)
  adding: aps/0133.png (deflated 17%)
  adding: aps/0024.png (deflated 16%)
  adding: aps/0138.png (deflated 16%)
  adding: aps/0152.png (deflated 15%)
  adding: aps/0129.png (deflated 15%)
  adding: aps/0268.png (deflated 18%)
  adding: aps/0201.png (deflated 15%)
  adding: aps/0225.png (deflated 17%)
  adding: aps/0252.png (deflated 15%)
  adding: aps/0283.png (deflated 15%)
  adding: aps/0115.png (deflated 15%)
  adding: aps/0059.png (deflated 17%)
  adding: aps/0091.png (deflated 16%)
  adding: aps/0093.png (deflated 16%)
  adding: aps/0166.png (deflated 16%)
  adding: aps/0044.png (deflated 16%)
  adding: aps/0098.png (deflated 18%)
  adding: aps/0009.png (deflated 15%)
  adding: aps/0246.png (deflated 16%)
  adding: aps/0116.png (deflated 15%)
  adding: aps/0202.png (deflated 15%)
  adding: aps/0175.png (deflated 16%)
  adding: aps/0077.png (deflated 17%)
  adding: aps/0238.png (deflated 16%)
  adding: aps/0023.png (deflated 15%)
  adding: aps/0257.png (deflated 15%)
  adding: aps/0178.png (deflated 16%)
  adding: aps/0020.png (deflated 15%)
  adding: aps/0107.png (deflated 16%)
  adding: aps/0230.png (deflated 17%)
  adding: aps/0065.png (deflated 17%)
  adding: aps/0236.png (deflated 16%)
  adding: aps/0111.png (deflated 16%)
  adding: aps/0101.png (deflated 16%)
  adding: aps/0180.png (deflated 15%)
  adding: aps/0228.png (deflated 16%)
  adding: aps/0113.png (deflated 15%)
  adding: aps/0012.png (deflated 15%)
  adding: aps/0076.png (deflated 17%)
  adding: aps/0036.png (deflated 15%)
  adding: aps/0049.png (deflated 21%)
  adding: aps/0031.png (deflated 16%)
  adding: aps/0117.png (deflated 15%)
  adding: aps/0290.png (deflated 18%)
  adding: aps/0237.png (deflated 16%)
  adding: aps/0289.png (deflated 19%)
  adding: aps/0278.png (deflated 16%)
  adding: aps/0282.png (deflated 16%)
  adding: aps/0089.png (deflated 16%)
  adding: aps/0078.png (deflated 17%)
  adding: aps/0109.png (deflated 17%)
  adding: aps/0114.png (deflated 15%)
  adding: aps/0079.png (deflated 17%)
  adding: aps/0126.png (deflated 15%)
  adding: aps/0216.png (deflated 16%)
  adding: aps/0294.png (deflated 17%)
  adding: aps/0148.png (deflated 16%)
  adding: aps/0118.png (deflated 15%)
  adding: aps/0040.png (deflated 17%)
  adding: aps/0035.png (deflated 15%)
  adding: aps/0210.png (deflated 16%)
  adding: aps/0264.png (deflated 19%)
  adding: aps/0276.png (deflated 15%)
  adding: aps/0269.png (deflated 16%)
  adding: aps/0127.png (deflated 15%)
  adding: aps/0066.png (deflated 16%)
  adding: aps/0144.png (deflated 15%)
  adding: aps/0258.png (deflated 15%)
  adding: aps/0288.png (deflated 16%)
  adding: aps/0284.png (deflated 16%)
  adding: aps/0112.png (deflated 15%)
  adding: aps/0007.png (deflated 15%)
  adding: aps/0159.png (deflated 16%)
  adding: aps/0033.png (deflated 16%)
  adding: aps/0285.png (deflated 16%)
  adding: aps/0195.png (deflated 17%)
  adding: aps/0206.png (deflated 18%)
  adding: aps/0227.png (deflated 16%)
  adding: aps/0132.png (deflated 15%)
  adding: aps/0279.png (deflated 13%)
  adding: aps/0055.png (deflated 16%)
  adding: aps/0262.png (deflated 15%)
  adding: aps/0155.png (deflated 15%)
  adding: aps/0249.png (deflated 16%)
  adding: aps/0008.png (deflated 15%)
  adding: aps/0254.png (deflated 16%)
  adding: aps/0211.png (deflated 15%)
  adding: aps/0102.png (deflated 16%)
  adding: aps/0207.png (deflated 17%)
  adding: aps/0053.png (deflated 16%)
  adding: aps/0060.png (deflated 16%)
  adding: aps/0136.png (deflated 15%)
  adding: aps/0185.png (deflated 17%)
  adding: aps/0194.png (deflated 17%)
  adding: aps/0248.png (deflated 15%)
  adding: aps/0149.png (deflated 16%)
  adding: aps/0205.png (deflated 19%)
  adding: aps/0255.png (deflated 15%)
  adding: aps/0233.png (deflated 16%)
  adding: aps/0026.png (deflated 16%)
  adding: aps/0196.png (deflated 16%)
  adding: aps/0096.png (deflated 17%)
  adding: aps/0061.png (deflated 20%)
  adding: aps/0021.png (deflated 15%)
  adding: aps/0030.png (deflated 16%)
  adding: aps/0128.png (deflated 15%)
  adding: aps/0086.png (deflated 18%)
  adding: aps/0176.png (deflated 16%)
  adding: aps/0121.png (deflated 17%)
  adding: aps/0243.png (deflated 17%)
  adding: aps/0162.png (deflated 18%)
  adding: aps/0273.png (deflated 15%)
  adding: aps/0038.png (deflated 17%)
  adding: aps/0173.png (deflated 16%)
  adding: aps/0156.png (deflated 15%)
  adding: aps/0048.png (deflated 16%)
  adding: aps/0217.png (deflated 20%)
  adding: aps/0017.png (deflated 15%)
  adding: aps/0080.png (deflated 16%)
  adding: aps/0099.png (deflated 17%)
  adding: aps/0212.png (deflated 16%)
  adding: aps/0103.png (deflated 16%)
  adding: aps/0267.png (deflated 18%)
  adding: aps/0160.png (deflated 17%)
  adding: aps/0165.png (deflated 16%)
  adding: aps/0234.png (deflated 16%)
  adding: aps/0190.png (deflated 15%)
  adding: aps/0034.png (deflated 16%)
  adding: aps/0182.png (deflated 17%)
  adding: aps/0241.png (deflated 18%)
  adding: aps/0143.png (deflated 15%)
  adding: aps/0222.png (deflated 17%)
  adding: aps/0291.png (deflated 17%)
  adding: aps/0135.png (deflated 16%)
  adding: aps/0037.png (deflated 18%)
  adding: aps/0045.png (deflated 16%)
  adding: aps/0271.png (deflated 16%)
  adding: aps/0005.png (deflated 15%)
  adding: aps/0187.png (deflated 16%)
  adding: aps/0292.png (deflated 17%)
  adding: aps/0122.png (deflated 16%)
  adding: aps/0188.png (deflated 15%)
  adding: aps/0002.png (deflated 16%)
  adding: aps/0028.png (deflated 14%)
  adding: aps/0244.png (deflated 18%)
  adding: aps/0287.png (deflated 16%)
  adding: aps/0280.png (deflated 13%)
  adding: aps/0220.png (deflated 18%)
  adding: aps/0006.png (deflated 15%)
  adding: aps/0154.png (deflated 15%)
  adding: aps/0177.png (deflated 15%)
  adding: aps/0056.png (deflated 16%)
  adding: aps/0015.png (deflated 16%)
  adding: aps/0073.png (deflated 20%)
  adding: aps/0124.png (deflated 15%)
  adding: aps/0131.png (deflated 15%)
  adding: aps/0151.png (deflated 15%)
  adding: aps/0163.png (deflated 18%)
  adding: aps/0181.png (deflated 19%)
  adding: aps/0047.png (deflated 16%)
  adding: dvs/ (stored 0%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0204.png (stored 0%)
  adding: dvs/0275.png (stored 0%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0231.png (stored 0%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0042.png (stored 0%)
  adding: dvs/0004.png (stored 0%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0057.png (stored 0%)
  adding: dvs/0039.png (stored 0%)
  adding: dvs/0150.png (stored 0%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0092.png (stored 0%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0014.png (stored 0%)
  adding: dvs/0226.png (stored 0%)
  adding: dvs/0105.png (stored 0%)
  adding: dvs/0170.png (stored 0%)
  adding: dvs/0256.png (stored 0%)
  adding: dvs/0010.png (stored 0%)
  adding: dvs/0200.png (stored 0%)
  adding: dvs/0164.png (stored 0%)
  adding: dvs/0125.png (stored 0%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0183.png (stored 0%)
  adding: dvs/0119.png (stored 0%)
  adding: dvs/0274.png (stored 0%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0286.png (stored 0%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0270.png (stored 0%)
  adding: dvs/0277.png (stored 0%)
  adding: dvs/0167.png (stored 0%)
  adding: dvs/0130.png (stored 0%)
  adding: dvs/0251.png (stored 0%)
  adding: dvs/0189.png (stored 0%)
  adding: dvs/0213.png (stored 0%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0223.png (stored 0%)
  adding: dvs/0168.png (stored 0%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0235.png (stored 0%)
  adding: dvs/0158.png (stored 0%)
  adding: dvs/0218.png (deflated 2%)
  adding: dvs/0242.png (stored 0%)
  adding: dvs/0239.png (stored 0%)
  adding: dvs/0215.png (stored 0%)
  adding: dvs/0281.png (stored 0%)
  adding: dvs/0224.png (stored 0%)
  adding: dvs/0157.png (stored 0%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0253.png (stored 0%)
  adding: dvs/0120.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0245.png (stored 0%)
  adding: dvs/0094.png (stored 0%)
  adding: dvs/0240.png (stored 0%)
  adding: dvs/0027.png (stored 0%)
  adding: dvs/0069.png (stored 0%)
  adding: dvs/0186.png (stored 0%)
  adding: dvs/0214.png (stored 0%)
  adding: dvs/0263.png (stored 0%)
  adding: dvs/0260.png (stored 0%)
  adding: dvs/0266.png (stored 0%)
  adding: dvs/0064.png (stored 0%)
  adding: dvs/0174.png (stored 0%)
  adding: dvs/0261.png (stored 0%)
  adding: dvs/0072.png (stored 0%)
  adding: dvs/0003.png (stored 0%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0123.png (stored 0%)
  adding: dvs/0293.png (stored 0%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0221.png (stored 0%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0153.png (stored 0%)
  adding: dvs/0232.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0203.png (stored 0%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0209.png (stored 0%)
  adding: dvs/0001.png (stored 0%)
  adding: dvs/0068.png (stored 0%)
  adding: dvs/0097.png (stored 0%)
  adding: dvs/0250.png (stored 0%)
  adding: dvs/0259.png (stored 0%)
  adding: dvs/0208.png (stored 0%)
  adding: dvs/0161.png (stored 0%)
  adding: dvs/0104.png (stored 0%)
  adding: dvs/0100.png (stored 0%)
  adding: dvs/0011.png (stored 0%)

'The chosen video file: /content/video/spring_4s.MOV'

FPS: 30.004011231448054
Frame count: 374
Duration: 12.46 sec
The Final v2e command:

'v2e -i /content/video/spring_4s.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/spring_4s.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/spring_4s.MOV
INFO:v2e:Input video frame rate 30.004011231448054Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/spring_4s.MOV has total 374 frames with total duration 12.43s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 374 frames 0 to 373
(From 0.0s to 12.433333333333334s, duration 12.433333333333334s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 373.0 frames with duration 12.43s and playback duration 12.43s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 373 from video input
INFO:v2e:Input video /content/video/spring_4s.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 374 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/374 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 374/374 [00:10<00:00, 34.19fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmphljjpjmq
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 47 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/47 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 15
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   2% 1/47 [00:04<03:09,  4.12s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 12
slomo-interp:   4% 2/47 [00:06<02:26,  3.26s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 13
slomo-interp: 100% 47/47 [05:40<00:00,  7.24s/ batch of 8 fr]
write-orig-avi: 100% 374/374 [00:00<00:00, 903.69fr/s]
write-slomo-vid: 100% 12205/12205 [00:26<00:00, 459.85fr/s]
INFO:v2ecore.slomo:Wrote 12205 frames and returning 12205 frame times.
Average upsampling factor= 32.6
INFO:v2e:SloMo average upsampling factor=32.60; average DVS timestamp resolution=1.02ms
INFO:v2e:*** Stage 3/3: emulating DVS events from 12205 frames
dvs:   0% 5/12205 [00:00<04:05, 49.77fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs: 100% 12205/12205 [04:24<00:00, 46.08fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 372 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 374 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 12205 frames
INFO:v2e:generated total 20.90M events (10.44M on, 10.46M off)
INFO:v2e:Avg event rate for N=89960 px and total time =12.433 s
	Total: 1.68MHz (839.76kHz on, 841.54kHz off)
	Per pixel:  18.69Hz (9.33Hz on, 9.35Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 748 frames in 644.71s (1.16fr/s)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 372 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 374 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 12205 frames
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 374
Output folder: /content/v2e-output/aps
APS frames found: 374

Saving DVS frames:   0%|          | 0/374 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:12.47, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:12.47, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x5d2939dd7840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x5d2939de0a80] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x5d2939fab900] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5d2939fab900] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5d2939fab900] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  374 fps= 40 q=-1.0 Lsize=    8352kB time=00:00:12.36 bitrate=5532.8kbits/s speed=1.34x
video:8347kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.063564%
[libx264 @ 0x5d2939fab900] frame I:5     Avg QP:25.64  size: 23650
[libx264 @ 0x5d2939fab900] frame P:97    Avg QP:28.83  size: 25712
[libx264 @ 0x5d2939fab900] frame B:272   Avg QP:32.05  size: 21817
[libx264 @ 0x5d2939fab900] consecutive B-frames:  2.7%  0.5%  1.6% 95.2%
[libx264 @ 0x5d2939fab900] mb I  I16..4:  6.1% 57.1% 36.8%
[libx264 @ 0x5d2939fab900] mb P  I16..4:  2.9% 11.9% 36.8%  P16..4: 23.5% 12.5%  7.6%  0.0%  0.0%    skip: 4.7%
[libx264 @ 0x5d2939fab900] mb B  I16..4:  4.6%  1.8% 19.8%  B16..8: 28.9% 10.8%  7.0%  direct: 2.6%  skip:24.6%  L0:44.4% L1:42.5% BI:13.2%
[libx264 @ 0x5d2939fab900] 8x8 transform intra:15.3% inter:39.3%
[libx264 @ 0x5d2939fab900] coded y,uvDC,uvAC intra: 76.1% 78.3% 76.1% inter: 28.1% 18.4% 14.1%
[libx264 @ 0x5d2939fab900] i16 v,h,dc,p: 28% 13% 54%  5%
[libx264 @ 0x5d2939fab900] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 42% 12% 30%  3%  2%  3%  2%  4%  2%
[libx264 @ 0x5d2939fab900] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 26% 13% 30%  6%  4%  6%  4%  6%  4%
[libx264 @ 0x5d2939fab900] i8c dc,h,v,p: 62%  9% 24%  5%
[libx264 @ 0x5d2939fab900] Weighted P-Frames: Y:28.9% UV:19.6%
[libx264 @ 0x5d2939fab900] ref P L0: 44.7% 26.1% 18.7%  8.9%  1.6%
[libx264 @ 0x5d2939fab900] ref B L0: 78.6% 16.2%  5.1%
[libx264 @ 0x5d2939fab900] ref B L1: 90.5%  9.5%
[libx264 @ 0x5d2939fab900] kb/s:5484.48
/content/v2e-output
  adding: aps/ (stored 0%)
  adding: aps/0146.png (deflated 18%)
  adding: aps/0204.png (deflated 15%)
  adding: aps/0275.png (deflated 16%)
  adding: aps/0081.png (deflated 17%)
  adding: aps/0025.png (deflated 16%)
  adding: aps/0179.png (deflated 15%)
  adding: aps/0231.png (deflated 17%)
  adding: aps/0134.png (deflated 19%)
  adding: aps/0366.png (deflated 15%)
  adding: aps/0106.png (deflated 15%)
  adding: aps/0042.png (deflated 16%)
  adding: aps/0004.png (deflated 16%)
  adding: aps/0142.png (deflated 16%)
  adding: aps/0371.png (deflated 15%)
  adding: aps/0018.png (deflated 15%)
  adding: aps/0306.png (deflated 16%)
  adding: aps/0361.png (deflated 16%)
  adding: aps/0328.png (deflated 17%)
  adding: aps/0057.png (deflated 17%)
  adding: aps/0039.png (deflated 16%)
  adding: aps/0150.png (deflated 15%)
  adding: aps/0316.png (deflated 16%)
  adding: aps/0367.png (deflated 15%)
  adding: aps/0016.png (deflated 16%)
  adding: aps/0092.png (deflated 16%)
  adding: aps/0046.png (deflated 16%)
  adding: aps/0087.png (deflated 17%)
  adding: aps/0014.png (deflated 17%)
  adding: aps/0226.png (deflated 15%)
  adding: aps/0105.png (deflated 15%)
  adding: aps/0170.png (deflated 17%)
  adding: aps/0313.png (deflated 18%)
  adding: aps/0256.png (deflated 14%)
  adding: aps/0010.png (deflated 15%)
  adding: aps/0200.png (deflated 15%)
  adding: aps/0164.png (deflated 16%)
  adding: aps/0125.png (deflated 17%)
  adding: aps/0082.png (deflated 16%)
  adding: aps/0300.png (deflated 15%)
  adding: aps/0183.png (deflated 16%)
  adding: aps/0119.png (deflated 16%)
  adding: aps/0274.png (deflated 15%)
  adding: aps/0041.png (deflated 15%)
  adding: aps/0286.png (deflated 15%)
  adding: aps/0137.png (deflated 17%)
  adding: aps/0374.png (deflated 16%)
  adding: aps/0362.png (deflated 16%)
  adding: aps/0270.png (deflated 17%)
  adding: aps/0331.png (deflated 15%)
  adding: aps/0277.png (deflated 18%)
  adding: aps/0167.png (deflated 16%)
  adding: aps/0130.png (deflated 16%)
  adding: aps/0251.png (deflated 15%)
  adding: aps/0189.png (deflated 16%)
  adding: aps/0213.png (deflated 15%)
  adding: aps/0198.png (deflated 15%)
  adding: aps/0223.png (deflated 15%)
  adding: aps/0168.png (deflated 16%)
  adding: aps/0050.png (deflated 16%)
  adding: aps/0235.png (deflated 16%)
  adding: aps/0158.png (deflated 18%)
  adding: aps/0218.png (deflated 16%)
  adding: aps/0242.png (deflated 17%)
  adding: aps/0340.png (deflated 17%)
  adding: aps/0334.png (deflated 15%)
  adding: aps/0239.png (deflated 15%)
  adding: aps/0215.png (deflated 15%)
  adding: aps/0281.png (deflated 16%)
  adding: aps/0224.png (deflated 15%)
  adding: aps/0333.png (deflated 16%)
  adding: aps/0330.png (deflated 16%)
  adding: aps/0157.png (deflated 18%)
  adding: aps/0110.png (deflated 18%)
  adding: aps/0359.png (deflated 15%)
  adding: aps/0324.png (deflated 16%)
  adding: aps/0253.png (deflated 16%)
  adding: aps/0337.png (deflated 26%)
  adding: aps/0120.png (deflated 15%)
  adding: aps/0108.png (deflated 15%)
  adding: aps/0325.png (deflated 20%)
  adding: aps/0043.png (deflated 16%)
  adding: aps/0085.png (deflated 20%)
  adding: aps/0370.png (deflated 15%)
  adding: aps/0245.png (deflated 16%)
  adding: aps/0094.png (deflated 17%)
  adding: aps/0240.png (deflated 17%)
  adding: aps/0027.png (deflated 16%)
  adding: aps/0069.png (deflated 15%)
  adding: aps/0186.png (deflated 15%)
  adding: aps/0349.png (deflated 19%)
  adding: aps/0214.png (deflated 16%)
  adding: aps/0263.png (deflated 15%)
  adding: aps/0260.png (deflated 15%)
  adding: aps/0266.png (deflated 18%)
  adding: aps/0064.png (deflated 16%)
  adding: aps/0174.png (deflated 15%)
  adding: aps/0261.png (deflated 15%)
  adding: aps/0072.png (deflated 15%)
  adding: aps/0003.png (deflated 16%)
  adding: aps/0141.png (deflated 16%)
  adding: aps/0123.png (deflated 18%)
  adding: aps/0293.png (deflated 16%)
  adding: aps/0090.png (deflated 16%)
  adding: aps/0221.png (deflated 16%)
  adding: aps/0088.png (deflated 17%)
  adding: aps/0153.png (deflated 16%)
  adding: aps/0232.png (deflated 17%)
  adding: aps/0145.png (deflated 19%)
  adding: aps/0203.png (deflated 17%)
  adding: aps/0051.png (deflated 18%)
  adding: aps/0019.png (deflated 15%)
  adding: aps/0296.png (deflated 16%)
  adding: aps/0339.png (deflated 18%)
  adding: aps/0209.png (deflated 16%)
  adding: aps/0001.png (deflated 18%)
  adding: aps/0068.png (deflated 16%)
  adding: aps/0097.png (deflated 19%)
  adding: aps/0250.png (deflated 16%)
  adding: aps/0259.png (deflated 16%)
  adding: aps/0208.png (deflated 16%)
  adding: aps/0161.png (deflated 18%)
  adding: aps/0365.png (deflated 15%)
  adding: aps/0104.png (deflated 16%)
  adding: aps/0100.png (deflated 17%)
  adding: aps/0336.png (deflated 16%)
  adding: aps/0011.png (deflated 15%)
  adding: aps/0295.png (deflated 16%)
  adding: aps/0303.png (deflated 17%)
  adding: aps/0302.png (deflated 18%)
  adding: aps/0032.png (deflated 16%)
  adding: aps/0191.png (deflated 15%)
  adding: aps/0062.png (deflated 17%)
  adding: aps/0192.png (deflated 15%)
  adding: aps/0067.png (deflated 15%)
  adding: aps/0184.png (deflated 16%)
  adding: aps/0343.png (deflated 21%)
  adding: aps/0013.png (deflated 17%)
  adding: aps/0363.png (deflated 15%)
  adding: aps/0172.png (deflated 16%)
  adding: aps/0140.png (deflated 17%)
  adding: aps/0197.png (deflated 15%)
  adding: aps/0219.png (deflated 16%)
  adding: aps/0354.png (deflated 15%)
  adding: aps/0169.png (deflated 18%)
  adding: aps/0193.png (deflated 17%)
  adding: aps/0022.png (deflated 15%)
  adding: aps/0084.png (deflated 16%)
  adding: aps/0074.png (deflated 17%)
  adding: aps/0054.png (deflated 18%)
  adding: aps/0309.png (deflated 15%)
  adding: aps/0229.png (deflated 23%)
  adding: aps/0083.png (deflated 17%)
  adding: aps/0147.png (deflated 17%)
  adding: aps/0171.png (deflated 18%)
  adding: aps/0372.png (deflated 15%)
  adding: aps/0070.png (deflated 16%)
  adding: aps/0199.png (deflated 15%)
  adding: aps/0360.png (deflated 15%)
  adding: aps/0071.png (deflated 13%)
  adding: aps/0063.png (deflated 16%)
  adding: aps/0058.png (deflated 15%)
  adding: aps/0265.png (deflated 19%)
  adding: aps/0075.png (deflated 16%)
  adding: aps/0318.png (deflated 15%)
  adding: aps/0369.png (deflated 15%)
  adding: aps/0272.png (deflated 17%)
  adding: aps/0139.png (deflated 17%)
  adding: aps/0052.png (deflated 17%)
  adding: aps/0029.png (deflated 15%)
  adding: aps/0095.png (deflated 16%)
  adding: aps/0247.png (deflated 16%)
  adding: aps/0133.png (deflated 19%)
  adding: aps/0024.png (deflated 15%)
  adding: aps/0319.png (deflated 16%)
  adding: aps/0323.png (deflated 15%)
  adding: aps/0138.png (deflated 17%)
  adding: aps/0307.png (deflated 15%)
  adding: aps/0152.png (deflated 15%)
  adding: aps/0129.png (deflated 16%)
  adding: aps/0268.png (deflated 17%)
  adding: aps/0201.png (deflated 15%)
  adding: aps/0225.png (deflated 15%)
  adding: aps/0252.png (deflated 15%)
  adding: aps/0283.png (deflated 18%)
  adding: aps/0115.png (deflated 16%)
  adding: aps/0059.png (deflated 15%)
  adding: aps/0091.png (deflated 16%)
  adding: aps/0093.png (deflated 16%)
  adding: aps/0166.png (deflated 16%)
  adding: aps/0044.png (deflated 16%)
  adding: aps/0098.png (deflated 17%)
  adding: aps/0345.png (deflated 19%)
  adding: aps/0350.png (deflated 17%)
  adding: aps/0009.png (deflated 15%)
  adding: aps/0246.png (deflated 16%)
  adding: aps/0116.png (deflated 16%)
  adding: aps/0202.png (deflated 15%)
  adding: aps/0175.png (deflated 15%)
  adding: aps/0077.png (deflated 18%)
  adding: aps/0238.png (deflated 16%)
  adding: aps/0023.png (deflated 15%)
  adding: aps/0257.png (deflated 14%)
  adding: aps/0308.png (deflated 15%)
  adding: aps/0341.png (deflated 21%)
  adding: aps/0178.png (deflated 15%)
  adding: aps/0020.png (deflated 15%)
  adding: aps/0107.png (deflated 15%)
  adding: aps/0230.png (deflated 20%)
  adding: aps/0065.png (deflated 16%)
  adding: aps/0236.png (deflated 16%)
  adding: aps/0111.png (deflated 18%)
  adding: aps/0101.png (deflated 17%)
  adding: aps/0180.png (deflated 15%)
  adding: aps/0228.png (deflated 15%)
  adding: aps/0113.png (deflated 17%)
  adding: aps/0012.png (deflated 15%)
  adding: aps/0076.png (deflated 17%)
  adding: aps/0036.png (deflated 15%)
  adding: aps/0049.png (deflated 20%)
  adding: aps/0031.png (deflated 15%)
  adding: aps/0117.png (deflated 16%)
  adding: aps/0290.png (deflated 18%)
  adding: aps/0237.png (deflated 16%)
  adding: aps/0289.png (deflated 20%)
  adding: aps/0278.png (deflated 17%)
  adding: aps/0282.png (deflated 16%)
  adding: aps/0346.png (deflated 19%)
  adding: aps/0089.png (deflated 17%)
  adding: aps/0078.png (deflated 17%)
  adding: aps/0109.png (deflated 20%)
  adding: aps/0114.png (deflated 16%)
  adding: aps/0079.png (deflated 17%)
  adding: aps/0126.png (deflated 17%)
  adding: aps/0299.png (deflated 15%)
  adding: aps/0216.png (deflated 15%)
  adding: aps/0294.png (deflated 16%)
  adding: aps/0148.png (deflated 17%)
  adding: aps/0118.png (deflated 15%)
  adding: aps/0040.png (deflated 16%)
  adding: aps/0035.png (deflated 16%)
  adding: aps/0321.png (deflated 15%)
  adding: aps/0312.png (deflated 14%)
  adding: aps/0210.png (deflated 16%)
  adding: aps/0264.png (deflated 15%)
  adding: aps/0276.png (deflated 16%)
  adding: aps/0315.png (deflated 16%)
  adding: aps/0269.png (deflated 19%)
  adding: aps/0127.png (deflated 16%)
  adding: aps/0066.png (deflated 16%)
  adding: aps/0144.png (deflated 15%)
  adding: aps/0314.png (deflated 17%)
  adding: aps/0332.png (deflated 15%)
  adding: aps/0258.png (deflated 15%)
  adding: aps/0288.png (deflated 17%)
  adding: aps/0358.png (deflated 15%)
  adding: aps/0284.png (deflated 16%)
  adding: aps/0311.png (deflated 15%)
  adding: aps/0112.png (deflated 17%)
  adding: aps/0007.png (deflated 15%)
  adding: aps/0159.png (deflated 18%)
  adding: aps/0347.png (deflated 17%)
  adding: aps/0033.png (deflated 15%)
  adding: aps/0285.png (deflated 15%)
  adding: aps/0310.png (deflated 15%)
  adding: aps/0195.png (deflated 16%)
  adding: aps/0373.png (deflated 17%)
  adding: aps/0206.png (deflated 16%)
  adding: aps/0227.png (deflated 15%)
  adding: aps/0132.png (deflated 16%)
  adding: aps/0279.png (deflated 19%)
  adding: aps/0055.png (deflated 18%)
  adding: aps/0262.png (deflated 16%)
  adding: aps/0155.png (deflated 15%)
  adding: aps/0249.png (deflated 15%)
  adding: aps/0008.png (deflated 15%)
  adding: aps/0254.png (deflated 16%)
  adding: aps/0211.png (deflated 16%)
  adding: aps/0102.png (deflated 16%)
  adding: aps/0207.png (deflated 16%)
  adding: aps/0053.png (deflated 17%)
  adding: aps/0060.png (deflated 15%)
  adding: aps/0136.png (deflated 17%)
  adding: aps/0185.png (deflated 15%)
  adding: aps/0194.png (deflated 16%)
  adding: aps/0322.png (deflated 15%)
  adding: aps/0248.png (deflated 16%)
  adding: aps/0351.png (deflated 17%)
  adding: aps/0149.png (deflated 16%)
  adding: aps/0298.png (deflated 16%)
  adding: aps/0205.png (deflated 16%)
  adding: aps/0344.png (deflated 20%)
  adding: aps/0255.png (deflated 16%)
  adding: aps/0233.png (deflated 17%)
  adding: aps/0026.png (deflated 16%)
  adding: aps/0357.png (deflated 15%)
  adding: aps/0364.png (deflated 15%)
  adding: aps/0196.png (deflated 16%)
  adding: aps/0096.png (deflated 15%)
  adding: aps/0061.png (deflated 17%)
  adding: aps/0342.png (deflated 18%)
  adding: aps/0021.png (deflated 15%)
  adding: aps/0030.png (deflated 15%)
  adding: aps/0128.png (deflated 16%)
  adding: aps/0086.png (deflated 19%)
  adding: aps/0176.png (deflated 15%)
  adding: aps/0121.png (deflated 18%)
  adding: aps/0327.png (deflated 17%)
  adding: aps/0243.png (deflated 17%)
  adding: aps/0352.png (deflated 16%)
  adding: aps/0162.png (deflated 17%)
  adding: aps/0273.png (deflated 16%)
  adding: aps/0038.png (deflated 17%)
  adding: aps/0173.png (deflated 16%)
  adding: aps/0326.png (deflated 18%)
  adding: aps/0156.png (deflated 15%)
  adding: aps/0048.png (deflated 17%)
  adding: aps/0217.png (deflated 17%)
  adding: aps/0017.png (deflated 16%)
  adding: aps/0080.png (deflated 17%)
  adding: aps/0099.png (deflated 17%)
  adding: aps/0212.png (deflated 15%)
  adding: aps/0103.png (deflated 16%)
  adding: aps/0267.png (deflated 18%)
  adding: aps/0320.png (deflated 15%)
  adding: aps/0160.png (deflated 18%)
  adding: aps/0165.png (deflated 16%)
  adding: aps/0234.png (deflated 16%)
  adding: aps/0190.png (deflated 15%)
  adding: aps/0304.png (deflated 17%)
  adding: aps/0353.png (deflated 15%)
  adding: aps/0034.png (deflated 15%)
  adding: aps/0182.png (deflated 16%)
  adding: aps/0241.png (deflated 17%)
  adding: aps/0143.png (deflated 16%)
  adding: aps/0222.png (deflated 15%)
  adding: aps/0291.png (deflated 19%)
  adding: aps/0305.png (deflated 16%)
  adding: aps/0368.png (deflated 15%)
  adding: aps/0135.png (deflated 18%)
  adding: aps/0037.png (deflated 17%)
  adding: aps/0045.png (deflated 16%)
  adding: aps/0271.png (deflated 17%)
  adding: aps/0005.png (deflated 16%)
  adding: aps/0297.png (deflated 16%)
  adding: aps/0187.png (deflated 14%)
  adding: aps/0292.png (deflated 17%)
  adding: aps/0122.png (deflated 18%)
  adding: aps/0188.png (deflated 15%)
  adding: aps/0002.png (deflated 17%)
  adding: aps/0028.png (deflated 16%)
  adding: aps/0355.png (deflated 15%)
  adding: aps/0244.png (deflated 16%)
  adding: aps/0329.png (deflated 16%)
  adding: aps/0287.png (deflated 18%)
  adding: aps/0338.png (deflated 21%)
  adding: aps/0280.png (deflated 17%)
  adding: aps/0220.png (deflated 16%)
  adding: aps/0348.png (deflated 17%)
  adding: aps/0006.png (deflated 15%)
  adding: aps/0335.png (deflated 15%)
  adding: aps/0301.png (deflated 20%)
  adding: aps/0154.png (deflated 15%)
  adding: aps/0177.png (deflated 15%)
  adding: aps/0317.png (deflated 16%)
  adding: aps/0056.png (deflated 15%)
  adding: aps/0356.png (deflated 15%)
  adding: aps/0015.png (deflated 16%)
  adding: aps/0073.png (deflated 18%)
  adding: aps/0124.png (deflated 17%)
  adding: aps/0131.png (deflated 16%)
  adding: aps/0151.png (deflated 16%)
  adding: aps/0163.png (deflated 16%)
  adding: aps/0181.png (deflated 16%)
  adding: aps/0047.png (deflated 16%)
  adding: dvs/ (stored 0%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0204.png (stored 0%)
  adding: dvs/0275.png (stored 0%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0231.png (stored 0%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0366.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0042.png (stored 0%)
  adding: dvs/0004.png (stored 0%)
  adding: dvs/0142.png (stored 0%)

In [ ]:
# if RAM overloaded

def create_frames_from_csv(csv_path, output_dir, aps_dir, width=346, height=260):
    os.makedirs(output_dir, exist_ok=True)

    # Get sorted list of APS frames to match DVS frame count
    aps_frames = sorted([
        f for f in os.listdir(aps_dir)
        if f.lower().endswith(('.png', '.jpg', '.jpeg'))
    ])
    num_frames = len(aps_frames)
    if num_frames == 0:
        raise ValueError(f"No frames found in '{aps_dir}'.")
    print(f"APS frames found: {num_frames}")

    # Read only first row to get t_start (avoids loading entire CSV)
    first_chunk = pd.read_csv(csv_path, nrows=1)
    t_start = first_chunk['t'].iloc[0]

    # Read only last row to get t_end (avoids loading entire CSV)
    with open(csv_path, 'rb') as f:
        f.seek(-2, 2)
        while f.read(1) != b'\n':
            f.seek(-2, 1)
        last_line = f.readline().decode()
    t_end = float(last_line.split(',')[0])

    # Create evenly spaced time boundaries for each frame
    frame_boundaries = np.linspace(t_start, t_end, num_frames + 1)

    # Pre-allocate accumulation frames (~30 MB total, safe)
    frames = [np.zeros((height, width), dtype=np.int16) for _ in range(num_frames)]

    print("Reading events and building frames (chunked)...")
    chunk_size = 5_000_000  # 5M rows per chunk (~160 MB RAM per iteration)

    for chunk in tqdm(pd.read_csv(csv_path, chunksize=chunk_size),
                      desc="Processing chunks"):
        t = chunk['t'].to_numpy()
        x = chunk['x'].to_numpy()
        y = chunk['y'].to_numpy()
        p = chunk['p'].to_numpy()

        # Assign each event to its corresponding frame index
        frame_idxs = np.searchsorted(frame_boundaries[1:], t, side='right')
        frame_idxs = np.clip(frame_idxs, 0, num_frames - 1)

        # Filter out out-of-bounds pixel coordinates
        valid = (x >= 0) & (x < width) & (y >= 0) & (y < height)
        x = x[valid]
        y = y[valid]
        p = p[valid]
        frame_idxs = frame_idxs[valid]

        # Convert polarity: ON=+1, OFF=-1
        vals = np.where(p, 1, -1).astype(np.int16)

        # Accumulate events into their respective frames
        for fi in np.unique(frame_idxs):
            mask = frame_idxs == fi
            np.add.at(frames[fi], (y[mask], x[mask]), vals[mask])

    # Render and save DVS frames as PNG images
    print("Saving DVS frames...")
    for frame_idx, frame in enumerate(tqdm(frames, desc="Saving DVS frames")):
        img = np.full((height, width, 3), 255, dtype=np.uint8)
        img[frame > 0] = (220, 30, 30)
        img[frame < 0] = (30, 30, 200)
        file_name = aps_frames[frame_idx]
        Image.fromarray(img).save(os.path.join(output_dir, file_name))


for seq in tqdm(sequences):
    %cd /content
    !rm -rf '/content/v2e-output'

    os.makedirs('/content/video', exist_ok=True)
    shutil.copy(f'/content/drive/MyDrive/Diploma_project/own_videos/{initials}/flicker/{seq}.MOV', '/content/video')

    video_path = f"/content/video/{seq}.MOV"

    if video_path != "" and os.path.isfile(video_path):
        display("The chosen video file: {}".format(video_path))
    else:
        print("The file path is empty or invalid, choose a file")

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise ValueError(f"Cannot open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    duration_sec = frame_count / fps if fps > 0 else 0

    print(f"FPS: {fps}")
    print(f"Frame count: {frame_count}")
    print(f"Duration: {duration_sec:.2f} sec")

    cap.release()

    output_folder = "/content/v2e-output"
    overwrite = True
    unique_output_folder = False
    out_filename = "events.h5"
    davis_output = True
    skip_video_output = False
    dvs_exposure = f"duration {1/fps:.3f}"
    output_mode = "dvs346"
    input_frame_rate = 30
    input_slowmotion_factor = 1
    disable_slomo = False
    timestamp_resolution = 0.001
    auto_timestamp_resolution = True
    slomo_model = "/content/v2e/input/SuperSloMo39.ckpt"
    condition = "Clean"
    thres = 0.2
    sigma = 0.03
    cutoff_hz = 200
    leak_rate_hz = 5.18
    shot_noise_rate_hz = 2.716

    if condition == "Clean":
        thres = 0.2
        sigma = 0.02
        cutoff_hz = 0
        leak_rate_hz = 0
        shot_noise_rate_hz = 0
    elif condition == "Noisy":
        thres = 0.2
        sigma_thres = 0.05
        cutoff_hz = 30
        leak_rate_hz = 0.1
        shot_noise_rate_hz = 5

    v2e_command = ["v2e"]
    v2e_command += ["-i", video_path]
    v2e_command += ["-o", output_folder]

    if overwrite:
        v2e_command.append("--overwrite")

    v2e_command += ["--unique_output_folder", "{}".format(unique_output_folder).lower()]

    if davis_output:
        v2e_command += ["--davis_output"]
    v2e_command += ["--dvs_h5", out_filename]
    v2e_command += ["--dvs_aedat2", "None"]
    v2e_command += ["--dvs_text", "None"]
    v2e_command += ["--no_preview"]

    if skip_video_output:
        v2e_command += ["--skip_video_output"]
    else:
        dvs_exposure = f"duration {1/input_frame_rate:.6f}"
        v2e_command += ["--dvs_exposure", dvs_exposure]

    v2e_command += ["--input_frame_rate", "{}".format(input_frame_rate)]
    v2e_command += ["--input_slowmotion_factor", "{}".format(input_slowmotion_factor)]

    if disable_slomo:
        v2e_command += ["--disable_slomo"]
        v2e_command += ["--auto_timestamp_resolution", "false"]
    else:
        v2e_command += ["--slomo_model", slomo_model]
        if auto_timestamp_resolution:
            v2e_command += ["--auto_timestamp_resolution", "{}".format(auto_timestamp_resolution).lower()]
        else:
            v2e_command += ["--timestamp_resolution", "{}".format(timestamp_resolution)]

    v2e_command += ["--pos_thres", "{}".format(thres)]
    v2e_command += ["--neg_thres", "{}".format(thres)]
    v2e_command += ["--sigma_thres", "{}".format(sigma)]
    v2e_command += ["--cutoff_hz", "{}".format(cutoff_hz)]
    v2e_command += ["--leak_rate_hz", "{}".format(leak_rate_hz)]
    v2e_command += ["--shot_noise_rate_hz", "{}".format(shot_noise_rate_hz)]
    v2e_command += [f"--{output_mode}"]

    final_v2e_command = " ".join(v2e_command)
    print("The Final v2e command:")
    display(final_v2e_command)

    !$final_v2e_command

    # Convert h5 events to csv (chunked, memory-safe)
    h5_path  = "/content/v2e-output/events.h5"
    csv_path = "/content/v2e-output/events.csv"
    chunk_size = 5_000_000  # 5M rows per chunk (~160 MB RAM)

    with h5py.File(h5_path, "r") as f:
        total = f["events"].shape[0]
        print(f"Total events: {total:,}")
        first = True
        for start in range(0, total, chunk_size):
            chunk = f["events"][start:start + chunk_size]
            df = pd.DataFrame(chunk, columns=["t", "x", "y", "p"])
            df.to_csv(csv_path, mode='w' if first else 'a',
                      index=False, header=first)
            first = False
            print(f"  Written {min(start + chunk_size, total):,}/{total:,}")

    print(f"Saved: {csv_path}")

    # Extract APS frames
    video_path = "/content/v2e-output/video_orig.avi"
    output_dir = "/content/v2e-output/aps"
    os.makedirs(output_dir, exist_ok=True)

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise ValueError(f"Cannot open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_count = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break
        frame_path = os.path.join(output_dir, f"{frame_count + 1:04d}.png")
        cv2.imwrite(frame_path, frame)
        frame_count += 1

    cap.release()
    print("Detected FPS:", fps)
    print("Saved frames:", frame_count)
    print("Output folder:", output_dir)

    # Generate DVS frames (chunked, memory-safe)
    create_frames_from_csv(
        csv_path="/content/v2e-output/events.csv",
        output_dir="/content/v2e-output/dvs",
        aps_dir="/content/v2e-output/aps",
        width=346,
        height=260
    )

    !ffmpeg -y -framerate 30 -i /content/v2e-output/aps/%04d.png -framerate 30 -i /content/v2e-output/dvs/%04d.png -filter_complex hstack -c:v libx264 -pix_fmt yuv420p /content/v2e-output/aps_dvs.mp4

    !rm -rf '/content/v2e-output/dvs-video-frame_times.txt'
    !rm -rf '/content/v2e-output/dvs-video.avi'
    !rm -rf '/content/v2e-output/events.h5'
    !rm -rf '/content/v2e-output/v2e-args.txt'
    !rm -rf '/content/v2e-output/video_orig.avi'
    !rm -rf '/content/v2e-output/video_slomo.avi'

    %cd /content/v2e-output
    !zip -r /content/{seq}.zip .

    shutil.copy(
        f"/content/{seq}.zip",
        f"/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/{initials}/flicker/{seq}.zip"
    )

    base = f"/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/{initials}/flicker"
    os.environ['SEQ'] = seq
    os.environ['BASE'] = base
    !unzip "$BASE/$SEQ.zip" -d "$BASE/$SEQ"

    print(f"✓ Done: {seq}")

  0%|          | 0/15 [00:00<?, ?it/s]

/content

'The chosen video file: /content/video/key_1:2hz.MOV'

FPS: 29.972375690607734
Frame count: 217
Duration: 7.24 sec
The Final v2e command:

'v2e -i /content/video/key_1:2hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/key_1:2hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/key_1:2hz.MOV
INFO:v2e:Input video frame rate 29.972375690607734Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/key_1:2hz.MOV has total 217 frames with total duration 7.20s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 217 frames 0 to 216
(From 0.0s to 7.2s, duration 7.2s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 216.0 frames with duration 7.20s and playback duration 7.20s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 216 from video input
INFO:v2e:Input video /content/video/key_1:2hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 217 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/217 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 217/217 [00:06<00:00, 36.03fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpi0pd301l
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 27 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/27 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 13
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/27 [00:04<01:57,  4.52s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 16
slomo-interp:   7% 2/27 [00:08<01:49,  4.39s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 161
slomo-interp: 100% 27/27 [08:25<00:00, 18.71s/ batch of 8 fr]
write-orig-avi: 100% 217/217 [00:00<00:00, 839.80fr/s]
write-slomo-vid: 100% 14200/14200 [00:35<00:00, 404.37fr/s]
INFO:v2ecore.slomo:Wrote 14200 frames and returning 14200 frame times.
Average upsampling factor= 65.7
INFO:v2e:SloMo average upsampling factor=65.74; average DVS timestamp resolution=507.04us
INFO:v2e:*** Stage 3/3: emulating DVS events from 14200 frames
dvs:   0% 2/14200 [00:00<36:57,  6.40fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:  12% 1770/14200 [00:38<05:06, 40.60fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #1,778 at t=1.3340s
WARNING:v2ecore.emulator:no signal events generated for frame #1,779 at t=1.3342s
dvs:  13% 1874/14200 [00:39<02:51, 71.72fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #1,882 at t=1.3533s
dvs:  14% 1951/14200 [00:40<02:30, 81.64fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #1,958 at t=1.3674s
WARNING:v2ecore.emulator:no signal events generated for frame #1,960 at t=1.3677s
dvs:  14% 1969/14200 [00:40<02:34, 79.26fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #1,974 at t=1.3703s
WARNING:v2ecore.emulator:no signal events generated for frame #1,975 at t=1.3705s
WARNING:v2ecore.emulator:no signal events generated for frame #1,976 at t=1.3707s
WARNING:v2ecore.emulator:no signal events generated for frame #1,977 at t=1.3709s
dvs:  14% 1986/14200 [00:41<04:06, 49.51fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #1,987 at t=1.3728s
WARNING:v2ecore.emulator:no signal events generated for frame #1,988 at t=1.3729s
WARNING:v2ecore.emulator:no signal events generated for frame #1,989 at t=1.3731s
WARNING:v2ecore.emulator:no signal events generated for frame #1,992 at t=1.3737s
WARNING:v2ecore.emulator:no signal events generated for frame #1,993 at t=1.3739s
WARNING:v2ecore.emulator:no signal events generated for frame #1,995 at t=1.3742s
WARNING:v2ecore.emulator:no signal events generated for frame #1,998 at t=1.3748s
WARNING:v2ecore.emulator:no signal events generated for frame #1,999 at t=1.3750s
WARNING:v2ecore.emulator:no signal events generated for frame #2,001 at t=1.3753s
WARNING:v2ecore.emulator:no signal events generated for frame #2,003 at t=1.3757s
WARNING:v2ecore.emulator:no signal events generated for frame #2,004 at t=1.3759s
dvs:  14% 2010/14200 [00:41<02:48, 72.18fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,011 at t=1.3772s
WARNING:v2ecore.emulator:no signal events generated for frame #2,014 at t=1.3778s
dvs:  14% 2018/14200 [00:41<02:58, 68.11fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,022 at t=1.3792s
WARNING:v2ecore.emulator:no signal events generated for frame #2,024 at t=1.3796s
WARNING:v2ecore.emulator:no signal events generated for frame #2,026 at t=1.3800s
dvs:  14% 2026/14200 [00:41<03:06, 65.32fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,031 at t=1.3809s
WARNING:v2ecore.emulator:no signal events generated for frame #2,033 at t=1.3813s
WARNING:v2ecore.emulator:no signal events generated for frame #2,036 at t=1.3818s
dvs:  14% 2042/14200 [00:42<02:46, 73.04fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,045 at t=1.3835s
WARNING:v2ecore.emulator:no signal events generated for frame #2,046 at t=1.3837s
WARNING:v2ecore.emulator:no signal events generated for frame #2,047 at t=1.3839s
dvs:  14% 2050/14200 [00:42<02:52, 70.28fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,052 at t=1.3848s
WARNING:v2ecore.emulator:no signal events generated for frame #2,056 at t=1.3855s
WARNING:v2ecore.emulator:no signal events generated for frame #2,057 at t=1.3857s
WARNING:v2ecore.emulator:no signal events generated for frame #2,061 at t=1.3865s
WARNING:v2ecore.emulator:no signal events generated for frame #2,063 at t=1.3868s
WARNING:v2ecore.emulator:no signal events generated for frame #2,066 at t=1.3874s
dvs:  15% 2066/14200 [00:42<02:36, 77.64fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,072 at t=1.3885s
WARNING:v2ecore.emulator:no signal events generated for frame #2,073 at t=1.3887s
WARNING:v2ecore.emulator:no signal events generated for frame #2,075 at t=1.3891s
WARNING:v2ecore.emulator:no signal events generated for frame #2,081 at t=1.3902s
WARNING:v2ecore.emulator:no signal events generated for frame #2,088 at t=1.3915s
dvs:  15% 2089/14200 [00:42<01:51, 108.85fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,101 at t=1.3939s
dvs:  15% 2102/14200 [00:42<02:26, 82.77fr/s] WARNING:v2ecore.emulator:no signal events generated for frame #2,110 at t=1.3955s
dvs:  15% 2121/14200 [00:43<02:50, 70.75fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,123 at t=1.3979s
dvs:  15% 2137/14200 [00:43<03:07, 64.46fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,138 at t=1.4007s
WARNING:v2ecore.emulator:no signal events generated for frame #2,140 at t=1.4011s
WARNING:v2ecore.emulator:no signal events generated for frame #2,144 at t=1.4018s
dvs:  15% 2144/14200 [00:43<03:14, 61.94fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,145 at t=1.4020s
WARNING:v2ecore.emulator:no signal events generated for frame #2,147 at t=1.4024s
WARNING:v2ecore.emulator:no signal events generated for frame #2,148 at t=1.4026s
WARNING:v2ecore.emulator:no signal events generated for frame #2,149 at t=1.4028s
WARNING:v2ecore.emulator:no signal events generated for frame #2,153 at t=1.4035s
WARNING:v2ecore.emulator:no signal events generated for frame #2,155 at t=1.4039s
WARNING:v2ecore.emulator:no signal events generated for frame #2,156 at t=1.4041s
WARNING:v2ecore.emulator:no signal events generated for frame #2,157 at t=1.4042s
WARNING:v2ecore.emulator:no signal events generated for frame #2,159 at t=1.4046s
WARNING:v2ecore.emulator:no signal events generated for frame #2,161 at t=1.4050s
WARNING:v2ecore.emulator:no signal events generated for frame #2,162 at t=1.4052s
WARNING:v2ecore.emulator:no signal events generated for frame #2,163 at t=1.4054s
WARNING:v2ecore.emulator:no signal events generated for frame #2,165 at t=1.4057s
WARNING:v2ecore.emulator:no signal events generated for frame #2,168 at t=1.4063s
dvs:  15% 2168/14200 [00:43<01:58, 101.38fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,169 at t=1.4065s
WARNING:v2ecore.emulator:no signal events generated for frame #2,171 at t=1.4068s
WARNING:v2ecore.emulator:no signal events generated for frame #2,174 at t=1.4074s
WARNING:v2ecore.emulator:no signal events generated for frame #2,180 at t=1.4085s
dvs:  15% 2180/14200 [00:44<03:15, 61.36fr/s] WARNING:v2ecore.emulator:no signal events generated for frame #2,187 at t=1.4098s
WARNING:v2ecore.emulator:no signal events generated for frame #2,189 at t=1.4102s
dvs:  15% 2189/14200 [00:44<03:23, 58.94fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,191 at t=1.4105s
WARNING:v2ecore.emulator:no signal events generated for frame #2,194 at t=1.4111s
dvs:  16% 2204/14200 [00:44<03:37, 55.05fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,208 at t=1.4137s
dvs:  16% 2218/14200 [00:44<03:57, 50.40fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,223 at t=1.4165s
dvs:  16% 2226/14200 [00:44<03:50, 51.87fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,233 at t=1.4183s
dvs:  16% 2242/14200 [00:45<03:15, 61.28fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,250 at t=1.4215s
dvs:  16% 2314/14200 [00:46<03:19, 59.64fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,320 at t=1.4344s
WARNING:v2ecore.emulator:no signal events generated for frame #2,321 at t=1.4346s
WARNING:v2ecore.emulator:no signal events generated for frame #2,322 at t=1.4348s
dvs:  16% 2330/14200 [00:46<03:24, 58.00fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,332 at t=1.4367s
WARNING:v2ecore.emulator:no signal events generated for frame #2,335 at t=1.4372s
WARNING:v2ecore.emulator:no signal events generated for frame #2,336 at t=1.4374s
WARNING:v2ecore.emulator:no signal events generated for frame #2,337 at t=1.4376s
WARNING:v2ecore.emulator:no signal events generated for frame #2,339 at t=1.4380s
WARNING:v2ecore.emulator:no signal events generated for frame #2,344 at t=1.4389s
WARNING:v2ecore.emulator:no signal events generated for frame #2,346 at t=1.4393s
dvs:  17% 2346/14200 [00:46<02:38, 74.57fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,350 at t=1.4400s
WARNING:v2ecore.emulator:no signal events generated for frame #2,355 at t=1.4409s
dvs:  17% 2355/14200 [00:46<02:34, 76.89fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,362 at t=1.4422s
WARNING:v2ecore.emulator:no signal events generated for frame #2,364 at t=1.4426s
dvs:  17% 2364/14200 [00:47<02:30, 78.73fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,368 at t=1.4433s
dvs:  17% 2373/14200 [00:47<02:28, 79.80fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,377 at t=1.4450s
WARNING:v2ecore.emulator:no signal events generated for frame #2,386 at t=1.4467s
dvs:  17% 2386/14200 [00:47<02:18, 85.61fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,392 at t=1.4478s
dvs:  17% 2413/14200 [00:47<02:18, 85.35fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,417 at t=1.4524s
WARNING:v2ecore.emulator:no signal events generated for frame #2,421 at t=1.4532s
dvs:  17% 2446/14200 [00:47<02:04, 94.30fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,450 at t=1.4585s
dvs:  18% 2493/14200 [00:48<02:20, 83.14fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,498 at t=1.4674s
WARNING:v2ecore.emulator:no signal events generated for frame #2,499 at t=1.4676s
WARNING:v2ecore.emulator:no signal events generated for frame #2,501 at t=1.4680s
dvs:  18% 2503/14200 [00:48<02:13, 87.37fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,506 at t=1.4689s
WARNING:v2ecore.emulator:no signal events generated for frame #2,508 at t=1.4693s
dvs: 100% 14200/14200 [04:28<00:00, 52.94fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 215 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 217 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 14200 frames
INFO:v2e:generated total 15.45M events (7.65M on, 7.81M off)
INFO:v2e:Avg event rate for N=89960 px and total time =7.200 s
	Total: 2.15MHz (1.06MHz on, 1.08MHz off)
	Per pixel:  23.86Hz (11.80Hz on, 12.05Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 434 frames in 816.31s (1.88s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 215 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 217 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 14200 frames
Total events: 15,452,550
  Written 5,000,000/15,452,550
  Written 10,000,000/15,452,550
  Written 15,000,000/15,452,550
  Written 15,452,550/15,452,550
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 217
Output folder: /content/v2e-output/aps
APS frames found: 217
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/217 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:07.23, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:07.23, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x597b7c9a1840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x597b7c9aa480] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x597b7c9d5280] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x597b7c9d5280] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x597b7c9d5280] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  217 fps= 60 q=-1.0 Lsize=    1755kB time=00:00:07.13 bitrate=2015.1kbits/s speed=1.98x
video:1752kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.178469%
[libx264 @ 0x597b7c9d5280] frame I:9     Avg QP:26.44  size: 40071
[libx264 @ 0x597b7c9d5280] frame P:83    Avg QP:27.51  size: 11544
[libx264 @ 0x597b7c9d5280] frame B:125   Avg QP:29.79  size:  3793
[libx264 @ 0x597b7c9d5280] consecutive B-frames: 21.7%  3.7%  2.8% 71.9%
[libx264 @ 0x597b7c9d5280] mb I  I16..4:  1.6% 53.2% 45.1%
[libx264 @ 0x597b7c9d5280] mb P  I16..4:  5.7% 28.6% 14.9%  P16..4: 17.3%  4.0%  3.4%  0.0%  0.0%    skip:26.1%
[libx264 @ 0x597b7c9d5280] mb B  I16..4:  3.2%  1.3%  2.9%  B16..8: 28.1%  2.5%  1.0%  direct: 1.4%  skip:59.6%  L0:44.1% L1:53.9% BI: 2.0%
[libx264 @ 0x597b7c9d5280] 8x8 transform intra:50.9% inter:57.5%
[libx264 @ 0x597b7c9d5280] coded y,uvDC,uvAC intra: 61.9% 36.4% 34.4% inter: 13.0% 2.7% 1.2%
[libx264 @ 0x597b7c9d5280] i16 v,h,dc,p: 42% 14% 40%  5%
[libx264 @ 0x597b7c9d5280] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 49%  8% 31%  2%  1%  2%  1%  3%  2%
[libx264 @ 0x597b7c9d5280] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 34% 13% 30%  4%  4%  4%  3%  4%  3%
[libx264 @ 0x597b7c9d5280] i8c dc,h,v,p: 80%  5% 13%  2%
[libx264 @ 0x597b7c9d5280] Weighted P-Frames: Y:30.1% UV:16.9%
[libx264 @ 0x597b7c9d5280] ref P L0: 63.9% 15.4% 14.3%  5.4%  1.0%
[libx264 @ 0x597b7c9d5280] ref B L0: 80.9% 16.1%  3.0%
[libx264 @ 0x597b7c9d5280] ref B L1: 89.9% 10.1%
[libx264 @ 0x597b7c9d5280] kb/s:1982.93
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (deflated 2%)
  adding: dvs/0140.png (stored 0%)
  adding: dvs/0104.png (deflated 30%)
  adding: dvs/0160.png (deflated 23%)
  adding: dvs/0105.png (deflated 24%)
  adding: dvs/0199.png (deflated 73%)
  adding: dvs/0134.png (deflated 29%)
  adding: dvs/0077.png (deflated 8%)
  adding: dvs/0011.png (deflated 13%)
  adding: dvs/0026.png (stored 0%)
  adding: dvs/0154.png (deflated 4%)
  adding: dvs/0128.png (deflated 18%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0120.png (deflated 1%)
  adding: dvs/0163.png (deflated 29%)
  adding: dvs/0084.png (stored 0%)
  adding: dvs/0066.png (deflated 8%)
  adding: dvs/0010.png (deflated 34%)
  adding: dvs/0191.png (deflated 0%)
  adding: dvs/0007.png (deflated 8%)
  adding: dvs/0071.png (deflated 9%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (deflated 25%)
  adding: dvs/0062.png (deflated 4%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0197.png (stored 0%)
  adding: dvs/0143.png (stored 0%)
  adding: dvs/0184.png (deflated 3%)
  adding: dvs/0178.png (stored 0%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (deflated 2%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (stored 0%)
  adding: dvs/0126.png (deflated 10%)
  adding: dvs/0150.png (deflated 0%)
  adding: dvs/0042.png (deflated 2%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (stored 0%)
  adding: dvs/0075.png (deflated 7%)
  adding: dvs/0036.png (deflated 2%)
  adding: dvs/0207.png (stored 0%)
  adding: dvs/0095.png (deflated 6%)
  adding: dvs/0065.png (deflated 6%)
  adding: dvs/0057.png (stored 0%)
  adding: dvs/0033.png (stored 0%)
  adding: dvs/0211.png (stored 0%)
  adding: dvs/0182.png (deflated 12%)
  adding: dvs/0091.png (deflated 1%)
  adding: dvs/0067.png (deflated 1%)
  adding: dvs/0081.png (deflated 4%)
  adding: dvs/0047.png (deflated 0%)
  adding: dvs/0151.png (deflated 0%)
  adding: dvs/0056.png (stored 0%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (deflated 1%)
  adding: dvs/0020.png (deflated 8%)
  adding: dvs/0106.png (deflated 9%)
  adding: dvs/0072.png (deflated 8%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (deflated 0%)
  adding: dvs/0157.png (deflated 18%)
  adding: dvs/0013.png (deflated 21%)
  adding: dvs/0158.png (deflated 24%)
  adding: dvs/0034.png (stored 0%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (deflated 16%)
  adding: dvs/0175.png (stored 0%)
  adding: dvs/0167.png (deflated 31%)
  adding: dvs/0041.png (deflated 0%)
  adding: dvs/0177.png (stored 0%)
  adding: dvs/0032.png (deflated 1%)
  adding: dvs/0093.png (deflated 6%)
  adding: dvs/0004.png (deflated 8%)
  adding: dvs/0006.png (deflated 6%)
  adding: dvs/0159.png (deflated 19%)
  adding: dvs/0188.png (deflated 15%)
  adding: dvs/0030.png (stored 0%)
  adding: dvs/0130.png (deflated 19%)
  adding: dvs/0132.png (deflated 21%)
  adding: dvs/0009.png (deflated 2%)
  adding: dvs/0205.png (stored 0%)
  adding: dvs/0215.png (stored 0%)
  adding: dvs/0162.png (deflated 28%)
  adding: dvs/0209.png (deflated 10%)
  adding: dvs/0017.png (deflated 9%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (stored 0%)
  adding: dvs/0170.png (stored 0%)
  adding: dvs/0035.png (deflated 1%)
  adding: dvs/0201.png (deflated 20%)
  adding: dvs/0018.png (deflated 29%)
  adding: dvs/0156.png (deflated 12%)
  adding: dvs/0196.png (deflated 0%)
  adding: dvs/0147.png (deflated 7%)
  adding: dvs/0183.png (deflated 3%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0069.png (deflated 13%)
  adding: dvs/0148.png (deflated 5%)
  adding: dvs/0060.png (stored 0%)
  adding: dvs/0003.png (deflated 5%)
  adding: dvs/0187.png (deflated 12%)
  adding: dvs/0029.png (deflated 0%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (deflated 0%)
  adding: dvs/0001.png (deflated 54%)
  adding: dvs/0200.png (stored 0%)
  adding: dvs/0046.png (deflated 2%)
  adding: dvs/0135.png (deflated 25%)
  adding: dvs/0080.png (deflated 0%)
  adding: dvs/0094.png (deflated 9%)
  adding: dvs/0212.png (deflated 0%)
  adding: dvs/0090.png (deflated 0%)
  adding: dvs/0203.png (stored 0%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (deflated 29%)
  adding: dvs/0024.png (stored 0%)
  adding: dvs/0061.png (stored 0%)
  adding: dvs/0039.png (stored 0%)
  adding: dvs/0101.png (deflated 26%)
  adding: dvs/0152.png (deflated 1%)
  adding: dvs/0097.png (deflated 24%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (deflated 2%)
  adding: dvs/0070.png (deflated 13%)
  adding: dvs/0129.png (deflated 15%)
  adding: dvs/0206.png (stored 0%)
  adding: dvs/0037.png (deflated 5%)
  adding: dvs/0073.png (deflated 7%)
  adding: dvs/0116.png (stored 0%)
  adding: dvs/0185.png (deflated 1%)
  adding: dvs/0021.png (deflated 8%)
  adding: dvs/0137.png (deflated 28%)
  adding: dvs/0015.png (deflated 5%)
  adding: dvs/0166.png (deflated 35%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0121.png (deflated 10%)
  adding: dvs/0027.png (deflated 2%)
  adding: dvs/0040.png (deflated 0%)
  adding: dvs/0074.png (deflated 7%)
  adding: dvs/0149.png (deflated 8%)
  adding: dvs/0096.png (deflated 22%)
  adding: dvs/0068.png (deflated 5%)
  adding: dvs/0181.png (deflated 2%)
  adding: dvs/0180.png (stored 0%)
  adding: dvs/0076.png (deflated 8%)
  adding: dvs/0079.png (stored 0%)
  adding: dvs/0078.png (stored 0%)
  adding: dvs/0125.png (deflated 11%)
  adding: dvs/0127.png (deflated 10%)
  adding: dvs/0099.png (deflated 17%)
  adding: dvs/0194.png (stored 0%)
  adding: dvs/0008.png (deflated 18%)
  adding: dvs/0028.png (deflated 1%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (deflated 5%)
  adding: dvs/0118.png (stored 0%)
  adding: dvs/0103.png (deflated 35%)
  adding: dvs/0092.png (deflated 3%)
  adding: dvs/0012.png (deflated 15%)
  adding: dvs/0133.png (deflated 26%)
  adding: dvs/0165.png (deflated 35%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (deflated 3%)
  adding: dvs/0155.png (deflated 5%)
  adding: dvs/0193.png (stored 0%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (stored 0%)
  adding: dvs/0144.png (stored 0%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0016.png (deflated 12%)
  adding: dvs/0202.png (deflated 6%)
  adding: dvs/0208.png (deflated 1%)
  adding: dvs/0114.png (stored 0%)
  adding: dvs/0107.png (deflated 11%)
  adding: dvs/0123.png (deflated 8%)
  adding: dvs/0109.png (stored 0%)
  adding: dvs/0189.png (deflated 2%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0058.png (stored 0%)
  adding: dvs/0153.png (deflated 0%)
  adding: dvs/0217.png (stored 0%)
  adding: dvs/0139.png (deflated 0%)
  adding: dvs/0174.png (stored 0%)
  adding: dvs/0192.png (stored 0%)
  adding: dvs/0169.png (deflated 23%)
  adding: dvs/0098.png (deflated 18%)
  adding: dvs/0048.png (stored 0%)
  adding: dvs/0089.png (deflated 1%)
  adding: dvs/0122.png (deflated 11%)
  adding: dvs/0002.png (deflated 36%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (stored 0%)
  adding: dvs/0176.png (stored 0%)
  adding: dvs/0213.png (deflated 0%)
  adding: dvs/0136.png (deflated 42%)
  adding: dvs/0214.png (deflated 0%)
  adding: dvs/0005.png (stored 0%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (deflated 30%)
  adding: dvs/0124.png (deflated 6%)
  adding: dvs/0204.png (stored 0%)
  adding: dvs/0087.png (deflated 5%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0173.png (stored 0%)
  adding: dvs/0186.png (deflated 1%)
  adding: dvs/0131.png (deflated 19%)
  adding: dvs/0210.png (stored 0%)
  adding: dvs/0119.png (deflated 0%)
  adding: dvs/0216.png (stored 0%)
  adding: dvs/0083.png (stored 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (deflated 12%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 16%)
  adding: aps/0140.png (deflated 22%)
  adding: aps/0104.png (deflated 19%)
  adding: aps/0160.png (deflated 18%)
  adding: aps/0105.png (deflated 20%)
  adding: aps/0199.png (deflated 27%)
  adding: aps/0134.png (deflated 16%)
  adding: aps/0077.png (deflated 17%)
  adding: aps/0011.png (deflated 16%)
  adding: aps/0026.png (deflated 18%)
  adding: aps/0154.png (deflated 19%)
  adding: aps/0128.png (deflated 16%)
  adding: aps/0171.png (deflated 18%)
  adding: aps/0108.png (deflated 19%)
  adding: aps/0145.png (deflated 19%)
  adding: aps/0120.png (deflated 16%)
  adding: aps/0163.png (deflated 19%)
  adding: aps/0084.png (deflated 19%)
  adding: aps/0066.png (deflated 16%)
  adding: aps/0010.png (deflated 16%)
  adding: aps/0191.png (deflated 16%)
  adding: aps/0007.png (deflated 16%)
  adding: aps/0071.png (deflated 16%)
  adding: aps/0053.png (deflated 18%)
  adding: aps/0161.png (deflated 18%)
  adding: aps/0062.png (deflated 16%)
  adding: aps/0082.png (deflated 22%)
  adding: aps/0197.png (deflated 16%)
  adding: aps/0143.png (deflated 20%)
  adding: aps/0184.png (deflated 17%)
  adding: aps/0178.png (deflated 17%)
  adding: aps/0054.png (deflated 19%)
  adding: aps/0022.png (deflated 24%)
  adding: aps/0045.png (deflated 19%)
  adding: aps/0086.png (deflated 18%)
  adding: aps/0117.png (deflated 17%)
  adding: aps/0052.png (deflated 18%)
  adding: aps/0126.png (deflated 16%)
  adding: aps/0150.png (deflated 18%)
  adding: aps/0042.png (deflated 19%)
  adding: aps/0112.png (deflated 18%)
  adding: aps/0168.png (deflated 18%)
  adding: aps/0075.png (deflated 17%)
  adding: aps/0036.png (deflated 19%)
  adding: aps/0207.png (deflated 19%)
  adding: aps/0095.png (deflated 19%)
  adding: aps/0065.png (deflated 16%)
  adding: aps/0057.png (deflated 17%)
  adding: aps/0033.png (deflated 20%)
  adding: aps/0211.png (deflated 19%)
  adding: aps/0182.png (deflated 16%)
  adding: aps/0091.png (deflated 17%)
  adding: aps/0067.png (deflated 16%)
  adding: aps/0081.png (deflated 23%)
  adding: aps/0047.png (deflated 19%)
  adding: aps/0151.png (deflated 20%)
  adding: aps/0056.png (deflated 18%)
  adding: aps/0142.png (deflated 21%)
  adding: aps/0044.png (deflated 19%)
  adding: aps/0020.png (deflated 26%)
  adding: aps/0106.png (deflated 19%)
  adding: aps/0072.png (deflated 16%)
  adding: aps/0113.png (deflated 18%)
  adding: aps/0043.png (deflated 18%)
  adding: aps/0157.png (deflated 18%)
  adding: aps/0013.png (deflated 16%)
  adding: aps/0158.png (deflated 18%)
  adding: aps/0034.png (deflated 19%)
  adding: aps/0138.png (deflated 16%)
  adding: aps/0100.png (deflated 19%)
  adding: aps/0175.png (deflated 18%)
  adding: aps/0167.png (deflated 19%)
  adding: aps/0041.png (deflated 18%)
  adding: aps/0177.png (deflated 17%)
  adding: aps/0032.png (deflated 18%)
  adding: aps/0093.png (deflated 19%)
  adding: aps/0004.png (deflated 17%)
  adding: aps/0006.png (deflated 17%)
  adding: aps/0159.png (deflated 18%)
  adding: aps/0188.png (deflated 17%)
  adding: aps/0030.png (deflated 18%)
  adding: aps/0130.png (deflated 16%)
  adding: aps/0132.png (deflated 16%)
  adding: aps/0009.png (deflated 16%)
  adding: aps/0205.png (deflated 18%)
  adding: aps/0215.png (deflated 19%)
  adding: aps/0162.png (deflated 19%)
  adding: aps/0209.png (deflated 18%)
  adding: aps/0017.png (deflated 16%)
  adding: aps/0051.png (deflated 19%)
  adding: aps/0190.png (deflated 16%)
  adding: aps/0170.png (deflated 22%)
  adding: aps/0035.png (deflated 20%)
  adding: aps/0201.png (deflated 22%)
  adding: aps/0018.png (deflated 16%)
  adding: aps/0156.png (deflated 18%)
  adding: aps/0196.png (deflated 17%)
  adding: aps/0147.png (deflated 20%)
  adding: aps/0183.png (deflated 16%)
  adding: aps/0198.png (deflated 16%)
  adding: aps/0069.png (deflated 16%)
  adding: aps/0148.png (deflated 19%)
  adding: aps/0060.png (deflated 17%)
  adding: aps/0003.png (deflated 16%)
  adding: aps/0187.png (deflated 16%)
  adding: aps/0029.png (deflated 18%)
  adding: aps/0115.png (deflated 18%)
  adding: aps/0141.png (deflated 22%)
  adding: aps/0001.png (deflated 17%)
  adding: aps/0200.png (deflated 25%)
  adding: aps/0046.png (deflated 19%)
  adding: aps/0135.png (deflated 16%)
  adding: aps/0080.png (deflated 26%)
  adding: aps/0094.png (deflated 19%)
  adding: aps/0212.png (deflated 19%)
  adding: aps/0090.png (deflated 19%)
  adding: aps/0203.png (deflated 19%)
  adding: aps/0049.png (deflated 33%)
  adding: aps/0164.png (deflated 19%)
  adding: aps/0024.png (deflated 19%)
  adding: aps/0061.png (deflated 16%)
  adding: aps/0039.png (deflated 18%)
  adding: aps/0101.png (deflated 19%)
  adding: aps/0152.png (deflated 19%)
  adding: aps/0097.png (deflated 19%)
  adding: aps/0059.png (deflated 17%)
  adding: aps/0038.png (deflated 19%)
  adding: aps/0070.png (deflated 16%)
  adding: aps/0129.png (deflated 16%)
  adding: aps/0206.png (deflated 17%)
  adding: aps/0037.png (deflated 19%)
  adding: aps/0073.png (deflated 16%)
  adding: aps/0116.png (deflated 16%)
  adding: aps/0185.png (deflated 16%)
  adding: aps/0021.png (deflated 23%)
  adding: aps/0137.png (deflated 16%)
  adding: aps/0015.png (deflated 17%)
  adding: aps/0166.png (deflated 19%)
  adding: aps/0146.png (deflated 18%)
  adding: aps/0121.png (deflated 16%)
  adding: aps/0027.png (deflated 18%)
  adding: aps/0040.png (deflated 19%)
  adding: aps/0074.png (deflated 16%)
  adding: aps/0149.png (deflated 18%)
  adding: aps/0096.png (deflated 19%)
  adding: aps/0068.png (deflated 16%)
  adding: aps/0181.png (deflated 16%)
  adding: aps/0180.png (deflated 17%)
  adding: aps/0076.png (deflated 17%)
  adding: aps/0079.png (deflated 24%)
  adding: aps/0078.png (deflated 16%)
  adding: aps/0125.png (deflated 16%)
  adding: aps/0127.png (deflated 16%)
  adding: aps/0099.png (deflated 19%)
  adding: aps/0194.png (deflated 17%)
  adding: aps/0008.png (deflated 16%)
  adding: aps/0028.png (deflated 19%)
  adding: aps/0050.png (deflated 21%)
  adding: aps/0088.png (deflated 18%)
  adding: aps/0118.png (deflated 17%)
  adding: aps/0103.png (deflated 19%)
  adding: aps/0092.png (deflated 19%)
  adding: aps/0012.png (deflated 16%)
  adding: aps/0133.png (deflated 16%)
  adding: aps/0165.png (deflated 19%)
  adding: aps/0031.png (deflated 19%)
  adding: aps/0064.png (deflated 16%)
  adding: aps/0155.png (deflated 18%)
  adding: aps/0193.png (deflated 17%)
  adding: aps/0055.png (deflated 18%)
  adding: aps/0195.png (deflated 16%)
  adding: aps/0144.png (deflated 19%)
  adding: aps/0110.png (deflated 22%)
  adding: aps/0016.png (deflated 16%)
  adding: aps/0202.png (deflated 24%)
  adding: aps/0208.png (deflated 20%)
  adding: aps/0114.png (deflated 18%)

'The chosen video file: /content/video/key_1hz.MOV'

FPS: 29.972875226039783
Frame count: 221
Duration: 7.37 sec
The Final v2e command:

'v2e -i /content/video/key_1hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/key_1hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/key_1hz.MOV
INFO:v2e:Input video frame rate 29.972875226039783Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/key_1hz.MOV has total 221 frames with total duration 7.33s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 221 frames 0 to 220
(From 0.0s to 7.333333333333333s, duration 7.333333333333333s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 220.0 frames with duration 7.33s and playback duration 7.33s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 220 from video input
INFO:v2e:Input video /content/video/key_1hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 221 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/221 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 221/221 [00:08<00:00, 25.40fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmp9m18ml6y
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 28 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/28 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 183
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/28 [00:50<22:34, 50.15s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 71
slomo-interp:   7% 2/28 [01:10<14:11, 32.74s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 165
slomo-interp: 100% 28/28 [14:05<00:00, 30.20s/ batch of 8 fr]
write-orig-avi: 100% 221/221 [00:00<00:00, 883.88fr/s]
write-slomo-vid: 100% 24664/24664 [00:55<00:00, 443.08fr/s]
INFO:v2ecore.slomo:Wrote 24664 frames and returning 24664 frame times.
Average upsampling factor=113.4
INFO:v2e:SloMo average upsampling factor=113.39; average DVS timestamp resolution=293.96us
INFO:v2e:*** Stage 3/3: emulating DVS events from 24664 frames
dvs:   0% 0/24664 [00:00<?, ?fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2 at t=0.0002s
WARNING:v2ecore.emulator:no signal events generated for frame #3 at t=0.0004s
WARNING:v2ecore.emulator:no signal events generated for frame #4 at t=0.0005s
WARNING:v2ecore.emulator:no signal events generated for frame #5 at t=0.0007s
WARNING:v2ecore.emulator:no signal events generated for frame #6 at t=0.0009s
WARNING:v2ecore.emulator:no signal events generated for frame #7 at t=0.0011s
WARNING:v2ecore.emulator:no signal events generated for frame #8 at t=0.0013s
WARNING:v2ecore.emulator:no signal events generated for frame #9 at t=0.0015s
WARNING:v2ecore.emulator:no signal events generated for frame #10 at t=0.0016s
WARNING:v2ecore.emulator:no signal events generated for frame #11 at t=0.0018s
WARNING:v2ecore.emulator:no signal events generated for frame #12 at t=0.0020s
dvs:   0% 13/24664 [00:00<03:55, 104.57fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #14 at t=0.0024s
INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:   2% 551/24664 [00:08<04:41, 85.67fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #553 at t=0.1005s
dvs:   3% 729/24664 [00:11<04:26, 89.93fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #737 at t=0.1341s
dvs:   4% 916/24664 [00:13<04:44, 83.33fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #917 at t=0.1669s
dvs:   8% 2035/24664 [00:36<04:50, 78.03fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,036 at t=0.5340s
WARNING:v2ecore.emulator:no signal events generated for frame #2,037 at t=0.5342s
dvs:   8% 2066/24664 [00:36<05:55, 63.52fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,068 at t=0.5404s
WARNING:v2ecore.emulator:no signal events generated for frame #2,072 at t=0.5412s
dvs:   9% 2197/24664 [00:38<04:23, 85.17fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,199 at t=0.5669s
WARNING:v2ecore.emulator:no signal events generated for frame #2,204 at t=0.5679s
dvs:   9% 2208/24664 [00:38<04:05, 91.65fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,209 at t=0.5689s
WARNING:v2ecore.emulator:no signal events generated for frame #2,214 at t=0.5699s
dvs:   9% 2218/24664 [00:38<05:39, 66.13fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,221 at t=0.5713s
dvs:  13% 3184/24664 [00:53<04:12, 84.94fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,194 at t=0.7679s
dvs:  13% 3194/24664 [00:53<04:45, 75.30fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,195 at t=0.7681s
WARNING:v2ecore.emulator:no signal events generated for frame #3,196 at t=0.7683s
WARNING:v2ecore.emulator:no signal events generated for frame #3,197 at t=0.7685s
dvs:  13% 3210/24664 [00:53<05:56, 60.22fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,214 at t=0.7719s
WARNING:v2ecore.emulator:no signal events generated for frame #3,219 at t=0.7729s
WARNING:v2ecore.emulator:no signal events generated for frame #3,220 at t=0.7732s
dvs:  13% 3221/24664 [00:53<05:02, 70.84fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,224 at t=0.7740s
WARNING:v2ecore.emulator:no signal events generated for frame #3,225 at t=0.7742s
WARNING:v2ecore.emulator:no signal events generated for frame #3,228 at t=0.7748s
WARNING:v2ecore.emulator:no signal events generated for frame #3,230 at t=0.7752s
WARNING:v2ecore.emulator:no signal events generated for frame #3,233 at t=0.7758s
WARNING:v2ecore.emulator:no signal events generated for frame #3,234 at t=0.7760s
WARNING:v2ecore.emulator:no signal events generated for frame #3,242 at t=0.7776s
dvs:  13% 3242/24664 [00:54<03:47, 94.13fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,243 at t=0.7778s
dvs:  13% 3252/24664 [00:54<03:44, 95.23fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,257 at t=0.7806s
WARNING:v2ecore.emulator:no signal events generated for frame #3,260 at t=0.7812s
WARNING:v2ecore.emulator:no signal events generated for frame #3,262 at t=0.7816s
dvs:  13% 3266/24664 [00:54<03:27, 103.05fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,268 at t=0.7828s
WARNING:v2ecore.emulator:no signal events generated for frame #3,270 at t=0.7833s
WARNING:v2ecore.emulator:no signal events generated for frame #3,276 at t=0.7845s
dvs:  13% 3277/24664 [00:54<03:24, 104.46fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,280 at t=0.7853s
WARNING:v2ecore.emulator:no signal events generated for frame #3,281 at t=0.7855s
WARNING:v2ecore.emulator:no signal events generated for frame #3,284 at t=0.7861s
WARNING:v2ecore.emulator:no signal events generated for frame #3,287 at t=0.7867s
WARNING:v2ecore.emulator:no signal events generated for frame #3,289 at t=0.7871s
WARNING:v2ecore.emulator:no signal events generated for frame #3,294 at t=0.7881s
WARNING:v2ecore.emulator:no signal events generated for frame #3,295 at t=0.7883s
WARNING:v2ecore.emulator:no signal events generated for frame #3,296 at t=0.7885s
WARNING:v2ecore.emulator:no signal events generated for frame #3,298 at t=0.7889s
dvs:  13% 3298/24664 [00:54<04:19, 82.38fr/s] WARNING:v2ecore.emulator:no signal events generated for frame #3,299 at t=0.7891s
WARNING:v2ecore.emulator:no signal events generated for frame #3,301 at t=0.7895s
WARNING:v2ecore.emulator:no signal events generated for frame #3,303 at t=0.7899s
dvs:  13% 3308/24664 [00:54<04:12, 84.48fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,313 at t=0.7919s
WARNING:v2ecore.emulator:no signal events generated for frame #3,315 at t=0.7923s
WARNING:v2ecore.emulator:no signal events generated for frame #3,320 at t=0.7934s
dvs:  13% 3322/24664 [00:54<03:50, 92.39fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,330 at t=0.7954s
dvs:  14% 3333/24664 [00:55<03:54, 91.13fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,334 at t=0.7962s
WARNING:v2ecore.emulator:no signal events generated for frame #3,339 at t=0.7972s
dvs:  16% 3935/24664 [01:04<04:06, 84.24fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,939 at t=1.0671s
WARNING:v2ecore.emulator:no signal events generated for frame #3,940 at t=1.0673s
dvs:  16% 3946/24664 [01:05<04:25, 78.03fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,947 at t=1.0686s
WARNING:v2ecore.emulator:no signal events generated for frame #3,953 at t=1.0697s
WARNING:v2ecore.emulator:no signal events generated for frame #3,954 at t=1.0699s
WARNING:v2ecore.emulator:no signal events generated for frame #3,956 at t=1.0703s
dvs:  16% 3962/24664 [01:05<04:56, 69.82fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,965 at t=1.0719s
dvs:  16% 3981/24664 [01:05<04:23, 78.46fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,982 at t=1.0751s
WARNING:v2ecore.emulator:no signal events generated for frame #3,984 at t=1.0755s
WARNING:v2ecore.emulator:no signal events generated for frame #3,986 at t=1.0759s
dvs:  16% 3992/24664 [01:05<04:01, 85.48fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,998 at t=1.0781s
WARNING:v2ecore.emulator:no signal events generated for frame #3,999 at t=1.0783s
dvs:  16% 4002/24664 [01:05<04:28, 76.97fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,003 at t=1.0791s
dvs:  16% 4012/24664 [01:05<04:10, 82.29fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,016 at t=1.0815s
WARNING:v2ecore.emulator:no signal events generated for frame #4,018 at t=1.0819s
dvs:  16% 4022/24664 [01:06<03:59, 86.25fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,027 at t=1.0835s
dvs:  16% 4042/24664 [01:06<04:23, 78.14fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,050 at t=1.0879s
dvs:  16% 4053/24664 [01:06<04:01, 85.36fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,063 at t=1.0903s
dvs:  17% 4072/24664 [01:06<04:02, 84.98fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,075 at t=1.0925s
WARNING:v2ecore.emulator:no signal events generated for frame #4,076 at t=1.0927s
WARNING:v2ecore.emulator:no signal events generated for frame #4,080 at t=1.0935s
dvs:  17% 4092/24664 [01:06<04:11, 81.84fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,094 at t=1.0961s
WARNING:v2ecore.emulator:no signal events generated for frame #4,096 at t=1.0965s
WARNING:v2ecore.emulator:no signal events generated for frame #4,100 at t=1.0972s
dvs:  17% 4103/24664 [01:07<03:51, 88.95fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,105 at t=1.0982s
WARNING:v2ecore.emulator:no signal events generated for frame #4,108 at t=1.0987s
WARNING:v2ecore.emulator:no signal events generated for frame #4,110 at t=1.0991s
dvs:  17% 4124/24664 [01:07<03:35, 95.10fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,125 at t=1.1019s
dvs:  17% 4143/24664 [01:07<04:45, 71.83fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,146 at t=1.1058s
dvs:  17% 4152/24664 [01:07<04:29, 76.07fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,161 at t=1.1086s
dvs:  17% 4161/24664 [01:07<04:18, 79.41fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,165 at t=1.1094s
WARNING:v2ecore.emulator:no signal events generated for frame #4,166 at t=1.1096s
dvs:  17% 4190/24664 [01:08<05:15, 64.80fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,192 at t=1.1144s
dvs:  17% 4218/24664 [01:08<04:52, 69.91fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,227 at t=1.1210s
dvs:  17% 4269/24664 [01:09<04:09, 81.91fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,273 at t=1.1296s
WARNING:v2ecore.emulator:no signal events generated for frame #4,280 at t=1.1309s
dvs:  18% 4322/24664 [01:10<06:00, 56.39fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,333 at t=1.1409s
dvs: 100% 24664/24664 [07:05<00:00, 57.92fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 219 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 221 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 24664 frames
INFO:v2e:generated total 38.48M events (19.07M on, 19.41M off)
INFO:v2e:Avg event rate for N=89960 px and total time =7.333 s
	Total: 5.25MHz (2.60MHz on, 2.65MHz off)
	Per pixel:  58.34Hz (28.91Hz on, 29.43Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 442 frames in 1.34ks (3.03s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 219 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 221 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 24664 frames
Total events: 38,484,464
  Written 5,000,000/38,484,464
  Written 10,000,000/38,484,464
  Written 15,000,000/38,484,464
  Written 20,000,000/38,484,464
  Written 25,000,000/38,484,464
  Written 30,000,000/38,484,464
  Written 35,000,000/38,484,464
  Written 38,484,464/38,484,464
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 221
Output folder: /content/v2e-output/aps
APS frames found: 221
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/221 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:07.37, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:07.37, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x55961bace840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x55961bad72c0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x55961baeb480] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x55961baeb480] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x55961baeb480] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  221 fps= 47 q=-1.0 Lsize=    3832kB time=00:00:07.26 bitrate=4320.3kbits/s speed=1.54x
video:3830kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.072142%
[libx264 @ 0x55961baeb480] frame I:19    Avg QP:26.33  size: 43212
[libx264 @ 0x55961baeb480] frame P:121   Avg QP:28.94  size: 19648
[libx264 @ 0x55961baeb480] frame B:81    Avg QP:30.37  size:  8917
[libx264 @ 0x55961baeb480] consecutive B-frames: 47.1%  9.0%  9.5% 34.4%
[libx264 @ 0x55961baeb480] mb I  I16..4:  1.7% 53.4% 44.9%
[libx264 @ 0x55961baeb480] mb P  I16..4:  7.8% 34.4% 26.8%  P16..4: 13.3%  1.9%  1.4%  0.0%  0.0%    skip:14.5%
[libx264 @ 0x55961baeb480] mb B  I16..4:  7.2%  3.1%  6.8%  B16..8: 25.3%  3.7%  2.0%  direct: 2.6%  skip:49.4%  L0:36.8% L1:61.4% BI: 1.7%
[libx264 @ 0x55961baeb480] 8x8 transform intra:46.6% inter:54.0%
[libx264 @ 0x55961baeb480] coded y,uvDC,uvAC intra: 66.5% 44.5% 42.3% inter: 19.0% 5.2% 2.1%
[libx264 @ 0x55961baeb480] i16 v,h,dc,p: 34% 14% 46%  5%
[libx264 @ 0x55961baeb480] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 52%  9% 28%  2%  1%  2%  1%  3%  2%
[libx264 @ 0x55961baeb480] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 12% 31%  6%  5%  6%  5%  5%  4%
[libx264 @ 0x55961baeb480] i8c dc,h,v,p: 77%  5% 13%  4%
[libx264 @ 0x55961baeb480] Weighted P-Frames: Y:28.1% UV:23.1%
[libx264 @ 0x55961baeb480] ref P L0: 57.1% 20.8% 13.7%  7.9%  0.5%
[libx264 @ 0x55961baeb480] ref B L0: 83.6% 14.8%  1.6%
[libx264 @ 0x55961baeb480] ref B L1: 89.7% 10.3%
[libx264 @ 0x55961baeb480] kb/s:4257.83
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (deflated 4%)
  adding: dvs/0140.png (deflated 5%)
  adding: dvs/0104.png (stored 0%)
  adding: dvs/0160.png (stored 0%)
  adding: dvs/0105.png (stored 0%)
  adding: dvs/0199.png (deflated 1%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0077.png (deflated 0%)
  adding: dvs/0011.png (stored 0%)
  adding: dvs/0026.png (stored 0%)
  adding: dvs/0154.png (deflated 5%)
  adding: dvs/0128.png (stored 0%)
  adding: dvs/0171.png (deflated 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0120.png (stored 0%)
  adding: dvs/0163.png (stored 0%)
  adding: dvs/0084.png (stored 0%)
  adding: dvs/0066.png (stored 0%)
  adding: dvs/0010.png (stored 0%)
  adding: dvs/0191.png (stored 0%)
  adding: dvs/0007.png (deflated 73%)
  adding: dvs/0071.png (stored 0%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (stored 0%)
  adding: dvs/0062.png (stored 0%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0221.png (stored 0%)
  adding: dvs/0197.png (deflated 1%)
  adding: dvs/0143.png (deflated 0%)
  adding: dvs/0184.png (deflated 5%)
  adding: dvs/0178.png (stored 0%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (stored 0%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (stored 0%)
  adding: dvs/0126.png (stored 0%)
  adding: dvs/0219.png (deflated 7%)
  adding: dvs/0150.png (stored 0%)
  adding: dvs/0042.png (stored 0%)
  adding: dvs/0220.png (stored 0%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (deflated 4%)
  adding: dvs/0075.png (stored 0%)
  adding: dvs/0036.png (stored 0%)
  adding: dvs/0207.png (stored 0%)
  adding: dvs/0095.png (deflated 5%)
  adding: dvs/0065.png (deflated 8%)
  adding: dvs/0057.png (stored 0%)
  adding: dvs/0033.png (deflated 2%)
  adding: dvs/0211.png (stored 0%)
  adding: dvs/0182.png (deflated 0%)
  adding: dvs/0091.png (stored 0%)
  adding: dvs/0067.png (stored 0%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0047.png (stored 0%)
  adding: dvs/0151.png (stored 0%)
  adding: dvs/0056.png (stored 0%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (stored 0%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0072.png (stored 0%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (stored 0%)
  adding: dvs/0013.png (stored 0%)
  adding: dvs/0158.png (deflated 1%)
  adding: dvs/0034.png (deflated 1%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (stored 0%)
  adding: dvs/0175.png (stored 0%)
  adding: dvs/0167.png (stored 0%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0177.png (stored 0%)
  adding: dvs/0032.png (stored 0%)
  adding: dvs/0093.png (deflated 1%)
  adding: dvs/0004.png (deflated 1%)
  adding: dvs/0006.png (stored 0%)
  adding: dvs/0159.png (deflated 8%)
  adding: dvs/0188.png (deflated 76%)
  adding: dvs/0030.png (stored 0%)
  adding: dvs/0130.png (stored 0%)
  adding: dvs/0132.png (stored 0%)
  adding: dvs/0009.png (stored 0%)
  adding: dvs/0205.png (stored 0%)
  adding: dvs/0215.png (deflated 2%)
  adding: dvs/0162.png (stored 0%)
  adding: dvs/0209.png (stored 0%)
  adding: dvs/0017.png (deflated 1%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (stored 0%)
  adding: dvs/0170.png (deflated 21%)
  adding: dvs/0035.png (deflated 2%)
  adding: dvs/0201.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (deflated 10%)
  adding: dvs/0196.png (stored 0%)
  adding: dvs/0147.png (stored 0%)
  adding: dvs/0183.png (stored 0%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0069.png (deflated 0%)
  adding: dvs/0148.png (stored 0%)
  adding: dvs/0060.png (stored 0%)
  adding: dvs/0003.png (deflated 6%)
  adding: dvs/0187.png (stored 0%)
  adding: dvs/0029.png (stored 0%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0001.png (deflated 23%)
  adding: dvs/0200.png (deflated 2%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0135.png (stored 0%)
  adding: dvs/0080.png (deflated 14%)
  adding: dvs/0094.png (deflated 7%)
  adding: dvs/0212.png (stored 0%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0203.png (deflated 2%)
  adding: dvs/0049.png (deflated 9%)
  adding: dvs/0164.png (stored 0%)
  adding: dvs/0024.png (stored 0%)
  adding: dvs/0061.png (stored 0%)
  adding: dvs/0039.png (stored 0%)
  adding: dvs/0101.png (stored 0%)
  adding: dvs/0152.png (deflated 0%)
  adding: dvs/0097.png (stored 0%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (stored 0%)
  adding: dvs/0070.png (stored 0%)
  adding: dvs/0129.png (deflated 0%)
  adding: dvs/0206.png (stored 0%)
  adding: dvs/0037.png (deflated 14%)
  adding: dvs/0073.png (stored 0%)
  adding: dvs/0116.png (stored 0%)
  adding: dvs/0185.png (deflated 7%)
  adding: dvs/0021.png (deflated 13%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0015.png (stored 0%)
  adding: dvs/0166.png (stored 0%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0121.png (stored 0%)
  adding: dvs/0027.png (stored 0%)
  adding: dvs/0040.png (stored 0%)
  adding: dvs/0074.png (stored 0%)
  adding: dvs/0149.png (stored 0%)
  adding: dvs/0096.png (stored 0%)
  adding: dvs/0068.png (stored 0%)
  adding: dvs/0181.png (stored 0%)
  adding: dvs/0180.png (stored 0%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (deflated 11%)
  adding: dvs/0078.png (deflated 2%)
  adding: dvs/0125.png (deflated 10%)
  adding: dvs/0127.png (stored 0%)
  adding: dvs/0099.png (deflated 1%)
  adding: dvs/0194.png (stored 0%)
  adding: dvs/0008.png (deflated 8%)
  adding: dvs/0028.png (stored 0%)
  adding: dvs/0050.png (deflated 7%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (stored 0%)
  adding: dvs/0103.png (stored 0%)
  adding: dvs/0092.png (stored 0%)
  adding: dvs/0012.png (stored 0%)
  adding: dvs/0133.png (stored 0%)
  adding: dvs/0165.png (stored 0%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (deflated 8%)
  adding: dvs/0155.png (deflated 5%)
  adding: dvs/0193.png (stored 0%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (stored 0%)
  adding: dvs/0144.png (stored 0%)
  adding: dvs/0110.png (deflated 6%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0202.png (deflated 2%)
  adding: dvs/0208.png (stored 0%)
  adding: dvs/0114.png (stored 0%)
  adding: dvs/0107.png (stored 0%)
  adding: dvs/0123.png (stored 0%)
  adding: dvs/0109.png (deflated 8%)
  adding: dvs/0189.png (deflated 25%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0058.png (stored 0%)
  adding: dvs/0153.png (stored 0%)
  adding: dvs/0217.png (stored 0%)
  adding: dvs/0139.png (deflated 3%)
  adding: dvs/0174.png (stored 0%)
  adding: dvs/0192.png (stored 0%)
  adding: dvs/0169.png (deflated 15%)
  adding: dvs/0098.png (stored 0%)
  adding: dvs/0218.png (deflated 63%)
  adding: dvs/0048.png (deflated 0%)
  adding: dvs/0089.png (stored 0%)
  adding: dvs/0122.png (stored 0%)
  adding: dvs/0002.png (deflated 3%)
  adding: dvs/0111.png (deflated 1%)
  adding: dvs/0172.png (stored 0%)
  adding: dvs/0176.png (stored 0%)
  adding: dvs/0213.png (stored 0%)
  adding: dvs/0136.png (stored 0%)
  adding: dvs/0214.png (stored 0%)
  adding: dvs/0005.png (deflated 1%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (stored 0%)
  adding: dvs/0124.png (deflated 10%)
  adding: dvs/0204.png (stored 0%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0173.png (deflated 0%)
  adding: dvs/0186.png (deflated 8%)
  adding: dvs/0131.png (stored 0%)
  adding: dvs/0210.png (stored 0%)
  adding: dvs/0119.png (stored 0%)
  adding: dvs/0216.png (deflated 3%)
  adding: dvs/0083.png (stored 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (stored 0%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 17%)
  adding: aps/0140.png (deflated 18%)
  adding: aps/0104.png (deflated 19%)
  adding: aps/0160.png (deflated 21%)
  adding: aps/0105.png (deflated 19%)
  adding: aps/0199.png (deflated 17%)
  adding: aps/0134.png (deflated 19%)
  adding: aps/0077.png (deflated 18%)
  adding: aps/0011.png (deflated 22%)
  adding: aps/0026.png (deflated 19%)
  adding: aps/0154.png (deflated 17%)
  adding: aps/0128.png (deflated 32%)
  adding: aps/0171.png (deflated 19%)
  adding: aps/0108.png (deflated 19%)
  adding: aps/0145.png (deflated 26%)
  adding: aps/0120.png (deflated 17%)
  adding: aps/0163.png (deflated 19%)
  adding: aps/0084.png (deflated 21%)
  adding: aps/0066.png (deflated 17%)
  adding: aps/0010.png (deflated 22%)
  adding: aps/0191.png (deflated 19%)
  adding: aps/0007.png (deflated 16%)
  adding: aps/0071.png (deflated 20%)
  adding: aps/0053.png (deflated 29%)
  adding: aps/0161.png (deflated 19%)
  adding: aps/0062.png (deflated 16%)
  adding: aps/0082.png (deflated 27%)
  adding: aps/0221.png (deflated 21%)
  adding: aps/0197.png (deflated 18%)
  adding: aps/0143.png (deflated 35%)
  adding: aps/0184.png (deflated 17%)
  adding: aps/0178.png (deflated 17%)
  adding: aps/0054.png (deflated 21%)
  adding: aps/0022.png (deflated 23%)
  adding: aps/0045.png (deflated 18%)
  adding: aps/0086.png (deflated 19%)
  adding: aps/0117.png (deflated 19%)
  adding: aps/0052.png (deflated 23%)
  adding: aps/0126.png (deflated 16%)
  adding: aps/0219.png (deflated 25%)
  adding: aps/0150.png (deflated 17%)
  adding: aps/0042.png (deflated 20%)
  adding: aps/0220.png (deflated 21%)
  adding: aps/0112.png (deflated 19%)
  adding: aps/0168.png (deflated 18%)
  adding: aps/0075.png (deflated 18%)
  adding: aps/0036.png (deflated 16%)
  adding: aps/0207.png (deflated 18%)
  adding: aps/0095.png (deflated 16%)
  adding: aps/0065.png (deflated 16%)
  adding: aps/0057.png (deflated 18%)
  adding: aps/0033.png (deflated 16%)
  adding: aps/0211.png (deflated 17%)
  adding: aps/0182.png (deflated 16%)
  adding: aps/0091.png (deflated 17%)
  adding: aps/0067.png (deflated 16%)
  adding: aps/0081.png (deflated 19%)
  adding: aps/0047.png (deflated 18%)
  adding: aps/0151.png (deflated 17%)
  adding: aps/0056.png (deflated 20%)
  adding: aps/0142.png (deflated 19%)
  adding: aps/0044.png (deflated 19%)
  adding: aps/0020.png (deflated 18%)
  adding: aps/0106.png (deflated 18%)
  adding: aps/0072.png (deflated 19%)
  adding: aps/0113.png (deflated 36%)
  adding: aps/0043.png (deflated 19%)
  adding: aps/0157.png (deflated 17%)
  adding: aps/0013.png (deflated 20%)
  adding: aps/0158.png (deflated 34%)
  adding: aps/0034.png (deflated 17%)
  adding: aps/0138.png (deflated 18%)
  adding: aps/0100.png (deflated 22%)
  adding: aps/0175.png (deflated 25%)
  adding: aps/0167.png (deflated 18%)
  adding: aps/0041.png (deflated 21%)
  adding: aps/0177.png (deflated 18%)
  adding: aps/0032.png (deflated 17%)
  adding: aps/0093.png (deflated 17%)
  adding: aps/0004.png (deflated 17%)
  adding: aps/0006.png (deflated 17%)
  adding: aps/0159.png (deflated 23%)
  adding: aps/0188.png (deflated 34%)
  adding: aps/0030.png (deflated 17%)
  adding: aps/0130.png (deflated 22%)
  adding: aps/0132.png (deflated 19%)
  adding: aps/0009.png (deflated 24%)
  adding: aps/0205.png (deflated 23%)
  adding: aps/0215.png (deflated 16%)
  adding: aps/0162.png (deflated 19%)
  adding: aps/0209.png (deflated 17%)
  adding: aps/0017.png (deflated 18%)
  adding: aps/0051.png (deflated 20%)
  adding: aps/0190.png (deflated 21%)
  adding: aps/0170.png (deflated 18%)
  adding: aps/0035.png (deflated 16%)
  adding: aps/0201.png (deflated 20%)
  adding: aps/0018.png (deflated 19%)
  adding: aps/0156.png (deflated 17%)
  adding: aps/0196.png (deflated 18%)
  adding: aps/0147.png (deflated 18%)
  adding: aps/0183.png (deflated 17%)
  adding: aps/0198.png (deflated 18%)
  adding: aps/0069.png (deflated 25%)
  adding: aps/0148.png (deflated 17%)
  adding: aps/0060.png (deflated 17%)
  adding: aps/0003.png (deflated 16%)
  adding: aps/0187.png (deflated 16%)
  adding: aps/0029.png (deflated 17%)
  adding: aps/0115.png (deflated 26%)
  adding: aps/0141.png (deflated 20%)
  adding: aps/0001.png (deflated 17%)
  adding: aps/0200.png (deflated 18%)
  adding: aps/0046.png (deflated 18%)
  adding: aps/0135.png (deflated 18%)
  adding: aps/0080.png (deflated 18%)
  adding: aps/0094.png (deflated 17%)
  adding: aps/0212.png (deflated 17%)
  adding: aps/0090.png (deflated 17%)
  adding: aps/0203.png (deflated 35%)
  adding: aps/0049.png (deflated 17%)
  adding: aps/0164.png (deflated 19%)
  adding: aps/0024.png (deflated 22%)
  adding: aps/0061.png (deflated 17%)
  adding: aps/0039.png (deflated 30%)
  adding: aps/0101.png (deflated 20%)
  adding: aps/0152.png (deflated 17%)
  adding: aps/0097.png (deflated 16%)
  adding: aps/0059.png (deflated 17%)
  adding: aps/0038.png (deflated 34%)
  adding: aps/0070.png (deflated 21%)
  adding: aps/0129.png (deflated 23%)
  adding: aps/0206.png (deflated 19%)
  adding: aps/0037.png (deflated 16%)
  adding: aps/0073.png (deflated 19%)
  adding: aps/0116.png (deflated 20%)
  adding: aps/0185.png (deflated 17%)
  adding: aps/0021.png (deflated 20%)
  adding: aps/0137.png (deflated 18%)
  adding: aps/0015.png (deflated 19%)
  adding: aps/0166.png (deflated 19%)
  adding: aps/0146.png (deflated 19%)
  adding: aps/0121.png (deflated 17%)
  adding: aps/0027.png (deflated 18%)
  adding: aps/0040.png (deflated 23%)
  adding: aps/0074.png (deflated 18%)
  adding: aps/0149.png (deflated 17%)
  adding: aps/0096.png (deflated 16%)
  adding: aps/0068.png (deflated 36%)
  adding: aps/0181.png (deflated 17%)
  adding: aps/0180.png (deflated 17%)
  adding: aps/0076.png (deflated 18%)
  adding: aps/0079.png (deflated 18%)
  adding: aps/0078.png (deflated 18%)
  adding: aps/0125.png (deflated 16%)
  adding: aps/0127.png (deflated 17%)
  adding: aps/0099.png (deflated 23%)
  adding: aps/0194.png (deflated 19%)
  adding: aps/0008.png (deflated 36%)
  adding: aps/0028.png (deflated 17%)
  adding: aps/0050.png (deflated 18%)
  adding: aps/0088.png (deflated 19%)
  adding: aps/0118.png (deflated 17%)
  adding: aps/0103.png (deflated 19%)
  adding: aps/0092.png (deflated 17%)
  adding: aps/0012.png (deflated 20%)
  adding: aps/0133.png (deflated 19%)
  adding: aps/0165.png (deflated 18%)
  adding: aps/0031.png (deflated 17%)
  adding: aps/0064.png (deflated 17%)
  adding: aps/0155.png (deflated 17%)
  adding: aps/0193.png (deflated 19%)
  adding: aps/0055.png (deflated 21%)
  adding: aps/0195.png (deflated 19%)
  adding: aps/0144.png (deflated 29%)
  adding: aps/0110.png (deflated 18%)
  adding: aps/0016.png (deflated 18%)
  adding: aps/0202.png (deflated 21%)

'The chosen video file: /content/video/key_2hz.MOV'

FPS: 29.97104247104247
Frame count: 207
Duration: 6.91 sec
The Final v2e command:

'v2e -i /content/video/key_2hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/key_2hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/key_2hz.MOV
INFO:v2e:Input video frame rate 29.97104247104247Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/key_2hz.MOV has total 207 frames with total duration 6.87s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 207 frames 0 to 206
(From 0.0s to 6.866666666666666s, duration 6.866666666666666s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 206.0 frames with duration 6.87s and playback duration 6.87s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 206 from video input
INFO:v2e:Input video /content/video/key_2hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 207 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/207 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 207/207 [00:07<00:00, 25.93fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpkaemc_o2
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 26 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/26 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 183
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/26 [00:47<19:49, 47.59s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 137
slomo-interp:   8% 2/26 [01:24<16:29, 41.22s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 177
slomo-interp: 100% 26/26 [18:33<00:00, 42.82s/ batch of 8 fr]
write-orig-avi: 100% 207/207 [00:00<00:00, 786.48fr/s]
write-slomo-vid: 100% 33000/33000 [01:12<00:00, 452.90fr/s]
INFO:v2ecore.slomo:Wrote 33000 frames and returning 33000 frame times.
Average upsampling factor=160.0
INFO:v2e:SloMo average upsampling factor=160.00; average DVS timestamp resolution=208.33us
INFO:v2e:*** Stage 3/3: emulating DVS events from 33000 frames
dvs:   0% 2/33000 [00:00<29:00, 18.95fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:  46% 15295/33000 [04:12<03:20, 88.39fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,300 at t=3.1009s
WARNING:v2ecore.emulator:no signal events generated for frame #15,302 at t=3.1012s
WARNING:v2ecore.emulator:no signal events generated for frame #15,303 at t=3.1014s
WARNING:v2ecore.emulator:no signal events generated for frame #15,304 at t=3.1016s
WARNING:v2ecore.emulator:no signal events generated for frame #15,305 at t=3.1018s
dvs:  46% 15305/33000 [04:12<04:37, 63.73fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,307 at t=3.1022s
WARNING:v2ecore.emulator:no signal events generated for frame #15,308 at t=3.1023s
WARNING:v2ecore.emulator:no signal events generated for frame #15,309 at t=3.1025s
WARNING:v2ecore.emulator:no signal events generated for frame #15,310 at t=3.1027s
WARNING:v2ecore.emulator:no signal events generated for frame #15,311 at t=3.1029s
WARNING:v2ecore.emulator:no signal events generated for frame #15,312 at t=3.1031s
WARNING:v2ecore.emulator:no signal events generated for frame #15,313 at t=3.1033s
WARNING:v2ecore.emulator:no signal events generated for frame #15,314 at t=3.1035s
WARNING:v2ecore.emulator:no signal events generated for frame #15,316 at t=3.1038s
WARNING:v2ecore.emulator:no signal events generated for frame #15,318 at t=3.1042s
WARNING:v2ecore.emulator:no signal events generated for frame #15,319 at t=3.1044s
WARNING:v2ecore.emulator:no signal events generated for frame #15,320 at t=3.1046s
WARNING:v2ecore.emulator:no signal events generated for frame #15,322 at t=3.1049s
dvs:  46% 15322/33000 [04:13<05:09, 57.09fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,323 at t=3.1051s
WARNING:v2ecore.emulator:no signal events generated for frame #15,324 at t=3.1053s
WARNING:v2ecore.emulator:no signal events generated for frame #15,325 at t=3.1055s
WARNING:v2ecore.emulator:no signal events generated for frame #15,326 at t=3.1057s
WARNING:v2ecore.emulator:no signal events generated for frame #15,327 at t=3.1059s
WARNING:v2ecore.emulator:no signal events generated for frame #15,328 at t=3.1061s
WARNING:v2ecore.emulator:no signal events generated for frame #15,329 at t=3.1063s
WARNING:v2ecore.emulator:no signal events generated for frame #15,330 at t=3.1064s
WARNING:v2ecore.emulator:no signal events generated for frame #15,332 at t=3.1068s
WARNING:v2ecore.emulator:no signal events generated for frame #15,333 at t=3.1070s
WARNING:v2ecore.emulator:no signal events generated for frame #15,334 at t=3.1072s
WARNING:v2ecore.emulator:no signal events generated for frame #15,335 at t=3.1074s
WARNING:v2ecore.emulator:no signal events generated for frame #15,337 at t=3.1077s
WARNING:v2ecore.emulator:no signal events generated for frame #15,338 at t=3.1079s
WARNING:v2ecore.emulator:no signal events generated for frame #15,339 at t=3.1081s
WARNING:v2ecore.emulator:no signal events generated for frame #15,340 at t=3.1083s
WARNING:v2ecore.emulator:no signal events generated for frame #15,341 at t=3.1085s
WARNING:v2ecore.emulator:no signal events generated for frame #15,342 at t=3.1087s
WARNING:v2ecore.emulator:no signal events generated for frame #15,343 at t=3.1089s
WARNING:v2ecore.emulator:no signal events generated for frame #15,344 at t=3.1090s
WARNING:v2ecore.emulator:no signal events generated for frame #15,345 at t=3.1092s
WARNING:v2ecore.emulator:no signal events generated for frame #15,346 at t=3.1094s
WARNING:v2ecore.emulator:no signal events generated for frame #15,347 at t=3.1096s
WARNING:v2ecore.emulator:no signal events generated for frame #15,350 at t=3.1102s
WARNING:v2ecore.emulator:no signal events generated for frame #15,351 at t=3.1103s
WARNING:v2ecore.emulator:no signal events generated for frame #15,353 at t=3.1107s
WARNING:v2ecore.emulator:no signal events generated for frame #15,354 at t=3.1109s
WARNING:v2ecore.emulator:no signal events generated for frame #15,355 at t=3.1111s
WARNING:v2ecore.emulator:no signal events generated for frame #15,359 at t=3.1118s
dvs:  47% 15359/33000 [04:13<02:41, 109.16fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,362 at t=3.1124s
WARNING:v2ecore.emulator:no signal events generated for frame #15,363 at t=3.1126s
WARNING:v2ecore.emulator:no signal events generated for frame #15,364 at t=3.1128s
WARNING:v2ecore.emulator:no signal events generated for frame #15,365 at t=3.1130s
WARNING:v2ecore.emulator:no signal events generated for frame #15,367 at t=3.1133s
WARNING:v2ecore.emulator:no signal events generated for frame #15,368 at t=3.1135s
WARNING:v2ecore.emulator:no signal events generated for frame #15,370 at t=3.1139s
WARNING:v2ecore.emulator:no signal events generated for frame #15,371 at t=3.1141s
WARNING:v2ecore.emulator:no signal events generated for frame #15,372 at t=3.1143s
WARNING:v2ecore.emulator:no signal events generated for frame #15,373 at t=3.1144s
dvs:  47% 15375/33000 [04:13<02:51, 103.04fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,377 at t=3.1152s
WARNING:v2ecore.emulator:no signal events generated for frame #15,378 at t=3.1154s
WARNING:v2ecore.emulator:no signal events generated for frame #15,380 at t=3.1158s
WARNING:v2ecore.emulator:no signal events generated for frame #15,381 at t=3.1159s
WARNING:v2ecore.emulator:no signal events generated for frame #15,382 at t=3.1161s
WARNING:v2ecore.emulator:no signal events generated for frame #15,383 at t=3.1163s
WARNING:v2ecore.emulator:no signal events generated for frame #15,384 at t=3.1165s
WARNING:v2ecore.emulator:no signal events generated for frame #15,385 at t=3.1167s
WARNING:v2ecore.emulator:no signal events generated for frame #15,386 at t=3.1169s
WARNING:v2ecore.emulator:no signal events generated for frame #15,387 at t=3.1171s
WARNING:v2ecore.emulator:no signal events generated for frame #15,388 at t=3.1172s
WARNING:v2ecore.emulator:no signal events generated for frame #15,389 at t=3.1174s
WARNING:v2ecore.emulator:no signal events generated for frame #15,391 at t=3.1178s
WARNING:v2ecore.emulator:no signal events generated for frame #15,394 at t=3.1184s
dvs:  47% 15394/33000 [04:13<02:33, 114.85fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,395 at t=3.1185s
WARNING:v2ecore.emulator:no signal events generated for frame #15,396 at t=3.1187s
WARNING:v2ecore.emulator:no signal events generated for frame #15,398 at t=3.1191s
WARNING:v2ecore.emulator:no signal events generated for frame #15,399 at t=3.1193s
WARNING:v2ecore.emulator:no signal events generated for frame #15,400 at t=3.1195s
WARNING:v2ecore.emulator:no signal events generated for frame #15,401 at t=3.1197s
WARNING:v2ecore.emulator:no signal events generated for frame #15,402 at t=3.1198s
WARNING:v2ecore.emulator:no signal events generated for frame #15,404 at t=3.1202s
WARNING:v2ecore.emulator:no signal events generated for frame #15,406 at t=3.1206s
WARNING:v2ecore.emulator:no signal events generated for frame #15,407 at t=3.1208s
WARNING:v2ecore.emulator:no signal events generated for frame #15,410 at t=3.1213s
dvs:  47% 15410/33000 [04:13<02:25, 120.98fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,411 at t=3.1215s
WARNING:v2ecore.emulator:no signal events generated for frame #15,412 at t=3.1217s
WARNING:v2ecore.emulator:no signal events generated for frame #15,414 at t=3.1221s
WARNING:v2ecore.emulator:no signal events generated for frame #15,415 at t=3.1223s
WARNING:v2ecore.emulator:no signal events generated for frame #15,416 at t=3.1225s
WARNING:v2ecore.emulator:no signal events generated for frame #15,417 at t=3.1226s
WARNING:v2ecore.emulator:no signal events generated for frame #15,418 at t=3.1228s
WARNING:v2ecore.emulator:no signal events generated for frame #15,419 at t=3.1230s
WARNING:v2ecore.emulator:no signal events generated for frame #15,420 at t=3.1232s
WARNING:v2ecore.emulator:no signal events generated for frame #15,422 at t=3.1236s
WARNING:v2ecore.emulator:no signal events generated for frame #15,424 at t=3.1239s
WARNING:v2ecore.emulator:no signal events generated for frame #15,425 at t=3.1241s
WARNING:v2ecore.emulator:no signal events generated for frame #15,426 at t=3.1243s
WARNING:v2ecore.emulator:no signal events generated for frame #15,427 at t=3.1245s
WARNING:v2ecore.emulator:no signal events generated for frame #15,429 at t=3.1249s
WARNING:v2ecore.emulator:no signal events generated for frame #15,430 at t=3.1251s
WARNING:v2ecore.emulator:no signal events generated for frame #15,431 at t=3.1252s
WARNING:v2ecore.emulator:no signal events generated for frame #15,433 at t=3.1256s
dvs: 100% 33000/33000 [09:28<00:00, 58.09fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 205 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 207 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 33000 frames
INFO:v2e:generated total 57.91M events (28.85M on, 29.06M off)
INFO:v2e:Avg event rate for N=89960 px and total time =6.867 s
	Total: 8.43MHz (4.20MHz on, 4.23MHz off)
	Per pixel:  93.75Hz (46.71Hz on, 47.04Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 414 frames in 1.77ks (4.26s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 205 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 207 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 33000 frames
Total events: 57,909,542
  Written 5,000,000/57,909,542
  Written 10,000,000/57,909,542
  Written 15,000,000/57,909,542
  Written 20,000,000/57,909,542
  Written 25,000,000/57,909,542
  Written 30,000,000/57,909,542
  Written 35,000,000/57,909,542
  Written 40,000,000/57,909,542
  Written 45,000,000/57,909,542
  Written 50,000,000/57,909,542
  Written 55,000,000/57,909,542
  Written 57,909,542/57,909,542
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 207
Output folder: /content/v2e-output/aps
APS frames found: 207
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/207 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:06.90, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:06.90, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x595e6e2c3840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x595e6e2c8ec0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x595e6e78cf40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x595e6e78cf40] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x595e6e78cf40] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  207 fps= 35 q=-1.0 Lsize=    5027kB time=00:00:06.80 bitrate=6055.9kbits/s speed=1.15x
video:5025kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.038343%
[libx264 @ 0x595e6e78cf40] frame I:29    Avg QP:26.68  size: 37850
[libx264 @ 0x595e6e78cf40] frame P:170   Avg QP:29.55  size: 22726
[libx264 @ 0x595e6e78cf40] frame B:8     Avg QP:31.50  size: 22984
[libx264 @ 0x595e6e78cf40] consecutive B-frames: 92.3%  7.7%  0.0%  0.0%
[libx264 @ 0x595e6e78cf40] mb I  I16..4:  2.9% 52.0% 45.2%
[libx264 @ 0x595e6e78cf40] mb P  I16..4:  8.7% 37.8% 29.3%  P16..4: 11.9%  1.7%  0.9%  0.0%  0.0%    skip: 9.6%
[libx264 @ 0x595e6e78cf40] mb B  I16..4:  2.8%  7.0% 31.9%  B16..8:  9.5%  2.4%  1.4%  direct:20.0%  skip:25.0%  L0:46.3% L1:46.5% BI: 7.2%
[libx264 @ 0x595e6e78cf40] 8x8 transform intra:49.6% inter:81.6%
[libx264 @ 0x595e6e78cf40] coded y,uvDC,uvAC intra: 68.3% 44.6% 42.7% inter: 37.0% 3.6% 1.9%
[libx264 @ 0x595e6e78cf40] i16 v,h,dc,p: 30%  8% 54%  8%
[libx264 @ 0x595e6e78cf40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 53%  9% 25%  2%  2%  3%  1%  3%  2%
[libx264 @ 0x595e6e78cf40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 12% 29%  6%  5%  6%  5%  5%  4%
[libx264 @ 0x595e6e78cf40] i8c dc,h,v,p: 77%  5% 15%  4%
[libx264 @ 0x595e6e78cf40] Weighted P-Frames: Y:36.5% UV:28.8%
[libx264 @ 0x595e6e78cf40] ref P L0: 46.6% 35.1% 13.1%  4.5%  0.7%
[libx264 @ 0x595e6e78cf40] ref B L0: 83.7% 16.3%
[libx264 @ 0x595e6e78cf40] kb/s:5965.13
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (stored 0%)
  adding: dvs/0140.png (stored 0%)
  adding: dvs/0104.png (stored 0%)
  adding: dvs/0160.png (stored 0%)
  adding: dvs/0105.png (stored 0%)
  adding: dvs/0199.png (stored 0%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0077.png (stored 0%)
  adding: dvs/0011.png (stored 0%)
  adding: dvs/0026.png (deflated 2%)
  adding: dvs/0154.png (stored 0%)
  adding: dvs/0128.png (stored 0%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0120.png (stored 0%)
  adding: dvs/0163.png (stored 0%)
  adding: dvs/0084.png (stored 0%)
  adding: dvs/0066.png (stored 0%)
  adding: dvs/0010.png (deflated 64%)
  adding: dvs/0191.png (deflated 59%)
  adding: dvs/0007.png (stored 0%)
  adding: dvs/0071.png (stored 0%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (stored 0%)
  adding: dvs/0062.png (stored 0%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0197.png (stored 0%)
  adding: dvs/0143.png (stored 0%)
  adding: dvs/0184.png (stored 0%)
  adding: dvs/0178.png (stored 0%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (stored 0%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (stored 0%)
  adding: dvs/0126.png (stored 0%)
  adding: dvs/0150.png (stored 0%)
  adding: dvs/0042.png (stored 0%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (deflated 40%)
  adding: dvs/0075.png (stored 0%)
  adding: dvs/0036.png (stored 0%)
  adding: dvs/0207.png (deflated 15%)
  adding: dvs/0095.png (stored 0%)
  adding: dvs/0065.png (stored 0%)
  adding: dvs/0057.png (stored 0%)
  adding: dvs/0033.png (stored 0%)
  adding: dvs/0182.png (stored 0%)
  adding: dvs/0091.png (stored 0%)
  adding: dvs/0067.png (stored 0%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0047.png (stored 0%)
  adding: dvs/0151.png (stored 0%)
  adding: dvs/0056.png (stored 0%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (stored 0%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0072.png (stored 0%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (stored 0%)
  adding: dvs/0013.png (stored 0%)
  adding: dvs/0158.png (stored 0%)
  adding: dvs/0034.png (stored 0%)
  adding: dvs/0138.png (deflated 0%)
  adding: dvs/0100.png (stored 0%)
  adding: dvs/0175.png (stored 0%)
  adding: dvs/0167.png (stored 0%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0177.png (deflated 18%)
  adding: dvs/0032.png (deflated 0%)
  adding: dvs/0093.png (stored 0%)
  adding: dvs/0004.png (stored 0%)
  adding: dvs/0006.png (stored 0%)
  adding: dvs/0159.png (stored 0%)
  adding: dvs/0188.png (stored 0%)
  adding: dvs/0030.png (stored 0%)
  adding: dvs/0130.png (stored 0%)
  adding: dvs/0132.png (stored 0%)
  adding: dvs/0009.png (deflated 22%)
  adding: dvs/0205.png (deflated 29%)
  adding: dvs/0162.png (deflated 10%)
  adding: dvs/0017.png (deflated 26%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (deflated 5%)
  adding: dvs/0170.png (stored 0%)
  adding: dvs/0035.png (stored 0%)
  adding: dvs/0201.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (stored 0%)
  adding: dvs/0196.png (stored 0%)
  adding: dvs/0147.png (deflated 1%)
  adding: dvs/0183.png (deflated 60%)
  adding: dvs/0198.png (deflated 75%)
  adding: dvs/0069.png (stored 0%)
  adding: dvs/0148.png (stored 0%)
  adding: dvs/0060.png (stored 0%)
  adding: dvs/0003.png (stored 0%)
  adding: dvs/0187.png (stored 0%)
  adding: dvs/0029.png (stored 0%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0001.png (stored 0%)
  adding: dvs/0200.png (stored 0%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0135.png (stored 0%)
  adding: dvs/0080.png (stored 0%)
  adding: dvs/0094.png (stored 0%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0203.png (stored 0%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (stored 0%)
  adding: dvs/0024.png (deflated 2%)
  adding: dvs/0061.png (stored 0%)
  adding: dvs/0039.png (deflated 2%)
  adding: dvs/0101.png (stored 0%)
  adding: dvs/0152.png (stored 0%)
  adding: dvs/0097.png (stored 0%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (stored 0%)
  adding: dvs/0070.png (stored 0%)
  adding: dvs/0129.png (stored 0%)
  adding: dvs/0206.png (deflated 57%)
  adding: dvs/0037.png (stored 0%)
  adding: dvs/0073.png (stored 0%)
  adding: dvs/0116.png (stored 0%)
  adding: dvs/0185.png (stored 0%)
  adding: dvs/0021.png (stored 0%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0015.png (stored 0%)
  adding: dvs/0166.png (deflated 0%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0121.png (stored 0%)
  adding: dvs/0027.png (stored 0%)
  adding: dvs/0040.png (stored 0%)
  adding: dvs/0074.png (stored 0%)
  adding: dvs/0149.png (stored 0%)
  adding: dvs/0096.png (stored 0%)
  adding: dvs/0068.png (stored 0%)
  adding: dvs/0181.png (stored 0%)
  adding: dvs/0180.png (stored 0%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (stored 0%)
  adding: dvs/0078.png (stored 0%)
  adding: dvs/0125.png (stored 0%)
  adding: dvs/0127.png (stored 0%)
  adding: dvs/0099.png (stored 0%)
  adding: dvs/0194.png (deflated 0%)
  adding: dvs/0008.png (stored 0%)
  adding: dvs/0028.png (stored 0%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (stored 0%)
  adding: dvs/0103.png (stored 0%)
  adding: dvs/0092.png (stored 0%)
  adding: dvs/0012.png (deflated 22%)
  adding: dvs/0133.png (stored 0%)
  adding: dvs/0165.png (stored 0%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (stored 0%)
  adding: dvs/0155.png (stored 0%)
  adding: dvs/0193.png (stored 0%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (stored 0%)
  adding: dvs/0144.png (stored 0%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0202.png (stored 0%)
  adding: dvs/0114.png (stored 0%)
  adding: dvs/0107.png (stored 0%)
  adding: dvs/0123.png (deflated 1%)
  adding: dvs/0109.png (stored 0%)
  adding: dvs/0189.png (stored 0%)
  adding: dvs/0025.png (deflated 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0058.png (stored 0%)
  adding: dvs/0153.png (deflated 5%)
  adding: dvs/0139.png (stored 0%)
  adding: dvs/0174.png (stored 0%)
  adding: dvs/0192.png (deflated 39%)
  adding: dvs/0169.png (stored 0%)
  adding: dvs/0098.png (stored 0%)
  adding: dvs/0048.png (stored 0%)
  adding: dvs/0089.png (stored 0%)
  adding: dvs/0122.png (stored 0%)
  adding: dvs/0002.png (deflated 70%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (stored 0%)
  adding: dvs/0176.png (deflated 12%)
  adding: dvs/0136.png (stored 0%)
  adding: dvs/0005.png (stored 0%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (stored 0%)
  adding: dvs/0124.png (stored 0%)
  adding: dvs/0204.png (stored 0%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0173.png (stored 0%)
  adding: dvs/0186.png (stored 0%)
  adding: dvs/0131.png (stored 0%)
  adding: dvs/0119.png (stored 0%)
  adding: dvs/0083.png (stored 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (stored 0%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 39%)
  adding: aps/0140.png (deflated 17%)
  adding: aps/0104.png (deflated 20%)
  adding: aps/0160.png (deflated 20%)
  adding: aps/0105.png (deflated 20%)
  adding: aps/0199.png (deflated 18%)
  adding: aps/0134.png (deflated 19%)
  adding: aps/0077.png (deflated 19%)
  adding: aps/0011.png (deflated 34%)
  adding: aps/0026.png (deflated 25%)
  adding: aps/0154.png (deflated 18%)
  adding: aps/0128.png (deflated 18%)
  adding: aps/0171.png (deflated 17%)
  adding: aps/0108.png (deflated 39%)
  adding: aps/0145.png (deflated 20%)
  adding: aps/0120.png (deflated 21%)
  adding: aps/0163.png (deflated 22%)
  adding: aps/0084.png (deflated 17%)
  adding: aps/0066.png (deflated 18%)
  adding: aps/0010.png (deflated 24%)
  adding: aps/0191.png (deflated 31%)
  adding: aps/0007.png (deflated 19%)
  adding: aps/0071.png (deflated 24%)
  adding: aps/0053.png (deflated 17%)
  adding: aps/0161.png (deflated 31%)
  adding: aps/0062.png (deflated 19%)
  adding: aps/0082.png (deflated 19%)
  adding: aps/0197.png (deflated 18%)
  adding: aps/0143.png (deflated 18%)
  adding: aps/0184.png (deflated 18%)
  adding: aps/0178.png (deflated 24%)
  adding: aps/0054.png (deflated 17%)
  adding: aps/0022.png (deflated 18%)
  adding: aps/0045.png (deflated 19%)
  adding: aps/0086.png (deflated 33%)
  adding: aps/0117.png (deflated 26%)
  adding: aps/0052.png (deflated 19%)
  adding: aps/0126.png (deflated 17%)
  adding: aps/0150.png (deflated 20%)
  adding: aps/0042.png (deflated 24%)
  adding: aps/0112.png (deflated 18%)
  adding: aps/0168.png (deflated 38%)
  adding: aps/0075.png (deflated 20%)
  adding: aps/0036.png (deflated 18%)
  adding: aps/0207.png (deflated 23%)
  adding: aps/0095.png (deflated 20%)
  adding: aps/0065.png (deflated 18%)
  adding: aps/0057.png (deflated 24%)
  adding: aps/0033.png (deflated 31%)
  adding: aps/0182.png (deflated 19%)
  adding: aps/0091.png (deflated 19%)
  adding: aps/0067.png (deflated 18%)
  adding: aps/0081.png (deflated 18%)
  adding: aps/0047.png (deflated 19%)
  adding: aps/0151.png (deflated 18%)
  adding: aps/0056.png (deflated 25%)
  adding: aps/0142.png (deflated 18%)
  adding: aps/0044.png (deflated 20%)
  adding: aps/0020.png (deflated 18%)
  adding: aps/0106.png (deflated 19%)
  adding: aps/0072.png (deflated 23%)
  adding: aps/0113.png (deflated 17%)
  adding: aps/0043.png (deflated 21%)
  adding: aps/0157.png (deflated 18%)
  adding: aps/0013.png (deflated 24%)
  adding: aps/0158.png (deflated 18%)
  adding: aps/0034.png (deflated 18%)
  adding: aps/0138.png (deflated 38%)
  adding: aps/0100.png (deflated 19%)
  adding: aps/0175.png (deflated 20%)
  adding: aps/0167.png (deflated 19%)
  adding: aps/0041.png (deflated 23%)
  adding: aps/0177.png (deflated 25%)
  adding: aps/0032.png (deflated 19%)
  adding: aps/0093.png (deflated 38%)
  adding: aps/0004.png (deflated 19%)
  adding: aps/0006.png (deflated 18%)
  adding: aps/0159.png (deflated 17%)
  adding: aps/0188.png (deflated 17%)
  adding: aps/0030.png (deflated 20%)
  adding: aps/0130.png (deflated 20%)
  adding: aps/0132.png (deflated 25%)
  adding: aps/0009.png (deflated 18%)
  adding: aps/0205.png (deflated 22%)
  adding: aps/0162.png (deflated 24%)
  adding: aps/0017.png (deflated 19%)
  adding: aps/0051.png (deflated 19%)
  adding: aps/0190.png (deflated 22%)
  adding: aps/0170.png (deflated 17%)
  adding: aps/0035.png (deflated 17%)
  adding: aps/0201.png (deflated 17%)
  adding: aps/0018.png (deflated 37%)
  adding: aps/0156.png (deflated 17%)
  adding: aps/0196.png (deflated 19%)
  adding: aps/0147.png (deflated 24%)
  adding: aps/0183.png (deflated 37%)
  adding: aps/0198.png (deflated 37%)
  adding: aps/0069.png (deflated 18%)
  adding: aps/0148.png (deflated 21%)
  adding: aps/0060.png (deflated 19%)
  adding: aps/0003.png (deflated 35%)
  adding: aps/0187.png (deflated 18%)
  adding: aps/0029.png (deflated 20%)
  adding: aps/0115.png (deflated 18%)
  adding: aps/0141.png (deflated 17%)
  adding: aps/0001.png (deflated 21%)
  adding: aps/0200.png (deflated 17%)
  adding: aps/0046.png (deflated 19%)
  adding: aps/0135.png (deflated 19%)
  adding: aps/0080.png (deflated 19%)
  adding: aps/0094.png (deflated 20%)
  adding: aps/0090.png (deflated 20%)
  adding: aps/0203.png (deflated 17%)
  adding: aps/0049.png (deflated 20%)
  adding: aps/0164.png (deflated 19%)
  adding: aps/0024.png (deflated 17%)
  adding: aps/0061.png (deflated 19%)
  adding: aps/0039.png (deflated 17%)
  adding: aps/0101.png (deflated 32%)
  adding: aps/0152.png (deflated 19%)
  adding: aps/0097.png (deflated 18%)
  adding: aps/0059.png (deflated 19%)
  adding: aps/0038.png (deflated 17%)
  adding: aps/0070.png (deflated 26%)
  adding: aps/0129.png (deflated 17%)
  adding: aps/0206.png (deflated 30%)
  adding: aps/0037.png (deflated 18%)
  adding: aps/0073.png (deflated 21%)
  adding: aps/0116.png (deflated 33%)
  adding: aps/0185.png (deflated 17%)
  adding: aps/0021.png (deflated 18%)
  adding: aps/0137.png (deflated 18%)
  adding: aps/0015.png (deflated 20%)
  adding: aps/0166.png (deflated 20%)
  adding: aps/0146.png (deflated 28%)
  adding: aps/0121.png (deflated 19%)
  adding: aps/0027.png (deflated 23%)
  adding: aps/0040.png (deflated 25%)
  adding: aps/0074.png (deflated 20%)
  adding: aps/0149.png (deflated 19%)
  adding: aps/0096.png (deflated 17%)
  adding: aps/0068.png (deflated 18%)
  adding: aps/0181.png (deflated 19%)
  adding: aps/0180.png (deflated 20%)
  adding: aps/0076.png (deflated 19%)
  adding: aps/0079.png (deflated 20%)
  adding: aps/0078.png (deflated 39%)
  adding: aps/0125.png (deflated 17%)
  adding: aps/0127.png (deflated 17%)
  adding: aps/0099.png (deflated 17%)
  adding: aps/0194.png (deflated 21%)
  adding: aps/0008.png (deflated 19%)
  adding: aps/0028.png (deflated 20%)
  adding: aps/0050.png (deflated 19%)
  adding: aps/0088.png (deflated 24%)
  adding: aps/0118.png (deflated 24%)
  adding: aps/0103.png (deflated 20%)
  adding: aps/0092.png (deflated 19%)
  adding: aps/0012.png (deflated 24%)
  adding: aps/0133.png (deflated 22%)
  adding: aps/0165.png (deflated 19%)
  adding: aps/0031.png (deflated 19%)
  adding: aps/0064.png (deflated 21%)
  adding: aps/0155.png (deflated 17%)
  adding: aps/0193.png (deflated 21%)
  adding: aps/0055.png (deflated 26%)
  adding: aps/0195.png (deflated 19%)
  adding: aps/0144.png (deflated 17%)
  adding: aps/0110.png (deflated 18%)
  adding: aps/0016.png (deflated 19%)
  adding: aps/0202.png (deflated 18%)
  adding: aps/0114.png (deflated 17%)
  adding: aps/0107.png (deflated 18%)
  adding: aps/0123.png (deflated 38%)
  adding: aps/0109.png (deflated 18%)
  adding: aps/0189.png (deflated 17%)
  adding: aps/0025.png (deflated 25%)
  adding: aps/0085.png (deflated 18%)
  adding: aps/0058.png (deflated 20%)
  adding: aps/0153.png (deflated 37%)
  adding: aps/0139.png (deflated 18%)
  adding: aps/0174.png (deflated 17%)
  adding: aps/0192.png (deflated 23%)
  adding: aps/0169.png (deflated 18%)
  adding: aps/0098.png (deflated 18%)
  adding: aps/0048.png (deflated 35%)
  adding: aps/0089.png (deflated 21%)
  adding: aps/0122.png (deflated 20%)
  adding: aps/0002.png (deflated 19%)
  adding: aps/0111.png (deflated 17%)
  adding: aps/0172.png (deflated 18%)
  adding: aps/0176.png (deflated 29%)
  adding: aps/0136.png (deflated 19%)
  adding: aps/0005.png (deflated 18%)

'The chosen video file: /content/video/lamp_1:2hz.MOV'

FPS: 29.970760233918128
Frame count: 205
Duration: 6.84 sec
The Final v2e command:

'v2e -i /content/video/lamp_1:2hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/lamp_1:2hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/lamp_1:2hz.MOV
INFO:v2e:Input video frame rate 29.970760233918128Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/lamp_1:2hz.MOV has total 205 frames with total duration 6.80s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 205 frames 0 to 204
(From 0.0s to 6.8s, duration 6.8s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 204.0 frames with duration 6.80s and playback duration 6.80s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 204 from video input
INFO:v2e:Input video /content/video/lamp_1:2hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 205 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/205 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 205/205 [00:09<00:00, 20.91fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmprfjnax5k
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 26 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/26 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 161
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/26 [00:43<18:19, 43.99s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 38
slomo-interp:   8% 2/26 [00:54<09:49, 24.55s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 11
slomo-interp: 100% 26/26 [07:19<00:00, 16.88s/ batch of 8 fr]
write-orig-avi: 100% 205/205 [00:00<00:00, 855.84fr/s]
write-slomo-vid: 100% 12356/12356 [00:31<00:00, 396.69fr/s]
INFO:v2ecore.slomo:Wrote 12356 frames and returning 12356 frame times.
Average upsampling factor= 59.5
INFO:v2e:SloMo average upsampling factor=59.54; average DVS timestamp resolution=559.86us
INFO:v2e:*** Stage 3/3: emulating DVS events from 12356 frames
dvs:   0% 0/12356 [00:00<?, ?fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2 at t=0.0002s
WARNING:v2ecore.emulator:no signal events generated for frame #3 at t=0.0004s
WARNING:v2ecore.emulator:no signal events generated for frame #4 at t=0.0006s
WARNING:v2ecore.emulator:no signal events generated for frame #5 at t=0.0008s
WARNING:v2ecore.emulator:no signal events generated for frame #6 at t=0.0010s
WARNING:v2ecore.emulator:no signal events generated for frame #7 at t=0.0012s
dvs:   0% 7/12356 [00:00<02:58, 69.36fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #8 at t=0.0015s
WARNING:v2ecore.emulator:no signal events generated for frame #9 at t=0.0017s
WARNING:v2ecore.emulator:no signal events generated for frame #10 at t=0.0019s
WARNING:v2ecore.emulator:no signal events generated for frame #11 at t=0.0021s
WARNING:v2ecore.emulator:no signal events generated for frame #12 at t=0.0023s
WARNING:v2ecore.emulator:no signal events generated for frame #13 at t=0.0025s
WARNING:v2ecore.emulator:no signal events generated for frame #14 at t=0.0027s
WARNING:v2ecore.emulator:no signal events generated for frame #15 at t=0.0029s
WARNING:v2ecore.emulator:no signal events generated for frame #16 at t=0.0031s
WARNING:v2ecore.emulator:no signal events generated for frame #17 at t=0.0033s
WARNING:v2ecore.emulator:no signal events generated for frame #21 at t=0.0041s
dvs:   0% 22/12356 [00:00<01:47, 115.15fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #25 at t=0.0050s
WARNING:v2ecore.emulator:no signal events generated for frame #29 at t=0.0058s
INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:  22% 2730/12356 [00:53<02:12, 72.82fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,734 at t=1.2368s
WARNING:v2ecore.emulator:no signal events generated for frame #2,735 at t=1.2370s
dvs:  22% 2738/12356 [00:54<03:10, 50.36fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,745 at t=1.2388s
WARNING:v2ecore.emulator:no signal events generated for frame #2,752 at t=1.2400s
WARNING:v2ecore.emulator:no signal events generated for frame #2,754 at t=1.2403s
dvs:  22% 2754/12356 [00:54<02:21, 67.98fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,756 at t=1.2407s
dvs:  22% 2762/12356 [00:54<02:16, 70.05fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,763 at t=1.2419s
WARNING:v2ecore.emulator:no signal events generated for frame #2,770 at t=1.2432s
dvs:  22% 2770/12356 [00:54<02:14, 71.19fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,772 at t=1.2435s
WARNING:v2ecore.emulator:no signal events generated for frame #2,774 at t=1.2439s
dvs:  22% 2778/12356 [00:54<02:11, 72.93fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,779 at t=1.2447s
WARNING:v2ecore.emulator:no signal events generated for frame #2,782 at t=1.2453s
dvs:  23% 2802/12356 [00:54<02:12, 72.02fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,804 at t=1.2491s
WARNING:v2ecore.emulator:no signal events generated for frame #2,805 at t=1.2493s
dvs:  23% 2818/12356 [00:55<02:08, 73.94fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,823 at t=1.2525s
dvs:  23% 2826/12356 [00:55<02:07, 74.79fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,828 at t=1.2533s
WARNING:v2ecore.emulator:no signal events generated for frame #2,834 at t=1.2544s
dvs:  23% 2834/12356 [00:55<02:05, 75.87fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,837 at t=1.2549s
dvs:  23% 2842/12356 [00:55<02:05, 75.73fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,844 at t=1.2561s
WARNING:v2ecore.emulator:no signal events generated for frame #2,849 at t=1.2570s
WARNING:v2ecore.emulator:no signal events generated for frame #2,854 at t=1.2579s
dvs:  23% 2858/12356 [00:55<01:44, 91.15fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,867 at t=1.2602s
dvs:  23% 2867/12356 [00:55<01:47, 88.39fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,875 at t=1.2616s
dvs:  23% 2876/12356 [00:55<01:48, 87.49fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,880 at t=1.2625s
dvs:  23% 2885/12356 [00:55<01:55, 81.81fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,891 at t=1.2644s
WARNING:v2ecore.emulator:no signal events generated for frame #2,893 at t=1.2647s
dvs:  52% 6443/12356 [02:08<01:19, 74.65fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,448 at t=3.1594s
dvs:  55% 6778/12356 [02:13<01:51, 50.14fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,780 at t=3.2402s
dvs:  64% 7938/12356 [02:37<01:00, 73.39fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #7,945 at t=4.0708s
WARNING:v2ecore.emulator:no signal events generated for frame #7,946 at t=4.0710s
WARNING:v2ecore.emulator:no signal events generated for frame #7,950 at t=4.0719s
dvs:  65% 8090/12356 [02:39<00:57, 74.10fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #8,094 at t=4.1033s
dvs:  66% 8098/12356 [02:40<01:22, 51.69fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #8,099 at t=4.1044s
WARNING:v2ecore.emulator:no signal events generated for frame #8,100 at t=4.1046s
WARNING:v2ecore.emulator:no signal events generated for frame #8,102 at t=4.1051s
WARNING:v2ecore.emulator:no signal events generated for frame #8,103 at t=4.1053s
WARNING:v2ecore.emulator:no signal events generated for frame #8,106 at t=4.1059s
dvs:  66% 8106/12356 [02:40<01:14, 57.00fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #8,110 at t=4.1068s
WARNING:v2ecore.emulator:no signal events generated for frame #8,111 at t=4.1070s
WARNING:v2ecore.emulator:no signal events generated for frame #8,113 at t=4.1075s
WARNING:v2ecore.emulator:no signal events generated for frame #8,114 at t=4.1077s
WARNING:v2ecore.emulator:no signal events generated for frame #8,117 at t=4.1083s
WARNING:v2ecore.emulator:no signal events generated for frame #8,118 at t=4.1085s
WARNING:v2ecore.emulator:no signal events generated for frame #8,119 at t=4.1088s
WARNING:v2ecore.emulator:no signal events generated for frame #8,120 at t=4.1090s
WARNING:v2ecore.emulator:no signal events generated for frame #8,122 at t=4.1094s
dvs:  66% 8122/12356 [02:40<00:55, 75.88fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #8,124 at t=4.1098s
WARNING:v2ecore.emulator:no signal events generated for frame #8,126 at t=4.1103s
WARNING:v2ecore.emulator:no signal events generated for frame #8,127 at t=4.1105s
WARNING:v2ecore.emulator:no signal events generated for frame #8,128 at t=4.1107s
WARNING:v2ecore.emulator:no signal events generated for frame #8,129 at t=4.1109s
WARNING:v2ecore.emulator:no signal events generated for frame #8,130 at t=4.1112s
WARNING:v2ecore.emulator:no signal events generated for frame #8,131 at t=4.1114s
WARNING:v2ecore.emulator:no signal events generated for frame #8,132 at t=4.1116s
WARNING:v2ecore.emulator:no signal events generated for frame #8,135 at t=4.1122s
dvs:  66% 8138/12356 [02:40<00:47, 88.83fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #8,139 at t=4.1131s
WARNING:v2ecore.emulator:no signal events generated for frame #8,140 at t=4.1133s
WARNING:v2ecore.emulator:no signal events generated for frame #8,142 at t=4.1138s
WARNING:v2ecore.emulator:no signal events generated for frame #8,143 at t=4.1140s
WARNING:v2ecore.emulator:no signal events generated for frame #8,144 at t=4.1142s
WARNING:v2ecore.emulator:no signal events generated for frame #8,145 at t=4.1144s
WARNING:v2ecore.emulator:no signal events generated for frame #8,146 at t=4.1146s
WARNING:v2ecore.emulator:no signal events generated for frame #8,148 at t=4.1151s
WARNING:v2ecore.emulator:no signal events generated for frame #8,152 at t=4.1160s
dvs:  66% 8154/12356 [02:40<00:44, 95.48fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #8,156 at t=4.1168s
WARNING:v2ecore.emulator:no signal events generated for frame #8,157 at t=4.1170s
WARNING:v2ecore.emulator:no signal events generated for frame #8,164 at t=4.1186s
dvs:  66% 8164/12356 [02:40<00:45, 92.98fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #8,166 at t=4.1190s
WARNING:v2ecore.emulator:no signal events generated for frame #8,172 at t=4.1203s
dvs:  66% 8174/12356 [02:40<00:45, 91.47fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #8,177 at t=4.1214s
WARNING:v2ecore.emulator:no signal events generated for frame #8,179 at t=4.1218s
WARNING:v2ecore.emulator:no signal events generated for frame #8,183 at t=4.1227s
WARNING:v2ecore.emulator:no signal events generated for frame #8,184 at t=4.1229s
dvs:  66% 8186/12356 [02:40<00:44, 93.41fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #8,189 at t=4.1240s
WARNING:v2ecore.emulator:no signal events generated for frame #8,190 at t=4.1242s
WARNING:v2ecore.emulator:no signal events generated for frame #8,191 at t=4.1245s
WARNING:v2ecore.emulator:no signal events generated for frame #8,193 at t=4.1249s
WARNING:v2ecore.emulator:no signal events generated for frame #8,194 at t=4.1251s
WARNING:v2ecore.emulator:no signal events generated for frame #8,196 at t=4.1255s
WARNING:v2ecore.emulator:no signal events generated for frame #8,198 at t=4.1260s
WARNING:v2ecore.emulator:no signal events generated for frame #8,201 at t=4.1266s
dvs: 100% 12356/12356 [04:06<00:00, 50.16fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 203 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 205 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 12356 frames
INFO:v2e:generated total 11.22M events (5.56M on, 5.66M off)
INFO:v2e:Avg event rate for N=89960 px and total time =6.800 s
	Total: 1.65MHz (818.30kHz on, 832.38kHz off)
	Per pixel:  18.35Hz (9.10Hz on, 9.25Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 410 frames in 728.11s (1.78s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 203 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 205 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 12356 frames
Total events: 11,224,627
  Written 5,000,000/11,224,627
  Written 10,000,000/11,224,627
  Written 11,224,627/11,224,627
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 205
Output folder: /content/v2e-output/aps
APS frames found: 205
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/205 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:06.83, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:06.83, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x58e40ff67840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x58e40ff709c0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x58e40ffa04c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x58e40ffa04c0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x58e40ffa04c0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  205 fps= 55 q=-1.0 Lsize=    2108kB time=00:00:06.73 bitrate=2565.2kbits/s speed=1.79x
video:2105kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.144022%
[libx264 @ 0x58e40ffa04c0] frame I:11    Avg QP:25.13  size: 30282
[libx264 @ 0x58e40ffa04c0] frame P:74    Avg QP:28.13  size: 14373
[libx264 @ 0x58e40ffa04c0] frame B:120   Avg QP:29.91  size:  6321
[libx264 @ 0x58e40ffa04c0] consecutive B-frames: 20.5%  3.9%  1.5% 74.1%
[libx264 @ 0x58e40ffa04c0] mb I  I16..4:  4.9% 57.2% 37.9%
[libx264 @ 0x58e40ffa04c0] mb P  I16..4:  4.2% 25.5% 20.6%  P16..4: 20.5%  4.2%  3.7%  0.0%  0.0%    skip:21.3%
[libx264 @ 0x58e40ffa04c0] mb B  I16..4:  4.7%  1.8%  4.5%  B16..8: 27.0%  4.1%  1.9%  direct: 1.8%  skip:54.1%  L0:42.0% L1:54.8% BI: 3.1%
[libx264 @ 0x58e40ffa04c0] 8x8 transform intra:44.6% inter:50.4%
[libx264 @ 0x58e40ffa04c0] coded y,uvDC,uvAC intra: 63.5% 43.2% 40.9% inter: 16.5% 4.0% 1.8%
[libx264 @ 0x58e40ffa04c0] i16 v,h,dc,p: 43% 16% 38%  3%
[libx264 @ 0x58e40ffa04c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 49%  9% 30%  2%  1%  2%  1%  3%  2%
[libx264 @ 0x58e40ffa04c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 31% 13% 32%  5%  4%  5%  4%  4%  3%
[libx264 @ 0x58e40ffa04c0] i8c dc,h,v,p: 78%  6% 13%  3%
[libx264 @ 0x58e40ffa04c0] Weighted P-Frames: Y:25.7% UV:18.9%
[libx264 @ 0x58e40ffa04c0] ref P L0: 59.8% 18.6% 15.1%  5.8%  0.8%
[libx264 @ 0x58e40ffa04c0] ref B L0: 79.4% 17.2%  3.4%
[libx264 @ 0x58e40ffa04c0] ref B L1: 89.7% 10.3%
[libx264 @ 0x58e40ffa04c0] kb/s:2523.20
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (deflated 6%)
  adding: dvs/0140.png (stored 0%)
  adding: dvs/0104.png (stored 0%)
  adding: dvs/0160.png (stored 0%)
  adding: dvs/0105.png (deflated 4%)
  adding: dvs/0199.png (stored 0%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0077.png (stored 0%)
  adding: dvs/0011.png (stored 0%)
  adding: dvs/0026.png (stored 0%)
  adding: dvs/0154.png (deflated 15%)
  adding: dvs/0128.png (stored 0%)
  adding: dvs/0171.png (deflated 7%)
  adding: dvs/0108.png (deflated 6%)
  adding: dvs/0145.png (deflated 4%)
  adding: dvs/0120.png (deflated 9%)
  adding: dvs/0163.png (stored 0%)
  adding: dvs/0084.png (stored 0%)
  adding: dvs/0066.png (stored 0%)
  adding: dvs/0010.png (stored 0%)
  adding: dvs/0191.png (stored 0%)
  adding: dvs/0007.png (stored 0%)
  adding: dvs/0071.png (stored 0%)
  adding: dvs/0053.png (deflated 9%)
  adding: dvs/0161.png (stored 0%)
  adding: dvs/0062.png (deflated 5%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0197.png (stored 0%)
  adding: dvs/0143.png (stored 0%)
  adding: dvs/0184.png (deflated 1%)
  adding: dvs/0178.png (deflated 7%)
  adding: dvs/0054.png (deflated 11%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (stored 0%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (deflated 2%)
  adding: dvs/0052.png (deflated 3%)
  adding: dvs/0126.png (stored 0%)
  adding: dvs/0150.png (deflated 19%)
  adding: dvs/0042.png (stored 0%)
  adding: dvs/0112.png (deflated 6%)
  adding: dvs/0168.png (deflated 1%)
  adding: dvs/0075.png (stored 0%)
  adding: dvs/0036.png (stored 0%)
  adding: dvs/0095.png (deflated 1%)
  adding: dvs/0065.png (deflated 6%)
  adding: dvs/0057.png (deflated 7%)
  adding: dvs/0033.png (stored 0%)
  adding: dvs/0182.png (deflated 0%)
  adding: dvs/0091.png (stored 0%)
  adding: dvs/0067.png (stored 0%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0047.png (deflated 1%)
  adding: dvs/0151.png (deflated 20%)
  adding: dvs/0056.png (deflated 11%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (stored 0%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (deflated 0%)
  adding: dvs/0072.png (stored 0%)
  adding: dvs/0113.png (deflated 3%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (deflated 3%)
  adding: dvs/0013.png (stored 0%)
  adding: dvs/0158.png (stored 0%)
  adding: dvs/0034.png (stored 0%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (stored 0%)
  adding: dvs/0175.png (deflated 7%)
  adding: dvs/0167.png (deflated 1%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0177.png (deflated 8%)
  adding: dvs/0032.png (stored 0%)
  adding: dvs/0093.png (stored 0%)
  adding: dvs/0004.png (deflated 11%)
  adding: dvs/0006.png (deflated 23%)
  adding: dvs/0159.png (stored 0%)
  adding: dvs/0188.png (stored 0%)
  adding: dvs/0030.png (stored 0%)
  adding: dvs/0130.png (stored 0%)
  adding: dvs/0132.png (stored 0%)
  adding: dvs/0009.png (stored 0%)
  adding: dvs/0205.png (stored 0%)
  adding: dvs/0162.png (stored 0%)
  adding: dvs/0017.png (stored 0%)
  adding: dvs/0051.png (deflated 4%)
  adding: dvs/0190.png (stored 0%)
  adding: dvs/0170.png (deflated 2%)
  adding: dvs/0035.png (stored 0%)
  adding: dvs/0201.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (stored 0%)
  adding: dvs/0196.png (stored 0%)
  adding: dvs/0147.png (deflated 9%)
  adding: dvs/0183.png (deflated 0%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0069.png (deflated 4%)
  adding: dvs/0148.png (deflated 15%)
  adding: dvs/0060.png (deflated 8%)
  adding: dvs/0003.png (deflated 1%)
  adding: dvs/0187.png (deflated 39%)
  adding: dvs/0029.png (stored 0%)
  adding: dvs/0115.png (deflated 1%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0001.png (deflated 24%)
  adding: dvs/0200.png (stored 0%)
  adding: dvs/0046.png (deflated 1%)
  adding: dvs/0135.png (stored 0%)
  adding: dvs/0080.png (deflated 0%)
  adding: dvs/0094.png (deflated 0%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0203.png (deflated 1%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (stored 0%)
  adding: dvs/0024.png (stored 0%)
  adding: dvs/0061.png (deflated 8%)
  adding: dvs/0039.png (stored 0%)
  adding: dvs/0101.png (stored 0%)
  adding: dvs/0152.png (deflated 19%)
  adding: dvs/0097.png (stored 0%)
  adding: dvs/0059.png (deflated 4%)
  adding: dvs/0038.png (deflated 3%)
  adding: dvs/0070.png (stored 0%)
  adding: dvs/0129.png (deflated 5%)
  adding: dvs/0037.png (stored 0%)
  adding: dvs/0073.png (stored 0%)
  adding: dvs/0116.png (deflated 3%)
  adding: dvs/0185.png (deflated 2%)
  adding: dvs/0021.png (stored 0%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0015.png (stored 0%)
  adding: dvs/0166.png (deflated 1%)
  adding: dvs/0146.png (deflated 9%)
  adding: dvs/0121.png (deflated 4%)
  adding: dvs/0027.png (stored 0%)
  adding: dvs/0040.png (stored 0%)
  adding: dvs/0074.png (deflated 0%)
  adding: dvs/0149.png (deflated 35%)
  adding: dvs/0096.png (stored 0%)
  adding: dvs/0068.png (stored 0%)
  adding: dvs/0181.png (deflated 1%)
  adding: dvs/0180.png (stored 0%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (deflated 0%)
  adding: dvs/0078.png (stored 0%)
  adding: dvs/0125.png (deflated 13%)
  adding: dvs/0127.png (stored 0%)
  adding: dvs/0099.png (stored 0%)
  adding: dvs/0194.png (stored 0%)
  adding: dvs/0008.png (deflated 18%)
  adding: dvs/0028.png (stored 0%)
  adding: dvs/0050.png (deflated 4%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (deflated 2%)
  adding: dvs/0103.png (stored 0%)
  adding: dvs/0092.png (stored 0%)
  adding: dvs/0012.png (stored 0%)
  adding: dvs/0133.png (stored 0%)
  adding: dvs/0165.png (deflated 0%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (deflated 12%)
  adding: dvs/0155.png (deflated 17%)
  adding: dvs/0193.png (stored 0%)
  adding: dvs/0055.png (deflated 11%)
  adding: dvs/0195.png (stored 0%)
  adding: dvs/0144.png (deflated 0%)
  adding: dvs/0110.png (deflated 5%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0202.png (stored 0%)
  adding: dvs/0114.png (deflated 2%)
  adding: dvs/0107.png (deflated 1%)
  adding: dvs/0123.png (deflated 5%)
  adding: dvs/0109.png (deflated 3%)
  adding: dvs/0189.png (deflated 8%)
  adding: dvs/0025.png (deflated 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0058.png (deflated 6%)
  adding: dvs/0153.png (deflated 21%)
  adding: dvs/0139.png (stored 0%)
  adding: dvs/0174.png (deflated 3%)
  adding: dvs/0192.png (stored 0%)
  adding: dvs/0169.png (deflated 2%)
  adding: dvs/0098.png (stored 0%)
  adding: dvs/0048.png (deflated 0%)
  adding: dvs/0089.png (stored 0%)
  adding: dvs/0122.png (deflated 4%)
  adding: dvs/0002.png (deflated 3%)
  adding: dvs/0111.png (deflated 7%)
  adding: dvs/0172.png (deflated 1%)
  adding: dvs/0176.png (deflated 5%)
  adding: dvs/0136.png (stored 0%)
  adding: dvs/0005.png (stored 0%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (stored 0%)
  adding: dvs/0124.png (deflated 8%)
  adding: dvs/0204.png (deflated 0%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (deflated 1%)
  adding: dvs/0173.png (deflated 1%)
  adding: dvs/0186.png (deflated 1%)
  adding: dvs/0131.png (stored 0%)
  adding: dvs/0119.png (deflated 3%)
  adding: dvs/0083.png (stored 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (stored 0%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 16%)
  adding: aps/0140.png (deflated 18%)
  adding: aps/0104.png (deflated 16%)
  adding: aps/0160.png (deflated 19%)
  adding: aps/0105.png (deflated 16%)
  adding: aps/0199.png (deflated 19%)
  adding: aps/0134.png (deflated 18%)
  adding: aps/0077.png (deflated 18%)
  adding: aps/0011.png (deflated 18%)
  adding: aps/0026.png (deflated 18%)
  adding: aps/0154.png (deflated 18%)
  adding: aps/0128.png (deflated 19%)
  adding: aps/0171.png (deflated 16%)
  adding: aps/0108.png (deflated 16%)
  adding: aps/0145.png (deflated 18%)
  adding: aps/0120.png (deflated 16%)
  adding: aps/0163.png (deflated 16%)
  adding: aps/0084.png (deflated 19%)
  adding: aps/0066.png (deflated 16%)
  adding: aps/0010.png (deflated 18%)
  adding: aps/0191.png (deflated 18%)
  adding: aps/0007.png (deflated 20%)
  adding: aps/0071.png (deflated 19%)
  adding: aps/0053.png (deflated 16%)
  adding: aps/0161.png (deflated 17%)
  adding: aps/0062.png (deflated 16%)
  adding: aps/0082.png (deflated 19%)
  adding: aps/0197.png (deflated 17%)
  adding: aps/0143.png (deflated 18%)
  adding: aps/0184.png (deflated 16%)
  adding: aps/0178.png (deflated 16%)
  adding: aps/0054.png (deflated 16%)
  adding: aps/0022.png (deflated 18%)
  adding: aps/0045.png (deflated 16%)
  adding: aps/0086.png (deflated 19%)
  adding: aps/0117.png (deflated 16%)
  adding: aps/0052.png (deflated 16%)
  adding: aps/0126.png (deflated 16%)
  adding: aps/0150.png (deflated 18%)
  adding: aps/0042.png (deflated 16%)
  adding: aps/0112.png (deflated 16%)
  adding: aps/0168.png (deflated 16%)
  adding: aps/0075.png (deflated 19%)
  adding: aps/0036.png (deflated 18%)
  adding: aps/0095.png (deflated 19%)
  adding: aps/0065.png (deflated 16%)
  adding: aps/0057.png (deflated 16%)
  adding: aps/0033.png (deflated 18%)
  adding: aps/0182.png (deflated 16%)
  adding: aps/0091.png (deflated 18%)
  adding: aps/0067.png (deflated 17%)
  adding: aps/0081.png (deflated 18%)
  adding: aps/0047.png (deflated 16%)
  adding: aps/0151.png (deflated 18%)
  adding: aps/0056.png (deflated 16%)
  adding: aps/0142.png (deflated 18%)
  adding: aps/0044.png (deflated 16%)
  adding: aps/0020.png (deflated 18%)
  adding: aps/0106.png (deflated 16%)
  adding: aps/0072.png (deflated 18%)
  adding: aps/0113.png (deflated 16%)
  adding: aps/0043.png (deflated 16%)
  adding: aps/0157.png (deflated 33%)
  adding: aps/0013.png (deflated 18%)
  adding: aps/0158.png (deflated 27%)
  adding: aps/0034.png (deflated 19%)
  adding: aps/0138.png (deflated 18%)
  adding: aps/0100.png (deflated 18%)
  adding: aps/0175.png (deflated 16%)
  adding: aps/0167.png (deflated 16%)
  adding: aps/0041.png (deflated 18%)
  adding: aps/0177.png (deflated 16%)
  adding: aps/0032.png (deflated 19%)
  adding: aps/0093.png (deflated 18%)
  adding: aps/0004.png (deflated 16%)
  adding: aps/0006.png (deflated 16%)
  adding: aps/0159.png (deflated 31%)
  adding: aps/0188.png (deflated 18%)
  adding: aps/0030.png (deflated 18%)
  adding: aps/0130.png (deflated 19%)
  adding: aps/0132.png (deflated 18%)
  adding: aps/0009.png (deflated 20%)
  adding: aps/0205.png (deflated 18%)
  adding: aps/0162.png (deflated 17%)
  adding: aps/0017.png (deflated 19%)
  adding: aps/0051.png (deflated 17%)
  adding: aps/0190.png (deflated 18%)
  adding: aps/0170.png (deflated 16%)
  adding: aps/0035.png (deflated 18%)
  adding: aps/0201.png (deflated 18%)
  adding: aps/0018.png (deflated 18%)
  adding: aps/0156.png (deflated 18%)
  adding: aps/0196.png (deflated 18%)
  adding: aps/0147.png (deflated 18%)
  adding: aps/0183.png (deflated 16%)
  adding: aps/0198.png (deflated 18%)
  adding: aps/0069.png (deflated 21%)
  adding: aps/0148.png (deflated 18%)
  adding: aps/0060.png (deflated 16%)
  adding: aps/0003.png (deflated 16%)
  adding: aps/0187.png (deflated 22%)
  adding: aps/0029.png (deflated 18%)
  adding: aps/0115.png (deflated 16%)
  adding: aps/0141.png (deflated 18%)
  adding: aps/0001.png (deflated 16%)
  adding: aps/0200.png (deflated 19%)
  adding: aps/0046.png (deflated 16%)
  adding: aps/0135.png (deflated 18%)
  adding: aps/0080.png (deflated 18%)
  adding: aps/0094.png (deflated 19%)
  adding: aps/0090.png (deflated 18%)
  adding: aps/0203.png (deflated 18%)
  adding: aps/0049.png (deflated 16%)
  adding: aps/0164.png (deflated 16%)
  adding: aps/0024.png (deflated 18%)
  adding: aps/0061.png (deflated 16%)
  adding: aps/0039.png (deflated 25%)
  adding: aps/0101.png (deflated 18%)
  adding: aps/0152.png (deflated 18%)
  adding: aps/0097.png (deflated 32%)
  adding: aps/0059.png (deflated 16%)
  adding: aps/0038.png (deflated 27%)
  adding: aps/0070.png (deflated 20%)
  adding: aps/0129.png (deflated 20%)
  adding: aps/0037.png (deflated 25%)
  adding: aps/0073.png (deflated 18%)
  adding: aps/0116.png (deflated 16%)
  adding: aps/0185.png (deflated 16%)
  adding: aps/0021.png (deflated 18%)
  adding: aps/0137.png (deflated 17%)
  adding: aps/0015.png (deflated 18%)
  adding: aps/0166.png (deflated 16%)
  adding: aps/0146.png (deflated 18%)
  adding: aps/0121.png (deflated 16%)
  adding: aps/0027.png (deflated 19%)
  adding: aps/0040.png (deflated 19%)
  adding: aps/0074.png (deflated 19%)
  adding: aps/0149.png (deflated 17%)
  adding: aps/0096.png (deflated 18%)
  adding: aps/0068.png (deflated 23%)
  adding: aps/0181.png (deflated 16%)
  adding: aps/0180.png (deflated 16%)
  adding: aps/0076.png (deflated 19%)
  adding: aps/0079.png (deflated 18%)
  adding: aps/0078.png (deflated 18%)
  adding: aps/0125.png (deflated 16%)
  adding: aps/0127.png (deflated 21%)
  adding: aps/0099.png (deflated 27%)
  adding: aps/0194.png (deflated 18%)
  adding: aps/0008.png (deflated 20%)
  adding: aps/0028.png (deflated 18%)
  adding: aps/0050.png (deflated 17%)
  adding: aps/0088.png (deflated 18%)
  adding: aps/0118.png (deflated 16%)
  adding: aps/0103.png (deflated 17%)
  adding: aps/0092.png (deflated 18%)
  adding: aps/0012.png (deflated 18%)
  adding: aps/0133.png (deflated 19%)
  adding: aps/0165.png (deflated 16%)
  adding: aps/0031.png (deflated 19%)
  adding: aps/0064.png (deflated 16%)
  adding: aps/0155.png (deflated 17%)
  adding: aps/0193.png (deflated 18%)
  adding: aps/0055.png (deflated 16%)
  adding: aps/0195.png (deflated 18%)
  adding: aps/0144.png (deflated 17%)
  adding: aps/0110.png (deflated 16%)
  adding: aps/0016.png (deflated 18%)
  adding: aps/0202.png (deflated 18%)
  adding: aps/0114.png (deflated 16%)
  adding: aps/0107.png (deflated 16%)
  adding: aps/0123.png (deflated 16%)
  adding: aps/0109.png (deflated 16%)
  adding: aps/0189.png (deflated 20%)
  adding: aps/0025.png (deflated 18%)
  adding: aps/0085.png (deflated 18%)
  adding: aps/0058.png (deflated 16%)
  adding: aps/0153.png (deflated 17%)
  adding: aps/0139.png (deflated 19%)
  adding: aps/0174.png (deflated 16%)
  adding: aps/0192.png (deflated 17%)
  adding: aps/0169.png (deflated 16%)
  adding: aps/0098.png (deflated 31%)
  adding: aps/0048.png (deflated 16%)
  adding: aps/0089.png (deflated 18%)
  adding: aps/0122.png (deflated 16%)
  adding: aps/0002.png (deflated 16%)
  adding: aps/0111.png (deflated 16%)
  adding: aps/0172.png (deflated 16%)
  adding: aps/0176.png (deflated 16%)
  adding: aps/0136.png (deflated 18%)

'The chosen video file: /content/video/lamp_1hz.MOV'

FPS: 29.971181556195965
Frame count: 208
Duration: 6.94 sec
The Final v2e command:

'v2e -i /content/video/lamp_1hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/lamp_1hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/lamp_1hz.MOV
INFO:v2e:Input video frame rate 29.971181556195965Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/lamp_1hz.MOV has total 208 frames with total duration 6.90s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 208 frames 0 to 207
(From 0.0s to 6.9s, duration 6.9s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 207.0 frames with duration 6.90s and playback duration 6.90s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 207 from video input
INFO:v2e:Input video /content/video/lamp_1hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 208 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/208 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 208/208 [00:06<00:00, 31.75fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpwy1bj_ig
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 26 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/26 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 15
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/26 [00:05<02:05,  5.02s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 184
slomo-interp:   8% 2/26 [00:55<12:44, 31.85s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 45
slomo-interp: 100% 26/26 [14:14<00:00, 32.85s/ batch of 8 fr]
write-orig-avi: 100% 208/208 [00:00<00:00, 853.22fr/s]
write-slomo-vid: 100% 24493/24493 [00:58<00:00, 415.42fr/s]
INFO:v2ecore.slomo:Wrote 24493 frames and returning 24493 frame times.
Average upsampling factor=118.6
INFO:v2e:SloMo average upsampling factor=118.58; average DVS timestamp resolution=281.11us
INFO:v2e:*** Stage 3/3: emulating DVS events from 24493 frames
dvs:   0% 0/24493 [00:00<?, ?fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2 at t=0.0022s
dvs:   0% 4/24493 [00:00<10:14, 39.88fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:   1% 306/24493 [00:06<07:04, 57.03fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #309 at t=0.3007s
WARNING:v2ecore.emulator:no signal events generated for frame #312 at t=0.3013s
dvs:   1% 314/24493 [00:06<07:04, 56.89fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #320 at t=0.3027s
dvs:   1% 330/24493 [00:06<07:18, 55.14fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #336 at t=0.3056s
dvs:   2% 370/24493 [00:07<07:57, 50.50fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #376 at t=0.3129s
dvs:   2% 418/24493 [00:08<07:35, 52.87fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #426 at t=0.3219s
dvs:   2% 493/24493 [00:09<04:59, 80.14fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #502 at t=0.3357s
dvs:   2% 520/24493 [00:10<04:55, 81.06fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #526 at t=0.3400s
WARNING:v2ecore.emulator:no signal events generated for frame #529 at t=0.3406s
dvs:   2% 573/24493 [00:11<06:14, 63.86fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #574 at t=0.3487s
dvs:   2% 599/24493 [00:11<05:15, 75.81fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #601 at t=0.3536s
dvs:   3% 637/24493 [00:11<04:40, 84.99fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #639 at t=0.3605s
dvs:  11% 2591/24493 [00:47<04:32, 80.43fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,600 at t=0.9348s
dvs:  22% 5330/24493 [01:41<04:22, 73.10fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,337 at t=1.9352s
WARNING:v2ecore.emulator:no signal events generated for frame #5,342 at t=1.9361s
WARNING:v2ecore.emulator:no signal events generated for frame #5,345 at t=1.9367s
WARNING:v2ecore.emulator:no signal events generated for frame #5,346 at t=1.9368s
WARNING:v2ecore.emulator:no signal events generated for frame #5,350 at t=1.9376s
WARNING:v2ecore.emulator:no signal events generated for frame #5,351 at t=1.9378s
WARNING:v2ecore.emulator:no signal events generated for frame #5,354 at t=1.9383s
dvs:  22% 5354/24493 [01:41<04:18, 74.16fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,358 at t=1.9390s
WARNING:v2ecore.emulator:no signal events generated for frame #5,361 at t=1.9396s
WARNING:v2ecore.emulator:no signal events generated for frame #5,366 at t=1.9405s
dvs:  22% 5370/24493 [01:41<03:41, 86.24fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,378 at t=1.9427s
dvs:  22% 5379/24493 [01:41<03:41, 86.48fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,387 at t=1.9443s
dvs:  22% 5388/24493 [01:41<03:48, 83.75fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,393 at t=1.9454s
WARNING:v2ecore.emulator:no signal events generated for frame #5,400 at t=1.9467s
dvs:  22% 5402/24493 [01:41<03:24, 93.46fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,409 at t=1.9483s
WARNING:v2ecore.emulator:no signal events generated for frame #5,411 at t=1.9487s
WARNING:v2ecore.emulator:no signal events generated for frame #5,415 at t=1.9494s
WARNING:v2ecore.emulator:no signal events generated for frame #5,416 at t=1.9496s
dvs:  22% 5418/24493 [01:42<03:13, 98.41fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,419 at t=1.9501s
WARNING:v2ecore.emulator:no signal events generated for frame #5,427 at t=1.9516s
dvs:  22% 5428/24493 [01:42<03:15, 97.63fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,432 at t=1.9525s
WARNING:v2ecore.emulator:no signal events generated for frame #5,435 at t=1.9531s
WARNING:v2ecore.emulator:no signal events generated for frame #5,438 at t=1.9536s
dvs:  22% 5438/24493 [01:42<03:15, 97.50fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,439 at t=1.9538s
dvs:  22% 5448/24493 [01:42<03:21, 94.52fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,451 at t=1.9560s
WARNING:v2ecore.emulator:no signal events generated for frame #5,457 at t=1.9571s
dvs:  22% 5458/24493 [01:42<03:29, 91.07fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,459 at t=1.9574s
WARNING:v2ecore.emulator:no signal events generated for frame #5,462 at t=1.9580s
WARNING:v2ecore.emulator:no signal events generated for frame #5,465 at t=1.9585s
dvs:  22% 5474/24493 [01:42<03:10, 99.69fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,479 at t=1.9611s
WARNING:v2ecore.emulator:no signal events generated for frame #5,484 at t=1.9620s
dvs:  22% 5484/24493 [01:42<03:13, 98.05fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,489 at t=1.9629s
dvs:  24% 5994/24493 [01:52<04:24, 69.89fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,000 at t=2.0560s
dvs:  39% 9466/24493 [02:53<04:41, 53.45fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,474 at t=2.8417s
dvs:  39% 9474/24493 [02:53<04:13, 59.34fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,481 at t=2.8430s
WARNING:v2ecore.emulator:no signal events generated for frame #9,484 at t=2.8436s
dvs:  39% 9499/24493 [02:53<03:10, 78.80fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,502 at t=2.8469s
dvs:  39% 9517/24493 [02:54<03:07, 79.69fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,523 at t=2.8508s
WARNING:v2ecore.emulator:no signal events generated for frame #9,526 at t=2.8514s
dvs:  39% 9562/24493 [02:54<03:38, 68.19fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,565 at t=2.8586s
dvs:  40% 9802/24493 [02:58<03:31, 69.50fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,803 at t=2.9027s
dvs:  40% 9810/24493 [02:58<03:24, 71.91fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,815 at t=2.9049s
dvs:  40% 9818/24493 [02:59<04:49, 50.77fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,825 at t=2.9067s
WARNING:v2ecore.emulator:no signal events generated for frame #9,828 at t=2.9073s
WARNING:v2ecore.emulator:no signal events generated for frame #9,830 at t=2.9077s
WARNING:v2ecore.emulator:no signal events generated for frame #9,831 at t=2.9079s
WARNING:v2ecore.emulator:no signal events generated for frame #9,832 at t=2.9080s
dvs:  40% 9834/24493 [02:59<03:30, 69.78fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,838 at t=2.9092s
WARNING:v2ecore.emulator:no signal events generated for frame #9,839 at t=2.9093s
WARNING:v2ecore.emulator:no signal events generated for frame #9,841 at t=2.9097s
WARNING:v2ecore.emulator:no signal events generated for frame #9,844 at t=2.9103s
WARNING:v2ecore.emulator:no signal events generated for frame #9,849 at t=2.9112s
WARNING:v2ecore.emulator:no signal events generated for frame #9,856 at t=2.9125s
dvs:  40% 9858/24493 [02:59<02:39, 91.92fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,859 at t=2.9130s
WARNING:v2ecore.emulator:no signal events generated for frame #9,862 at t=2.9136s
WARNING:v2ecore.emulator:no signal events generated for frame #9,863 at t=2.9138s
WARNING:v2ecore.emulator:no signal events generated for frame #9,865 at t=2.9142s
WARNING:v2ecore.emulator:no signal events generated for frame #9,866 at t=2.9143s
WARNING:v2ecore.emulator:no signal events generated for frame #9,867 at t=2.9145s
WARNING:v2ecore.emulator:no signal events generated for frame #9,870 at t=2.9151s
WARNING:v2ecore.emulator:no signal events generated for frame #9,872 at t=2.9155s
WARNING:v2ecore.emulator:no signal events generated for frame #9,873 at t=2.9156s
WARNING:v2ecore.emulator:no signal events generated for frame #9,874 at t=2.9158s
WARNING:v2ecore.emulator:no signal events generated for frame #9,875 at t=2.9160s
WARNING:v2ecore.emulator:no signal events generated for frame #9,876 at t=2.9162s
WARNING:v2ecore.emulator:no signal events generated for frame #9,879 at t=2.9167s
WARNING:v2ecore.emulator:no signal events generated for frame #9,881 at t=2.9171s
WARNING:v2ecore.emulator:no signal events generated for frame #9,883 at t=2.9175s
WARNING:v2ecore.emulator:no signal events generated for frame #9,884 at t=2.9177s
WARNING:v2ecore.emulator:no signal events generated for frame #9,885 at t=2.9179s
WARNING:v2ecore.emulator:no signal events generated for frame #9,887 at t=2.9182s
WARNING:v2ecore.emulator:no signal events generated for frame #9,888 at t=2.9184s
WARNING:v2ecore.emulator:no signal events generated for frame #9,889 at t=2.9186s
WARNING:v2ecore.emulator:no signal events generated for frame #9,890 at t=2.9188s
dvs:  40% 9892/24493 [02:59<01:41, 144.29fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,893 at t=2.9193s
WARNING:v2ecore.emulator:no signal events generated for frame #9,894 at t=2.9195s
WARNING:v2ecore.emulator:no signal events generated for frame #9,896 at t=2.9199s
WARNING:v2ecore.emulator:no signal events generated for frame #9,897 at t=2.9201s
WARNING:v2ecore.emulator:no signal events generated for frame #9,899 at t=2.9205s
WARNING:v2ecore.emulator:no signal events generated for frame #9,900 at t=2.9206s
WARNING:v2ecore.emulator:no signal events generated for frame #9,903 at t=2.9212s
WARNING:v2ecore.emulator:no signal events generated for frame #9,904 at t=2.9214s
WARNING:v2ecore.emulator:no signal events generated for frame #9,905 at t=2.9216s
WARNING:v2ecore.emulator:no signal events generated for frame #9,906 at t=2.9217s
WARNING:v2ecore.emulator:no signal events generated for frame #9,907 at t=2.9219s
WARNING:v2ecore.emulator:no signal events generated for frame #9,912 at t=2.9229s
dvs: 100% 24493/24493 [07:34<00:00, 53.87fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 206 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 208 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 24493 frames
INFO:v2e:generated total 25.31M events (12.73M on, 12.58M off)
INFO:v2e:Avg event rate for N=89960 px and total time =6.900 s
	Total: 3.67MHz (1.85MHz on, 1.82MHz off)
	Per pixel:  40.77Hz (20.51Hz on, 20.26Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 416 frames in 1.38ks (3.31s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 206 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 208 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 24493 frames
Total events: 25,309,509
  Written 5,000,000/25,309,509
  Written 10,000,000/25,309,509
  Written 15,000,000/25,309,509
  Written 20,000,000/25,309,509
  Written 25,000,000/25,309,509
  Written 25,309,509/25,309,509
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 208
Output folder: /content/v2e-output/aps
APS frames found: 208
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/208 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:06.93, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:06.93, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x579a6908b840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x579a6909cf00] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x579a69310940] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x579a69310940] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x579a69310940] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  208 fps= 31 q=-1.0 Lsize=    3553kB time=00:00:06.83 bitrate=4258.8kbits/s speed=1.02x
video:3550kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.077828%
[libx264 @ 0x579a69310940] frame I:22    Avg QP:26.56  size: 45417
[libx264 @ 0x579a69310940] frame P:94    Avg QP:29.06  size: 20263
[libx264 @ 0x579a69310940] frame B:92    Avg QP:30.12  size:  7939
[libx264 @ 0x579a69310940] consecutive B-frames: 38.9%  1.9% 13.0% 46.2%
[libx264 @ 0x579a69310940] mb I  I16..4:  1.5% 48.3% 50.2%
[libx264 @ 0x579a69310940] mb P  I16..4:  6.0% 31.0% 29.8%  P16..4: 14.2%  2.6%  1.9%  0.0%  0.0%    skip:14.5%
[libx264 @ 0x579a69310940] mb B  I16..4:  6.7%  2.1%  5.8%  B16..8: 26.4%  4.8%  2.7%  direct: 2.9%  skip:48.5%  L0:39.6% L1:57.5% BI: 2.9%
[libx264 @ 0x579a69310940] 8x8 transform intra:42.5% inter:50.4%
[libx264 @ 0x579a69310940] coded y,uvDC,uvAC intra: 68.2% 47.8% 45.5% inter: 20.1% 5.6% 2.4%
[libx264 @ 0x579a69310940] i16 v,h,dc,p: 41% 18% 37%  4%
[libx264 @ 0x579a69310940] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 51% 11% 25%  2%  2%  3%  1%  3%  2%
[libx264 @ 0x579a69310940] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 12% 31%  6%  5%  6%  5%  5%  4%
[libx264 @ 0x579a69310940] i8c dc,h,v,p: 76%  6% 13%  4%
[libx264 @ 0x579a69310940] Weighted P-Frames: Y:20.2% UV:18.1%
[libx264 @ 0x579a69310940] ref P L0: 72.0% 13.3%  9.6%  4.5%  0.5%
[libx264 @ 0x579a69310940] ref B L0: 81.0% 16.2%  2.7%
[libx264 @ 0x579a69310940] ref B L1: 88.9% 11.1%
[libx264 @ 0x579a69310940] kb/s:4193.37
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (stored 0%)
  adding: dvs/0140.png (stored 0%)
  adding: dvs/0104.png (stored 0%)
  adding: dvs/0160.png (deflated 5%)
  adding: dvs/0105.png (stored 0%)
  adding: dvs/0199.png (stored 0%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0077.png (stored 0%)
  adding: dvs/0011.png (stored 0%)
  adding: dvs/0026.png (stored 0%)
  adding: dvs/0154.png (stored 0%)
  adding: dvs/0128.png (deflated 1%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0120.png (stored 0%)
  adding: dvs/0163.png (deflated 22%)
  adding: dvs/0084.png (stored 0%)
  adding: dvs/0066.png (deflated 1%)
  adding: dvs/0010.png (deflated 3%)
  adding: dvs/0191.png (deflated 3%)
  adding: dvs/0007.png (deflated 3%)
  adding: dvs/0071.png (deflated 3%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (deflated 6%)
  adding: dvs/0062.png (stored 0%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0197.png (stored 0%)
  adding: dvs/0143.png (deflated 0%)
  adding: dvs/0184.png (stored 0%)
  adding: dvs/0178.png (stored 0%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (stored 0%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (stored 0%)
  adding: dvs/0126.png (stored 0%)
  adding: dvs/0150.png (stored 0%)
  adding: dvs/0042.png (deflated 10%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (stored 0%)
  adding: dvs/0075.png (stored 0%)
  adding: dvs/0036.png (stored 0%)
  adding: dvs/0207.png (deflated 0%)
  adding: dvs/0095.png (stored 0%)
  adding: dvs/0065.png (stored 0%)
  adding: dvs/0057.png (stored 0%)
  adding: dvs/0033.png (stored 0%)
  adding: dvs/0182.png (stored 0%)
  adding: dvs/0091.png (stored 0%)
  adding: dvs/0067.png (deflated 2%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0047.png (stored 0%)
  adding: dvs/0151.png (stored 0%)
  adding: dvs/0056.png (stored 0%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (deflated 30%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0072.png (stored 0%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (deflated 1%)
  adding: dvs/0013.png (deflated 23%)
  adding: dvs/0158.png (deflated 3%)
  adding: dvs/0034.png (stored 0%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (deflated 2%)
  adding: dvs/0175.png (stored 0%)
  adding: dvs/0167.png (stored 0%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0177.png (stored 0%)
  adding: dvs/0032.png (stored 0%)
  adding: dvs/0093.png (stored 0%)
  adding: dvs/0004.png (stored 0%)
  adding: dvs/0006.png (deflated 2%)
  adding: dvs/0159.png (deflated 4%)
  adding: dvs/0188.png (deflated 1%)
  adding: dvs/0030.png (stored 0%)
  adding: dvs/0130.png (deflated 2%)
  adding: dvs/0132.png (stored 0%)
  adding: dvs/0009.png (deflated 11%)
  adding: dvs/0205.png (deflated 0%)
  adding: dvs/0162.png (stored 0%)
  adding: dvs/0017.png (stored 0%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (deflated 5%)
  adding: dvs/0170.png (stored 0%)
  adding: dvs/0035.png (stored 0%)
  adding: dvs/0201.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (deflated 1%)
  adding: dvs/0196.png (stored 0%)
  adding: dvs/0147.png (stored 0%)
  adding: dvs/0183.png (stored 0%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0069.png (deflated 4%)
  adding: dvs/0148.png (stored 0%)
  adding: dvs/0060.png (stored 0%)
  adding: dvs/0003.png (stored 0%)
  adding: dvs/0187.png (stored 0%)
  adding: dvs/0029.png (stored 0%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0001.png (deflated 2%)
  adding: dvs/0200.png (stored 0%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0135.png (stored 0%)
  adding: dvs/0080.png (stored 0%)
  adding: dvs/0094.png (stored 0%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0203.png (stored 0%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (stored 0%)
  adding: dvs/0024.png (stored 0%)
  adding: dvs/0061.png (stored 0%)
  adding: dvs/0039.png (deflated 1%)
  adding: dvs/0101.png (deflated 5%)
  adding: dvs/0152.png (stored 0%)
  adding: dvs/0097.png (stored 0%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (deflated 0%)
  adding: dvs/0070.png (deflated 5%)
  adding: dvs/0129.png (deflated 3%)
  adding: dvs/0206.png (stored 0%)
  adding: dvs/0037.png (deflated 0%)
  adding: dvs/0073.png (stored 0%)
  adding: dvs/0116.png (stored 0%)
  adding: dvs/0185.png (stored 0%)
  adding: dvs/0021.png (stored 0%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0015.png (stored 0%)
  adding: dvs/0166.png (stored 0%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0121.png (stored 0%)
  adding: dvs/0027.png (deflated 4%)
  adding: dvs/0040.png (deflated 0%)
  adding: dvs/0074.png (stored 0%)
  adding: dvs/0149.png (stored 0%)
  adding: dvs/0096.png (stored 0%)
  adding: dvs/0068.png (deflated 4%)
  adding: dvs/0181.png (stored 0%)
  adding: dvs/0180.png (stored 0%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (stored 0%)
  adding: dvs/0078.png (stored 0%)
  adding: dvs/0125.png (stored 0%)
  adding: dvs/0127.png (stored 0%)
  adding: dvs/0099.png (deflated 2%)
  adding: dvs/0194.png (stored 0%)
  adding: dvs/0008.png (deflated 2%)
  adding: dvs/0028.png (stored 0%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (stored 0%)
  adding: dvs/0103.png (stored 0%)
  adding: dvs/0092.png (stored 0%)
  adding: dvs/0012.png (deflated 67%)
  adding: dvs/0133.png (stored 0%)
  adding: dvs/0165.png (stored 0%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (stored 0%)
  adding: dvs/0155.png (stored 0%)
  adding: dvs/0193.png (deflated 59%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (deflated 35%)
  adding: dvs/0144.png (stored 0%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0202.png (stored 0%)
  adding: dvs/0208.png (stored 0%)
  adding: dvs/0114.png (stored 0%)
  adding: dvs/0107.png (stored 0%)
  adding: dvs/0123.png (stored 0%)
  adding: dvs/0109.png (stored 0%)
  adding: dvs/0189.png (deflated 3%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0058.png (stored 0%)
  adding: dvs/0153.png (stored 0%)
  adding: dvs/0139.png (stored 0%)
  adding: dvs/0174.png (stored 0%)
  adding: dvs/0192.png (stored 0%)
  adding: dvs/0169.png (stored 0%)
  adding: dvs/0098.png (deflated 1%)
  adding: dvs/0048.png (stored 0%)
  adding: dvs/0089.png (stored 0%)
  adding: dvs/0122.png (stored 0%)
  adding: dvs/0002.png (deflated 0%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (stored 0%)
  adding: dvs/0176.png (deflated 0%)
  adding: dvs/0136.png (stored 0%)
  adding: dvs/0005.png (deflated 0%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (stored 0%)
  adding: dvs/0124.png (stored 0%)
  adding: dvs/0204.png (stored 0%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0173.png (stored 0%)
  adding: dvs/0186.png (deflated 1%)
  adding: dvs/0131.png (deflated 2%)
  adding: dvs/0119.png (stored 0%)
  adding: dvs/0083.png (deflated 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (stored 0%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 17%)
  adding: aps/0140.png (deflated 19%)
  adding: aps/0104.png (deflated 19%)
  adding: aps/0160.png (deflated 16%)
  adding: aps/0105.png (deflated 18%)
  adding: aps/0199.png (deflated 18%)
  adding: aps/0134.png (deflated 19%)
  adding: aps/0077.png (deflated 18%)
  adding: aps/0011.png (deflated 16%)
  adding: aps/0026.png (deflated 18%)
  adding: aps/0154.png (deflated 16%)
  adding: aps/0128.png (deflated 16%)
  adding: aps/0171.png (deflated 18%)
  adding: aps/0108.png (deflated 18%)
  adding: aps/0145.png (deflated 18%)
  adding: aps/0120.png (deflated 29%)
  adding: aps/0163.png (deflated 23%)
  adding: aps/0084.png (deflated 18%)
  adding: aps/0066.png (deflated 16%)
  adding: aps/0010.png (deflated 16%)
  adding: aps/0191.png (deflated 16%)
  adding: aps/0007.png (deflated 16%)
  adding: aps/0071.png (deflated 16%)
  adding: aps/0053.png (deflated 18%)
  adding: aps/0161.png (deflated 16%)
  adding: aps/0062.png (deflated 17%)
  adding: aps/0082.png (deflated 18%)
  adding: aps/0197.png (deflated 18%)
  adding: aps/0143.png (deflated 18%)
  adding: aps/0184.png (deflated 17%)
  adding: aps/0178.png (deflated 35%)
  adding: aps/0054.png (deflated 18%)
  adding: aps/0022.png (deflated 18%)
  adding: aps/0045.png (deflated 19%)
  adding: aps/0086.png (deflated 18%)
  adding: aps/0117.png (deflated 19%)
  adding: aps/0052.png (deflated 18%)
  adding: aps/0126.png (deflated 16%)
  adding: aps/0150.png (deflated 29%)
  adding: aps/0042.png (deflated 16%)
  adding: aps/0112.png (deflated 19%)
  adding: aps/0168.png (deflated 18%)
  adding: aps/0075.png (deflated 19%)
  adding: aps/0036.png (deflated 16%)
  adding: aps/0207.png (deflated 19%)
  adding: aps/0095.png (deflated 16%)
  adding: aps/0065.png (deflated 16%)
  adding: aps/0057.png (deflated 18%)
  adding: aps/0033.png (deflated 17%)
  adding: aps/0182.png (deflated 18%)
  adding: aps/0091.png (deflated 18%)
  adding: aps/0067.png (deflated 16%)
  adding: aps/0081.png (deflated 18%)
  adding: aps/0047.png (deflated 18%)
  adding: aps/0151.png (deflated 22%)
  adding: aps/0056.png (deflated 18%)
  adding: aps/0142.png (deflated 18%)
  adding: aps/0044.png (deflated 20%)
  adding: aps/0020.png (deflated 19%)
  adding: aps/0106.png (deflated 18%)
  adding: aps/0072.png (deflated 16%)
  adding: aps/0113.png (deflated 19%)
  adding: aps/0043.png (deflated 23%)
  adding: aps/0157.png (deflated 16%)
  adding: aps/0013.png (deflated 24%)
  adding: aps/0158.png (deflated 16%)
  adding: aps/0034.png (deflated 16%)
  adding: aps/0138.png (deflated 18%)
  adding: aps/0100.png (deflated 16%)
  adding: aps/0175.png (deflated 18%)
  adding: aps/0167.png (deflated 18%)
  adding: aps/0041.png (deflated 16%)
  adding: aps/0177.png (deflated 18%)
  adding: aps/0032.png (deflated 17%)
  adding: aps/0093.png (deflated 17%)
  adding: aps/0004.png (deflated 16%)
  adding: aps/0006.png (deflated 16%)
  adding: aps/0159.png (deflated 16%)
  adding: aps/0188.png (deflated 17%)
  adding: aps/0030.png (deflated 28%)
  adding: aps/0130.png (deflated 16%)
  adding: aps/0132.png (deflated 16%)
  adding: aps/0009.png (deflated 16%)
  adding: aps/0205.png (deflated 18%)
  adding: aps/0162.png (deflated 16%)
  adding: aps/0017.png (deflated 18%)
  adding: aps/0051.png (deflated 18%)
  adding: aps/0190.png (deflated 17%)
  adding: aps/0170.png (deflated 18%)
  adding: aps/0035.png (deflated 16%)
  adding: aps/0201.png (deflated 17%)
  adding: aps/0018.png (deflated 19%)
  adding: aps/0156.png (deflated 16%)
  adding: aps/0196.png (deflated 18%)
  adding: aps/0147.png (deflated 18%)
  adding: aps/0183.png (deflated 17%)
  adding: aps/0198.png (deflated 18%)
  adding: aps/0069.png (deflated 16%)
  adding: aps/0148.png (deflated 35%)
  adding: aps/0060.png (deflated 28%)
  adding: aps/0003.png (deflated 17%)
  adding: aps/0187.png (deflated 16%)
  adding: aps/0029.png (deflated 31%)
  adding: aps/0115.png (deflated 18%)
  adding: aps/0141.png (deflated 18%)
  adding: aps/0001.png (deflated 18%)
  adding: aps/0200.png (deflated 18%)
  adding: aps/0046.png (deflated 19%)
  adding: aps/0135.png (deflated 18%)
  adding: aps/0080.png (deflated 18%)
  adding: aps/0094.png (deflated 16%)
  adding: aps/0090.png (deflated 30%)
  adding: aps/0203.png (deflated 19%)
  adding: aps/0049.png (deflated 18%)
  adding: aps/0164.png (deflated 19%)
  adding: aps/0024.png (deflated 18%)
  adding: aps/0061.png (deflated 18%)
  adding: aps/0039.png (deflated 16%)
  adding: aps/0101.png (deflated 16%)
  adding: aps/0152.png (deflated 17%)
  adding: aps/0097.png (deflated 17%)
  adding: aps/0059.png (deflated 31%)
  adding: aps/0038.png (deflated 16%)
  adding: aps/0070.png (deflated 16%)
  adding: aps/0129.png (deflated 16%)
  adding: aps/0206.png (deflated 18%)
  adding: aps/0037.png (deflated 16%)
  adding: aps/0073.png (deflated 21%)
  adding: aps/0116.png (deflated 19%)
  adding: aps/0185.png (deflated 16%)
  adding: aps/0021.png (deflated 19%)
  adding: aps/0137.png (deflated 18%)
  adding: aps/0015.png (deflated 18%)
  adding: aps/0166.png (deflated 19%)
  adding: aps/0146.png (deflated 18%)
  adding: aps/0121.png (deflated 19%)
  adding: aps/0027.png (deflated 18%)
  adding: aps/0040.png (deflated 16%)
  adding: aps/0074.png (deflated 19%)
  adding: aps/0149.png (deflated 32%)
  adding: aps/0096.png (deflated 16%)
  adding: aps/0068.png (deflated 16%)
  adding: aps/0181.png (deflated 19%)
  adding: aps/0180.png (deflated 21%)
  adding: aps/0076.png (deflated 18%)
  adding: aps/0079.png (deflated 19%)
  adding: aps/0078.png (deflated 18%)
  adding: aps/0125.png (deflated 16%)
  adding: aps/0127.png (deflated 16%)
  adding: aps/0099.png (deflated 16%)
  adding: aps/0194.png (deflated 20%)
  adding: aps/0008.png (deflated 16%)
  adding: aps/0028.png (deflated 35%)
  adding: aps/0050.png (deflated 18%)
  adding: aps/0088.png (deflated 32%)
  adding: aps/0118.png (deflated 35%)
  adding: aps/0103.png (deflated 23%)
  adding: aps/0092.png (deflated 17%)
  adding: aps/0012.png (deflated 16%)
  adding: aps/0133.png (deflated 22%)
  adding: aps/0165.png (deflated 19%)
  adding: aps/0031.png (deflated 18%)
  adding: aps/0064.png (deflated 16%)
  adding: aps/0155.png (deflated 17%)
  adding: aps/0193.png (deflated 22%)
  adding: aps/0055.png (deflated 18%)
  adding: aps/0195.png (deflated 18%)
  adding: aps/0144.png (deflated 18%)
  adding: aps/0110.png (deflated 18%)
  adding: aps/0016.png (deflated 18%)
  adding: aps/0202.png (deflated 18%)
  adding: aps/0208.png (deflated 33%)
  adding: aps/0114.png (deflated 19%)
  adding: aps/0107.png (deflated 18%)
  adding: aps/0123.png (deflated 17%)
  adding: aps/0109.png (deflated 18%)
  adding: aps/0189.png (deflated 17%)
  adding: aps/0025.png (deflated 18%)
  adding: aps/0085.png (deflated 18%)
  adding: aps/0058.png (deflated 35%)
  adding: aps/0153.png (deflated 17%)
  adding: aps/0139.png (deflated 19%)
  adding: aps/0174.png (deflated 18%)
  adding: aps/0192.png (deflated 16%)
  adding: aps/0169.png (deflated 19%)
  adding: aps/0098.png (deflated 16%)
  adding: aps/0048.png (deflated 19%)
  adding: aps/0089.png (deflated 27%)
  adding: aps/0122.png (deflated 18%)
  adding: aps/0002.png (deflated 17%)
  adding: aps/0111.png (deflated 18%)

'The chosen video file: /content/video/lamp_2hz.MOV'

FPS: 29.97275204359673
Frame count: 220
Duration: 7.34 sec
The Final v2e command:

'v2e -i /content/video/lamp_2hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/lamp_2hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/lamp_2hz.MOV
INFO:v2e:Input video frame rate 29.97275204359673Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/lamp_2hz.MOV has total 220 frames with total duration 7.30s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 220 frames 0 to 219
(From 0.0s to 7.3s, duration 7.3s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 219.0 frames with duration 7.30s and playback duration 7.30s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 219 from video input
INFO:v2e:Input video /content/video/lamp_2hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 220 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/220 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 220/220 [00:06<00:00, 33.89fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmp7tlgj73k
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 28 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/28 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 184
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/28 [00:50<22:33, 50.13s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 182
slomo-interp:   7% 2/28 [01:41<21:56, 50.63s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 178
slomo-interp: 100% 28/28 [22:31<00:00, 48.26s/ batch of 8 fr]
write-orig-avi: 100% 220/220 [00:00<00:00, 717.40fr/s]
write-slomo-vid: 100% 38153/38153 [01:33<00:00, 408.69fr/s]
INFO:v2ecore.slomo:Wrote 38153 frames and returning 38153 frame times.
Average upsampling factor=172.4
INFO:v2e:SloMo average upsampling factor=172.36; average DVS timestamp resolution=193.40us
INFO:v2e:*** Stage 3/3: emulating DVS events from 38153 frames
dvs:   0% 2/38153 [00:00<39:21, 16.16fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:  43% 16506/38153 [05:07<07:20, 49.09fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,507 at t=3.0767s
dvs:  43% 16538/38153 [05:08<06:50, 52.62fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,544 at t=3.0834s
dvs:  43% 16546/38153 [05:08<07:14, 49.70fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,551 at t=3.0847s
dvs:  44% 16634/38153 [05:10<08:23, 42.72fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,638 at t=3.1005s
dvs:  44% 16674/38153 [05:11<06:12, 57.70fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,682 at t=3.1085s
dvs:  44% 16762/38153 [05:12<05:09, 69.12fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,765 at t=3.1237s
dvs:  53% 20290/38153 [06:18<04:17, 69.28fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #20,291 at t=3.7789s
dvs:  88% 33754/38153 [10:43<01:23, 52.39fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #33,761 at t=6.4280s
dvs: 100% 38153/38153 [12:11<00:00, 52.14fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 219 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 220 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 38153 frames
INFO:v2e:generated total 50.19M events (25.79M on, 24.40M off)
INFO:v2e:Avg event rate for N=89960 px and total time =7.300 s
	Total: 6.88MHz (3.53MHz on, 3.34MHz off)
	Per pixel:  76.43Hz (39.28Hz on, 37.15Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 440 frames in 2.19ks (4.97s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 219 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 220 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 38153 frames
Total events: 50,191,155
  Written 5,000,000/50,191,155
  Written 10,000,000/50,191,155
  Written 15,000,000/50,191,155
  Written 20,000,000/50,191,155
  Written 25,000,000/50,191,155
  Written 30,000,000/50,191,155
  Written 35,000,000/50,191,155
  Written 40,000,000/50,191,155
  Written 45,000,000/50,191,155
  Written 50,000,000/50,191,155
  Written 50,191,155/50,191,155
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 220
Output folder: /content/v2e-output/aps
APS frames found: 220
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/220 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:07.33, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:07.33, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x589731470840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x589731479300] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x589731491580] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x589731491580] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x589731491580] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  220 fps= 24 q=-1.0 Lsize=    5646kB time=00:00:07.23 bitrate=6393.8kbits/s speed=0.774x
video:5643kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.041134%
[libx264 @ 0x589731491580] frame I:31    Avg QP:27.03  size: 43788
[libx264 @ 0x589731491580] frame P:154   Avg QP:29.45  size: 23720
[libx264 @ 0x589731491580] frame B:35    Avg QP:31.35  size: 21938
[libx264 @ 0x589731491580] consecutive B-frames: 75.0%  8.2%  9.5%  7.3%
[libx264 @ 0x589731491580] mb I  I16..4:  1.7% 49.1% 49.2%
[libx264 @ 0x589731491580] mb P  I16..4:  6.2% 39.4% 34.2%  P16..4:  9.7%  1.8%  1.0%  0.0%  0.0%    skip: 7.8%
[libx264 @ 0x589731491580] mb B  I16..4: 11.7%  2.6% 19.9%  B16..8: 16.5%  5.9%  4.0%  direct: 7.8%  skip:31.6%  L0:38.5% L1:55.5% BI: 6.0%
[libx264 @ 0x589731491580] 8x8 transform intra:46.3% inter:68.3%
[libx264 @ 0x589731491580] coded y,uvDC,uvAC intra: 71.4% 46.7% 44.6% inter: 37.3% 7.3% 3.4%
[libx264 @ 0x589731491580] i16 v,h,dc,p: 37% 15% 42%  5%
[libx264 @ 0x589731491580] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 51% 11% 24%  2%  2%  3%  1%  3%  3%
[libx264 @ 0x589731491580] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 12% 30%  6%  5%  6%  5%  5%  4%
[libx264 @ 0x589731491580] i8c dc,h,v,p: 77%  6% 13%  4%
[libx264 @ 0x589731491580] Weighted P-Frames: Y:23.4% UV:21.4%
[libx264 @ 0x589731491580] ref P L0: 56.3% 26.5% 11.4%  4.6%  1.2%
[libx264 @ 0x589731491580] ref B L0: 85.1% 13.5%  1.4%
[libx264 @ 0x589731491580] ref B L1: 97.2%  2.8%
[libx264 @ 0x589731491580] kb/s:6303.32
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (stored 0%)
  adding: dvs/0140.png (stored 0%)
  adding: dvs/0104.png (stored 0%)
  adding: dvs/0160.png (stored 0%)
  adding: dvs/0105.png (stored 0%)
  adding: dvs/0199.png (stored 0%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0077.png (stored 0%)
  adding: dvs/0011.png (stored 0%)
  adding: dvs/0026.png (stored 0%)
  adding: dvs/0154.png (stored 0%)
  adding: dvs/0128.png (stored 0%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0120.png (stored 0%)
  adding: dvs/0163.png (stored 0%)
  adding: dvs/0084.png (stored 0%)
  adding: dvs/0066.png (stored 0%)
  adding: dvs/0010.png (stored 0%)
  adding: dvs/0191.png (stored 0%)
  adding: dvs/0007.png (stored 0%)
  adding: dvs/0071.png (stored 0%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (stored 0%)
  adding: dvs/0062.png (stored 0%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0197.png (stored 0%)
  adding: dvs/0143.png (stored 0%)
  adding: dvs/0184.png (stored 0%)
  adding: dvs/0178.png (stored 0%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (stored 0%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (stored 0%)
  adding: dvs/0126.png (stored 0%)
  adding: dvs/0219.png (stored 0%)
  adding: dvs/0150.png (stored 0%)
  adding: dvs/0042.png (stored 0%)
  adding: dvs/0220.png (stored 0%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (stored 0%)
  adding: dvs/0075.png (stored 0%)
  adding: dvs/0036.png (deflated 3%)
  adding: dvs/0207.png (stored 0%)
  adding: dvs/0095.png (stored 0%)
  adding: dvs/0065.png (stored 0%)
  adding: dvs/0057.png (stored 0%)
  adding: dvs/0033.png (stored 0%)
  adding: dvs/0211.png (deflated 16%)
  adding: dvs/0182.png (stored 0%)
  adding: dvs/0091.png (stored 0%)
  adding: dvs/0067.png (stored 0%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0047.png (stored 0%)
  adding: dvs/0151.png (stored 0%)
  adding: dvs/0056.png (stored 0%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (stored 0%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0072.png (stored 0%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (deflated 1%)
  adding: dvs/0013.png (stored 0%)
  adding: dvs/0158.png (stored 0%)
  adding: dvs/0034.png (stored 0%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (stored 0%)
  adding: dvs/0175.png (stored 0%)
  adding: dvs/0167.png (stored 0%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0177.png (stored 0%)
  adding: dvs/0032.png (stored 0%)
  adding: dvs/0093.png (stored 0%)
  adding: dvs/0004.png (stored 0%)
  adding: dvs/0006.png (deflated 11%)
  adding: dvs/0159.png (stored 0%)
  adding: dvs/0188.png (stored 0%)
  adding: dvs/0030.png (stored 0%)
  adding: dvs/0130.png (stored 0%)
  adding: dvs/0132.png (stored 0%)
  adding: dvs/0009.png (stored 0%)
  adding: dvs/0205.png (stored 0%)
  adding: dvs/0215.png (stored 0%)
  adding: dvs/0162.png (stored 0%)
  adding: dvs/0209.png (stored 0%)
  adding: dvs/0017.png (stored 0%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (stored 0%)
  adding: dvs/0170.png (stored 0%)
  adding: dvs/0035.png (stored 0%)
  adding: dvs/0201.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (stored 0%)
  adding: dvs/0196.png (deflated 15%)
  adding: dvs/0147.png (stored 0%)
  adding: dvs/0183.png (stored 0%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0069.png (stored 0%)
  adding: dvs/0148.png (stored 0%)
  adding: dvs/0060.png (stored 0%)
  adding: dvs/0003.png (stored 0%)
  adding: dvs/0187.png (deflated 3%)
  adding: dvs/0029.png (deflated 7%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0001.png (deflated 52%)
  adding: dvs/0200.png (stored 0%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0135.png (stored 0%)
  adding: dvs/0080.png (stored 0%)
  adding: dvs/0094.png (stored 0%)
  adding: dvs/0212.png (stored 0%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0203.png (stored 0%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (stored 0%)
  adding: dvs/0024.png (stored 0%)
  adding: dvs/0061.png (stored 0%)
  adding: dvs/0039.png (stored 0%)
  adding: dvs/0101.png (stored 0%)
  adding: dvs/0152.png (stored 0%)
  adding: dvs/0097.png (stored 0%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (stored 0%)
  adding: dvs/0070.png (stored 0%)
  adding: dvs/0129.png (stored 0%)
  adding: dvs/0206.png (stored 0%)
  adding: dvs/0037.png (stored 0%)
  adding: dvs/0073.png (stored 0%)
  adding: dvs/0116.png (stored 0%)
  adding: dvs/0185.png (stored 0%)
  adding: dvs/0021.png (deflated 3%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0015.png (stored 0%)
  adding: dvs/0166.png (stored 0%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0121.png (stored 0%)
  adding: dvs/0027.png (stored 0%)
  adding: dvs/0040.png (stored 0%)
  adding: dvs/0074.png (stored 0%)
  adding: dvs/0149.png (stored 0%)
  adding: dvs/0096.png (stored 0%)
  adding: dvs/0068.png (stored 0%)
  adding: dvs/0181.png (deflated 6%)
  adding: dvs/0180.png (deflated 0%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (stored 0%)
  adding: dvs/0078.png (stored 0%)
  adding: dvs/0125.png (stored 0%)
  adding: dvs/0127.png (stored 0%)
  adding: dvs/0099.png (stored 0%)
  adding: dvs/0194.png (stored 0%)
  adding: dvs/0008.png (stored 0%)
  adding: dvs/0028.png (stored 0%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (stored 0%)
  adding: dvs/0103.png (stored 0%)
  adding: dvs/0092.png (stored 0%)
  adding: dvs/0012.png (stored 0%)
  adding: dvs/0133.png (stored 0%)
  adding: dvs/0165.png (stored 0%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (stored 0%)
  adding: dvs/0155.png (stored 0%)
  adding: dvs/0193.png (stored 0%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (deflated 56%)
  adding: dvs/0144.png (stored 0%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0202.png (deflated 7%)
  adding: dvs/0208.png (stored 0%)
  adding: dvs/0114.png (stored 0%)
  adding: dvs/0107.png (stored 0%)
  adding: dvs/0123.png (stored 0%)
  adding: dvs/0109.png (stored 0%)
  adding: dvs/0189.png (stored 0%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0058.png (stored 0%)
  adding: dvs/0153.png (stored 0%)
  adding: dvs/0217.png (deflated 27%)
  adding: dvs/0139.png (stored 0%)
  adding: dvs/0174.png (stored 0%)
  adding: dvs/0192.png (stored 0%)
  adding: dvs/0169.png (stored 0%)
  adding: dvs/0098.png (stored 0%)
  adding: dvs/0218.png (stored 0%)
  adding: dvs/0048.png (stored 0%)
  adding: dvs/0089.png (stored 0%)
  adding: dvs/0122.png (stored 0%)
  adding: dvs/0002.png (stored 0%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (deflated 1%)
  adding: dvs/0176.png (stored 0%)
  adding: dvs/0213.png (deflated 0%)
  adding: dvs/0136.png (stored 0%)
  adding: dvs/0214.png (stored 0%)
  adding: dvs/0005.png (stored 0%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (stored 0%)
  adding: dvs/0124.png (stored 0%)
  adding: dvs/0204.png (stored 0%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0173.png (stored 0%)
  adding: dvs/0186.png (stored 0%)
  adding: dvs/0131.png (stored 0%)
  adding: dvs/0210.png (deflated 76%)
  adding: dvs/0119.png (stored 0%)
  adding: dvs/0216.png (stored 0%)
  adding: dvs/0083.png (stored 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (deflated 33%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 19%)
  adding: aps/0140.png (deflated 18%)
  adding: aps/0104.png (deflated 16%)
  adding: aps/0160.png (deflated 18%)
  adding: aps/0105.png (deflated 23%)
  adding: aps/0199.png (deflated 18%)
  adding: aps/0134.png (deflated 16%)
  adding: aps/0077.png (deflated 18%)
  adding: aps/0011.png (deflated 18%)
  adding: aps/0026.png (deflated 18%)
  adding: aps/0154.png (deflated 18%)
  adding: aps/0128.png (deflated 29%)
  adding: aps/0171.png (deflated 19%)
  adding: aps/0108.png (deflated 18%)
  adding: aps/0145.png (deflated 20%)
  adding: aps/0120.png (deflated 23%)
  adding: aps/0163.png (deflated 17%)
  adding: aps/0084.png (deflated 22%)
  adding: aps/0066.png (deflated 19%)
  adding: aps/0010.png (deflated 18%)
  adding: aps/0191.png (deflated 18%)
  adding: aps/0007.png (deflated 35%)
  adding: aps/0071.png (deflated 17%)
  adding: aps/0053.png (deflated 32%)
  adding: aps/0161.png (deflated 18%)
  adding: aps/0062.png (deflated 19%)
  adding: aps/0082.png (deflated 34%)
  adding: aps/0197.png (deflated 18%)
  adding: aps/0143.png (deflated 29%)
  adding: aps/0184.png (deflated 17%)
  adding: aps/0178.png (deflated 17%)
  adding: aps/0054.png (deflated 22%)
  adding: aps/0022.png (deflated 34%)
  adding: aps/0045.png (deflated 26%)
  adding: aps/0086.png (deflated 17%)
  adding: aps/0117.png (deflated 17%)
  adding: aps/0052.png (deflated 32%)
  adding: aps/0126.png (deflated 19%)
  adding: aps/0219.png (deflated 20%)
  adding: aps/0150.png (deflated 24%)
  adding: aps/0042.png (deflated 17%)
  adding: aps/0220.png (deflated 18%)
  adding: aps/0112.png (deflated 34%)
  adding: aps/0168.png (deflated 18%)
  adding: aps/0075.png (deflated 24%)
  adding: aps/0036.png (deflated 18%)
  adding: aps/0207.png (deflated 17%)
  adding: aps/0095.png (deflated 18%)
  adding: aps/0065.png (deflated 18%)
  adding: aps/0057.png (deflated 17%)
  adding: aps/0033.png (deflated 18%)
  adding: aps/0211.png (deflated 19%)
  adding: aps/0182.png (deflated 18%)
  adding: aps/0091.png (deflated 19%)
  adding: aps/0067.png (deflated 34%)
  adding: aps/0081.png (deflated 18%)
  adding: aps/0047.png (deflated 19%)
  adding: aps/0151.png (deflated 20%)
  adding: aps/0056.png (deflated 17%)
  adding: aps/0142.png (deflated 33%)
  adding: aps/0044.png (deflated 16%)
  adding: aps/0020.png (deflated 19%)
  adding: aps/0106.png (deflated 20%)
  adding: aps/0072.png (deflated 17%)
  adding: aps/0113.png (deflated 31%)
  adding: aps/0043.png (deflated 17%)
  adding: aps/0157.png (deflated 33%)
  adding: aps/0013.png (deflated 17%)
  adding: aps/0158.png (deflated 30%)
  adding: aps/0034.png (deflated 19%)
  adding: aps/0138.png (deflated 18%)
  adding: aps/0100.png (deflated 18%)
  adding: aps/0175.png (deflated 20%)
  adding: aps/0167.png (deflated 19%)
  adding: aps/0041.png (deflated 17%)
  adding: aps/0177.png (deflated 17%)
  adding: aps/0032.png (deflated 19%)
  adding: aps/0093.png (deflated 19%)
  adding: aps/0004.png (deflated 18%)
  adding: aps/0006.png (deflated 20%)
  adding: aps/0159.png (deflated 19%)
  adding: aps/0188.png (deflated 31%)
  adding: aps/0030.png (deflated 24%)
  adding: aps/0130.png (deflated 20%)
  adding: aps/0132.png (deflated 18%)
  adding: aps/0009.png (deflated 20%)
  adding: aps/0205.png (deflated 18%)
  adding: aps/0215.png (deflated 18%)
  adding: aps/0162.png (deflated 18%)
  adding: aps/0209.png (deflated 16%)
  adding: aps/0017.png (deflated 19%)
  adding: aps/0051.png (deflated 18%)
  adding: aps/0190.png (deflated 19%)
  adding: aps/0170.png (deflated 19%)
  adding: aps/0035.png (deflated 19%)
  adding: aps/0201.png (deflated 18%)
  adding: aps/0018.png (deflated 18%)
  adding: aps/0156.png (deflated 18%)
  adding: aps/0196.png (deflated 20%)
  adding: aps/0147.png (deflated 17%)
  adding: aps/0183.png (deflated 18%)
  adding: aps/0198.png (deflated 18%)
  adding: aps/0069.png (deflated 22%)
  adding: aps/0148.png (deflated 17%)
  adding: aps/0060.png (deflated 24%)
  adding: aps/0003.png (deflated 19%)
  adding: aps/0187.png (deflated 35%)
  adding: aps/0029.png (deflated 16%)
  adding: aps/0115.png (deflated 21%)
  adding: aps/0141.png (deflated 18%)
  adding: aps/0001.png (deflated 22%)
  adding: aps/0200.png (deflated 19%)
  adding: aps/0046.png (deflated 19%)
  adding: aps/0135.png (deflated 22%)
  adding: aps/0080.png (deflated 18%)
  adding: aps/0094.png (deflated 18%)
  adding: aps/0212.png (deflated 18%)
  adding: aps/0090.png (deflated 24%)
  adding: aps/0203.png (deflated 31%)
  adding: aps/0049.png (deflated 18%)
  adding: aps/0164.png (deflated 17%)
  adding: aps/0024.png (deflated 21%)
  adding: aps/0061.png (deflated 20%)
  adding: aps/0039.png (deflated 21%)
  adding: aps/0101.png (deflated 17%)
  adding: aps/0152.png (deflated 18%)
  adding: aps/0097.png (deflated 34%)
  adding: aps/0059.png (deflated 16%)
  adding: aps/0038.png (deflated 31%)
  adding: aps/0070.png (deflated 19%)
  adding: aps/0129.png (deflated 21%)
  adding: aps/0206.png (deflated 18%)
  adding: aps/0037.png (deflated 34%)
  adding: aps/0073.png (deflated 17%)
  adding: aps/0116.png (deflated 17%)
  adding: aps/0185.png (deflated 18%)
  adding: aps/0021.png (deflated 19%)
  adding: aps/0137.png (deflated 18%)
  adding: aps/0015.png (deflated 24%)
  adding: aps/0166.png (deflated 21%)
  adding: aps/0146.png (deflated 17%)
  adding: aps/0121.png (deflated 21%)
  adding: aps/0027.png (deflated 17%)
  adding: aps/0040.png (deflated 19%)
  adding: aps/0074.png (deflated 17%)
  adding: aps/0149.png (deflated 16%)
  adding: aps/0096.png (deflated 18%)
  adding: aps/0068.png (deflated 32%)
  adding: aps/0181.png (deflated 19%)
  adding: aps/0180.png (deflated 24%)
  adding: aps/0076.png (deflated 19%)
  adding: aps/0079.png (deflated 19%)
  adding: aps/0078.png (deflated 19%)
  adding: aps/0125.png (deflated 19%)
  adding: aps/0127.png (deflated 33%)
  adding: aps/0099.png (deflated 20%)
  adding: aps/0194.png (deflated 17%)
  adding: aps/0008.png (deflated 32%)
  adding: aps/0028.png (deflated 17%)
  adding: aps/0050.png (deflated 18%)
  adding: aps/0088.png (deflated 17%)
  adding: aps/0118.png (deflated 17%)
  adding: aps/0103.png (deflated 17%)
  adding: aps/0092.png (deflated 19%)
  adding: aps/0012.png (deflated 17%)
  adding: aps/0133.png (deflated 17%)
  adding: aps/0165.png (deflated 25%)
  adding: aps/0031.png (deflated 20%)
  adding: aps/0064.png (deflated 18%)
  adding: aps/0155.png (deflated 17%)
  adding: aps/0193.png (deflated 16%)
  adding: aps/0055.png (deflated 18%)
  adding: aps/0195.png (deflated 27%)
  adding: aps/0144.png (deflated 21%)
  adding: aps/0110.png (deflated 19%)
  adding: aps/0016.png (deflated 19%)
  adding: aps/0202.png (deflated 33%)
  adding: aps/0208.png (deflated 17%)
  adding: aps/0114.png (deflated 21%)
  adding: aps/0107.png (deflated 19%)
  adding: aps/0123.png (deflated 19%)

'The chosen video file: /content/video/repeater_1:2hz.MOV'

FPS: 29.97104247104247
Frame count: 207
Duration: 6.91 sec
The Final v2e command:

'v2e -i /content/video/repeater_1:2hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/repeater_1:2hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/repeater_1:2hz.MOV
INFO:v2e:Input video frame rate 29.97104247104247Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/repeater_1:2hz.MOV has total 207 frames with total duration 6.87s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 207 frames 0 to 206
(From 0.0s to 6.866666666666666s, duration 6.866666666666666s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 206.0 frames with duration 6.87s and playback duration 6.87s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 206 from video input
INFO:v2e:Input video /content/video/repeater_1:2hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 207 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/207 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 207/207 [00:08<00:00, 23.67fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpprgmtv0k
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 26 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/26 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 16
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/26 [00:04<02:02,  4.89s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 9
slomo-interp:   8% 2/26 [00:07<01:32,  3.83s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 13
slomo-interp: 100% 26/26 [06:02<00:00, 13.95s/ batch of 8 fr]
write-orig-avi: 100% 207/207 [00:00<00:00, 639.58fr/s]
write-slomo-vid: 100% 10508/10508 [00:27<00:00, 383.34fr/s]
INFO:v2ecore.slomo:Wrote 10508 frames and returning 10508 frame times.
Average upsampling factor= 50.6
INFO:v2e:SloMo average upsampling factor=50.62; average DVS timestamp resolution=658.56us
INFO:v2e:*** Stage 3/3: emulating DVS events from 10508 frames
dvs:   0% 0/10508 [00:00<?, ?fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2 at t=0.0021s
dvs:   0% 3/10508 [00:00<05:54, 29.60fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:  20% 2139/10508 [00:49<01:54, 73.32fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,145 at t=1.9050s
WARNING:v2ecore.emulator:no signal events generated for frame #2,151 at t=1.9062s
dvs:  20% 2154/10508 [00:49<02:18, 60.52fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,159 at t=1.9077s
WARNING:v2ecore.emulator:no signal events generated for frame #2,162 at t=1.9082s
dvs:  21% 2164/10508 [00:49<02:02, 68.11fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,171 at t=1.9099s
dvs:  21% 2172/10508 [00:49<01:57, 70.71fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,173 at t=1.9103s
dvs:  21% 2180/10508 [00:49<01:55, 72.29fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,183 at t=1.9122s
WARNING:v2ecore.emulator:no signal events generated for frame #2,187 at t=1.9129s
WARNING:v2ecore.emulator:no signal events generated for frame #2,189 at t=1.9133s
dvs:  21% 2189/10508 [00:50<01:48, 76.62fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,196 at t=1.9146s
WARNING:v2ecore.emulator:no signal events generated for frame #2,197 at t=1.9148s
dvs:  21% 2198/10508 [00:50<01:47, 77.62fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,206 at t=1.9165s
dvs:  21% 2207/10508 [00:50<01:44, 79.15fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,214 at t=1.9180s
dvs:  21% 2216/10508 [00:50<01:43, 80.47fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,217 at t=1.9185s
WARNING:v2ecore.emulator:no signal events generated for frame #2,218 at t=1.9187s
WARNING:v2ecore.emulator:no signal events generated for frame #2,220 at t=1.9191s
dvs:  21% 2226/10508 [00:50<01:38, 83.97fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,229 at t=1.9208s
WARNING:v2ecore.emulator:no signal events generated for frame #2,232 at t=1.9213s
dvs:  21% 2235/10508 [00:50<01:41, 81.27fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,242 at t=1.9232s
dvs:  21% 2244/10508 [00:50<01:39, 82.81fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,246 at t=1.9240s
WARNING:v2ecore.emulator:no signal events generated for frame #2,247 at t=1.9242s
WARNING:v2ecore.emulator:no signal events generated for frame #2,253 at t=1.9253s
dvs:  21% 2253/10508 [00:50<01:38, 83.60fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,254 at t=1.9255s
WARNING:v2ecore.emulator:no signal events generated for frame #2,257 at t=1.9260s
WARNING:v2ecore.emulator:no signal events generated for frame #2,264 at t=1.9273s
dvs:  22% 2266/10508 [00:50<01:28, 92.92fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,267 at t=1.9279s
dvs:  22% 2276/10508 [00:51<01:30, 91.20fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,280 at t=1.9303s
dvs:  34% 3546/10508 [01:15<03:32, 32.72fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,554 at t=2.6682s
dvs:  34% 3554/10508 [01:15<02:58, 38.93fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,556 at t=2.6686s
WARNING:v2ecore.emulator:no signal events generated for frame #3,557 at t=2.6688s
WARNING:v2ecore.emulator:no signal events generated for frame #3,558 at t=2.6690s
WARNING:v2ecore.emulator:no signal events generated for frame #3,559 at t=2.6692s
WARNING:v2ecore.emulator:no signal events generated for frame #3,561 at t=2.6696s
WARNING:v2ecore.emulator:no signal events generated for frame #3,562 at t=2.6698s
WARNING:v2ecore.emulator:no signal events generated for frame #3,563 at t=2.6701s
WARNING:v2ecore.emulator:no signal events generated for frame #3,564 at t=2.6703s
WARNING:v2ecore.emulator:no signal events generated for frame #3,566 at t=2.6707s
WARNING:v2ecore.emulator:no signal events generated for frame #3,567 at t=2.6709s
WARNING:v2ecore.emulator:no signal events generated for frame #3,569 at t=2.6713s
WARNING:v2ecore.emulator:no signal events generated for frame #3,570 at t=2.6715s
WARNING:v2ecore.emulator:no signal events generated for frame #3,573 at t=2.6722s
WARNING:v2ecore.emulator:no signal events generated for frame #3,575 at t=2.6726s
WARNING:v2ecore.emulator:no signal events generated for frame #3,577 at t=2.6730s
WARNING:v2ecore.emulator:no signal events generated for frame #3,579 at t=2.6734s
WARNING:v2ecore.emulator:no signal events generated for frame #3,582 at t=2.6740s
dvs:  34% 3584/10508 [01:15<01:22, 83.49fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,586 at t=2.6749s
WARNING:v2ecore.emulator:no signal events generated for frame #3,587 at t=2.6751s
WARNING:v2ecore.emulator:no signal events generated for frame #3,590 at t=2.6757s
WARNING:v2ecore.emulator:no signal events generated for frame #3,592 at t=2.6761s
WARNING:v2ecore.emulator:no signal events generated for frame #3,593 at t=2.6764s
WARNING:v2ecore.emulator:no signal events generated for frame #3,594 at t=2.6766s
WARNING:v2ecore.emulator:no signal events generated for frame #3,595 at t=2.6768s
dvs:  34% 3596/10508 [01:15<01:42, 67.71fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,599 at t=2.6776s
WARNING:v2ecore.emulator:no signal events generated for frame #3,602 at t=2.6782s
WARNING:v2ecore.emulator:no signal events generated for frame #3,604 at t=2.6787s
WARNING:v2ecore.emulator:no signal events generated for frame #3,605 at t=2.6789s
dvs:  34% 3606/10508 [01:16<01:38, 70.33fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,607 at t=2.6793s
WARNING:v2ecore.emulator:no signal events generated for frame #3,609 at t=2.6797s
WARNING:v2ecore.emulator:no signal events generated for frame #3,611 at t=2.6801s
WARNING:v2ecore.emulator:no signal events generated for frame #3,615 at t=2.6810s
WARNING:v2ecore.emulator:no signal events generated for frame #3,617 at t=2.6814s
WARNING:v2ecore.emulator:no signal events generated for frame #3,618 at t=2.6816s
WARNING:v2ecore.emulator:no signal events generated for frame #3,626 at t=2.6833s
dvs:  35% 3626/10508 [01:16<01:18, 87.12fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,630 at t=2.6841s
WARNING:v2ecore.emulator:no signal events generated for frame #3,634 at t=2.6850s
dvs:  35% 3637/10508 [01:16<01:16, 89.49fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,638 at t=2.6858s
WARNING:v2ecore.emulator:no signal events generated for frame #3,642 at t=2.6866s
WARNING:v2ecore.emulator:no signal events generated for frame #3,646 at t=2.6875s
WARNING:v2ecore.emulator:no signal events generated for frame #3,647 at t=2.6877s
WARNING:v2ecore.emulator:no signal events generated for frame #3,648 at t=2.6879s
dvs:  35% 3648/10508 [01:16<01:14, 91.64fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,651 at t=2.6885s
WARNING:v2ecore.emulator:no signal events generated for frame #3,653 at t=2.6889s
WARNING:v2ecore.emulator:no signal events generated for frame #3,654 at t=2.6891s
dvs:  35% 3659/10508 [01:16<01:27, 78.64fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,661 at t=2.6906s
WARNING:v2ecore.emulator:no signal events generated for frame #3,663 at t=2.6910s
WARNING:v2ecore.emulator:no signal events generated for frame #3,666 at t=2.6917s
dvs:  35% 3668/10508 [01:16<01:26, 79.18fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,675 at t=2.6936s
dvs:  35% 3677/10508 [01:16<01:25, 80.05fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,679 at t=2.6944s
WARNING:v2ecore.emulator:no signal events generated for frame #3,684 at t=2.6954s
WARNING:v2ecore.emulator:no signal events generated for frame #3,686 at t=2.6959s
dvs:  35% 3686/10508 [01:16<01:23, 81.96fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,689 at t=2.6965s
WARNING:v2ecore.emulator:no signal events generated for frame #3,691 at t=2.6969s
dvs:  35% 3698/10508 [01:17<01:22, 82.97fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,702 at t=2.6992s
WARNING:v2ecore.emulator:no signal events generated for frame #3,705 at t=2.6998s
WARNING:v2ecore.emulator:no signal events generated for frame #3,713 at t=2.7015s
WARNING:v2ecore.emulator:no signal events generated for frame #3,714 at t=2.7017s
WARNING:v2ecore.emulator:no signal events generated for frame #3,720 at t=2.7030s
dvs:  35% 3722/10508 [01:17<01:03, 106.84fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,729 at t=2.7049s
dvs:  36% 3738/10508 [01:17<01:23, 80.99fr/s] WARNING:v2ecore.emulator:no signal events generated for frame #3,746 at t=2.7084s
dvs:  59% 6243/10508 [02:05<00:57, 74.70fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,244 at t=3.8376s
dvs:  64% 6770/10508 [02:15<00:51, 73.18fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,778 at t=3.9377s
dvs:  65% 6778/10508 [02:15<01:12, 51.78fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,779 at t=3.9379s
WARNING:v2ecore.emulator:no signal events generated for frame #6,780 at t=3.9381s
dvs:  65% 6810/10508 [02:16<01:07, 54.81fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,811 at t=3.9439s
WARNING:v2ecore.emulator:no signal events generated for frame #6,812 at t=3.9440s
dvs:  65% 6826/10508 [02:16<00:59, 62.15fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,831 at t=3.9476s
WARNING:v2ecore.emulator:no signal events generated for frame #6,832 at t=3.9478s
WARNING:v2ecore.emulator:no signal events generated for frame #6,833 at t=3.9480s
WARNING:v2ecore.emulator:no signal events generated for frame #6,834 at t=3.9482s
dvs: 100% 10508/10508 [03:33<00:00, 49.14fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 205 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 207 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 10508 frames
INFO:v2e:generated total 9.30M events (4.65M on, 4.65M off)
INFO:v2e:Avg event rate for N=89960 px and total time =6.867 s
	Total: 1.35MHz (676.98kHz on, 676.79kHz off)
	Per pixel:  15.05Hz (7.53Hz on, 7.52Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 414 frames in 614.61s (1.48s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 205 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 207 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 10508 frames
Total events: 9,295,899
  Written 5,000,000/9,295,899
  Written 9,295,899/9,295,899
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 207
Output folder: /content/v2e-output/aps
APS frames found: 207
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/207 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:06.90, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:06.90, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x56b3b7bb3840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x56b3b7bb8ec0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x56b3b7ce4980] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x56b3b7ce4980] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x56b3b7ce4980] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  207 fps= 56 q=-1.0 Lsize=    1759kB time=00:00:06.80 bitrate=2119.6kbits/s speed=1.83x
video:1756kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.173528%
[libx264 @ 0x56b3b7ce4980] frame I:7     Avg QP:24.89  size: 35118
[libx264 @ 0x56b3b7ce4980] frame P:78    Avg QP:27.85  size: 13573
[libx264 @ 0x56b3b7ce4980] frame B:122   Avg QP:29.78  size:  4044
[libx264 @ 0x56b3b7ce4980] consecutive B-frames: 19.8%  3.9%  2.9% 73.4%
[libx264 @ 0x56b3b7ce4980] mb I  I16..4:  2.1% 55.5% 42.3%
[libx264 @ 0x56b3b7ce4980] mb P  I16..4:  3.7% 24.3% 19.0%  P16..4: 20.1%  5.0%  4.3%  0.0%  0.0%    skip:23.6%
[libx264 @ 0x56b3b7ce4980] mb B  I16..4:  3.5%  1.6%  2.3%  B16..8: 29.6%  3.6%  1.4%  direct: 1.6%  skip:56.3%  L0:45.7% L1:51.3% BI: 2.9%
[libx264 @ 0x56b3b7ce4980] 8x8 transform intra:47.1% inter:53.0%
[libx264 @ 0x56b3b7ce4980] coded y,uvDC,uvAC intra: 62.3% 39.3% 37.3% inter: 15.2% 3.1% 1.5%
[libx264 @ 0x56b3b7ce4980] i16 v,h,dc,p: 48% 17% 31%  4%
[libx264 @ 0x56b3b7ce4980] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 47%  9% 33%  2%  1%  2%  1%  3%  2%
[libx264 @ 0x56b3b7ce4980] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 13% 33%  5%  4%  5%  4%  4%  3%
[libx264 @ 0x56b3b7ce4980] i8c dc,h,v,p: 80%  5% 12%  3%
[libx264 @ 0x56b3b7ce4980] Weighted P-Frames: Y:21.8% UV:14.1%
[libx264 @ 0x56b3b7ce4980] ref P L0: 63.9% 15.6% 14.8%  5.4%  0.2%
[libx264 @ 0x56b3b7ce4980] ref B L0: 79.0% 17.1%  3.9%
[libx264 @ 0x56b3b7ce4980] ref B L1: 91.1%  8.9%
[libx264 @ 0x56b3b7ce4980] kb/s:2084.48
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (stored 0%)
  adding: dvs/0140.png (deflated 15%)
  adding: dvs/0104.png (deflated 27%)
  adding: dvs/0160.png (deflated 10%)
  adding: dvs/0105.png (deflated 15%)
  adding: dvs/0199.png (deflated 0%)
  adding: dvs/0134.png (deflated 15%)
  adding: dvs/0077.png (deflated 10%)
  adding: dvs/0011.png (stored 0%)
  adding: dvs/0026.png (stored 0%)
  adding: dvs/0154.png (stored 0%)
  adding: dvs/0128.png (stored 0%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (deflated 7%)
  adding: dvs/0145.png (deflated 11%)
  adding: dvs/0120.png (stored 0%)
  adding: dvs/0163.png (deflated 10%)
  adding: dvs/0084.png (deflated 12%)
  adding: dvs/0066.png (stored 0%)
  adding: dvs/0010.png (stored 0%)
  adding: dvs/0191.png (deflated 2%)
  adding: dvs/0007.png (deflated 3%)
  adding: dvs/0071.png (deflated 10%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (deflated 4%)
  adding: dvs/0062.png (stored 0%)
  adding: dvs/0082.png (deflated 9%)
  adding: dvs/0197.png (deflated 0%)
  adding: dvs/0143.png (deflated 15%)
  adding: dvs/0184.png (stored 0%)
  adding: dvs/0178.png (deflated 4%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (stored 0%)
  adding: dvs/0086.png (deflated 4%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (stored 0%)
  adding: dvs/0126.png (stored 0%)
  adding: dvs/0150.png (deflated 1%)
  adding: dvs/0042.png (stored 0%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (deflated 1%)
  adding: dvs/0075.png (deflated 9%)
  adding: dvs/0036.png (stored 0%)
  adding: dvs/0207.png (stored 0%)
  adding: dvs/0095.png (stored 0%)
  adding: dvs/0065.png (stored 0%)
  adding: dvs/0057.png (stored 0%)
  adding: dvs/0033.png (stored 0%)
  adding: dvs/0182.png (stored 0%)
  adding: dvs/0091.png (stored 0%)
  adding: dvs/0067.png (deflated 0%)
  adding: dvs/0081.png (deflated 15%)
  adding: dvs/0047.png (stored 0%)
  adding: dvs/0151.png (stored 0%)
  adding: dvs/0056.png (stored 0%)
  adding: dvs/0142.png (deflated 17%)
  adding: dvs/0044.png (stored 0%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (deflated 9%)
  adding: dvs/0072.png (deflated 8%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (stored 0%)
  adding: dvs/0013.png (stored 0%)
  adding: dvs/0158.png (stored 0%)
  adding: dvs/0034.png (stored 0%)
  adding: dvs/0138.png (deflated 23%)
  adding: dvs/0100.png (deflated 9%)
  adding: dvs/0175.png (stored 0%)
  adding: dvs/0167.png (deflated 1%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0177.png (stored 0%)
  adding: dvs/0032.png (stored 0%)
  adding: dvs/0093.png (stored 0%)
  adding: dvs/0004.png (deflated 1%)
  adding: dvs/0006.png (deflated 0%)
  adding: dvs/0159.png (deflated 2%)
  adding: dvs/0188.png (deflated 5%)
  adding: dvs/0030.png (stored 0%)
  adding: dvs/0130.png (deflated 12%)
  adding: dvs/0132.png (deflated 8%)
  adding: dvs/0009.png (deflated 0%)
  adding: dvs/0205.png (stored 0%)
  adding: dvs/0162.png (deflated 8%)
  adding: dvs/0017.png (stored 0%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (stored 0%)
  adding: dvs/0170.png (stored 0%)
  adding: dvs/0035.png (stored 0%)
  adding: dvs/0201.png (deflated 7%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (stored 0%)
  adding: dvs/0196.png (deflated 1%)
  adding: dvs/0147.png (stored 0%)
  adding: dvs/0183.png (stored 0%)
  adding: dvs/0198.png (deflated 2%)
  adding: dvs/0069.png (deflated 1%)
  adding: dvs/0148.png (deflated 0%)
  adding: dvs/0060.png (stored 0%)
  adding: dvs/0003.png (deflated 0%)
  adding: dvs/0187.png (deflated 1%)
  adding: dvs/0029.png (deflated 23%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (deflated 21%)
  adding: dvs/0001.png (deflated 5%)
  adding: dvs/0200.png (deflated 4%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0135.png (deflated 10%)
  adding: dvs/0080.png (deflated 15%)
  adding: dvs/0094.png (stored 0%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0203.png (deflated 1%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (deflated 22%)
  adding: dvs/0024.png (stored 0%)
  adding: dvs/0061.png (stored 0%)
  adding: dvs/0039.png (stored 0%)
  adding: dvs/0101.png (deflated 8%)
  adding: dvs/0152.png (stored 0%)
  adding: dvs/0097.png (stored 0%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (stored 0%)
  adding: dvs/0070.png (deflated 6%)
  adding: dvs/0129.png (deflated 2%)
  adding: dvs/0206.png (stored 0%)
  adding: dvs/0037.png (stored 0%)
  adding: dvs/0073.png (deflated 10%)
  adding: dvs/0116.png (stored 0%)
  adding: dvs/0185.png (stored 0%)
  adding: dvs/0021.png (stored 0%)
  adding: dvs/0137.png (deflated 11%)
  adding: dvs/0015.png (stored 0%)
  adding: dvs/0166.png (deflated 3%)
  adding: dvs/0146.png (deflated 11%)
  adding: dvs/0121.png (stored 0%)
  adding: dvs/0027.png (deflated 6%)
  adding: dvs/0040.png (stored 0%)
  adding: dvs/0074.png (deflated 8%)
  adding: dvs/0149.png (deflated 2%)
  adding: dvs/0096.png (deflated 0%)
  adding: dvs/0068.png (stored 0%)
  adding: dvs/0181.png (stored 0%)
  adding: dvs/0180.png (stored 0%)
  adding: dvs/0076.png (deflated 13%)
  adding: dvs/0079.png (deflated 11%)
  adding: dvs/0078.png (deflated 9%)
  adding: dvs/0125.png (stored 0%)
  adding: dvs/0127.png (deflated 0%)
  adding: dvs/0099.png (deflated 2%)
  adding: dvs/0194.png (deflated 0%)
  adding: dvs/0008.png (deflated 0%)
  adding: dvs/0028.png (deflated 1%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (stored 0%)
  adding: dvs/0103.png (deflated 22%)
  adding: dvs/0092.png (stored 0%)
  adding: dvs/0012.png (deflated 0%)
  adding: dvs/0133.png (deflated 15%)
  adding: dvs/0165.png (deflated 10%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (stored 0%)
  adding: dvs/0155.png (stored 0%)
  adding: dvs/0193.png (deflated 1%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (deflated 1%)
  adding: dvs/0144.png (deflated 11%)
  adding: dvs/0110.png (deflated 1%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0202.png (deflated 8%)
  adding: dvs/0114.png (stored 0%)
  adding: dvs/0107.png (deflated 3%)
  adding: dvs/0123.png (stored 0%)
  adding: dvs/0109.png (deflated 2%)
  adding: dvs/0189.png (stored 0%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0085.png (deflated 10%)
  adding: dvs/0058.png (stored 0%)
  adding: dvs/0153.png (stored 0%)
  adding: dvs/0139.png (deflated 8%)
  adding: dvs/0174.png (stored 0%)
  adding: dvs/0192.png (deflated 2%)
  adding: dvs/0169.png (deflated 3%)
  adding: dvs/0098.png (stored 0%)
  adding: dvs/0048.png (stored 0%)
  adding: dvs/0089.png (stored 0%)
  adding: dvs/0122.png (stored 0%)
  adding: dvs/0002.png (deflated 0%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (stored 0%)
  adding: dvs/0176.png (stored 0%)
  adding: dvs/0136.png (deflated 8%)
  adding: dvs/0005.png (deflated 1%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (deflated 21%)
  adding: dvs/0124.png (stored 0%)
  adding: dvs/0204.png (stored 0%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0173.png (stored 0%)
  adding: dvs/0186.png (stored 0%)
  adding: dvs/0131.png (deflated 12%)
  adding: dvs/0119.png (stored 0%)
  adding: dvs/0083.png (deflated 4%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (stored 0%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 17%)
  adding: aps/0140.png (deflated 17%)
  adding: aps/0104.png (deflated 18%)
  adding: aps/0160.png (deflated 19%)
  adding: aps/0105.png (deflated 18%)
  adding: aps/0199.png (deflated 16%)
  adding: aps/0134.png (deflated 17%)
  adding: aps/0077.png (deflated 16%)
  adding: aps/0011.png (deflated 16%)
  adding: aps/0026.png (deflated 16%)
  adding: aps/0154.png (deflated 18%)
  adding: aps/0128.png (deflated 16%)
  adding: aps/0171.png (deflated 18%)
  adding: aps/0108.png (deflated 18%)
  adding: aps/0145.png (deflated 16%)
  adding: aps/0120.png (deflated 28%)
  adding: aps/0163.png (deflated 19%)
  adding: aps/0084.png (deflated 16%)
  adding: aps/0066.png (deflated 16%)
  adding: aps/0010.png (deflated 16%)
  adding: aps/0191.png (deflated 16%)
  adding: aps/0007.png (deflated 16%)
  adding: aps/0071.png (deflated 16%)
  adding: aps/0053.png (deflated 17%)
  adding: aps/0161.png (deflated 19%)
  adding: aps/0062.png (deflated 18%)
  adding: aps/0082.png (deflated 16%)
  adding: aps/0197.png (deflated 16%)
  adding: aps/0143.png (deflated 16%)
  adding: aps/0184.png (deflated 17%)
  adding: aps/0178.png (deflated 31%)
  adding: aps/0054.png (deflated 18%)
  adding: aps/0022.png (deflated 16%)
  adding: aps/0045.png (deflated 19%)
  adding: aps/0086.png (deflated 16%)
  adding: aps/0117.png (deflated 18%)
  adding: aps/0052.png (deflated 18%)
  adding: aps/0126.png (deflated 16%)
  adding: aps/0150.png (deflated 20%)
  adding: aps/0042.png (deflated 20%)
  adding: aps/0112.png (deflated 19%)
  adding: aps/0168.png (deflated 18%)
  adding: aps/0075.png (deflated 16%)
  adding: aps/0036.png (deflated 18%)
  adding: aps/0207.png (deflated 16%)
  adding: aps/0095.png (deflated 18%)
  adding: aps/0065.png (deflated 17%)
  adding: aps/0057.png (deflated 18%)
  adding: aps/0033.png (deflated 19%)
  adding: aps/0182.png (deflated 18%)
  adding: aps/0091.png (deflated 19%)
  adding: aps/0067.png (deflated 17%)
  adding: aps/0081.png (deflated 16%)
  adding: aps/0047.png (deflated 18%)
  adding: aps/0151.png (deflated 19%)
  adding: aps/0056.png (deflated 18%)
  adding: aps/0142.png (deflated 16%)
  adding: aps/0044.png (deflated 19%)
  adding: aps/0020.png (deflated 16%)
  adding: aps/0106.png (deflated 18%)
  adding: aps/0072.png (deflated 16%)
  adding: aps/0113.png (deflated 19%)
  adding: aps/0043.png (deflated 19%)
  adding: aps/0157.png (deflated 18%)
  adding: aps/0013.png (deflated 16%)
  adding: aps/0158.png (deflated 18%)
  adding: aps/0034.png (deflated 19%)
  adding: aps/0138.png (deflated 16%)
  adding: aps/0100.png (deflated 19%)
  adding: aps/0175.png (deflated 18%)
  adding: aps/0167.png (deflated 18%)
  adding: aps/0041.png (deflated 18%)
  adding: aps/0177.png (deflated 18%)
  adding: aps/0032.png (deflated 19%)
  adding: aps/0093.png (deflated 19%)
  adding: aps/0004.png (deflated 17%)
  adding: aps/0006.png (deflated 17%)
  adding: aps/0159.png (deflated 18%)
  adding: aps/0188.png (deflated 16%)
  adding: aps/0030.png (deflated 25%)
  adding: aps/0130.png (deflated 16%)
  adding: aps/0132.png (deflated 17%)
  adding: aps/0009.png (deflated 16%)
  adding: aps/0205.png (deflated 16%)
  adding: aps/0162.png (deflated 19%)
  adding: aps/0017.png (deflated 16%)
  adding: aps/0051.png (deflated 17%)
  adding: aps/0190.png (deflated 16%)
  adding: aps/0170.png (deflated 18%)
  adding: aps/0035.png (deflated 18%)
  adding: aps/0201.png (deflated 16%)
  adding: aps/0018.png (deflated 16%)
  adding: aps/0156.png (deflated 18%)
  adding: aps/0196.png (deflated 17%)
  adding: aps/0147.png (deflated 16%)
  adding: aps/0183.png (deflated 17%)
  adding: aps/0198.png (deflated 17%)
  adding: aps/0069.png (deflated 17%)
  adding: aps/0148.png (deflated 28%)
  adding: aps/0060.png (deflated 22%)
  adding: aps/0003.png (deflated 17%)
  adding: aps/0187.png (deflated 16%)
  adding: aps/0029.png (deflated 24%)
  adding: aps/0115.png (deflated 18%)
  adding: aps/0141.png (deflated 16%)
  adding: aps/0001.png (deflated 20%)
  adding: aps/0200.png (deflated 17%)
  adding: aps/0046.png (deflated 18%)
  adding: aps/0135.png (deflated 16%)
  adding: aps/0080.png (deflated 16%)
  adding: aps/0094.png (deflated 19%)
  adding: aps/0090.png (deflated 22%)
  adding: aps/0203.png (deflated 17%)
  adding: aps/0049.png (deflated 19%)
  adding: aps/0164.png (deflated 18%)
  adding: aps/0024.png (deflated 16%)
  adding: aps/0061.png (deflated 20%)
  adding: aps/0039.png (deflated 18%)
  adding: aps/0101.png (deflated 19%)
  adding: aps/0152.png (deflated 18%)
  adding: aps/0097.png (deflated 18%)
  adding: aps/0059.png (deflated 30%)
  adding: aps/0038.png (deflated 18%)
  adding: aps/0070.png (deflated 16%)
  adding: aps/0129.png (deflated 16%)
  adding: aps/0206.png (deflated 16%)
  adding: aps/0037.png (deflated 18%)
  adding: aps/0073.png (deflated 16%)
  adding: aps/0116.png (deflated 18%)
  adding: aps/0185.png (deflated 16%)
  adding: aps/0021.png (deflated 16%)
  adding: aps/0137.png (deflated 16%)
  adding: aps/0015.png (deflated 16%)
  adding: aps/0166.png (deflated 18%)
  adding: aps/0146.png (deflated 16%)
  adding: aps/0121.png (deflated 19%)
  adding: aps/0027.png (deflated 16%)
  adding: aps/0040.png (deflated 18%)
  adding: aps/0074.png (deflated 16%)
  adding: aps/0149.png (deflated 20%)
  adding: aps/0096.png (deflated 18%)
  adding: aps/0068.png (deflated 16%)
  adding: aps/0181.png (deflated 20%)
  adding: aps/0180.png (deflated 22%)
  adding: aps/0076.png (deflated 16%)
  adding: aps/0079.png (deflated 16%)
  adding: aps/0078.png (deflated 16%)
  adding: aps/0125.png (deflated 17%)
  adding: aps/0127.png (deflated 16%)
  adding: aps/0099.png (deflated 18%)
  adding: aps/0194.png (deflated 16%)
  adding: aps/0008.png (deflated 16%)
  adding: aps/0028.png (deflated 19%)
  adding: aps/0050.png (deflated 17%)
  adding: aps/0088.png (deflated 22%)
  adding: aps/0118.png (deflated 36%)
  adding: aps/0103.png (deflated 18%)
  adding: aps/0092.png (deflated 18%)
  adding: aps/0012.png (deflated 16%)
  adding: aps/0133.png (deflated 17%)
  adding: aps/0165.png (deflated 18%)
  adding: aps/0031.png (deflated 20%)
  adding: aps/0064.png (deflated 16%)
  adding: aps/0155.png (deflated 18%)
  adding: aps/0193.png (deflated 16%)
  adding: aps/0055.png (deflated 18%)
  adding: aps/0195.png (deflated 16%)
  adding: aps/0144.png (deflated 16%)
  adding: aps/0110.png (deflated 18%)
  adding: aps/0016.png (deflated 16%)
  adding: aps/0202.png (deflated 17%)
  adding: aps/0114.png (deflated 18%)
  adding: aps/0107.png (deflated 18%)
  adding: aps/0123.png (deflated 18%)
  adding: aps/0109.png (deflated 17%)
  adding: aps/0189.png (deflated 16%)
  adding: aps/0025.png (deflated 17%)
  adding: aps/0085.png (deflated 16%)
  adding: aps/0058.png (deflated 35%)
  adding: aps/0153.png (deflated 19%)
  adding: aps/0139.png (deflated 16%)
  adding: aps/0174.png (deflated 18%)
  adding: aps/0192.png (deflated 16%)
  adding: aps/0169.png (deflated 17%)
  adding: aps/0098.png (deflated 18%)
  adding: aps/0048.png (deflated 18%)
  adding: aps/0089.png (deflated 20%)
  adding: aps/0122.png (deflated 19%)
  adding: aps/0002.png (deflated 19%)

'The chosen video file: /content/video/repeater_1hz.MOV'

FPS: 29.970760233918128
Frame count: 205
Duration: 6.84 sec
The Final v2e command:

'v2e -i /content/video/repeater_1hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/repeater_1hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/repeater_1hz.MOV
INFO:v2e:Input video frame rate 29.970760233918128Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/repeater_1hz.MOV has total 205 frames with total duration 6.80s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 205 frames 0 to 204
(From 0.0s to 6.8s, duration 6.8s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 204.0 frames with duration 6.80s and playback duration 6.80s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 204 from video input
INFO:v2e:Input video /content/video/repeater_1hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 205 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/205 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 205/205 [00:06<00:00, 34.06fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpa4nzk31k
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 26 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/26 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 45
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/26 [00:13<05:28, 13.14s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 183
slomo-interp:   8% 2/26 [01:04<14:20, 35.87s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 35
slomo-interp: 100% 26/26 [12:45<00:00, 29.46s/ batch of 8 fr]
write-orig-avi: 100% 205/205 [00:00<00:00, 857.59fr/s]
write-slomo-vid: 100% 21808/21808 [00:54<00:00, 402.78fr/s]
INFO:v2ecore.slomo:Wrote 21808 frames and returning 21808 frame times.
Average upsampling factor=105.0
INFO:v2e:SloMo average upsampling factor=104.96; average DVS timestamp resolution=317.58us
INFO:v2e:*** Stage 3/3: emulating DVS events from 21808 frames
dvs:   0% 0/21808 [00:00<?, ?fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2 at t=0.0007s
dvs:   0% 3/21808 [00:00<14:21, 25.31fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:   3% 723/21808 [00:13<04:40, 75.15fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #730 at t=0.3342s
dvs:  10% 2210/21808 [00:43<04:27, 73.23fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,213 at t=0.8207s
dvs:  10% 2284/21808 [00:44<04:01, 80.68fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,292 at t=0.8353s
dvs:  13% 2842/21808 [00:54<05:48, 54.44fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,851 at t=0.9389s
dvs:  13% 2851/21808 [00:54<05:05, 62.08fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,859 at t=0.9404s
dvs:  13% 2861/21808 [00:55<04:28, 70.54fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,862 at t=0.9410s
WARNING:v2ecore.emulator:no signal events generated for frame #2,863 at t=0.9411s
WARNING:v2ecore.emulator:no signal events generated for frame #2,870 at t=0.9424s
dvs:  13% 2871/21808 [00:55<04:04, 77.37fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,875 at t=0.9434s
dvs:  13% 2881/21808 [00:55<03:48, 82.66fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,886 at t=0.9454s
dvs:  13% 2890/21808 [00:55<04:25, 71.38fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,891 at t=0.9463s
WARNING:v2ecore.emulator:no signal events generated for frame #2,894 at t=0.9469s
WARNING:v2ecore.emulator:no signal events generated for frame #2,895 at t=0.9471s
dvs:  13% 2917/21808 [00:55<04:04, 77.37fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,919 at t=0.9515s
dvs:  13% 2926/21808 [00:55<03:54, 80.63fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,927 at t=0.9530s
dvs:  13% 2935/21808 [00:55<03:48, 82.56fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,944 at t=0.9562s
dvs:  13% 2944/21808 [00:56<03:47, 82.99fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2,946 at t=0.9565s
WARNING:v2ecore.emulator:no signal events generated for frame #2,949 at t=0.9571s
dvs:  25% 5362/21808 [01:42<04:59, 54.85fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,368 at t=1.9055s
WARNING:v2ecore.emulator:no signal events generated for frame #5,372 at t=1.9062s
dvs:  25% 5372/21808 [01:42<04:13, 64.82fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,373 at t=1.9064s
WARNING:v2ecore.emulator:no signal events generated for frame #5,374 at t=1.9066s
dvs:  25% 5380/21808 [01:42<04:02, 67.82fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,384 at t=1.9085s
WARNING:v2ecore.emulator:no signal events generated for frame #5,385 at t=1.9087s
WARNING:v2ecore.emulator:no signal events generated for frame #5,388 at t=1.9092s
WARNING:v2ecore.emulator:no signal events generated for frame #5,390 at t=1.9096s
WARNING:v2ecore.emulator:no signal events generated for frame #5,391 at t=1.9098s
WARNING:v2ecore.emulator:no signal events generated for frame #5,392 at t=1.9100s
WARNING:v2ecore.emulator:no signal events generated for frame #5,393 at t=1.9102s
WARNING:v2ecore.emulator:no signal events generated for frame #5,397 at t=1.9109s
WARNING:v2ecore.emulator:no signal events generated for frame #5,398 at t=1.9111s
WARNING:v2ecore.emulator:no signal events generated for frame #5,399 at t=1.9113s
WARNING:v2ecore.emulator:no signal events generated for frame #5,401 at t=1.9117s
WARNING:v2ecore.emulator:no signal events generated for frame #5,402 at t=1.9119s
WARNING:v2ecore.emulator:no signal events generated for frame #5,410 at t=1.9134s
dvs:  25% 5410/21808 [01:42<02:29, 109.96fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,414 at t=1.9141s
WARNING:v2ecore.emulator:no signal events generated for frame #5,415 at t=1.9143s
WARNING:v2ecore.emulator:no signal events generated for frame #5,416 at t=1.9145s
WARNING:v2ecore.emulator:no signal events generated for frame #5,417 at t=1.9147s
WARNING:v2ecore.emulator:no signal events generated for frame #5,421 at t=1.9154s
WARNING:v2ecore.emulator:no signal events generated for frame #5,424 at t=1.9160s
dvs:  25% 5426/21808 [01:42<02:23, 113.94fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,427 at t=1.9165s
WARNING:v2ecore.emulator:no signal events generated for frame #5,428 at t=1.9167s
WARNING:v2ecore.emulator:no signal events generated for frame #5,430 at t=1.9171s
WARNING:v2ecore.emulator:no signal events generated for frame #5,432 at t=1.9175s
WARNING:v2ecore.emulator:no signal events generated for frame #5,433 at t=1.9177s
WARNING:v2ecore.emulator:no signal events generated for frame #5,436 at t=1.9182s
WARNING:v2ecore.emulator:no signal events generated for frame #5,437 at t=1.9184s
WARNING:v2ecore.emulator:no signal events generated for frame #5,439 at t=1.9188s
WARNING:v2ecore.emulator:no signal events generated for frame #5,440 at t=1.9190s
dvs:  25% 5442/21808 [01:42<02:15, 120.85fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,443 at t=1.9195s
WARNING:v2ecore.emulator:no signal events generated for frame #5,446 at t=1.9201s
WARNING:v2ecore.emulator:no signal events generated for frame #5,449 at t=1.9207s
WARNING:v2ecore.emulator:no signal events generated for frame #5,451 at t=1.9210s
WARNING:v2ecore.emulator:no signal events generated for frame #5,455 at t=1.9218s
WARNING:v2ecore.emulator:no signal events generated for frame #5,457 at t=1.9222s
WARNING:v2ecore.emulator:no signal events generated for frame #5,458 at t=1.9224s
WARNING:v2ecore.emulator:no signal events generated for frame #5,459 at t=1.9225s
WARNING:v2ecore.emulator:no signal events generated for frame #5,460 at t=1.9227s
WARNING:v2ecore.emulator:no signal events generated for frame #5,461 at t=1.9229s
WARNING:v2ecore.emulator:no signal events generated for frame #5,463 at t=1.9233s
WARNING:v2ecore.emulator:no signal events generated for frame #5,464 at t=1.9235s
dvs:  25% 5466/21808 [01:43<02:01, 134.40fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,467 at t=1.9240s
WARNING:v2ecore.emulator:no signal events generated for frame #5,469 at t=1.9244s
WARNING:v2ecore.emulator:no signal events generated for frame #5,476 at t=1.9257s
WARNING:v2ecore.emulator:no signal events generated for frame #5,478 at t=1.9261s
dvs:  25% 5480/21808 [01:43<02:07, 127.58fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,486 at t=1.9276s
WARNING:v2ecore.emulator:no signal events generated for frame #5,489 at t=1.9282s
WARNING:v2ecore.emulator:no signal events generated for frame #5,491 at t=1.9285s
WARNING:v2ecore.emulator:no signal events generated for frame #5,492 at t=1.9287s
dvs:  25% 5506/21808 [01:43<02:41, 100.88fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,512 at t=1.9325s
WARNING:v2ecore.emulator:no signal events generated for frame #5,517 at t=1.9334s
dvs:  31% 6746/21808 [02:04<06:46, 37.03fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,752 at t=2.1700s
dvs:  34% 7346/21808 [02:13<03:22, 71.52fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #7,354 at t=2.3021s
dvs:  41% 8978/21808 [02:46<05:53, 36.29fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #8,985 at t=2.7702s
dvs:  42% 9154/21808 [02:49<04:07, 51.15fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,160 at t=2.8028s
dvs:  42% 9189/21808 [02:49<02:52, 72.99fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,196 at t=2.8096s
dvs:  42% 9216/21808 [02:50<02:37, 79.86fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,225 at t=2.8150s
dvs:  42% 9234/21808 [02:50<02:34, 81.52fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,243 at t=2.8183s
dvs:  43% 9270/21808 [02:50<02:31, 82.87fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,273 at t=2.8239s
dvs:  43% 9282/21808 [02:50<02:21, 88.69fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,289 at t=2.8269s
dvs:  43% 9328/21808 [02:51<02:14, 93.02fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,337 at t=2.8358s
dvs:  43% 9338/21808 [02:51<02:18, 90.27fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,341 at t=2.8366s
WARNING:v2ecore.emulator:no signal events generated for frame #9,343 at t=2.8370s
WARNING:v2ecore.emulator:no signal events generated for frame #9,344 at t=2.8371s
dvs:  43% 9348/21808 [02:51<03:17, 63.06fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,350 at t=2.8383s
dvs:  43% 9357/21808 [02:51<03:02, 68.30fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,364 at t=2.8409s
dvs:  43% 9390/21808 [02:52<02:45, 75.21fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,394 at t=2.8465s
dvs:  43% 9408/21808 [02:52<02:31, 81.98fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,412 at t=2.8498s
dvs:  43% 9417/21808 [02:52<02:29, 82.92fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,423 at t=2.8519s
dvs:  45% 9882/21808 [03:01<05:18, 37.41fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,889 at t=2.9418s
WARNING:v2ecore.emulator:no signal events generated for frame #9,897 at t=2.9448s
WARNING:v2ecore.emulator:no signal events generated for frame #9,905 at t=2.9479s
dvs:  45% 9915/21808 [03:01<02:59, 66.11fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,924 at t=2.9551s
dvs:  46% 9933/21808 [03:01<03:05, 63.87fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,941 at t=2.9615s
dvs:  58% 12669/21808 [03:50<02:39, 57.47fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,672 at t=3.8033s
dvs:  61% 13218/21808 [03:59<03:44, 38.34fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #13,224 at t=3.9062s
WARNING:v2ecore.emulator:no signal events generated for frame #13,225 at t=3.9064s
WARNING:v2ecore.emulator:no signal events generated for frame #13,228 at t=3.9069s
dvs: 100% 21808/21808 [06:29<00:00, 55.94fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 203 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 205 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 21808 frames
INFO:v2e:generated total 22.22M events (11.02M on, 11.20M off)
INFO:v2e:Avg event rate for N=89960 px and total time =6.800 s
	Total: 3.27MHz (1.62MHz on, 1.65MHz off)
	Per pixel:  36.32Hz (18.01Hz on, 18.31Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 410 frames in 1.22ks (2.97s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 203 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 205 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 21808 frames
Total events: 22,217,474
  Written 5,000,000/22,217,474
  Written 10,000,000/22,217,474
  Written 15,000,000/22,217,474
  Written 20,000,000/22,217,474
  Written 22,217,474/22,217,474
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 205
Output folder: /content/v2e-output/aps
APS frames found: 205
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/205 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:06.83, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:06.83, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x57d706717840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x57d706720980] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x57d706740300] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x57d706740300] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x57d706740300] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  205 fps= 36 q=-1.0 Lsize=    3307kB time=00:00:06.73 bitrate=4023.7kbits/s speed=1.19x
video:3305kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.082893%
[libx264 @ 0x57d706740300] frame I:21    Avg QP:26.18  size: 39003
[libx264 @ 0x57d706740300] frame P:94    Avg QP:29.12  size: 19709
[libx264 @ 0x57d706740300] frame B:90    Avg QP:30.17  size:  7905
[libx264 @ 0x57d706740300] consecutive B-frames: 38.5%  3.9% 14.6% 42.9%
[libx264 @ 0x57d706740300] mb I  I16..4:  1.9% 54.3% 43.8%
[libx264 @ 0x57d706740300] mb P  I16..4:  6.7% 29.7% 27.2%  P16..4: 15.0%  2.7%  1.9%  0.0%  0.0%    skip:16.8%
[libx264 @ 0x57d706740300] mb B  I16..4:  7.1%  2.5%  6.1%  B16..8: 26.3%  4.1%  2.1%  direct: 3.4%  skip:48.5%  L0:39.0% L1:58.2% BI: 2.8%
[libx264 @ 0x57d706740300] 8x8 transform intra:43.8% inter:51.7%
[libx264 @ 0x57d706740300] coded y,uvDC,uvAC intra: 67.8% 45.5% 43.4% inter: 19.0% 5.1% 2.2%
[libx264 @ 0x57d706740300] i16 v,h,dc,p: 42% 15% 39%  4%
[libx264 @ 0x57d706740300] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 50%  9% 28%  2%  1%  3%  1%  3%  2%
[libx264 @ 0x57d706740300] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 12% 31%  6%  5%  5%  5%  5%  4%
[libx264 @ 0x57d706740300] i8c dc,h,v,p: 78%  6% 12%  4%
[libx264 @ 0x57d706740300] Weighted P-Frames: Y:23.4% UV:19.1%
[libx264 @ 0x57d706740300] ref P L0: 68.6% 14.2% 11.5%  5.1%  0.6%
[libx264 @ 0x57d706740300] ref B L0: 78.4% 17.9%  3.7%
[libx264 @ 0x57d706740300] ref B L1: 89.4% 10.6%
[libx264 @ 0x57d706740300] kb/s:3960.81
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (stored 0%)
  adding: dvs/0140.png (stored 0%)
  adding: dvs/0104.png (deflated 1%)
  adding: dvs/0160.png (deflated 6%)
  adding: dvs/0105.png (stored 0%)
  adding: dvs/0199.png (stored 0%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0077.png (stored 0%)
  adding: dvs/0011.png (deflated 0%)
  adding: dvs/0026.png (stored 0%)
  adding: dvs/0154.png (stored 0%)
  adding: dvs/0128.png (deflated 4%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0120.png (stored 0%)
  adding: dvs/0163.png (deflated 50%)
  adding: dvs/0084.png (stored 0%)
  adding: dvs/0066.png (stored 0%)
  adding: dvs/0010.png (deflated 0%)
  adding: dvs/0191.png (deflated 11%)
  adding: dvs/0007.png (stored 0%)
  adding: dvs/0071.png (deflated 2%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (stored 0%)
  adding: dvs/0062.png (stored 0%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0197.png (stored 0%)
  adding: dvs/0143.png (stored 0%)
  adding: dvs/0184.png (stored 0%)
  adding: dvs/0178.png (deflated 8%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (stored 0%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (stored 0%)
  adding: dvs/0126.png (deflated 0%)
  adding: dvs/0150.png (stored 0%)
  adding: dvs/0042.png (stored 0%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (stored 0%)
  adding: dvs/0075.png (stored 0%)
  adding: dvs/0036.png (deflated 1%)
  adding: dvs/0095.png (stored 0%)
  adding: dvs/0065.png (stored 0%)
  adding: dvs/0057.png (stored 0%)
  adding: dvs/0033.png (stored 0%)
  adding: dvs/0182.png (stored 0%)
  adding: dvs/0091.png (stored 0%)
  adding: dvs/0067.png (stored 0%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0047.png (stored 0%)
  adding: dvs/0151.png (stored 0%)
  adding: dvs/0056.png (stored 0%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (stored 0%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0072.png (stored 0%)
  adding: dvs/0113.png (deflated 1%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (deflated 1%)
  adding: dvs/0013.png (deflated 4%)
  adding: dvs/0158.png (deflated 2%)
  adding: dvs/0034.png (stored 0%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (deflated 11%)
  adding: dvs/0175.png (deflated 4%)
  adding: dvs/0167.png (stored 0%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0177.png (stored 0%)
  adding: dvs/0032.png (stored 0%)
  adding: dvs/0093.png (stored 0%)
  adding: dvs/0004.png (stored 0%)
  adding: dvs/0006.png (stored 0%)
  adding: dvs/0159.png (deflated 7%)
  adding: dvs/0188.png (deflated 0%)
  adding: dvs/0030.png (stored 0%)
  adding: dvs/0130.png (deflated 8%)
  adding: dvs/0132.png (stored 0%)
  adding: dvs/0009.png (deflated 1%)
  adding: dvs/0205.png (stored 0%)
  adding: dvs/0162.png (stored 0%)
  adding: dvs/0017.png (stored 0%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (deflated 5%)
  adding: dvs/0170.png (stored 0%)
  adding: dvs/0035.png (stored 0%)
  adding: dvs/0201.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (stored 0%)
  adding: dvs/0196.png (stored 0%)
  adding: dvs/0147.png (stored 0%)
  adding: dvs/0183.png (stored 0%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0069.png (deflated 3%)
  adding: dvs/0148.png (deflated 0%)
  adding: dvs/0060.png (stored 0%)
  adding: dvs/0003.png (stored 0%)
  adding: dvs/0187.png (stored 0%)
  adding: dvs/0029.png (stored 0%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0001.png (stored 0%)
  adding: dvs/0200.png (stored 0%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0135.png (stored 0%)
  adding: dvs/0080.png (stored 0%)
  adding: dvs/0094.png (stored 0%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0203.png (stored 0%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (deflated 3%)
  adding: dvs/0024.png (stored 0%)
  adding: dvs/0061.png (stored 0%)
  adding: dvs/0039.png (deflated 1%)
  adding: dvs/0101.png (deflated 10%)
  adding: dvs/0152.png (stored 0%)
  adding: dvs/0097.png (deflated 4%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (stored 0%)
  adding: dvs/0070.png (deflated 4%)
  adding: dvs/0129.png (deflated 3%)
  adding: dvs/0037.png (deflated 1%)
  adding: dvs/0073.png (stored 0%)
  adding: dvs/0116.png (stored 0%)
  adding: dvs/0185.png (stored 0%)
  adding: dvs/0021.png (stored 0%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0015.png (stored 0%)
  adding: dvs/0166.png (stored 0%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0121.png (stored 0%)
  adding: dvs/0027.png (stored 0%)
  adding: dvs/0040.png (deflated 2%)
  adding: dvs/0074.png (deflated 0%)
  adding: dvs/0149.png (stored 0%)
  adding: dvs/0096.png (stored 0%)
  adding: dvs/0068.png (deflated 2%)
  adding: dvs/0181.png (stored 0%)
  adding: dvs/0180.png (stored 0%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (stored 0%)
  adding: dvs/0078.png (stored 0%)
  adding: dvs/0125.png (stored 0%)
  adding: dvs/0127.png (deflated 1%)
  adding: dvs/0099.png (deflated 8%)
  adding: dvs/0194.png (stored 0%)
  adding: dvs/0008.png (deflated 2%)
  adding: dvs/0028.png (stored 0%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (stored 0%)
  adding: dvs/0103.png (stored 0%)
  adding: dvs/0092.png (stored 0%)
  adding: dvs/0012.png (deflated 55%)
  adding: dvs/0133.png (stored 0%)
  adding: dvs/0165.png (deflated 6%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (stored 0%)
  adding: dvs/0155.png (stored 0%)
  adding: dvs/0193.png (deflated 12%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (deflated 1%)
  adding: dvs/0144.png (deflated 0%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0202.png (stored 0%)
  adding: dvs/0114.png (deflated 0%)
  adding: dvs/0107.png (stored 0%)
  adding: dvs/0123.png (stored 0%)
  adding: dvs/0109.png (stored 0%)
  adding: dvs/0189.png (deflated 0%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0058.png (stored 0%)
  adding: dvs/0153.png (stored 0%)
  adding: dvs/0139.png (stored 0%)
  adding: dvs/0174.png (deflated 1%)
  adding: dvs/0192.png (deflated 10%)
  adding: dvs/0169.png (stored 0%)
  adding: dvs/0098.png (deflated 3%)
  adding: dvs/0048.png (stored 0%)
  adding: dvs/0089.png (stored 0%)
  adding: dvs/0122.png (stored 0%)
  adding: dvs/0002.png (stored 0%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (stored 0%)
  adding: dvs/0176.png (deflated 4%)
  adding: dvs/0136.png (stored 0%)
  adding: dvs/0005.png (stored 0%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (stored 0%)
  adding: dvs/0124.png (stored 0%)
  adding: dvs/0204.png (stored 0%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0173.png (deflated 1%)
  adding: dvs/0186.png (stored 0%)
  adding: dvs/0131.png (deflated 5%)
  adding: dvs/0119.png (stored 0%)
  adding: dvs/0083.png (stored 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (stored 0%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 18%)
  adding: aps/0140.png (deflated 19%)
  adding: aps/0104.png (deflated 19%)
  adding: aps/0160.png (deflated 17%)
  adding: aps/0105.png (deflated 20%)
  adding: aps/0199.png (deflated 19%)
  adding: aps/0134.png (deflated 20%)
  adding: aps/0077.png (deflated 19%)
  adding: aps/0011.png (deflated 17%)
  adding: aps/0026.png (deflated 19%)
  adding: aps/0154.png (deflated 17%)
  adding: aps/0128.png (deflated 16%)
  adding: aps/0171.png (deflated 19%)
  adding: aps/0108.png (deflated 19%)
  adding: aps/0145.png (deflated 19%)
  adding: aps/0120.png (deflated 27%)
  adding: aps/0163.png (deflated 22%)
  adding: aps/0084.png (deflated 17%)
  adding: aps/0066.png (deflated 17%)
  adding: aps/0010.png (deflated 16%)
  adding: aps/0191.png (deflated 17%)
  adding: aps/0007.png (deflated 16%)
  adding: aps/0071.png (deflated 17%)
  adding: aps/0053.png (deflated 19%)
  adding: aps/0161.png (deflated 17%)
  adding: aps/0062.png (deflated 18%)
  adding: aps/0082.png (deflated 18%)
  adding: aps/0197.png (deflated 19%)
  adding: aps/0143.png (deflated 20%)
  adding: aps/0184.png (deflated 17%)
  adding: aps/0178.png (deflated 35%)
  adding: aps/0054.png (deflated 18%)
  adding: aps/0022.png (deflated 19%)
  adding: aps/0045.png (deflated 20%)
  adding: aps/0086.png (deflated 18%)
  adding: aps/0117.png (deflated 18%)
  adding: aps/0052.png (deflated 18%)
  adding: aps/0126.png (deflated 17%)
  adding: aps/0150.png (deflated 31%)
  adding: aps/0042.png (deflated 16%)
  adding: aps/0112.png (deflated 20%)
  adding: aps/0168.png (deflated 19%)
  adding: aps/0075.png (deflated 20%)
  adding: aps/0036.png (deflated 17%)
  adding: aps/0095.png (deflated 17%)
  adding: aps/0065.png (deflated 17%)
  adding: aps/0057.png (deflated 18%)
  adding: aps/0033.png (deflated 17%)
  adding: aps/0182.png (deflated 17%)
  adding: aps/0091.png (deflated 19%)
  adding: aps/0067.png (deflated 17%)
  adding: aps/0081.png (deflated 18%)
  adding: aps/0047.png (deflated 19%)
  adding: aps/0151.png (deflated 19%)
  adding: aps/0056.png (deflated 19%)
  adding: aps/0142.png (deflated 19%)
  adding: aps/0044.png (deflated 20%)
  adding: aps/0020.png (deflated 19%)
  adding: aps/0106.png (deflated 20%)
  adding: aps/0072.png (deflated 17%)
  adding: aps/0113.png (deflated 19%)
  adding: aps/0043.png (deflated 27%)
  adding: aps/0157.png (deflated 16%)
  adding: aps/0013.png (deflated 26%)
  adding: aps/0158.png (deflated 16%)
  adding: aps/0034.png (deflated 17%)
  adding: aps/0138.png (deflated 19%)
  adding: aps/0100.png (deflated 17%)
  adding: aps/0175.png (deflated 19%)
  adding: aps/0167.png (deflated 19%)
  adding: aps/0041.png (deflated 16%)
  adding: aps/0177.png (deflated 18%)
  adding: aps/0032.png (deflated 17%)
  adding: aps/0093.png (deflated 18%)
  adding: aps/0004.png (deflated 17%)
  adding: aps/0006.png (deflated 16%)
  adding: aps/0159.png (deflated 16%)
  adding: aps/0188.png (deflated 17%)
  adding: aps/0030.png (deflated 28%)
  adding: aps/0130.png (deflated 16%)
  adding: aps/0132.png (deflated 16%)
  adding: aps/0009.png (deflated 16%)
  adding: aps/0205.png (deflated 19%)
  adding: aps/0162.png (deflated 17%)
  adding: aps/0017.png (deflated 19%)
  adding: aps/0051.png (deflated 19%)
  adding: aps/0190.png (deflated 17%)
  adding: aps/0170.png (deflated 19%)
  adding: aps/0035.png (deflated 17%)
  adding: aps/0201.png (deflated 18%)
  adding: aps/0018.png (deflated 19%)
  adding: aps/0156.png (deflated 17%)
  adding: aps/0196.png (deflated 19%)
  adding: aps/0147.png (deflated 18%)
  adding: aps/0183.png (deflated 17%)
  adding: aps/0198.png (deflated 19%)
  adding: aps/0069.png (deflated 16%)
  adding: aps/0148.png (deflated 36%)
  adding: aps/0060.png (deflated 26%)
  adding: aps/0003.png (deflated 17%)
  adding: aps/0187.png (deflated 16%)
  adding: aps/0029.png (deflated 36%)
  adding: aps/0115.png (deflated 19%)
  adding: aps/0141.png (deflated 19%)
  adding: aps/0001.png (deflated 19%)
  adding: aps/0200.png (deflated 18%)
  adding: aps/0046.png (deflated 19%)
  adding: aps/0135.png (deflated 20%)
  adding: aps/0080.png (deflated 19%)
  adding: aps/0094.png (deflated 17%)
  adding: aps/0090.png (deflated 29%)
  adding: aps/0203.png (deflated 19%)
  adding: aps/0049.png (deflated 19%)
  adding: aps/0164.png (deflated 20%)
  adding: aps/0024.png (deflated 18%)
  adding: aps/0061.png (deflated 18%)
  adding: aps/0039.png (deflated 16%)
  adding: aps/0101.png (deflated 17%)
  adding: aps/0152.png (deflated 18%)
  adding: aps/0097.png (deflated 17%)
  adding: aps/0059.png (deflated 27%)
  adding: aps/0038.png (deflated 16%)
  adding: aps/0070.png (deflated 17%)
  adding: aps/0129.png (deflated 16%)
  adding: aps/0037.png (deflated 17%)
  adding: aps/0073.png (deflated 20%)
  adding: aps/0116.png (deflated 19%)
  adding: aps/0185.png (deflated 17%)
  adding: aps/0021.png (deflated 18%)
  adding: aps/0137.png (deflated 18%)
  adding: aps/0015.png (deflated 19%)
  adding: aps/0166.png (deflated 19%)
  adding: aps/0146.png (deflated 18%)
  adding: aps/0121.png (deflated 18%)
  adding: aps/0027.png (deflated 18%)
  adding: aps/0040.png (deflated 16%)
  adding: aps/0074.png (deflated 20%)
  adding: aps/0149.png (deflated 37%)
  adding: aps/0096.png (deflated 16%)
  adding: aps/0068.png (deflated 17%)
  adding: aps/0181.png (deflated 18%)
  adding: aps/0180.png (deflated 35%)
  adding: aps/0076.png (deflated 20%)
  adding: aps/0079.png (deflated 18%)
  adding: aps/0078.png (deflated 19%)
  adding: aps/0125.png (deflated 17%)
  adding: aps/0127.png (deflated 17%)
  adding: aps/0099.png (deflated 17%)
  adding: aps/0194.png (deflated 20%)
  adding: aps/0008.png (deflated 16%)
  adding: aps/0028.png (deflated 34%)
  adding: aps/0050.png (deflated 19%)
  adding: aps/0088.png (deflated 36%)
  adding: aps/0118.png (deflated 34%)
  adding: aps/0103.png (deflated 22%)
  adding: aps/0092.png (deflated 17%)
  adding: aps/0012.png (deflated 17%)
  adding: aps/0133.png (deflated 21%)
  adding: aps/0165.png (deflated 20%)
  adding: aps/0031.png (deflated 17%)
  adding: aps/0064.png (deflated 17%)
  adding: aps/0155.png (deflated 17%)
  adding: aps/0193.png (deflated 23%)
  adding: aps/0055.png (deflated 18%)
  adding: aps/0195.png (deflated 19%)
  adding: aps/0144.png (deflated 18%)
  adding: aps/0110.png (deflated 19%)
  adding: aps/0016.png (deflated 19%)
  adding: aps/0202.png (deflated 18%)
  adding: aps/0114.png (deflated 18%)
  adding: aps/0107.png (deflated 19%)
  adding: aps/0123.png (deflated 17%)
  adding: aps/0109.png (deflated 19%)
  adding: aps/0189.png (deflated 16%)
  adding: aps/0025.png (deflated 18%)
  adding: aps/0085.png (deflated 18%)
  adding: aps/0058.png (deflated 33%)
  adding: aps/0153.png (deflated 18%)
  adding: aps/0139.png (deflated 19%)
  adding: aps/0174.png (deflated 18%)
  adding: aps/0192.png (deflated 17%)
  adding: aps/0169.png (deflated 19%)
  adding: aps/0098.png (deflated 17%)
  adding: aps/0048.png (deflated 19%)
  adding: aps/0089.png (deflated 36%)
  adding: aps/0122.png (deflated 17%)
  adding: aps/0002.png (deflated 19%)
  adding: aps/0111.png (deflated 19%)
  adding: aps/0172.png (deflated 18%)
  adding: aps/0176.png (deflated 19%)
  adding: aps/0136.png (deflated 18%)
  adding: aps/0005.png (deflated 16%)
  adding: aps/0023.png (deflated 18%)
  adding: aps/0102.png (deflated 17%)

'The chosen video file: /content/video/repeater_2hz.MOV'

FPS: 29.97090203685742
Frame count: 206
Duration: 6.87 sec
The Final v2e command:

'v2e -i /content/video/repeater_2hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/repeater_2hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/repeater_2hz.MOV
INFO:v2e:Input video frame rate 29.97090203685742Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/repeater_2hz.MOV has total 206 frames with total duration 6.83s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 206 frames 0 to 205
(From 0.0s to 6.833333333333333s, duration 6.833333333333333s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 205.0 frames with duration 6.83s and playback duration 6.83s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 205 from video input
INFO:v2e:Input video /content/video/repeater_2hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 206 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/206 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 206/206 [00:06<00:00, 30.87fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpf9y3nv8p
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 26 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/26 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 180
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/26 [00:47<19:50, 47.61s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 178
slomo-interp:   8% 2/26 [01:37<19:29, 48.71s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 179
slomo-interp: 100% 26/26 [19:58<00:00, 46.10s/ batch of 8 fr]
write-orig-avi: 100% 206/206 [00:00<00:00, 620.86fr/s]
write-slomo-vid: 100% 35254/35254 [01:24<00:00, 419.39fr/s]
INFO:v2ecore.slomo:Wrote 35254 frames and returning 35254 frame times.
Average upsampling factor=170.4
INFO:v2e:SloMo average upsampling factor=170.38; average DVS timestamp resolution=195.64us
INFO:v2e:*** Stage 3/3: emulating DVS events from 35254 frames
dvs:   0% 0/35254 [00:00<?, ?fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2 at t=0.0002s
dvs:   0% 2/35254 [00:00<32:09, 18.27fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3 at t=0.0004s
WARNING:v2ecore.emulator:no signal events generated for frame #4 at t=0.0006s
WARNING:v2ecore.emulator:no signal events generated for frame #5 at t=0.0007s
WARNING:v2ecore.emulator:no signal events generated for frame #6 at t=0.0009s
WARNING:v2ecore.emulator:no signal events generated for frame #7 at t=0.0011s
WARNING:v2ecore.emulator:no signal events generated for frame #8 at t=0.0013s
WARNING:v2ecore.emulator:no signal events generated for frame #9 at t=0.0015s
WARNING:v2ecore.emulator:no signal events generated for frame #10 at t=0.0017s
WARNING:v2ecore.emulator:no signal events generated for frame #11 at t=0.0019s
dvs:   0% 12/35254 [00:00<09:34, 61.34fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:   0% 19/35254 [00:01<42:30, 13.81fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #25 at t=0.0044s
dvs:  62% 21882/35254 [06:05<03:00, 74.03fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #21,884 at t=4.1548s
dvs:  62% 21898/35254 [06:06<02:59, 74.39fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #21,902 at t=4.1582s
dvs:  69% 24466/35254 [06:52<03:23, 52.89fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #24,473 at t=4.6480s
dvs:  69% 24482/35254 [06:53<02:46, 64.70fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #24,487 at t=4.6507s
dvs:  77% 27059/35254 [07:39<02:04, 65.83fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #27,067 at t=5.1462s
dvs:  77% 27067/35254 [07:39<01:58, 69.13fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #27,070 at t=5.1468s
dvs: 100% 35254/35254 [10:03<00:00, 58.46fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 204 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 206 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 35254 frames
INFO:v2e:generated total 47.34M events (23.82M on, 23.52M off)
INFO:v2e:Avg event rate for N=89960 px and total time =6.833 s
	Total: 6.93MHz (3.49MHz on, 3.44MHz off)
	Per pixel:  77Hz (38.75Hz on, 38.26Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 412 frames in 1.89ks (4.60s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 204 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 206 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 35254 frames
Total events: 47,335,210
  Written 5,000,000/47,335,210
  Written 10,000,000/47,335,210
  Written 15,000,000/47,335,210
  Written 20,000,000/47,335,210
  Written 25,000,000/47,335,210
  Written 30,000,000/47,335,210
  Written 35,000,000/47,335,210
  Written 40,000,000/47,335,210
  Written 45,000,000/47,335,210
  Written 47,335,210/47,335,210
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 206
Output folder: /content/v2e-output/aps
APS frames found: 206
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/206 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:06.87, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:06.87, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x5cdb05405840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x5cdb0540e480] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x5cdb0584ec00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5cdb0584ec00] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5cdb0584ec00] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  206 fps= 27 q=-1.0 Lsize=    5145kB time=00:00:06.76 bitrate=6229.0kbits/s speed=0.877x
video:5143kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.042780%
[libx264 @ 0x5cdb0584ec00] frame I:26    Avg QP:26.84  size: 39670
[libx264 @ 0x5cdb0584ec00] frame P:150   Avg QP:29.50  size: 24496
[libx264 @ 0x5cdb0584ec00] frame B:30    Avg QP:31.22  size: 18665
[libx264 @ 0x5cdb0584ec00] consecutive B-frames: 76.7%  7.8% 11.7%  3.9%
[libx264 @ 0x5cdb0584ec00] mb I  I16..4:  2.5% 51.1% 46.4%
[libx264 @ 0x5cdb0584ec00] mb P  I16..4:  7.8% 39.3% 32.5%  P16..4: 10.8%  1.9%  1.1%  0.0%  0.0%    skip: 6.6%
[libx264 @ 0x5cdb0584ec00] mb B  I16..4: 12.1%  2.4% 16.9%  B16..8: 17.6%  5.8%  3.8%  direct: 6.6%  skip:34.8%  L0:42.8% L1:52.6% BI: 4.6%
[libx264 @ 0x5cdb0584ec00] 8x8 transform intra:47.1% inter:69.0%
[libx264 @ 0x5cdb0584ec00] coded y,uvDC,uvAC intra: 70.2% 45.8% 43.9% inter: 37.5% 6.5% 3.1%
[libx264 @ 0x5cdb0584ec00] i16 v,h,dc,p: 35% 11% 49%  5%
[libx264 @ 0x5cdb0584ec00] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 51% 10% 26%  2%  2%  3%  1%  3%  2%
[libx264 @ 0x5cdb0584ec00] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 12% 30%  6%  5%  6%  5%  5%  4%
[libx264 @ 0x5cdb0584ec00] i8c dc,h,v,p: 78%  5% 13%  4%
[libx264 @ 0x5cdb0584ec00] Weighted P-Frames: Y:25.3% UV:24.0%
[libx264 @ 0x5cdb0584ec00] ref P L0: 53.1% 28.8% 12.6%  4.9%  0.6%
[libx264 @ 0x5cdb0584ec00] ref B L0: 84.3% 12.4%  3.3%
[libx264 @ 0x5cdb0584ec00] ref B L1: 98.5%  1.5%
[libx264 @ 0x5cdb0584ec00] kb/s:6134.89
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (stored 0%)
  adding: dvs/0140.png (stored 0%)
  adding: dvs/0104.png (stored 0%)
  adding: dvs/0160.png (stored 0%)
  adding: dvs/0105.png (stored 0%)
  adding: dvs/0199.png (stored 0%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0077.png (stored 0%)
  adding: dvs/0011.png (stored 0%)
  adding: dvs/0026.png (stored 0%)
  adding: dvs/0154.png (stored 0%)
  adding: dvs/0128.png (stored 0%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0120.png (stored 0%)
  adding: dvs/0163.png (deflated 3%)
  adding: dvs/0084.png (stored 0%)
  adding: dvs/0066.png (stored 0%)
  adding: dvs/0010.png (stored 0%)
  adding: dvs/0191.png (stored 0%)
  adding: dvs/0007.png (stored 0%)
  adding: dvs/0071.png (stored 0%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (stored 0%)
  adding: dvs/0062.png (stored 0%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0197.png (stored 0%)
  adding: dvs/0143.png (stored 0%)
  adding: dvs/0184.png (stored 0%)
  adding: dvs/0178.png (deflated 34%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (stored 0%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (stored 0%)
  adding: dvs/0126.png (stored 0%)
  adding: dvs/0150.png (stored 0%)
  adding: dvs/0042.png (deflated 0%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (stored 0%)
  adding: dvs/0075.png (stored 0%)
  adding: dvs/0036.png (stored 0%)
  adding: dvs/0095.png (stored 0%)
  adding: dvs/0065.png (stored 0%)
  adding: dvs/0057.png (stored 0%)
  adding: dvs/0033.png (stored 0%)
  adding: dvs/0182.png (stored 0%)
  adding: dvs/0091.png (stored 0%)
  adding: dvs/0067.png (stored 0%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0047.png (stored 0%)
  adding: dvs/0151.png (stored 0%)
  adding: dvs/0056.png (stored 0%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (stored 0%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0072.png (stored 0%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (stored 0%)
  adding: dvs/0013.png (deflated 10%)
  adding: dvs/0158.png (stored 0%)
  adding: dvs/0034.png (deflated 3%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (stored 0%)
  adding: dvs/0175.png (stored 0%)
  adding: dvs/0167.png (stored 0%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0177.png (stored 0%)
  adding: dvs/0032.png (stored 0%)
  adding: dvs/0093.png (stored 0%)
  adding: dvs/0004.png (deflated 32%)
  adding: dvs/0006.png (stored 0%)
  adding: dvs/0159.png (stored 0%)
  adding: dvs/0188.png (stored 0%)
  adding: dvs/0030.png (stored 0%)
  adding: dvs/0130.png (stored 0%)
  adding: dvs/0132.png (stored 0%)
  adding: dvs/0009.png (stored 0%)
  adding: dvs/0205.png (stored 0%)
  adding: dvs/0162.png (stored 0%)
  adding: dvs/0017.png (stored 0%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (stored 0%)
  adding: dvs/0170.png (stored 0%)
  adding: dvs/0035.png (stored 0%)
  adding: dvs/0201.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (stored 0%)
  adding: dvs/0196.png (stored 0%)
  adding: dvs/0147.png (stored 0%)
  adding: dvs/0183.png (stored 0%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0069.png (stored 0%)
  adding: dvs/0148.png (stored 0%)
  adding: dvs/0060.png (stored 0%)
  adding: dvs/0003.png (stored 0%)
  adding: dvs/0187.png (stored 0%)
  adding: dvs/0029.png (deflated 41%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0001.png (deflated 2%)
  adding: dvs/0200.png (deflated 8%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0135.png (stored 0%)
  adding: dvs/0080.png (stored 0%)
  adding: dvs/0094.png (stored 0%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0203.png (stored 0%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (deflated 1%)
  adding: dvs/0024.png (stored 0%)
  adding: dvs/0061.png (stored 0%)
  adding: dvs/0039.png (stored 0%)
  adding: dvs/0101.png (stored 0%)
  adding: dvs/0152.png (stored 0%)
  adding: dvs/0097.png (stored 0%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (stored 0%)
  adding: dvs/0070.png (stored 0%)
  adding: dvs/0129.png (stored 0%)
  adding: dvs/0206.png (stored 0%)
  adding: dvs/0037.png (stored 0%)
  adding: dvs/0073.png (stored 0%)
  adding: dvs/0116.png (stored 0%)
  adding: dvs/0185.png (deflated 1%)
  adding: dvs/0021.png (stored 0%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0015.png (stored 0%)
  adding: dvs/0166.png (stored 0%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0121.png (stored 0%)
  adding: dvs/0027.png (deflated 28%)
  adding: dvs/0040.png (stored 0%)
  adding: dvs/0074.png (stored 0%)
  adding: dvs/0149.png (stored 0%)
  adding: dvs/0096.png (stored 0%)
  adding: dvs/0068.png (stored 0%)
  adding: dvs/0181.png (stored 0%)
  adding: dvs/0180.png (stored 0%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (stored 0%)
  adding: dvs/0078.png (stored 0%)
  adding: dvs/0125.png (stored 0%)
  adding: dvs/0127.png (stored 0%)
  adding: dvs/0099.png (stored 0%)
  adding: dvs/0194.png (deflated 20%)
  adding: dvs/0008.png (stored 0%)
  adding: dvs/0028.png (stored 0%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (stored 0%)
  adding: dvs/0103.png (stored 0%)
  adding: dvs/0092.png (stored 0%)
  adding: dvs/0012.png (deflated 71%)
  adding: dvs/0133.png (stored 0%)
  adding: dvs/0165.png (stored 0%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (stored 0%)
  adding: dvs/0155.png (stored 0%)
  adding: dvs/0193.png (deflated 71%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (stored 0%)
  adding: dvs/0144.png (stored 0%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0202.png (stored 0%)
  adding: dvs/0114.png (stored 0%)
  adding: dvs/0107.png (stored 0%)
  adding: dvs/0123.png (stored 0%)
  adding: dvs/0109.png (stored 0%)
  adding: dvs/0189.png (stored 0%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0058.png (stored 0%)
  adding: dvs/0153.png (stored 0%)
  adding: dvs/0139.png (stored 0%)
  adding: dvs/0174.png (stored 0%)
  adding: dvs/0192.png (stored 0%)
  adding: dvs/0169.png (stored 0%)
  adding: dvs/0098.png (stored 0%)
  adding: dvs/0048.png (stored 0%)
  adding: dvs/0089.png (stored 0%)
  adding: dvs/0122.png (stored 0%)
  adding: dvs/0002.png (stored 0%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (stored 0%)
  adding: dvs/0176.png (stored 0%)
  adding: dvs/0136.png (stored 0%)
  adding: dvs/0005.png (stored 0%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (stored 0%)
  adding: dvs/0124.png (stored 0%)
  adding: dvs/0204.png (stored 0%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (deflated 18%)
  adding: dvs/0173.png (stored 0%)
  adding: dvs/0186.png (stored 0%)
  adding: dvs/0131.png (stored 0%)
  adding: dvs/0119.png (stored 0%)
  adding: dvs/0083.png (stored 0%)
  adding: dvs/0019.png (deflated 12%)
  adding: dvs/0014.png (stored 0%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 19%)
  adding: aps/0140.png (deflated 30%)
  adding: aps/0104.png (deflated 20%)
  adding: aps/0160.png (deflated 17%)
  adding: aps/0105.png (deflated 19%)
  adding: aps/0199.png (deflated 19%)
  adding: aps/0134.png (deflated 20%)
  adding: aps/0077.png (deflated 18%)
  adding: aps/0011.png (deflated 16%)
  adding: aps/0026.png (deflated 17%)
  adding: aps/0154.png (deflated 19%)
  adding: aps/0128.png (deflated 19%)
  adding: aps/0171.png (deflated 30%)
  adding: aps/0108.png (deflated 19%)
  adding: aps/0145.png (deflated 18%)
  adding: aps/0120.png (deflated 20%)
  adding: aps/0163.png (deflated 25%)
  adding: aps/0084.png (deflated 18%)
  adding: aps/0066.png (deflated 33%)
  adding: aps/0010.png (deflated 17%)
  adding: aps/0191.png (deflated 17%)
  adding: aps/0007.png (deflated 17%)
  adding: aps/0071.png (deflated 16%)
  adding: aps/0053.png (deflated 19%)
  adding: aps/0161.png (deflated 16%)
  adding: aps/0062.png (deflated 19%)
  adding: aps/0082.png (deflated 21%)
  adding: aps/0197.png (deflated 19%)
  adding: aps/0143.png (deflated 19%)
  adding: aps/0184.png (deflated 19%)
  adding: aps/0178.png (deflated 27%)
  adding: aps/0054.png (deflated 17%)
  adding: aps/0022.png (deflated 21%)
  adding: aps/0045.png (deflated 20%)
  adding: aps/0086.png (deflated 17%)
  adding: aps/0117.png (deflated 17%)
  adding: aps/0052.png (deflated 22%)
  adding: aps/0126.png (deflated 27%)
  adding: aps/0150.png (deflated 19%)
  adding: aps/0042.png (deflated 17%)
  adding: aps/0112.png (deflated 22%)
  adding: aps/0168.png (deflated 19%)
  adding: aps/0075.png (deflated 18%)
  adding: aps/0036.png (deflated 34%)
  adding: aps/0095.png (deflated 36%)
  adding: aps/0065.png (deflated 37%)
  adding: aps/0057.png (deflated 17%)
  adding: aps/0033.png (deflated 19%)
  adding: aps/0182.png (deflated 19%)
  adding: aps/0091.png (deflated 19%)
  adding: aps/0067.png (deflated 20%)
  adding: aps/0081.png (deflated 35%)
  adding: aps/0047.png (deflated 19%)
  adding: aps/0151.png (deflated 19%)
  adding: aps/0056.png (deflated 17%)
  adding: aps/0142.png (deflated 22%)
  adding: aps/0044.png (deflated 21%)
  adding: aps/0020.png (deflated 37%)
  adding: aps/0106.png (deflated 19%)
  adding: aps/0072.png (deflated 16%)
  adding: aps/0113.png (deflated 19%)
  adding: aps/0043.png (deflated 26%)
  adding: aps/0157.png (deflated 21%)
  adding: aps/0013.png (deflated 27%)
  adding: aps/0158.png (deflated 18%)
  adding: aps/0034.png (deflated 19%)
  adding: aps/0138.png (deflated 18%)
  adding: aps/0100.png (deflated 18%)
  adding: aps/0175.png (deflated 17%)
  adding: aps/0167.png (deflated 19%)
  adding: aps/0041.png (deflated 17%)
  adding: aps/0177.png (deflated 16%)
  adding: aps/0032.png (deflated 18%)
  adding: aps/0093.png (deflated 18%)
  adding: aps/0004.png (deflated 19%)
  adding: aps/0006.png (deflated 18%)
  adding: aps/0159.png (deflated 17%)
  adding: aps/0188.png (deflated 18%)
  adding: aps/0030.png (deflated 20%)
  adding: aps/0130.png (deflated 17%)
  adding: aps/0132.png (deflated 16%)
  adding: aps/0009.png (deflated 18%)
  adding: aps/0205.png (deflated 18%)
  adding: aps/0162.png (deflated 17%)
  adding: aps/0017.png (deflated 19%)
  adding: aps/0051.png (deflated 33%)
  adding: aps/0190.png (deflated 18%)
  adding: aps/0170.png (deflated 33%)
  adding: aps/0035.png (deflated 36%)
  adding: aps/0201.png (deflated 32%)
  adding: aps/0018.png (deflated 19%)
  adding: aps/0156.png (deflated 31%)
  adding: aps/0196.png (deflated 19%)
  adding: aps/0147.png (deflated 16%)
  adding: aps/0183.png (deflated 18%)
  adding: aps/0198.png (deflated 19%)
  adding: aps/0069.png (deflated 18%)
  adding: aps/0148.png (deflated 25%)
  adding: aps/0060.png (deflated 19%)
  adding: aps/0003.png (deflated 19%)
  adding: aps/0187.png (deflated 20%)
  adding: aps/0029.png (deflated 23%)
  adding: aps/0115.png (deflated 17%)
  adding: aps/0141.png (deflated 29%)
  adding: aps/0001.png (deflated 20%)
  adding: aps/0200.png (deflated 31%)
  adding: aps/0046.png (deflated 19%)
  adding: aps/0135.png (deflated 19%)
  adding: aps/0080.png (deflated 37%)
  adding: aps/0094.png (deflated 18%)
  adding: aps/0090.png (deflated 19%)
  adding: aps/0203.png (deflated 18%)
  adding: aps/0049.png (deflated 19%)
  adding: aps/0164.png (deflated 20%)
  adding: aps/0024.png (deflated 18%)
  adding: aps/0061.png (deflated 20%)
  adding: aps/0039.png (deflated 18%)
  adding: aps/0101.png (deflated 17%)
  adding: aps/0152.png (deflated 19%)
  adding: aps/0097.png (deflated 21%)
  adding: aps/0059.png (deflated 20%)
  adding: aps/0038.png (deflated 19%)
  adding: aps/0070.png (deflated 17%)
  adding: aps/0129.png (deflated 18%)
  adding: aps/0206.png (deflated 16%)
  adding: aps/0037.png (deflated 21%)
  adding: aps/0073.png (deflated 26%)
  adding: aps/0116.png (deflated 17%)
  adding: aps/0185.png (deflated 32%)
  adding: aps/0021.png (deflated 36%)
  adding: aps/0137.png (deflated 18%)
  adding: aps/0015.png (deflated 18%)
  adding: aps/0166.png (deflated 20%)
  adding: aps/0146.png (deflated 17%)
  adding: aps/0121.png (deflated 19%)
  adding: aps/0027.png (deflated 17%)
  adding: aps/0040.png (deflated 18%)
  adding: aps/0074.png (deflated 20%)
  adding: aps/0149.png (deflated 20%)
  adding: aps/0096.png (deflated 34%)
  adding: aps/0068.png (deflated 19%)
  adding: aps/0181.png (deflated 19%)
  adding: aps/0180.png (deflated 19%)
  adding: aps/0076.png (deflated 19%)
  adding: aps/0079.png (deflated 19%)
  adding: aps/0078.png (deflated 19%)
  adding: aps/0125.png (deflated 31%)
  adding: aps/0127.png (deflated 21%)
  adding: aps/0099.png (deflated 17%)
  adding: aps/0194.png (deflated 22%)
  adding: aps/0008.png (deflated 18%)
  adding: aps/0028.png (deflated 28%)
  adding: aps/0050.png (deflated 38%)
  adding: aps/0088.png (deflated 25%)
  adding: aps/0118.png (deflated 25%)
  adding: aps/0103.png (deflated 25%)
  adding: aps/0092.png (deflated 18%)
  adding: aps/0012.png (deflated 16%)
  adding: aps/0133.png (deflated 24%)
  adding: aps/0165.png (deflated 20%)
  adding: aps/0031.png (deflated 18%)
  adding: aps/0064.png (deflated 19%)
  adding: aps/0155.png (deflated 32%)
  adding: aps/0193.png (deflated 25%)
  adding: aps/0055.png (deflated 18%)
  adding: aps/0195.png (deflated 19%)
  adding: aps/0144.png (deflated 18%)
  adding: aps/0110.png (deflated 32%)
  adding: aps/0016.png (deflated 19%)
  adding: aps/0202.png (deflated 21%)
  adding: aps/0114.png (deflated 17%)
  adding: aps/0107.png (deflated 19%)
  adding: aps/0123.png (deflated 19%)
  adding: aps/0109.png (deflated 19%)
  adding: aps/0189.png (deflated 17%)
  adding: aps/0025.png (deflated 17%)
  adding: aps/0085.png (deflated 17%)
  adding: aps/0058.png (deflated 26%)
  adding: aps/0153.png (deflated 19%)
  adding: aps/0139.png (deflated 19%)
  adding: aps/0174.png (deflated 18%)
  adding: aps/0192.png (deflated 16%)
  adding: aps/0169.png (deflated 19%)
  adding: aps/0098.png (deflated 19%)
  adding: aps/0048.png (deflated 19%)
  adding: aps/0089.png (deflated 19%)
  adding: aps/0122.png (deflated 19%)
  adding: aps/0002.png (deflated 19%)
  adding: aps/0111.png (deflated 26%)
  adding: aps/0172.png (deflated 22%)
  adding: aps/0176.png (deflated 17%)
  adding: aps/0136.png (deflated 19%)
  adding: aps/0005.png (deflated 25%)
  adding: aps/0023.png (deflated 18%)

'The chosen video file: /content/video/soap_1:2hz.MOV'

FPS: 29.97784888013783
Frame count: 203
Duration: 6.77 sec
The Final v2e command:

'v2e -i /content/video/soap_1:2hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/soap_1:2hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/soap_1:2hz.MOV
INFO:v2e:Input video frame rate 29.97784888013783Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/soap_1:2hz.MOV has total 203 frames with total duration 6.73s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 203 frames 0 to 202
(From 0.0s to 6.733333333333333s, duration 6.733333333333333s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 202.0 frames with duration 6.73s and playback duration 6.73s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 202 from video input
INFO:v2e:Input video /content/video/soap_1:2hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 203 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/203 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 203/203 [00:09<00:00, 21.32fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpezh6rsvp
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 26 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/26 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 11
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/26 [00:03<01:33,  3.75s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 158
slomo-interp:   8% 2/26 [00:46<10:40, 26.69s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 118
slomo-interp: 100% 26/26 [07:56<00:00, 18.35s/ batch of 8 fr]
write-orig-avi: 100% 203/203 [00:00<00:00, 928.33fr/s]
write-slomo-vid: 100% 13876/13876 [00:32<00:00, 422.63fr/s]
INFO:v2ecore.slomo:Wrote 13876 frames and returning 13876 frame times.
Average upsampling factor= 67.6
INFO:v2e:SloMo average upsampling factor=67.58; average DVS timestamp resolution=493.27us
INFO:v2e:*** Stage 3/3: emulating DVS events from 13876 frames
dvs:   0% 0/13876 [00:00<?, ?fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2 at t=0.0030s
dvs:   0% 2/13876 [00:00<11:59, 19.29fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:   1% 133/13876 [00:04<04:01, 57.01fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #137 at t=0.2768s
dvs:   1% 208/13876 [00:05<02:42, 84.29fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #217 at t=0.2937s
dvs:   2% 248/13876 [00:05<02:21, 96.43fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #250 at t=0.3007s
dvs:   2% 267/13876 [00:05<02:46, 81.91fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #275 at t=0.3060s
dvs:   3% 411/13876 [00:07<02:51, 78.51fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #415 at t=0.3355s
dvs:   3% 420/13876 [00:07<02:45, 81.17fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #428 at t=0.3382s
dvs:   3% 450/13876 [00:08<03:53, 57.38fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #453 at t=0.3435s
WARNING:v2ecore.emulator:no signal events generated for frame #454 at t=0.3437s
dvs:   3% 462/13876 [00:08<03:12, 69.63fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #468 at t=0.3467s
dvs:   3% 483/13876 [00:08<03:01, 73.97fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #490 at t=0.3513s
dvs:   4% 504/13876 [00:09<02:44, 81.40fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #509 at t=0.3553s
dvs:   4% 554/13876 [00:09<02:54, 76.14fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #564 at t=0.3669s
dvs:   4% 565/13876 [00:09<02:38, 83.75fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #570 at t=0.3682s
WARNING:v2ecore.emulator:no signal events generated for frame #572 at t=0.3686s
dvs:   4% 574/13876 [00:09<02:37, 84.65fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #580 at t=0.3703s
dvs:   4% 583/13876 [00:10<02:39, 83.44fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #584 at t=0.3712s
WARNING:v2ecore.emulator:no signal events generated for frame #591 at t=0.3726s
dvs:   4% 592/13876 [00:10<02:38, 83.82fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #595 at t=0.3735s
WARNING:v2ecore.emulator:no signal events generated for frame #598 at t=0.3741s
WARNING:v2ecore.emulator:no signal events generated for frame #601 at t=0.3747s
dvs:   4% 601/13876 [00:10<03:43, 59.52fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #607 at t=0.3760s
WARNING:v2ecore.emulator:no signal events generated for frame #609 at t=0.3764s
WARNING:v2ecore.emulator:no signal events generated for frame #611 at t=0.3769s
WARNING:v2ecore.emulator:no signal events generated for frame #613 at t=0.3773s
WARNING:v2ecore.emulator:no signal events generated for frame #614 at t=0.3775s
WARNING:v2ecore.emulator:no signal events generated for frame #615 at t=0.3777s
WARNING:v2ecore.emulator:no signal events generated for frame #618 at t=0.3783s
dvs:   4% 618/13876 [00:10<02:47, 79.07fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #619 at t=0.3785s
dvs:   5% 628/13876 [00:10<02:39, 83.24fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #638 at t=0.3826s
dvs:   5% 638/13876 [00:10<02:36, 84.72fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #639 at t=0.3828s
WARNING:v2ecore.emulator:no signal events generated for frame #642 at t=0.3834s
dvs:   5% 658/13876 [00:11<04:09, 52.95fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #663 at t=0.3878s
dvs:   5% 669/13876 [00:11<03:29, 62.93fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #677 at t=0.3908s
WARNING:v2ecore.emulator:no signal events generated for frame #678 at t=0.3910s
WARNING:v2ecore.emulator:no signal events generated for frame #679 at t=0.3912s
dvs:   5% 680/13876 [00:11<03:03, 71.92fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #689 at t=0.3933s
dvs:   5% 690/13876 [00:11<02:50, 77.52fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #692 at t=0.3939s
dvs:   5% 712/13876 [00:11<02:28, 88.41fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #714 at t=0.3986s
WARNING:v2ecore.emulator:no signal events generated for frame #722 at t=0.4003s
dvs:   5% 722/13876 [00:11<02:47, 78.31fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #723 at t=0.4005s
WARNING:v2ecore.emulator:no signal events generated for frame #724 at t=0.4007s
WARNING:v2ecore.emulator:no signal events generated for frame #726 at t=0.4011s
WARNING:v2ecore.emulator:no signal events generated for frame #729 at t=0.4018s
WARNING:v2ecore.emulator:no signal events generated for frame #732 at t=0.4024s
dvs:   5% 738/13876 [00:12<02:22, 92.20fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #739 at t=0.4039s
WARNING:v2ecore.emulator:no signal events generated for frame #743 at t=0.4047s
WARNING:v2ecore.emulator:no signal events generated for frame #745 at t=0.4051s
WARNING:v2ecore.emulator:no signal events generated for frame #747 at t=0.4056s
WARNING:v2ecore.emulator:no signal events generated for frame #750 at t=0.4062s
dvs:   5% 754/13876 [00:12<02:56, 74.47fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #756 at t=0.4075s
WARNING:v2ecore.emulator:no signal events generated for frame #757 at t=0.4077s
WARNING:v2ecore.emulator:no signal events generated for frame #760 at t=0.4083s
WARNING:v2ecore.emulator:no signal events generated for frame #763 at t=0.4089s
dvs:   6% 766/13876 [00:12<02:38, 82.73fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #769 at t=0.4102s
WARNING:v2ecore.emulator:no signal events generated for frame #774 at t=0.4112s
dvs:   6% 778/13876 [00:12<02:26, 89.67fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #783 at t=0.4131s
WARNING:v2ecore.emulator:no signal events generated for frame #784 at t=0.4134s
WARNING:v2ecore.emulator:no signal events generated for frame #785 at t=0.4136s
dvs:   6% 794/13876 [00:12<02:10, 100.19fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #797 at t=0.4161s
WARNING:v2ecore.emulator:no signal events generated for frame #800 at t=0.4167s
WARNING:v2ecore.emulator:no signal events generated for frame #804 at t=0.4176s
dvs:   6% 805/13876 [00:12<02:07, 102.36fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #806 at t=0.4180s
WARNING:v2ecore.emulator:no signal events generated for frame #808 at t=0.4184s
WARNING:v2ecore.emulator:no signal events generated for frame #812 at t=0.4193s
dvs:   6% 876/13876 [00:13<03:18, 65.41fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #881 at t=0.4338s
WARNING:v2ecore.emulator:no signal events generated for frame #882 at t=0.4340s
WARNING:v2ecore.emulator:no signal events generated for frame #883 at t=0.4342s
WARNING:v2ecore.emulator:no signal events generated for frame #884 at t=0.4345s
WARNING:v2ecore.emulator:no signal events generated for frame #885 at t=0.4347s
WARNING:v2ecore.emulator:no signal events generated for frame #886 at t=0.4349s
WARNING:v2ecore.emulator:no signal events generated for frame #888 at t=0.4353s
WARNING:v2ecore.emulator:no signal events generated for frame #890 at t=0.4357s
dvs:   6% 890/13876 [00:13<02:55, 73.93fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #892 at t=0.4361s
WARNING:v2ecore.emulator:no signal events generated for frame #893 at t=0.4364s
WARNING:v2ecore.emulator:no signal events generated for frame #894 at t=0.4366s
WARNING:v2ecore.emulator:no signal events generated for frame #895 at t=0.4368s
WARNING:v2ecore.emulator:no signal events generated for frame #896 at t=0.4370s
WARNING:v2ecore.emulator:no signal events generated for frame #897 at t=0.4372s
WARNING:v2ecore.emulator:no signal events generated for frame #899 at t=0.4376s
WARNING:v2ecore.emulator:no signal events generated for frame #900 at t=0.4378s
WARNING:v2ecore.emulator:no signal events generated for frame #901 at t=0.4380s
WARNING:v2ecore.emulator:no signal events generated for frame #903 at t=0.4385s
WARNING:v2ecore.emulator:no signal events generated for frame #904 at t=0.4387s
dvs:   7% 906/13876 [00:14<02:40, 80.76fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #907 at t=0.4393s
WARNING:v2ecore.emulator:no signal events generated for frame #909 at t=0.4397s
WARNING:v2ecore.emulator:no signal events generated for frame #911 at t=0.4402s
WARNING:v2ecore.emulator:no signal events generated for frame #912 at t=0.4404s
WARNING:v2ecore.emulator:no signal events generated for frame #913 at t=0.4406s
WARNING:v2ecore.emulator:no signal events generated for frame #914 at t=0.4408s
WARNING:v2ecore.emulator:no signal events generated for frame #916 at t=0.4412s
WARNING:v2ecore.emulator:no signal events generated for frame #917 at t=0.4414s
WARNING:v2ecore.emulator:no signal events generated for frame #918 at t=0.4416s
WARNING:v2ecore.emulator:no signal events generated for frame #920 at t=0.4421s
WARNING:v2ecore.emulator:no signal events generated for frame #921 at t=0.4423s
WARNING:v2ecore.emulator:no signal events generated for frame #923 at t=0.4427s
WARNING:v2ecore.emulator:no signal events generated for frame #924 at t=0.4429s
WARNING:v2ecore.emulator:no signal events generated for frame #925 at t=0.4431s
WARNING:v2ecore.emulator:no signal events generated for frame #926 at t=0.4433s
WARNING:v2ecore.emulator:no signal events generated for frame #927 at t=0.4435s
dvs: 100% 13876/13876 [03:55<00:00, 58.86fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 201 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 203 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 13876 frames
INFO:v2e:generated total 15.32M events (7.76M on, 7.56M off)
INFO:v2e:Avg event rate for N=89960 px and total time =6.733 s
	Total: 2.27MHz (1.15MHz on, 1.12MHz off)
	Per pixel:  25.29Hz (12.81Hz on, 12.48Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 406 frames in 756.99s (1.86s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 201 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 203 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 13876 frames
Total events: 15,315,956
  Written 5,000,000/15,315,956
  Written 10,000,000/15,315,956
  Written 15,000,000/15,315,956
  Written 15,315,956/15,315,956
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 203
Output folder: /content/v2e-output/aps
APS frames found: 203
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/203 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:06.77, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:06.77, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x58199b59d840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x58199b5ae740] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x58199b61a9c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x58199b61a9c0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x58199b61a9c0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  203 fps= 41 q=-1.0 Lsize=    1966kB time=00:00:06.66 bitrate=2416.4kbits/s speed=1.35x
video:1963kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.152840%
[libx264 @ 0x58199b61a9c0] frame I:9     Avg QP:25.76  size: 33206
[libx264 @ 0x58199b61a9c0] frame P:76    Avg QP:27.41  size: 14583
[libx264 @ 0x58199b61a9c0] frame B:118   Avg QP:30.09  size:  5108
[libx264 @ 0x58199b61a9c0] consecutive B-frames: 20.7%  3.9%  4.4% 70.9%
[libx264 @ 0x58199b61a9c0] mb I  I16..4:  2.3% 54.7% 42.9%
[libx264 @ 0x58199b61a9c0] mb P  I16..4:  4.8% 27.6% 18.7%  P16..4: 17.0%  3.5%  2.7%  0.0%  0.0%    skip:25.8%
[libx264 @ 0x58199b61a9c0] mb B  I16..4:  3.5%  1.4%  4.0%  B16..8: 20.9%  2.1%  1.0%  direct: 2.1%  skip:65.0%  L0:43.1% L1:54.4% BI: 2.5%
[libx264 @ 0x58199b61a9c0] 8x8 transform intra:47.1% inter:61.1%
[libx264 @ 0x58199b61a9c0] coded y,uvDC,uvAC intra: 64.3% 42.8% 40.7% inter: 12.4% 2.7% 1.0%
[libx264 @ 0x58199b61a9c0] i16 v,h,dc,p: 40% 14% 41%  5%
[libx264 @ 0x58199b61a9c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 49%  8% 30%  2%  2%  3%  1%  3%  2%
[libx264 @ 0x58199b61a9c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 12% 31%  5%  4%  5%  4%  4%  3%
[libx264 @ 0x58199b61a9c0] i8c dc,h,v,p: 79%  5% 13%  3%
[libx264 @ 0x58199b61a9c0] Weighted P-Frames: Y:31.6% UV:22.4%
[libx264 @ 0x58199b61a9c0] ref P L0: 56.4% 22.6% 14.8%  5.1%  1.2%
[libx264 @ 0x58199b61a9c0] ref B L0: 80.6% 16.6%  2.8%
[libx264 @ 0x58199b61a9c0] ref B L1: 91.1%  8.9%
[libx264 @ 0x58199b61a9c0] kb/s:2376.24
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (deflated 27%)
  adding: dvs/0140.png (stored 0%)
  adding: dvs/0104.png (deflated 20%)
  adding: dvs/0160.png (deflated 9%)
  adding: dvs/0105.png (deflated 12%)
  adding: dvs/0199.png (stored 0%)
  adding: dvs/0134.png (deflated 21%)
  adding: dvs/0077.png (stored 0%)
  adding: dvs/0011.png (deflated 14%)
  adding: dvs/0026.png (stored 0%)
  adding: dvs/0154.png (deflated 18%)
  adding: dvs/0128.png (deflated 12%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0120.png (deflated 12%)
  adding: dvs/0163.png (deflated 11%)
  adding: dvs/0084.png (stored 0%)
  adding: dvs/0066.png (deflated 16%)
  adding: dvs/0010.png (deflated 24%)
  adding: dvs/0191.png (deflated 9%)
  adding: dvs/0007.png (deflated 29%)
  adding: dvs/0071.png (deflated 18%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (deflated 5%)
  adding: dvs/0062.png (deflated 19%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0197.png (deflated 10%)
  adding: dvs/0143.png (stored 0%)
  adding: dvs/0184.png (deflated 16%)
  adding: dvs/0178.png (deflated 13%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (deflated 22%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (stored 0%)
  adding: dvs/0126.png (deflated 10%)
  adding: dvs/0150.png (deflated 3%)
  adding: dvs/0042.png (deflated 16%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (deflated 58%)
  adding: dvs/0075.png (deflated 9%)
  adding: dvs/0036.png (deflated 7%)
  adding: dvs/0095.png (deflated 12%)
  adding: dvs/0065.png (deflated 24%)
  adding: dvs/0057.png (deflated 14%)
  adding: dvs/0033.png (deflated 10%)
  adding: dvs/0182.png (deflated 27%)
  adding: dvs/0091.png (deflated 5%)
  adding: dvs/0067.png (deflated 9%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0047.png (deflated 29%)
  adding: dvs/0151.png (deflated 2%)
  adding: dvs/0056.png (deflated 9%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (deflated 29%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0072.png (deflated 16%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (deflated 13%)
  adding: dvs/0157.png (deflated 7%)
  adding: dvs/0013.png (deflated 29%)
  adding: dvs/0158.png (deflated 11%)
  adding: dvs/0034.png (deflated 11%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (deflated 17%)
  adding: dvs/0175.png (stored 0%)
  adding: dvs/0167.png (stored 0%)
  adding: dvs/0041.png (deflated 26%)
  adding: dvs/0177.png (stored 0%)
  adding: dvs/0032.png (deflated 9%)
  adding: dvs/0093.png (deflated 19%)
  adding: dvs/0004.png (deflated 24%)
  adding: dvs/0006.png (deflated 11%)
  adding: dvs/0159.png (deflated 2%)
  adding: dvs/0188.png (deflated 4%)
  adding: dvs/0030.png (deflated 7%)
  adding: dvs/0130.png (deflated 17%)
  adding: dvs/0132.png (deflated 22%)
  adding: dvs/0009.png (deflated 26%)
  adding: dvs/0162.png (deflated 11%)
  adding: dvs/0017.png (deflated 1%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (deflated 5%)
  adding: dvs/0170.png (stored 0%)
  adding: dvs/0035.png (deflated 3%)
  adding: dvs/0201.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (deflated 10%)
  adding: dvs/0196.png (stored 0%)
  adding: dvs/0147.png (stored 0%)
  adding: dvs/0183.png (deflated 25%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0069.png (deflated 9%)
  adding: dvs/0148.png (stored 0%)
  adding: dvs/0060.png (deflated 9%)
  adding: dvs/0003.png (deflated 18%)
  adding: dvs/0187.png (deflated 8%)
  adding: dvs/0029.png (deflated 2%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0001.png (deflated 32%)
  adding: dvs/0200.png (stored 0%)
  adding: dvs/0046.png (deflated 3%)
  adding: dvs/0135.png (deflated 14%)
  adding: dvs/0080.png (stored 0%)
  adding: dvs/0094.png (deflated 9%)
  adding: dvs/0090.png (deflated 3%)
  adding: dvs/0203.png (stored 0%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (deflated 15%)
  adding: dvs/0024.png (stored 0%)
  adding: dvs/0061.png (deflated 18%)
  adding: dvs/0039.png (deflated 14%)
  adding: dvs/0101.png (deflated 18%)
  adding: dvs/0152.png (deflated 5%)
  adding: dvs/0097.png (deflated 15%)
  adding: dvs/0059.png (deflated 6%)
  adding: dvs/0038.png (deflated 12%)
  adding: dvs/0070.png (deflated 12%)
  adding: dvs/0129.png (deflated 13%)
  adding: dvs/0037.png (deflated 15%)
  adding: dvs/0073.png (deflated 20%)
  adding: dvs/0116.png (deflated 3%)
  adding: dvs/0185.png (deflated 9%)
  adding: dvs/0021.png (stored 0%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0015.png (deflated 4%)
  adding: dvs/0166.png (deflated 6%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0121.png (deflated 14%)
  adding: dvs/0027.png (stored 0%)
  adding: dvs/0040.png (deflated 18%)
  adding: dvs/0074.png (deflated 10%)
  adding: dvs/0149.png (deflated 2%)
  adding: dvs/0096.png (deflated 11%)
  adding: dvs/0068.png (deflated 9%)
  adding: dvs/0181.png (deflated 14%)
  adding: dvs/0180.png (deflated 9%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (stored 0%)
  adding: dvs/0078.png (stored 0%)
  adding: dvs/0125.png (deflated 10%)
  adding: dvs/0127.png (deflated 12%)
  adding: dvs/0099.png (deflated 16%)
  adding: dvs/0194.png (deflated 2%)
  adding: dvs/0008.png (deflated 29%)
  adding: dvs/0028.png (deflated 0%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (deflated 1%)
  adding: dvs/0103.png (deflated 12%)
  adding: dvs/0092.png (deflated 8%)
  adding: dvs/0012.png (deflated 25%)
  adding: dvs/0133.png (deflated 21%)
  adding: dvs/0165.png (deflated 12%)
  adding: dvs/0031.png (deflated 2%)
  adding: dvs/0064.png (deflated 29%)
  adding: dvs/0155.png (deflated 9%)
  adding: dvs/0193.png (deflated 6%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (deflated 10%)
  adding: dvs/0144.png (stored 0%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0202.png (stored 0%)
  adding: dvs/0114.png (stored 0%)
  adding: dvs/0107.png (stored 0%)
  adding: dvs/0123.png (deflated 20%)
  adding: dvs/0109.png (stored 0%)
  adding: dvs/0189.png (deflated 11%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0058.png (deflated 6%)
  adding: dvs/0153.png (deflated 7%)
  adding: dvs/0139.png (stored 0%)
  adding: dvs/0174.png (stored 0%)
  adding: dvs/0192.png (deflated 8%)
  adding: dvs/0169.png (deflated 23%)
  adding: dvs/0098.png (deflated 17%)
  adding: dvs/0048.png (stored 0%)
  adding: dvs/0089.png (deflated 4%)
  adding: dvs/0122.png (deflated 12%)
  adding: dvs/0002.png (deflated 11%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (stored 0%)
  adding: dvs/0176.png (deflated 1%)
  adding: dvs/0136.png (deflated 2%)
  adding: dvs/0005.png (deflated 19%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (deflated 16%)
  adding: dvs/0124.png (deflated 15%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (deflated 11%)
  adding: dvs/0173.png (stored 0%)
  adding: dvs/0186.png (deflated 7%)
  adding: dvs/0131.png (deflated 16%)
  adding: dvs/0119.png (deflated 10%)
  adding: dvs/0083.png (stored 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (deflated 35%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 18%)
  adding: aps/0140.png (deflated 19%)
  adding: aps/0104.png (deflated 16%)
  adding: aps/0160.png (deflated 17%)
  adding: aps/0105.png (deflated 16%)
  adding: aps/0199.png (deflated 19%)
  adding: aps/0134.png (deflated 19%)
  adding: aps/0077.png (deflated 22%)
  adding: aps/0011.png (deflated 19%)
  adding: aps/0026.png (deflated 17%)
  adding: aps/0154.png (deflated 17%)
  adding: aps/0128.png (deflated 19%)
  adding: aps/0171.png (deflated 20%)
  adding: aps/0108.png (deflated 32%)
  adding: aps/0145.png (deflated 17%)
  adding: aps/0120.png (deflated 18%)
  adding: aps/0163.png (deflated 16%)
  adding: aps/0084.png (deflated 16%)
  adding: aps/0066.png (deflated 19%)
  adding: aps/0010.png (deflated 18%)
  adding: aps/0191.png (deflated 18%)
  adding: aps/0007.png (deflated 18%)
  adding: aps/0071.png (deflated 19%)
  adding: aps/0053.png (deflated 19%)
  adding: aps/0161.png (deflated 17%)
  adding: aps/0062.png (deflated 19%)
  adding: aps/0082.png (deflated 17%)
  adding: aps/0197.png (deflated 23%)
  adding: aps/0143.png (deflated 17%)
  adding: aps/0184.png (deflated 19%)
  adding: aps/0178.png (deflated 18%)
  adding: aps/0054.png (deflated 19%)
  adding: aps/0022.png (deflated 18%)
  adding: aps/0045.png (deflated 17%)
  adding: aps/0086.png (deflated 17%)
  adding: aps/0117.png (deflated 19%)
  adding: aps/0052.png (deflated 19%)
  adding: aps/0126.png (deflated 18%)
  adding: aps/0150.png (deflated 16%)
  adding: aps/0042.png (deflated 16%)
  adding: aps/0112.png (deflated 19%)
  adding: aps/0168.png (deflated 36%)
  adding: aps/0075.png (deflated 19%)
  adding: aps/0036.png (deflated 17%)
  adding: aps/0095.png (deflated 16%)
  adding: aps/0065.png (deflated 17%)
  adding: aps/0057.png (deflated 19%)
  adding: aps/0033.png (deflated 16%)
  adding: aps/0182.png (deflated 19%)
  adding: aps/0091.png (deflated 17%)
  adding: aps/0067.png (deflated 18%)
  adding: aps/0081.png (deflated 18%)
  adding: aps/0047.png (deflated 16%)
  adding: aps/0151.png (deflated 16%)
  adding: aps/0056.png (deflated 19%)
  adding: aps/0142.png (deflated 17%)
  adding: aps/0044.png (deflated 16%)
  adding: aps/0020.png (deflated 19%)
  adding: aps/0106.png (deflated 16%)
  adding: aps/0072.png (deflated 18%)
  adding: aps/0113.png (deflated 19%)
  adding: aps/0043.png (deflated 16%)
  adding: aps/0157.png (deflated 16%)
  adding: aps/0013.png (deflated 19%)
  adding: aps/0158.png (deflated 17%)
  adding: aps/0034.png (deflated 17%)
  adding: aps/0138.png (deflated 37%)
  adding: aps/0100.png (deflated 16%)
  adding: aps/0175.png (deflated 18%)
  adding: aps/0167.png (deflated 16%)
  adding: aps/0041.png (deflated 16%)
  adding: aps/0177.png (deflated 20%)
  adding: aps/0032.png (deflated 16%)
  adding: aps/0093.png (deflated 16%)
  adding: aps/0004.png (deflated 19%)
  adding: aps/0006.png (deflated 18%)
  adding: aps/0159.png (deflated 17%)
  adding: aps/0188.png (deflated 19%)
  adding: aps/0030.png (deflated 17%)
  adding: aps/0130.png (deflated 18%)
  adding: aps/0132.png (deflated 18%)
  adding: aps/0009.png (deflated 19%)
  adding: aps/0162.png (deflated 16%)
  adding: aps/0017.png (deflated 19%)
  adding: aps/0051.png (deflated 20%)
  adding: aps/0190.png (deflated 19%)
  adding: aps/0170.png (deflated 23%)
  adding: aps/0035.png (deflated 17%)
  adding: aps/0201.png (deflated 18%)
  adding: aps/0018.png (deflated 34%)
  adding: aps/0156.png (deflated 17%)
  adding: aps/0196.png (deflated 19%)
  adding: aps/0147.png (deflated 17%)
  adding: aps/0183.png (deflated 19%)
  adding: aps/0198.png (deflated 29%)
  adding: aps/0069.png (deflated 19%)
  adding: aps/0148.png (deflated 17%)
  adding: aps/0060.png (deflated 19%)
  adding: aps/0003.png (deflated 18%)
  adding: aps/0187.png (deflated 19%)
  adding: aps/0029.png (deflated 17%)
  adding: aps/0115.png (deflated 19%)
  adding: aps/0141.png (deflated 19%)
  adding: aps/0001.png (deflated 19%)
  adding: aps/0200.png (deflated 18%)
  adding: aps/0046.png (deflated 16%)
  adding: aps/0135.png (deflated 19%)
  adding: aps/0080.png (deflated 19%)
  adding: aps/0094.png (deflated 17%)
  adding: aps/0090.png (deflated 16%)
  adding: aps/0203.png (deflated 17%)
  adding: aps/0049.png (deflated 25%)
  adding: aps/0164.png (deflated 16%)
  adding: aps/0024.png (deflated 17%)
  adding: aps/0061.png (deflated 20%)
  adding: aps/0039.png (deflated 16%)
  adding: aps/0101.png (deflated 16%)
  adding: aps/0152.png (deflated 17%)
  adding: aps/0097.png (deflated 16%)
  adding: aps/0059.png (deflated 19%)
  adding: aps/0038.png (deflated 16%)
  adding: aps/0070.png (deflated 18%)
  adding: aps/0129.png (deflated 18%)
  adding: aps/0037.png (deflated 16%)
  adding: aps/0073.png (deflated 19%)
  adding: aps/0116.png (deflated 18%)
  adding: aps/0185.png (deflated 19%)
  adding: aps/0021.png (deflated 18%)
  adding: aps/0137.png (deflated 19%)
  adding: aps/0015.png (deflated 19%)
  adding: aps/0166.png (deflated 16%)
  adding: aps/0146.png (deflated 17%)
  adding: aps/0121.png (deflated 20%)
  adding: aps/0027.png (deflated 17%)
  adding: aps/0040.png (deflated 16%)
  adding: aps/0074.png (deflated 19%)
  adding: aps/0149.png (deflated 16%)
  adding: aps/0096.png (deflated 16%)
  adding: aps/0068.png (deflated 19%)
  adding: aps/0181.png (deflated 20%)
  adding: aps/0180.png (deflated 18%)
  adding: aps/0076.png (deflated 19%)
  adding: aps/0079.png (deflated 20%)
  adding: aps/0078.png (deflated 29%)
  adding: aps/0125.png (deflated 18%)
  adding: aps/0127.png (deflated 19%)
  adding: aps/0099.png (deflated 16%)
  adding: aps/0194.png (deflated 20%)
  adding: aps/0008.png (deflated 18%)
  adding: aps/0028.png (deflated 17%)
  adding: aps/0050.png (deflated 23%)
  adding: aps/0088.png (deflated 16%)
  adding: aps/0118.png (deflated 18%)
  adding: aps/0103.png (deflated 16%)
  adding: aps/0092.png (deflated 16%)
  adding: aps/0012.png (deflated 18%)
  adding: aps/0133.png (deflated 19%)
  adding: aps/0165.png (deflated 16%)
  adding: aps/0031.png (deflated 16%)
  adding: aps/0064.png (deflated 18%)
  adding: aps/0155.png (deflated 17%)
  adding: aps/0193.png (deflated 20%)
  adding: aps/0055.png (deflated 18%)
  adding: aps/0195.png (deflated 19%)
  adding: aps/0144.png (deflated 17%)
  adding: aps/0110.png (deflated 23%)
  adding: aps/0016.png (deflated 19%)
  adding: aps/0202.png (deflated 17%)
  adding: aps/0114.png (deflated 19%)
  adding: aps/0107.png (deflated 17%)
  adding: aps/0123.png (deflated 18%)
  adding: aps/0109.png (deflated 24%)
  adding: aps/0189.png (deflated 18%)
  adding: aps/0025.png (deflated 16%)
  adding: aps/0085.png (deflated 16%)
  adding: aps/0058.png (deflated 19%)
  adding: aps/0153.png (deflated 17%)
  adding: aps/0139.png (deflated 21%)
  adding: aps/0174.png (deflated 19%)
  adding: aps/0192.png (deflated 18%)
  adding: aps/0169.png (deflated 26%)
  adding: aps/0098.png (deflated 16%)
  adding: aps/0048.png (deflated 32%)
  adding: aps/0089.png (deflated 17%)
  adding: aps/0122.png (deflated 19%)
  adding: aps/0002.png (deflated 19%)
  adding: aps/0111.png (deflated 21%)
  adding: aps/0172.png (deflated 19%)
  adding: aps/0176.png (deflated 20%)

'The chosen video file: /content/video/soap_1hz.MOV'

FPS: 29.97090203685742
Frame count: 206
Duration: 6.87 sec
The Final v2e command:

'v2e -i /content/video/soap_1hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/soap_1hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/soap_1hz.MOV
INFO:v2e:Input video frame rate 29.97090203685742Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/soap_1hz.MOV has total 206 frames with total duration 6.83s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 206 frames 0 to 205
(From 0.0s to 6.833333333333333s, duration 6.833333333333333s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 205.0 frames with duration 6.83s and playback duration 6.83s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 205 from video input
INFO:v2e:Input video /content/video/soap_1hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 206 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/206 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 206/206 [00:07<00:00, 28.75fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpf0oottn7
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 26 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/26 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 154
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/26 [00:40<16:54, 40.57s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 71
slomo-interp:   8% 2/26 [00:58<11:00, 27.53s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 179
slomo-interp: 100% 26/26 [12:37<00:00, 29.14s/ batch of 8 fr]
write-orig-avi: 100% 206/206 [00:00<00:00, 538.84fr/s]
write-slomo-vid: 100% 22446/22446 [00:52<00:00, 427.19fr/s]
INFO:v2ecore.slomo:Wrote 22446 frames and returning 22446 frame times.
Average upsampling factor=110.4
INFO:v2e:SloMo average upsampling factor=110.42; average DVS timestamp resolution=301.87us
INFO:v2e:*** Stage 3/3: emulating DVS events from 22446 frames
dvs:   0% 0/22446 [00:00<?, ?fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2 at t=0.0002s
WARNING:v2ecore.emulator:no signal events generated for frame #3 at t=0.0004s
WARNING:v2ecore.emulator:no signal events generated for frame #4 at t=0.0006s
WARNING:v2ecore.emulator:no signal events generated for frame #5 at t=0.0009s
WARNING:v2ecore.emulator:no signal events generated for frame #6 at t=0.0011s
WARNING:v2ecore.emulator:no signal events generated for frame #7 at t=0.0013s
WARNING:v2ecore.emulator:no signal events generated for frame #8 at t=0.0015s
WARNING:v2ecore.emulator:no signal events generated for frame #9 at t=0.0017s
WARNING:v2ecore.emulator:no signal events generated for frame #10 at t=0.0019s
WARNING:v2ecore.emulator:no signal events generated for frame #11 at t=0.0022s
WARNING:v2ecore.emulator:no signal events generated for frame #12 at t=0.0024s
WARNING:v2ecore.emulator:no signal events generated for frame #13 at t=0.0026s
WARNING:v2ecore.emulator:no signal events generated for frame #14 at t=0.0028s
dvs:   0% 14/22446 [00:00<02:44, 136.70fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15 at t=0.0030s
WARNING:v2ecore.emulator:no signal events generated for frame #16 at t=0.0032s
WARNING:v2ecore.emulator:no signal events generated for frame #17 at t=0.0035s
INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:   0% 28/22446 [00:00<11:54, 31.36fr/s] WARNING:v2ecore.emulator:no signal events generated for frame #32 at t=0.0067s
dvs:   1% 170/22446 [00:02<04:30, 82.24fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #175 at t=0.0377s
dvs:   1% 314/22446 [00:05<06:14, 59.17fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #316 at t=0.0682s
dvs:   2% 461/22446 [00:07<04:23, 83.33fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #473 at t=0.1022s
dvs:   2% 484/22446 [00:07<05:17, 69.16fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #489 at t=0.1056s
dvs:   2% 531/22446 [00:08<04:45, 76.82fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #539 at t=0.1165s
dvs:   3% 626/22446 [00:09<04:49, 75.46fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #631 at t=0.1364s
WARNING:v2ecore.emulator:no signal events generated for frame #632 at t=0.1366s
dvs:   3% 648/22446 [00:09<05:35, 65.01fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #652 at t=0.1409s
dvs:  14% 3094/22446 [00:51<04:22, 73.62fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,096 at t=0.7745s
dvs:  14% 3207/22446 [00:52<03:31, 91.15fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,210 at t=0.7957s
dvs:  35% 7810/22446 [02:14<04:32, 53.64fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #7,812 at t=2.3464s
dvs:  35% 7858/22446 [02:15<04:31, 53.77fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #7,859 at t=2.3544s
dvs:  52% 11692/22446 [03:20<02:40, 67.06fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,697 at t=3.5406s
dvs:  52% 11746/22446 [03:21<02:19, 76.52fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,752 at t=3.5509s
dvs:  53% 11867/22446 [03:23<03:47, 46.41fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,868 at t=3.5728s
dvs:  53% 11914/22446 [03:23<03:10, 55.35fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,918 at t=3.5822s
dvs:  53% 11954/22446 [03:24<03:06, 56.31fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,961 at t=3.5903s
WARNING:v2ecore.emulator:no signal events generated for frame #11,962 at t=3.5905s
WARNING:v2ecore.emulator:no signal events generated for frame #11,970 at t=3.5920s
dvs:  54% 12010/22446 [03:25<04:25, 39.31fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,018 at t=3.6010s
dvs:  54% 12018/22446 [03:25<04:02, 42.98fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,025 at t=3.6024s
WARNING:v2ecore.emulator:no signal events generated for frame #12,031 at t=3.6035s
dvs:  54% 12050/22446 [03:26<03:53, 44.54fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,054 at t=3.6078s
dvs:  54% 12058/22446 [03:26<03:40, 47.02fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,060 at t=3.6090s
dvs:  54% 12230/22446 [03:28<02:27, 69.14fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,237 at t=3.6423s
dvs:  55% 12241/22446 [03:28<02:11, 77.79fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,244 at t=3.6436s
dvs:  57% 12722/22446 [03:35<02:09, 75.21fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,723 at t=3.7344s
WARNING:v2ecore.emulator:no signal events generated for frame #12,725 at t=3.7354s
WARNING:v2ecore.emulator:no signal events generated for frame #12,728 at t=3.7369s
dvs:  57% 12730/22446 [03:36<02:56, 54.99fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,736 at t=3.7408s
dvs:  57% 12739/22446 [03:36<02:35, 62.27fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,741 at t=3.7432s
WARNING:v2ecore.emulator:no signal events generated for frame #12,750 at t=3.7477s
dvs:  57% 12750/22446 [03:36<02:12, 73.02fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,753 at t=3.7491s
WARNING:v2ecore.emulator:no signal events generated for frame #12,754 at t=3.7496s
WARNING:v2ecore.emulator:no signal events generated for frame #12,755 at t=3.7501s
WARNING:v2ecore.emulator:no signal events generated for frame #12,756 at t=3.7506s
WARNING:v2ecore.emulator:no signal events generated for frame #12,757 at t=3.7511s
WARNING:v2ecore.emulator:no signal events generated for frame #12,758 at t=3.7516s
dvs:  57% 12772/22446 [03:36<01:53, 85.11fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,776 at t=3.7604s
WARNING:v2ecore.emulator:no signal events generated for frame #12,777 at t=3.7609s
WARNING:v2ecore.emulator:no signal events generated for frame #12,781 at t=3.7629s
dvs:  62% 13915/22446 [03:55<02:47, 50.86fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #13,919 at t=4.1339s
dvs:  68% 15322/22446 [04:21<02:14, 52.80fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,326 at t=4.5670s
dvs:  68% 15346/22446 [04:22<03:14, 36.48fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,348 at t=4.5717s
dvs:  68% 15354/22446 [04:22<02:53, 40.87fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,358 at t=4.5738s
dvs:  69% 15426/22446 [04:23<02:12, 53.07fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,428 at t=4.5888s
dvs:  69% 15445/22446 [04:24<01:39, 70.72fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,452 at t=4.5939s
dvs:  69% 15481/22446 [04:24<01:24, 82.19fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,486 at t=4.6012s
dvs:  69% 15506/22446 [04:25<02:11, 52.60fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,507 at t=4.6057s
dvs:  69% 15516/22446 [04:25<01:51, 62.35fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,525 at t=4.6095s
dvs:  70% 15645/22446 [04:26<01:22, 82.25fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,653 at t=4.6369s
dvs:  72% 16266/22446 [04:37<01:58, 52.10fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,269 at t=4.7685s
dvs:  73% 16274/22446 [04:37<02:01, 50.90fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,277 at t=4.7702s
WARNING:v2ecore.emulator:no signal events generated for frame #16,280 at t=4.7709s
WARNING:v2ecore.emulator:no signal events generated for frame #16,282 at t=4.7713s
dvs:  73% 16282/22446 [04:37<02:58, 34.55fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,285 at t=4.7719s
WARNING:v2ecore.emulator:no signal events generated for frame #16,289 at t=4.7728s
WARNING:v2ecore.emulator:no signal events generated for frame #16,293 at t=4.7736s
WARNING:v2ecore.emulator:no signal events generated for frame #16,295 at t=4.7741s
dvs:  73% 16298/22446 [04:38<02:07, 48.09fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,300 at t=4.7751s
WARNING:v2ecore.emulator:no signal events generated for frame #16,302 at t=4.7756s
dvs:  73% 16306/22446 [04:38<01:59, 51.45fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,307 at t=4.7766s
WARNING:v2ecore.emulator:no signal events generated for frame #16,309 at t=4.7771s
WARNING:v2ecore.emulator:no signal events generated for frame #16,314 at t=4.7781s
WARNING:v2ecore.emulator:no signal events generated for frame #16,315 at t=4.7783s
dvs:  73% 16318/22446 [04:38<01:36, 63.74fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,320 at t=4.7794s
WARNING:v2ecore.emulator:no signal events generated for frame #16,326 at t=4.7807s
dvs:  73% 16328/22446 [04:38<01:25, 71.20fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,330 at t=4.7815s
WARNING:v2ecore.emulator:no signal events generated for frame #16,334 at t=4.7824s
WARNING:v2ecore.emulator:no signal events generated for frame #16,337 at t=4.7830s
dvs:  73% 16337/22446 [04:38<01:22, 74.24fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,339 at t=4.7835s
WARNING:v2ecore.emulator:no signal events generated for frame #16,342 at t=4.7841s
WARNING:v2ecore.emulator:no signal events generated for frame #16,346 at t=4.7850s
dvs:  73% 16346/22446 [04:38<01:19, 76.76fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,349 at t=4.7856s
WARNING:v2ecore.emulator:no signal events generated for frame #16,350 at t=4.7858s
dvs:  73% 16357/22446 [04:38<01:11, 84.83fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,359 at t=4.7877s
WARNING:v2ecore.emulator:no signal events generated for frame #16,360 at t=4.7880s
WARNING:v2ecore.emulator:no signal events generated for frame #16,362 at t=4.7884s
WARNING:v2ecore.emulator:no signal events generated for frame #16,363 at t=4.7886s
dvs:  73% 16367/22446 [04:38<01:09, 87.67fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #16,370 at t=4.7901s
WARNING:v2ecore.emulator:no signal events generated for frame #16,371 at t=4.7903s
WARNING:v2ecore.emulator:no signal events generated for frame #16,372 at t=4.7905s
WARNING:v2ecore.emulator:no signal events generated for frame #16,373 at t=4.7907s
dvs: 100% 22446/22446 [06:25<00:00, 58.26fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 204 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 206 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 22446 frames
INFO:v2e:generated total 33.11M events (16.62M on, 16.49M off)
INFO:v2e:Avg event rate for N=89960 px and total time =6.833 s
	Total: 4.85MHz (2.43MHz on, 2.41MHz off)
	Per pixel:  53.86Hz (27.03Hz on, 26.83Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 412 frames in 1.20ks (2.92s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 204 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 206 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 22446 frames
Total events: 33,109,423
  Written 5,000,000/33,109,423
  Written 10,000,000/33,109,423
  Written 15,000,000/33,109,423
  Written 20,000,000/33,109,423
  Written 25,000,000/33,109,423
  Written 30,000,000/33,109,423
  Written 33,109,423/33,109,423
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 206
Output folder: /content/v2e-output/aps
APS frames found: 206
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/206 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:06.87, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:06.87, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x57de39aa0840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x57de39aa9480] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x57de39e4cc40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x57de39e4cc40] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x57de39e4cc40] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  206 fps= 46 q=-1.0 Lsize=    3834kB time=00:00:06.76 bitrate=4641.9kbits/s speed= 1.5x
video:3832kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.068024%
[libx264 @ 0x57de39e4cc40] frame I:18    Avg QP:26.34  size: 43372
[libx264 @ 0x57de39e4cc40] frame P:117   Avg QP:29.11  size: 21105
[libx264 @ 0x57de39e4cc40] frame B:71    Avg QP:30.66  size:  9479
[libx264 @ 0x57de39e4cc40] consecutive B-frames: 50.0% 10.7%  4.4% 35.0%
[libx264 @ 0x57de39e4cc40] mb I  I16..4:  1.1% 49.3% 49.6%
[libx264 @ 0x57de39e4cc40] mb P  I16..4:  8.5% 32.9% 28.4%  P16..4: 13.4%  2.1%  1.4%  0.0%  0.0%    skip:13.2%
[libx264 @ 0x57de39e4cc40] mb B  I16..4:  7.8%  2.3%  7.0%  B16..8: 24.4%  4.9%  3.0%  direct: 2.6%  skip:48.0%  L0:38.6% L1:59.1% BI: 2.3%
[libx264 @ 0x57de39e4cc40] 8x8 transform intra:43.8% inter:52.4%
[libx264 @ 0x57de39e4cc40] coded y,uvDC,uvAC intra: 68.4% 47.1% 44.6% inter: 21.0% 6.5% 2.7%
[libx264 @ 0x57de39e4cc40] i16 v,h,dc,p: 30% 14% 51%  5%
[libx264 @ 0x57de39e4cc40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 52%  9% 27%  2%  2%  3%  1%  3%  2%
[libx264 @ 0x57de39e4cc40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 12% 30%  6%  5%  5%  5%  5%  4%
[libx264 @ 0x57de39e4cc40] i8c dc,h,v,p: 77%  5% 14%  4%
[libx264 @ 0x57de39e4cc40] Weighted P-Frames: Y:29.1% UV:25.6%
[libx264 @ 0x57de39e4cc40] ref P L0: 61.9% 18.0% 13.4%  5.5%  1.2%
[libx264 @ 0x57de39e4cc40] ref B L0: 83.0% 15.2%  1.7%
[libx264 @ 0x57de39e4cc40] ref B L1: 87.4% 12.6%
[libx264 @ 0x57de39e4cc40] kb/s:4570.43
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (deflated 3%)
  adding: dvs/0140.png (stored 0%)
  adding: dvs/0104.png (stored 0%)
  adding: dvs/0160.png (stored 0%)
  adding: dvs/0105.png (stored 0%)
  adding: dvs/0199.png (stored 0%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0077.png (stored 0%)
  adding: dvs/0011.png (stored 0%)
  adding: dvs/0026.png (stored 0%)
  adding: dvs/0154.png (deflated 4%)
  adding: dvs/0128.png (stored 0%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0120.png (stored 0%)
  adding: dvs/0163.png (stored 0%)
  adding: dvs/0084.png (stored 0%)
  adding: dvs/0066.png (deflated 1%)
  adding: dvs/0010.png (stored 0%)
  adding: dvs/0191.png (stored 0%)
  adding: dvs/0007.png (deflated 78%)
  adding: dvs/0071.png (stored 0%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (stored 0%)
  adding: dvs/0062.png (stored 0%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0197.png (stored 0%)
  adding: dvs/0143.png (deflated 0%)
  adding: dvs/0184.png (deflated 7%)
  adding: dvs/0178.png (stored 0%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (stored 0%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (deflated 1%)
  adding: dvs/0126.png (stored 0%)
  adding: dvs/0150.png (stored 0%)
  adding: dvs/0042.png (stored 0%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (stored 0%)
  adding: dvs/0075.png (stored 0%)
  adding: dvs/0036.png (stored 0%)
  adding: dvs/0095.png (deflated 6%)
  adding: dvs/0065.png (deflated 1%)
  adding: dvs/0057.png (stored 0%)
  adding: dvs/0033.png (stored 0%)
  adding: dvs/0182.png (stored 0%)
  adding: dvs/0091.png (stored 0%)
  adding: dvs/0067.png (stored 0%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0047.png (stored 0%)
  adding: dvs/0151.png (stored 0%)
  adding: dvs/0056.png (stored 0%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (stored 0%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0072.png (stored 0%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (stored 0%)
  adding: dvs/0013.png (stored 0%)
  adding: dvs/0158.png (stored 0%)
  adding: dvs/0034.png (stored 0%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (stored 0%)
  adding: dvs/0175.png (stored 0%)
  adding: dvs/0167.png (stored 0%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0177.png (stored 0%)
  adding: dvs/0032.png (stored 0%)
  adding: dvs/0093.png (deflated 4%)
  adding: dvs/0004.png (deflated 7%)
  adding: dvs/0006.png (stored 0%)
  adding: dvs/0159.png (deflated 10%)
  adding: dvs/0188.png (deflated 42%)
  adding: dvs/0030.png (stored 0%)
  adding: dvs/0130.png (stored 0%)
  adding: dvs/0132.png (stored 0%)
  adding: dvs/0009.png (stored 0%)
  adding: dvs/0205.png (stored 0%)
  adding: dvs/0162.png (stored 0%)
  adding: dvs/0017.png (stored 0%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (stored 0%)
  adding: dvs/0170.png (deflated 0%)
  adding: dvs/0035.png (stored 0%)
  adding: dvs/0201.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (stored 0%)
  adding: dvs/0196.png (stored 0%)
  adding: dvs/0147.png (stored 0%)
  adding: dvs/0183.png (deflated 6%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0069.png (stored 0%)
  adding: dvs/0148.png (stored 0%)
  adding: dvs/0060.png (stored 0%)
  adding: dvs/0003.png (deflated 8%)
  adding: dvs/0187.png (deflated 1%)
  adding: dvs/0029.png (stored 0%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0001.png (deflated 32%)
  adding: dvs/0200.png (stored 0%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0135.png (stored 0%)
  adding: dvs/0080.png (deflated 1%)
  adding: dvs/0094.png (deflated 7%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0203.png (stored 0%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (stored 0%)
  adding: dvs/0024.png (stored 0%)
  adding: dvs/0061.png (stored 0%)
  adding: dvs/0039.png (stored 0%)
  adding: dvs/0101.png (stored 0%)
  adding: dvs/0152.png (stored 0%)
  adding: dvs/0097.png (stored 0%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (stored 0%)
  adding: dvs/0070.png (stored 0%)
  adding: dvs/0129.png (stored 0%)
  adding: dvs/0206.png (stored 0%)
  adding: dvs/0037.png (deflated 32%)
  adding: dvs/0073.png (stored 0%)
  adding: dvs/0116.png (stored 0%)
  adding: dvs/0185.png (deflated 6%)
  adding: dvs/0021.png (deflated 48%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0015.png (stored 0%)
  adding: dvs/0166.png (stored 0%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0121.png (stored 0%)
  adding: dvs/0027.png (stored 0%)
  adding: dvs/0040.png (stored 0%)
  adding: dvs/0074.png (stored 0%)
  adding: dvs/0149.png (stored 0%)
  adding: dvs/0096.png (stored 0%)
  adding: dvs/0068.png (stored 0%)
  adding: dvs/0181.png (stored 0%)
  adding: dvs/0180.png (stored 0%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (stored 0%)
  adding: dvs/0078.png (stored 0%)
  adding: dvs/0125.png (deflated 3%)
  adding: dvs/0127.png (stored 0%)
  adding: dvs/0099.png (stored 0%)
  adding: dvs/0194.png (stored 0%)
  adding: dvs/0008.png (deflated 50%)
  adding: dvs/0028.png (stored 0%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (stored 0%)
  adding: dvs/0103.png (stored 0%)
  adding: dvs/0092.png (deflated 0%)
  adding: dvs/0012.png (deflated 0%)
  adding: dvs/0133.png (stored 0%)
  adding: dvs/0165.png (stored 0%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (deflated 2%)
  adding: dvs/0155.png (deflated 2%)
  adding: dvs/0193.png (stored 0%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (stored 0%)
  adding: dvs/0144.png (stored 0%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0202.png (deflated 22%)
  adding: dvs/0114.png (stored 0%)
  adding: dvs/0107.png (stored 0%)
  adding: dvs/0123.png (deflated 1%)
  adding: dvs/0109.png (deflated 1%)
  adding: dvs/0189.png (deflated 31%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0058.png (stored 0%)
  adding: dvs/0153.png (stored 0%)
  adding: dvs/0139.png (stored 0%)
  adding: dvs/0174.png (stored 0%)
  adding: dvs/0192.png (stored 0%)
  adding: dvs/0169.png (stored 0%)
  adding: dvs/0098.png (stored 0%)
  adding: dvs/0048.png (stored 0%)
  adding: dvs/0089.png (stored 0%)
  adding: dvs/0122.png (stored 0%)
  adding: dvs/0002.png (deflated 21%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (deflated 20%)
  adding: dvs/0176.png (stored 0%)
  adding: dvs/0136.png (stored 0%)
  adding: dvs/0005.png (deflated 2%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (stored 0%)
  adding: dvs/0124.png (deflated 3%)
  adding: dvs/0204.png (stored 0%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0173.png (stored 0%)
  adding: dvs/0186.png (stored 0%)
  adding: dvs/0131.png (stored 0%)
  adding: dvs/0119.png (stored 0%)
  adding: dvs/0083.png (stored 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (stored 0%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 16%)
  adding: aps/0140.png (deflated 18%)
  adding: aps/0104.png (deflated 19%)
  adding: aps/0160.png (deflated 20%)
  adding: aps/0105.png (deflated 18%)
  adding: aps/0199.png (deflated 18%)
  adding: aps/0134.png (deflated 20%)
  adding: aps/0077.png (deflated 18%)
  adding: aps/0011.png (deflated 21%)
  adding: aps/0026.png (deflated 19%)
  adding: aps/0154.png (deflated 17%)
  adding: aps/0128.png (deflated 34%)
  adding: aps/0171.png (deflated 19%)
  adding: aps/0108.png (deflated 18%)
  adding: aps/0145.png (deflated 25%)
  adding: aps/0120.png (deflated 17%)
  adding: aps/0163.png (deflated 19%)
  adding: aps/0084.png (deflated 21%)
  adding: aps/0066.png (deflated 16%)
  adding: aps/0010.png (deflated 23%)
  adding: aps/0191.png (deflated 21%)
  adding: aps/0007.png (deflated 17%)
  adding: aps/0071.png (deflated 22%)
  adding: aps/0053.png (deflated 38%)
  adding: aps/0161.png (deflated 19%)
  adding: aps/0062.png (deflated 17%)
  adding: aps/0082.png (deflated 24%)
  adding: aps/0197.png (deflated 19%)
  adding: aps/0143.png (deflated 35%)
  adding: aps/0184.png (deflated 17%)
  adding: aps/0178.png (deflated 17%)
  adding: aps/0054.png (deflated 32%)
  adding: aps/0022.png (deflated 33%)
  adding: aps/0045.png (deflated 19%)
  adding: aps/0086.png (deflated 18%)
  adding: aps/0117.png (deflated 18%)
  adding: aps/0052.png (deflated 23%)
  adding: aps/0126.png (deflated 16%)
  adding: aps/0150.png (deflated 17%)
  adding: aps/0042.png (deflated 20%)
  adding: aps/0112.png (deflated 28%)
  adding: aps/0168.png (deflated 18%)
  adding: aps/0075.png (deflated 18%)
  adding: aps/0036.png (deflated 17%)
  adding: aps/0095.png (deflated 16%)
  adding: aps/0065.png (deflated 16%)
  adding: aps/0057.png (deflated 18%)
  adding: aps/0033.png (deflated 16%)
  adding: aps/0182.png (deflated 16%)
  adding: aps/0091.png (deflated 17%)
  adding: aps/0067.png (deflated 16%)
  adding: aps/0081.png (deflated 19%)
  adding: aps/0047.png (deflated 18%)
  adding: aps/0151.png (deflated 17%)
  adding: aps/0056.png (deflated 19%)
  adding: aps/0142.png (deflated 19%)
  adding: aps/0044.png (deflated 20%)
  adding: aps/0020.png (deflated 18%)
  adding: aps/0106.png (deflated 18%)
  adding: aps/0072.png (deflated 21%)
  adding: aps/0113.png (deflated 28%)
  adding: aps/0043.png (deflated 19%)
  adding: aps/0157.png (deflated 18%)
  adding: aps/0013.png (deflated 20%)
  adding: aps/0158.png (deflated 32%)
  adding: aps/0034.png (deflated 16%)
  adding: aps/0138.png (deflated 18%)
  adding: aps/0100.png (deflated 20%)
  adding: aps/0175.png (deflated 20%)
  adding: aps/0167.png (deflated 19%)
  adding: aps/0041.png (deflated 20%)
  adding: aps/0177.png (deflated 18%)
  adding: aps/0032.png (deflated 16%)
  adding: aps/0093.png (deflated 17%)
  adding: aps/0004.png (deflated 17%)
  adding: aps/0006.png (deflated 16%)
  adding: aps/0159.png (deflated 24%)
  adding: aps/0188.png (deflated 29%)
  adding: aps/0030.png (deflated 17%)
  adding: aps/0130.png (deflated 22%)
  adding: aps/0132.png (deflated 19%)
  adding: aps/0009.png (deflated 23%)
  adding: aps/0205.png (deflated 21%)
  adding: aps/0162.png (deflated 18%)
  adding: aps/0017.png (deflated 19%)
  adding: aps/0051.png (deflated 19%)
  adding: aps/0190.png (deflated 21%)
  adding: aps/0170.png (deflated 19%)
  adding: aps/0035.png (deflated 16%)
  adding: aps/0201.png (deflated 20%)
  adding: aps/0018.png (deflated 18%)
  adding: aps/0156.png (deflated 16%)
  adding: aps/0196.png (deflated 18%)
  adding: aps/0147.png (deflated 18%)
  adding: aps/0183.png (deflated 16%)
  adding: aps/0198.png (deflated 19%)
  adding: aps/0069.png (deflated 23%)
  adding: aps/0148.png (deflated 17%)
  adding: aps/0060.png (deflated 17%)
  adding: aps/0003.png (deflated 17%)
  adding: aps/0187.png (deflated 19%)
  adding: aps/0029.png (deflated 17%)
  adding: aps/0115.png (deflated 19%)
  adding: aps/0141.png (deflated 20%)
  adding: aps/0001.png (deflated 17%)
  adding: aps/0200.png (deflated 18%)
  adding: aps/0046.png (deflated 19%)
  adding: aps/0135.png (deflated 19%)
  adding: aps/0080.png (deflated 18%)
  adding: aps/0094.png (deflated 16%)
  adding: aps/0090.png (deflated 17%)
  adding: aps/0203.png (deflated 28%)
  adding: aps/0049.png (deflated 18%)
  adding: aps/0164.png (deflated 19%)
  adding: aps/0024.png (deflated 21%)
  adding: aps/0061.png (deflated 17%)
  adding: aps/0039.png (deflated 27%)
  adding: aps/0101.png (deflated 19%)
  adding: aps/0152.png (deflated 17%)
  adding: aps/0097.png (deflated 16%)
  adding: aps/0059.png (deflated 17%)
  adding: aps/0038.png (deflated 32%)
  adding: aps/0070.png (deflated 22%)
  adding: aps/0129.png (deflated 24%)
  adding: aps/0206.png (deflated 19%)
  adding: aps/0037.png (deflated 19%)
  adding: aps/0073.png (deflated 19%)
  adding: aps/0116.png (deflated 19%)
  adding: aps/0185.png (deflated 16%)
  adding: aps/0021.png (deflated 19%)
  adding: aps/0137.png (deflated 19%)
  adding: aps/0015.png (deflated 19%)
  adding: aps/0166.png (deflated 18%)
  adding: aps/0146.png (deflated 19%)
  adding: aps/0121.png (deflated 17%)
  adding: aps/0027.png (deflated 18%)
  adding: aps/0040.png (deflated 21%)
  adding: aps/0074.png (deflated 18%)
  adding: aps/0149.png (deflated 17%)
  adding: aps/0096.png (deflated 16%)
  adding: aps/0068.png (deflated 37%)
  adding: aps/0181.png (deflated 17%)
  adding: aps/0180.png (deflated 17%)
  adding: aps/0076.png (deflated 17%)
  adding: aps/0079.png (deflated 18%)
  adding: aps/0078.png (deflated 18%)
  adding: aps/0125.png (deflated 16%)
  adding: aps/0127.png (deflated 17%)
  adding: aps/0099.png (deflated 22%)
  adding: aps/0194.png (deflated 19%)
  adding: aps/0008.png (deflated 37%)
  adding: aps/0028.png (deflated 17%)
  adding: aps/0050.png (deflated 17%)
  adding: aps/0088.png (deflated 18%)
  adding: aps/0118.png (deflated 17%)
  adding: aps/0103.png (deflated 19%)
  adding: aps/0092.png (deflated 17%)
  adding: aps/0012.png (deflated 20%)
  adding: aps/0133.png (deflated 19%)
  adding: aps/0165.png (deflated 18%)
  adding: aps/0031.png (deflated 17%)
  adding: aps/0064.png (deflated 17%)
  adding: aps/0155.png (deflated 16%)
  adding: aps/0193.png (deflated 19%)
  adding: aps/0055.png (deflated 22%)
  adding: aps/0195.png (deflated 18%)
  adding: aps/0144.png (deflated 28%)
  adding: aps/0110.png (deflated 18%)
  adding: aps/0016.png (deflated 19%)
  adding: aps/0202.png (deflated 25%)
  adding: aps/0114.png (deflated 27%)
  adding: aps/0107.png (deflated 18%)
  adding: aps/0123.png (deflated 17%)
  adding: aps/0109.png (deflated 18%)
  adding: aps/0189.png (deflated 23%)
  adding: aps/0025.png (deflated 21%)
  adding: aps/0085.png (deflated 20%)
  adding: aps/0058.png (deflated 17%)
  adding: aps/0153.png (deflated 17%)
  adding: aps/0139.png (deflated 18%)
  adding: aps/0174.png (deflated 20%)
  adding: aps/0192.png (deflated 19%)
  adding: aps/0169.png (deflated 18%)
  adding: aps/0098.png (deflated 35%)
  adding: aps/0048.png (deflated 18%)
  adding: aps/0089.png (deflated 17%)
  adding: aps/0122.png (deflated 17%)
  adding: aps/0002.png (deflated 17%)
  adding: aps/0111.png (deflated 19%)
  adding: aps/0172.png (deflated 34%)
  adding: aps/0176.png (deflated 19%)
  adding: aps/0136.png (deflated 18%)
  adding: aps/0005.png (deflated 16%)

'The chosen video file: /content/video/soap_2hz.MOV'

FPS: 29.97827661115134
Frame count: 207
Duration: 6.91 sec
The Final v2e command:

'v2e -i /content/video/soap_2hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/soap_2hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/soap_2hz.MOV
INFO:v2e:Input video frame rate 29.97827661115134Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/soap_2hz.MOV has total 207 frames with total duration 6.87s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 207 frames 0 to 206
(From 0.0s to 6.866666666666666s, duration 6.866666666666666s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 206.0 frames with duration 6.87s and playback duration 6.87s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 206 from video input
INFO:v2e:Input video /content/video/soap_2hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 207 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/207 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 207/207 [00:07<00:00, 28.22fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpaepxd27_
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 26 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/26 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 176
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/26 [00:47<19:48, 47.53s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 174
slomo-interp:   8% 2/26 [01:32<18:30, 46.29s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 178
slomo-interp: 100% 26/26 [20:10<00:00, 46.54s/ batch of 8 fr]
write-orig-avi: 100% 207/207 [00:00<00:00, 527.57fr/s]
write-slomo-vid: 100% 35820/35820 [01:21<00:00, 439.33fr/s]
INFO:v2ecore.slomo:Wrote 35820 frames and returning 35820 frame times.
Average upsampling factor=174.0
INFO:v2e:SloMo average upsampling factor=173.96; average DVS timestamp resolution=191.61us
INFO:v2e:*** Stage 3/3: emulating DVS events from 35820 frames
dvs:   0% 0/35820 [00:00<?, ?fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #2 at t=0.0002s
WARNING:v2ecore.emulator:no signal events generated for frame #3 at t=0.0004s
dvs:   0% 3/35820 [00:00<20:25, 29.22fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4 at t=0.0006s
WARNING:v2ecore.emulator:no signal events generated for frame #5 at t=0.0008s
INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs: 100% 35820/35820 [10:41<00:00, 55.85fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 205 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 207 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 35820 frames
INFO:v2e:generated total 67.14M events (33.29M on, 33.85M off)
INFO:v2e:Avg event rate for N=89960 px and total time =6.867 s
	Total: 9.78MHz (4.85MHz on, 4.93MHz off)
	Per pixel:  108.69Hz (53.89Hz on, 54.80Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 414 frames in 1.94ks (4.70s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 205 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 207 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 35820 frames
Total events: 67,140,331
  Written 5,000,000/67,140,331
  Written 10,000,000/67,140,331
  Written 15,000,000/67,140,331
  Written 20,000,000/67,140,331
  Written 25,000,000/67,140,331
  Written 30,000,000/67,140,331
  Written 35,000,000/67,140,331
  Written 40,000,000/67,140,331
  Written 45,000,000/67,140,331
  Written 50,000,000/67,140,331
  Written 55,000,000/67,140,331
  Written 60,000,000/67,140,331
  Written 65,000,000/67,140,331
  Written 67,140,331/67,140,331
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 207
Output folder: /content/v2e-output/aps
APS frames found: 207
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/207 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:06.90, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:06.90, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x58ee36c95840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x58ee36c9aec0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x58ee36d0dc40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x58ee36d0dc40] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x58ee36d0dc40] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  207 fps= 31 q=-1.0 Lsize=    4793kB time=00:00:06.80 bitrate=5774.3kbits/s speed=   1x
video:4791kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.044537%
[libx264 @ 0x58ee36d0dc40] frame I:30    Avg QP:26.45  size: 35946
[libx264 @ 0x58ee36d0dc40] frame P:156   Avg QP:28.77  size: 21828
[libx264 @ 0x58ee36d0dc40] frame B:21    Avg QP:31.94  size: 20081
[libx264 @ 0x58ee36d0dc40] consecutive B-frames: 81.6% 12.6%  5.8%  0.0%
[libx264 @ 0x58ee36d0dc40] mb I  I16..4:  3.1% 52.8% 44.1%
[libx264 @ 0x58ee36d0dc40] mb P  I16..4:  9.4% 40.3% 28.7%  P16..4: 10.8%  1.6%  0.9%  0.0%  0.0%    skip: 8.4%
[libx264 @ 0x58ee36d0dc40] mb B  I16..4: 10.4%  2.1% 18.9%  B16..8: 17.5%  6.2%  4.2%  direct: 3.9%  skip:36.9%  L0:24.9% L1:67.2% BI: 7.9%
[libx264 @ 0x58ee36d0dc40] 8x8 transform intra:49.8% inter:69.5%
[libx264 @ 0x58ee36d0dc40] coded y,uvDC,uvAC intra: 65.5% 43.5% 41.2% inter: 32.4% 6.9% 3.5%
[libx264 @ 0x58ee36d0dc40] i16 v,h,dc,p: 31% 10% 53%  7%
[libx264 @ 0x58ee36d0dc40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 53% 11% 25%  2%  1%  2%  1%  3%  2%
[libx264 @ 0x58ee36d0dc40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 12% 29%  6%  5%  5%  5%  5%  4%
[libx264 @ 0x58ee36d0dc40] i8c dc,h,v,p: 77%  5% 14%  4%
[libx264 @ 0x58ee36d0dc40] Weighted P-Frames: Y:28.2% UV:18.6%
[libx264 @ 0x58ee36d0dc40] ref P L0: 60.1% 27.0%  9.6%  2.8%  0.6%
[libx264 @ 0x58ee36d0dc40] ref B L0: 87.8% 11.6%  0.6%
[libx264 @ 0x58ee36d0dc40] kb/s:5687.31
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (stored 0%)
  adding: dvs/0140.png (stored 0%)
  adding: dvs/0104.png (stored 0%)
  adding: dvs/0160.png (stored 0%)
  adding: dvs/0105.png (stored 0%)
  adding: dvs/0199.png (stored 0%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0077.png (stored 0%)
  adding: dvs/0011.png (stored 0%)
  adding: dvs/0026.png (deflated 46%)
  adding: dvs/0154.png (stored 0%)
  adding: dvs/0128.png (stored 0%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0120.png (stored 0%)
  adding: dvs/0163.png (stored 0%)
  adding: dvs/0084.png (deflated 10%)
  adding: dvs/0066.png (stored 0%)
  adding: dvs/0010.png (deflated 65%)
  adding: dvs/0191.png (deflated 41%)
  adding: dvs/0007.png (stored 0%)
  adding: dvs/0071.png (stored 0%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (deflated 0%)
  adding: dvs/0062.png (stored 0%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0197.png (stored 0%)
  adding: dvs/0143.png (stored 0%)
  adding: dvs/0184.png (stored 0%)
  adding: dvs/0178.png (deflated 12%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (stored 0%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (stored 0%)
  adding: dvs/0126.png (stored 0%)
  adding: dvs/0150.png (stored 0%)
  adding: dvs/0042.png (deflated 6%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (stored 0%)
  adding: dvs/0075.png (stored 0%)
  adding: dvs/0036.png (stored 0%)
  adding: dvs/0207.png (deflated 52%)
  adding: dvs/0095.png (stored 0%)
  adding: dvs/0065.png (stored 0%)
  adding: dvs/0057.png (deflated 29%)
  adding: dvs/0033.png (stored 0%)
  adding: dvs/0182.png (stored 0%)
  adding: dvs/0091.png (stored 0%)
  adding: dvs/0067.png (stored 0%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0047.png (stored 0%)
  adding: dvs/0151.png (deflated 0%)
  adding: dvs/0056.png (stored 0%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (stored 0%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0072.png (deflated 9%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (stored 0%)
  adding: dvs/0013.png (stored 0%)
  adding: dvs/0158.png (stored 0%)
  adding: dvs/0034.png (stored 0%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (stored 0%)
  adding: dvs/0175.png (deflated 8%)
  adding: dvs/0167.png (stored 0%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0177.png (deflated 12%)
  adding: dvs/0032.png (stored 0%)
  adding: dvs/0093.png (stored 0%)
  adding: dvs/0004.png (stored 0%)
  adding: dvs/0006.png (stored 0%)
  adding: dvs/0159.png (deflated 38%)
  adding: dvs/0188.png (stored 0%)
  adding: dvs/0030.png (deflated 8%)
  adding: dvs/0130.png (deflated 1%)
  adding: dvs/0132.png (stored 0%)
  adding: dvs/0009.png (stored 0%)
  adding: dvs/0205.png (stored 0%)
  adding: dvs/0162.png (stored 0%)
  adding: dvs/0017.png (stored 0%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (stored 0%)
  adding: dvs/0170.png (stored 0%)
  adding: dvs/0035.png (stored 0%)
  adding: dvs/0201.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (stored 0%)
  adding: dvs/0196.png (deflated 42%)
  adding: dvs/0147.png (stored 0%)
  adding: dvs/0183.png (stored 0%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0069.png (stored 0%)
  adding: dvs/0148.png (stored 0%)
  adding: dvs/0060.png (stored 0%)
  adding: dvs/0003.png (stored 0%)
  adding: dvs/0187.png (stored 0%)
  adding: dvs/0029.png (stored 0%)
  adding: dvs/0115.png (deflated 9%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0001.png (deflated 11%)
  adding: dvs/0200.png (stored 0%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0135.png (stored 0%)
  adding: dvs/0080.png (stored 0%)
  adding: dvs/0094.png (stored 0%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0203.png (stored 0%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (stored 0%)
  adding: dvs/0024.png (deflated 1%)
  adding: dvs/0061.png (stored 0%)
  adding: dvs/0039.png (stored 0%)
  adding: dvs/0101.png (stored 0%)
  adding: dvs/0152.png (stored 0%)
  adding: dvs/0097.png (stored 0%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (deflated 5%)
  adding: dvs/0070.png (stored 0%)
  adding: dvs/0129.png (deflated 18%)
  adding: dvs/0206.png (stored 0%)
  adding: dvs/0037.png (stored 0%)
  adding: dvs/0073.png (stored 0%)
  adding: dvs/0116.png (stored 0%)
  adding: dvs/0185.png (stored 0%)
  adding: dvs/0021.png (stored 0%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0015.png (deflated 26%)
  adding: dvs/0166.png (deflated 12%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0121.png (stored 0%)
  adding: dvs/0027.png (deflated 2%)
  adding: dvs/0040.png (stored 0%)
  adding: dvs/0074.png (stored 0%)
  adding: dvs/0149.png (stored 0%)
  adding: dvs/0096.png (stored 0%)
  adding: dvs/0068.png (stored 0%)
  adding: dvs/0181.png (deflated 30%)
  adding: dvs/0180.png (stored 0%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (stored 0%)
  adding: dvs/0078.png (stored 0%)
  adding: dvs/0125.png (stored 0%)
  adding: dvs/0127.png (stored 0%)
  adding: dvs/0099.png (stored 0%)
  adding: dvs/0194.png (stored 0%)
  adding: dvs/0008.png (deflated 67%)
  adding: dvs/0028.png (stored 0%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (stored 0%)
  adding: dvs/0103.png (stored 0%)
  adding: dvs/0092.png (stored 0%)
  adding: dvs/0012.png (stored 0%)
  adding: dvs/0133.png (stored 0%)
  adding: dvs/0165.png (stored 0%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (stored 0%)
  adding: dvs/0155.png (stored 0%)
  adding: dvs/0193.png (deflated 32%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (stored 0%)
  adding: dvs/0144.png (deflated 27%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0202.png (stored 0%)
  adding: dvs/0114.png (deflated 9%)
  adding: dvs/0107.png (stored 0%)
  adding: dvs/0123.png (stored 0%)
  adding: dvs/0109.png (stored 0%)
  adding: dvs/0189.png (deflated 81%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0085.png (deflated 20%)
  adding: dvs/0058.png (stored 0%)
  adding: dvs/0153.png (stored 0%)
  adding: dvs/0139.png (stored 0%)
  adding: dvs/0174.png (deflated 49%)
  adding: dvs/0192.png (deflated 5%)
  adding: dvs/0169.png (stored 0%)
  adding: dvs/0098.png (stored 0%)
  adding: dvs/0048.png (stored 0%)
  adding: dvs/0089.png (stored 0%)
  adding: dvs/0122.png (stored 0%)
  adding: dvs/0002.png (stored 0%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (stored 0%)
  adding: dvs/0176.png (stored 0%)
  adding: dvs/0136.png (stored 0%)
  adding: dvs/0005.png (stored 0%)
  adding: dvs/0023.png (deflated 32%)
  adding: dvs/0102.png (stored 0%)
  adding: dvs/0124.png (stored 0%)
  adding: dvs/0204.png (deflated 82%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0173.png (stored 0%)
  adding: dvs/0186.png (stored 0%)
  adding: dvs/0131.png (stored 0%)
  adding: dvs/0119.png (stored 0%)
  adding: dvs/0083.png (stored 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (stored 0%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 20%)
  adding: aps/0140.png (deflated 18%)
  adding: aps/0104.png (deflated 18%)
  adding: aps/0160.png (deflated 30%)
  adding: aps/0105.png (deflated 18%)
  adding: aps/0199.png (deflated 19%)
  adding: aps/0134.png (deflated 19%)
  adding: aps/0077.png (deflated 37%)
  adding: aps/0011.png (deflated 24%)
  adding: aps/0026.png (deflated 29%)
  adding: aps/0154.png (deflated 20%)
  adding: aps/0128.png (deflated 17%)
  adding: aps/0171.png (deflated 18%)
  adding: aps/0108.png (deflated 26%)
  adding: aps/0145.png (deflated 32%)
  adding: aps/0120.png (deflated 18%)
  adding: aps/0163.png (deflated 18%)
  adding: aps/0084.png (deflated 34%)
  adding: aps/0066.png (deflated 18%)
  adding: aps/0010.png (deflated 35%)
  adding: aps/0191.png (deflated 27%)
  adding: aps/0007.png (deflated 17%)
  adding: aps/0071.png (deflated 22%)
  adding: aps/0053.png (deflated 17%)
  adding: aps/0161.png (deflated 24%)
  adding: aps/0062.png (deflated 29%)
  adding: aps/0082.png (deflated 17%)
  adding: aps/0197.png (deflated 32%)
  adding: aps/0143.png (deflated 17%)
  adding: aps/0184.png (deflated 20%)
  adding: aps/0178.png (deflated 19%)
  adding: aps/0054.png (deflated 33%)
  adding: aps/0022.png (deflated 18%)
  adding: aps/0045.png (deflated 18%)
  adding: aps/0086.png (deflated 22%)
  adding: aps/0117.png (deflated 20%)
  adding: aps/0052.png (deflated 17%)
  adding: aps/0126.png (deflated 18%)
  adding: aps/0150.png (deflated 19%)
  adding: aps/0042.png (deflated 22%)
  adding: aps/0112.png (deflated 18%)
  adding: aps/0168.png (deflated 22%)
  adding: aps/0075.png (deflated 18%)
  adding: aps/0036.png (deflated 17%)
  adding: aps/0207.png (deflated 23%)
  adding: aps/0095.png (deflated 20%)
  adding: aps/0065.png (deflated 18%)
  adding: aps/0057.png (deflated 21%)
  adding: aps/0033.png (deflated 21%)
  adding: aps/0182.png (deflated 29%)
  adding: aps/0091.png (deflated 24%)
  adding: aps/0067.png (deflated 17%)
  adding: aps/0081.png (deflated 18%)
  adding: aps/0047.png (deflated 30%)
  adding: aps/0151.png (deflated 38%)
  adding: aps/0056.png (deflated 23%)
  adding: aps/0142.png (deflated 17%)
  adding: aps/0044.png (deflated 19%)
  adding: aps/0020.png (deflated 19%)
  adding: aps/0106.png (deflated 27%)
  adding: aps/0072.png (deflated 21%)
  adding: aps/0113.png (deflated 17%)
  adding: aps/0043.png (deflated 19%)
  adding: aps/0157.png (deflated 17%)
  adding: aps/0013.png (deflated 21%)
  adding: aps/0158.png (deflated 17%)
  adding: aps/0034.png (deflated 20%)
  adding: aps/0138.png (deflated 22%)
  adding: aps/0100.png (deflated 24%)
  adding: aps/0175.png (deflated 24%)
  adding: aps/0167.png (deflated 33%)
  adding: aps/0041.png (deflated 22%)
  adding: aps/0177.png (deflated 23%)
  adding: aps/0032.png (deflated 29%)
  adding: aps/0093.png (deflated 29%)
  adding: aps/0004.png (deflated 20%)
  adding: aps/0006.png (deflated 18%)
  adding: aps/0159.png (deflated 29%)
  adding: aps/0188.png (deflated 17%)
  adding: aps/0030.png (deflated 18%)
  adding: aps/0130.png (deflated 32%)
  adding: aps/0132.png (deflated 21%)
  adding: aps/0009.png (deflated 31%)
  adding: aps/0205.png (deflated 30%)
  adding: aps/0162.png (deflated 20%)
  adding: aps/0017.png (deflated 32%)
  adding: aps/0051.png (deflated 18%)
  adding: aps/0190.png (deflated 28%)
  adding: aps/0170.png (deflated 19%)
  adding: aps/0035.png (deflated 18%)
  adding: aps/0201.png (deflated 18%)
  adding: aps/0018.png (deflated 22%)
  adding: aps/0156.png (deflated 18%)
  adding: aps/0196.png (deflated 41%)
  adding: aps/0147.png (deflated 20%)
  adding: aps/0183.png (deflated 21%)
  adding: aps/0198.png (deflated 21%)
  adding: aps/0069.png (deflated 32%)
  adding: aps/0148.png (deflated 20%)
  adding: aps/0060.png (deflated 18%)
  adding: aps/0003.png (deflated 21%)
  adding: aps/0187.png (deflated 17%)
  adding: aps/0029.png (deflated 19%)
  adding: aps/0115.png (deflated 28%)
  adding: aps/0141.png (deflated 18%)
  adding: aps/0001.png (deflated 28%)
  adding: aps/0200.png (deflated 18%)
  adding: aps/0046.png (deflated 39%)
  adding: aps/0135.png (deflated 18%)
  adding: aps/0080.png (deflated 19%)
  adding: aps/0094.png (deflated 21%)
  adding: aps/0090.png (deflated 18%)
  adding: aps/0203.png (deflated 17%)
  adding: aps/0049.png (deflated 19%)
  adding: aps/0164.png (deflated 19%)
  adding: aps/0024.png (deflated 31%)
  adding: aps/0061.png (deflated 39%)
  adding: aps/0039.png (deflated 32%)
  adding: aps/0101.png (deflated 21%)
  adding: aps/0152.png (deflated 35%)
  adding: aps/0097.png (deflated 17%)
  adding: aps/0059.png (deflated 19%)
  adding: aps/0038.png (deflated 17%)
  adding: aps/0070.png (deflated 26%)
  adding: aps/0129.png (deflated 31%)
  adding: aps/0206.png (deflated 27%)
  adding: aps/0037.png (deflated 17%)
  adding: aps/0073.png (deflated 19%)
  adding: aps/0116.png (deflated 22%)
  adding: aps/0185.png (deflated 18%)
  adding: aps/0021.png (deflated 19%)
  adding: aps/0137.png (deflated 30%)
  adding: aps/0015.png (deflated 18%)
  adding: aps/0166.png (deflated 40%)
  adding: aps/0146.png (deflated 24%)
  adding: aps/0121.png (deflated 32%)
  adding: aps/0027.png (deflated 23%)
  adding: aps/0040.png (deflated 23%)
  adding: aps/0074.png (deflated 19%)
  adding: aps/0149.png (deflated 19%)
  adding: aps/0096.png (deflated 17%)
  adding: aps/0068.png (deflated 17%)
  adding: aps/0181.png (deflated 39%)
  adding: aps/0180.png (deflated 18%)
  adding: aps/0076.png (deflated 21%)
  adding: aps/0079.png (deflated 20%)
  adding: aps/0078.png (deflated 27%)
  adding: aps/0125.png (deflated 19%)
  adding: aps/0127.png (deflated 17%)
  adding: aps/0099.png (deflated 30%)
  adding: aps/0194.png (deflated 18%)
  adding: aps/0008.png (deflated 17%)
  adding: aps/0028.png (deflated 19%)
  adding: aps/0050.png (deflated 18%)
  adding: aps/0088.png (deflated 19%)
  adding: aps/0118.png (deflated 19%)
  adding: aps/0103.png (deflated 19%)
  adding: aps/0092.png (deflated 28%)
  adding: aps/0012.png (deflated 20%)
  adding: aps/0133.png (deflated 19%)
  adding: aps/0165.png (deflated 18%)
  adding: aps/0031.png (deflated 36%)
  adding: aps/0064.png (deflated 19%)
  adding: aps/0155.png (deflated 18%)
  adding: aps/0193.png (deflated 19%)
  adding: aps/0055.png (deflated 24%)
  adding: aps/0195.png (deflated 19%)
  adding: aps/0144.png (deflated 30%)
  adding: aps/0110.png (deflated 18%)
  adding: aps/0016.png (deflated 37%)
  adding: aps/0202.png (deflated 17%)
  adding: aps/0114.png (deflated 32%)
  adding: aps/0107.png (deflated 27%)
  adding: aps/0123.png (deflated 21%)
  adding: aps/0109.png (deflated 21%)
  adding: aps/0189.png (deflated 33%)
  adding: aps/0025.png (deflated 31%)
  adding: aps/0085.png (deflated 27%)
  adding: aps/0058.png (deflated 19%)
  adding: aps/0153.png (deflated 21%)
  adding: aps/0139.png (deflated 20%)
  adding: aps/0174.png (deflated 33%)
  adding: aps/0192.png (deflated 22%)
  adding: aps/0169.png (deflated 20%)
  adding: aps/0098.png (deflated 17%)
  adding: aps/0048.png (deflated 20%)
  adding: aps/0089.png (deflated 19%)
  adding: aps/0122.png (deflated 30%)
  adding: aps/0002.png (deflated 28%)
  adding: aps/0111.png (deflated 18%)
  adding: aps/0172.png (deflated 17%)
  adding: aps/0176.png (deflated 22%)
  adding: aps/0136.png (deflated 34%)

'The chosen video file: /content/video/white_1:2hz.MOV'

FPS: 29.971181556195965
Frame count: 208
Duration: 6.94 sec
The Final v2e command:

'v2e -i /content/video/white_1:2hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/white_1:2hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/white_1:2hz.MOV
INFO:v2e:Input video frame rate 29.971181556195965Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/white_1:2hz.MOV has total 208 frames with total duration 6.90s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 208 frames 0 to 207
(From 0.0s to 6.9s, duration 6.9s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 207.0 frames with duration 6.90s and playback duration 6.90s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 207 from video input
INFO:v2e:Input video /content/video/white_1:2hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 208 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/208 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 208/208 [00:07<00:00, 28.58fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpojbov08q
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 26 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/26 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 14
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/26 [00:05<02:19,  5.58s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 179
slomo-interp:   8% 2/26 [00:51<11:49, 29.55s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 15
slomo-interp: 100% 26/26 [07:16<00:00, 16.81s/ batch of 8 fr]
write-orig-avi: 100% 208/208 [00:00<00:00, 986.38fr/s]
write-slomo-vid: 100% 12827/12827 [00:30<00:00, 424.91fr/s]
INFO:v2ecore.slomo:Wrote 12827 frames and returning 12827 frame times.
Average upsampling factor= 61.7
INFO:v2e:SloMo average upsampling factor=61.73; average DVS timestamp resolution=539.98us
INFO:v2e:*** Stage 3/3: emulating DVS events from 12827 frames
dvs:   0% 2/12827 [00:00<13:58, 15.30fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:   1% 130/12827 [00:03<05:06, 41.48fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #134 at t=0.2707s
dvs:  33% 4193/12827 [01:14<01:38, 87.58fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,195 at t=2.1952s
dvs:  33% 4218/12827 [01:14<01:53, 75.55fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,224 at t=2.2010s
WARNING:v2ecore.emulator:no signal events generated for frame #4,225 at t=2.2012s
WARNING:v2ecore.emulator:no signal events generated for frame #4,226 at t=2.2014s
dvs:  33% 4271/12827 [01:15<01:43, 82.83fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,278 at t=2.2118s
dvs:  34% 4386/12827 [01:16<01:50, 76.38fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,392 at t=2.2346s
WARNING:v2ecore.emulator:no signal events generated for frame #4,393 at t=2.2348s
dvs:  35% 4453/12827 [01:17<02:14, 62.25fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,454 at t=2.2469s
dvs:  36% 4562/12827 [01:19<01:53, 73.03fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,568 at t=2.2697s
dvs:  36% 4590/12827 [01:19<01:55, 71.28fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,597 at t=2.2755s
dvs:  36% 4634/12827 [01:20<01:55, 70.98fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,640 at t=2.2841s
dvs:  36% 4651/12827 [01:20<02:01, 67.13fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,654 at t=2.2869s
dvs:  36% 4674/12827 [01:20<02:21, 57.55fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,682 at t=2.2925s
dvs:  37% 4690/12827 [01:21<02:33, 52.98fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,697 at t=2.2955s
dvs:  44% 5699/12827 [01:41<02:56, 40.48fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,706 at t=3.2014s
WARNING:v2ecore.emulator:no signal events generated for frame #5,708 at t=3.2018s
WARNING:v2ecore.emulator:no signal events generated for frame #5,709 at t=3.2020s
dvs:  45% 5709/12827 [01:41<02:20, 50.82fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,713 at t=3.2028s
WARNING:v2ecore.emulator:no signal events generated for frame #5,714 at t=3.2030s
WARNING:v2ecore.emulator:no signal events generated for frame #5,715 at t=3.2032s
WARNING:v2ecore.emulator:no signal events generated for frame #5,717 at t=3.2037s
WARNING:v2ecore.emulator:no signal events generated for frame #5,721 at t=3.2045s
WARNING:v2ecore.emulator:no signal events generated for frame #5,727 at t=3.2057s
dvs:  45% 5730/12827 [01:41<01:59, 59.55fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,733 at t=3.2070s
WARNING:v2ecore.emulator:no signal events generated for frame #5,736 at t=3.2076s
WARNING:v2ecore.emulator:no signal events generated for frame #5,737 at t=3.2078s
WARNING:v2ecore.emulator:no signal events generated for frame #5,741 at t=3.2086s
WARNING:v2ecore.emulator:no signal events generated for frame #5,744 at t=3.2092s
WARNING:v2ecore.emulator:no signal events generated for frame #5,746 at t=3.2096s
dvs:  45% 5746/12827 [01:41<01:36, 73.48fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,748 at t=3.2100s
WARNING:v2ecore.emulator:no signal events generated for frame #5,755 at t=3.2115s
dvs:  45% 5756/12827 [01:41<01:30, 78.26fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,761 at t=3.2127s
WARNING:v2ecore.emulator:no signal events generated for frame #5,763 at t=3.2131s
WARNING:v2ecore.emulator:no signal events generated for frame #5,764 at t=3.2133s
WARNING:v2ecore.emulator:no signal events generated for frame #5,766 at t=3.2137s
WARNING:v2ecore.emulator:no signal events generated for frame #5,767 at t=3.2140s
WARNING:v2ecore.emulator:no signal events generated for frame #5,770 at t=3.2146s
dvs:  45% 5770/12827 [01:42<01:20, 87.96fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,777 at t=3.2160s
WARNING:v2ecore.emulator:no signal events generated for frame #5,778 at t=3.2162s
WARNING:v2ecore.emulator:no signal events generated for frame #5,779 at t=3.2164s
WARNING:v2ecore.emulator:no signal events generated for frame #5,782 at t=3.2170s
dvs:  45% 5786/12827 [01:42<01:11, 99.07fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,794 at t=3.2195s
dvs:  45% 5797/12827 [01:42<01:12, 96.98fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,799 at t=3.2205s
WARNING:v2ecore.emulator:no signal events generated for frame #5,801 at t=3.2210s
dvs:  45% 5810/12827 [01:42<01:08, 102.69fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,813 at t=3.2234s
WARNING:v2ecore.emulator:no signal events generated for frame #5,818 at t=3.2244s
WARNING:v2ecore.emulator:no signal events generated for frame #5,821 at t=3.2251s
dvs:  45% 5821/12827 [01:42<01:07, 104.09fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,828 at t=3.2265s
WARNING:v2ecore.emulator:no signal events generated for frame #5,829 at t=3.2267s
dvs:  45% 5832/12827 [01:42<01:08, 102.51fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,833 at t=3.2275s
WARNING:v2ecore.emulator:no signal events generated for frame #5,837 at t=3.2284s
WARNING:v2ecore.emulator:no signal events generated for frame #5,840 at t=3.2290s
WARNING:v2ecore.emulator:no signal events generated for frame #5,842 at t=3.2294s
dvs:  46% 5843/12827 [01:42<01:07, 103.39fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,844 at t=3.2298s
WARNING:v2ecore.emulator:no signal events generated for frame #5,845 at t=3.2300s
WARNING:v2ecore.emulator:no signal events generated for frame #5,849 at t=3.2308s
dvs:  46% 5858/12827 [01:42<01:03, 109.78fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,868 at t=3.2347s
WARNING:v2ecore.emulator:no signal events generated for frame #5,870 at t=3.2352s
dvs:  46% 5870/12827 [01:43<01:02, 110.90fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,871 at t=3.2354s
WARNING:v2ecore.emulator:no signal events generated for frame #5,875 at t=3.2362s
WARNING:v2ecore.emulator:no signal events generated for frame #5,876 at t=3.2364s
WARNING:v2ecore.emulator:no signal events generated for frame #5,877 at t=3.2366s
WARNING:v2ecore.emulator:no signal events generated for frame #5,878 at t=3.2368s
WARNING:v2ecore.emulator:no signal events generated for frame #5,881 at t=3.2374s
dvs:  46% 5892/12827 [01:43<01:24, 81.67fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,897 at t=3.2407s
WARNING:v2ecore.emulator:no signal events generated for frame #5,898 at t=3.2409s
WARNING:v2ecore.emulator:no signal events generated for frame #5,899 at t=3.2411s
WARNING:v2ecore.emulator:no signal events generated for frame #5,906 at t=3.2426s
dvs:  46% 5906/12827 [01:43<01:14, 93.12fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,912 at t=3.2438s
WARNING:v2ecore.emulator:no signal events generated for frame #5,914 at t=3.2442s
WARNING:v2ecore.emulator:no signal events generated for frame #5,917 at t=3.2448s
dvs:  46% 5928/12827 [01:43<01:11, 96.14fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,934 at t=3.2483s
dvs:  46% 5939/12827 [01:43<01:22, 83.93fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,949 at t=3.2514s
dvs:  46% 5949/12827 [01:43<01:18, 87.60fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,950 at t=3.2516s
WARNING:v2ecore.emulator:no signal events generated for frame #5,954 at t=3.2524s
dvs:  46% 5959/12827 [01:44<01:17, 88.89fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,960 at t=3.2537s
WARNING:v2ecore.emulator:no signal events generated for frame #5,962 at t=3.2541s
WARNING:v2ecore.emulator:no signal events generated for frame #5,964 at t=3.2545s
WARNING:v2ecore.emulator:no signal events generated for frame #5,965 at t=3.2547s
WARNING:v2ecore.emulator:no signal events generated for frame #5,967 at t=3.2551s
dvs:  47% 5970/12827 [01:44<01:24, 81.34fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,971 at t=3.2559s
dvs:  47% 5989/12827 [01:44<01:21, 84.27fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #5,990 at t=3.2599s
dvs:  47% 6009/12827 [01:44<01:17, 88.52fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,018 at t=3.2656s
dvs:  47% 6019/12827 [01:44<01:30, 74.95fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,020 at t=3.2660s
dvs:  47% 6048/12827 [01:45<02:39, 42.52fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,051 at t=3.2724s
WARNING:v2ecore.emulator:no signal events generated for frame #6,054 at t=3.2730s
dvs:  48% 6125/12827 [01:46<01:24, 79.68fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,131 at t=3.2889s
dvs:  48% 6155/12827 [01:46<01:28, 75.04fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,158 at t=3.2944s
WARNING:v2ecore.emulator:no signal events generated for frame #6,165 at t=3.2959s
dvs:  90% 11594/12827 [03:28<00:17, 71.74fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,599 at t=6.2252s
dvs:  92% 11818/12827 [03:31<00:26, 38.56fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,819 at t=6.2694s
dvs:  93% 11930/12827 [03:34<00:29, 30.01fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,932 at t=6.2921s
dvs:  93% 11947/12827 [03:34<00:20, 43.27fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,948 at t=6.2953s
dvs: 100% 12827/12827 [03:50<00:00, 55.56fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 206 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 208 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 12827 frames
INFO:v2e:generated total 9.91M events (4.99M on, 4.92M off)
INFO:v2e:Avg event rate for N=89960 px and total time =6.900 s
	Total: 1.44MHz (723.13kHz on, 712.59kHz off)
	Per pixel:  15.96Hz (8.04Hz on, 7.92Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 416 frames in 707.08s (1.70s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 206 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 208 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 12827 frames
Total events: 9,906,464
  Written 5,000,000/9,906,464
  Written 9,906,464/9,906,464
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 208
Output folder: /content/v2e-output/aps
APS frames found: 208
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/208 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:06.93, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:06.93, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x5b8a11635840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x5b8a1163ed40] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x5b8a1164b040] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5b8a1164b040] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5b8a1164b040] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  208 fps= 46 q=-1.0 Lsize=    1842kB time=00:00:06.83 bitrate=2208.0kbits/s speed=1.51x
video:1839kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.166821%
[libx264 @ 0x5b8a1164b040] frame I:8     Avg QP:25.96  size: 37566
[libx264 @ 0x5b8a1164b040] frame P:74    Avg QP:27.53  size: 14750
[libx264 @ 0x5b8a1164b040] frame B:126   Avg QP:29.65  size:  3890
[libx264 @ 0x5b8a1164b040] consecutive B-frames: 17.8%  2.9%  4.3% 75.0%
[libx264 @ 0x5b8a1164b040] mb I  I16..4:  1.2% 54.8% 44.1%
[libx264 @ 0x5b8a1164b040] mb P  I16..4:  3.8% 27.0% 20.0%  P16..4: 16.9%  3.5%  3.4%  0.0%  0.0%    skip:25.4%
[libx264 @ 0x5b8a1164b040] mb B  I16..4:  3.7%  1.7%  2.2%  B16..8: 26.6%  3.1%  1.2%  direct: 1.7%  skip:59.8%  L0:45.8% L1:51.9% BI: 2.3%
[libx264 @ 0x5b8a1164b040] 8x8 transform intra:48.0% inter:47.8%
[libx264 @ 0x5b8a1164b040] coded y,uvDC,uvAC intra: 63.8% 40.0% 38.0% inter: 12.7% 2.7% 1.3%
[libx264 @ 0x5b8a1164b040] i16 v,h,dc,p: 47% 17% 32%  4%
[libx264 @ 0x5b8a1164b040] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 46%  9% 34%  2%  1%  2%  1%  3%  2%
[libx264 @ 0x5b8a1164b040] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 12% 33%  5%  4%  5%  4%  4%  3%
[libx264 @ 0x5b8a1164b040] i8c dc,h,v,p: 80%  5% 12%  3%
[libx264 @ 0x5b8a1164b040] Weighted P-Frames: Y:23.0% UV:18.9%
[libx264 @ 0x5b8a1164b040] ref P L0: 68.5% 10.1% 17.2%  3.8%  0.3%
[libx264 @ 0x5b8a1164b040] ref B L0: 76.4% 20.5%  3.1%
[libx264 @ 0x5b8a1164b040] ref B L1: 90.2%  9.8%
[libx264 @ 0x5b8a1164b040] kb/s:2171.74
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (deflated 6%)
  adding: dvs/0140.png (deflated 3%)
  adding: dvs/0104.png (stored 0%)
  adding: dvs/0160.png (stored 0%)
  adding: dvs/0105.png (stored 0%)
  adding: dvs/0199.png (stored 0%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0077.png (stored 0%)
  adding: dvs/0011.png (stored 0%)
  adding: dvs/0026.png (deflated 4%)
  adding: dvs/0154.png (deflated 16%)
  adding: dvs/0128.png (deflated 5%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (deflated 21%)
  adding: dvs/0120.png (deflated 1%)
  adding: dvs/0163.png (stored 0%)
  adding: dvs/0084.png (deflated 13%)
  adding: dvs/0066.png (deflated 1%)
  adding: dvs/0010.png (stored 0%)
  adding: dvs/0191.png (deflated 4%)
  adding: dvs/0007.png (deflated 28%)
  adding: dvs/0071.png (stored 0%)
  adding: dvs/0053.png (deflated 1%)
  adding: dvs/0161.png (deflated 18%)
  adding: dvs/0062.png (deflated 4%)
  adding: dvs/0082.png (deflated 10%)
  adding: dvs/0197.png (stored 0%)
  adding: dvs/0143.png (deflated 5%)
  adding: dvs/0184.png (deflated 0%)
  adding: dvs/0178.png (deflated 1%)
  adding: dvs/0054.png (deflated 1%)
  adding: dvs/0022.png (deflated 1%)
  adding: dvs/0045.png (deflated 0%)
  adding: dvs/0086.png (deflated 3%)
  adding: dvs/0117.png (deflated 2%)
  adding: dvs/0052.png (deflated 1%)
  adding: dvs/0126.png (deflated 18%)
  adding: dvs/0150.png (deflated 16%)
  adding: dvs/0042.png (stored 0%)
  adding: dvs/0112.png (deflated 0%)
  adding: dvs/0168.png (stored 0%)
  adding: dvs/0075.png (stored 0%)
  adding: dvs/0036.png (deflated 20%)
  adding: dvs/0207.png (deflated 2%)
  adding: dvs/0095.png (deflated 15%)
  adding: dvs/0065.png (deflated 2%)
  adding: dvs/0057.png (deflated 0%)
  adding: dvs/0033.png (deflated 15%)
  adding: dvs/0182.png (deflated 0%)
  adding: dvs/0091.png (deflated 14%)
  adding: dvs/0067.png (deflated 0%)
  adding: dvs/0081.png (deflated 11%)
  adding: dvs/0047.png (stored 0%)
  adding: dvs/0151.png (deflated 20%)
  adding: dvs/0056.png (deflated 0%)
  adding: dvs/0142.png (deflated 1%)
  adding: dvs/0044.png (stored 0%)
  adding: dvs/0020.png (deflated 5%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0072.png (stored 0%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (deflated 19%)
  adding: dvs/0013.png (stored 0%)
  adding: dvs/0158.png (deflated 14%)
  adding: dvs/0034.png (deflated 8%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (stored 0%)
  adding: dvs/0175.png (deflated 1%)
  adding: dvs/0167.png (stored 0%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0177.png (deflated 1%)
  adding: dvs/0032.png (deflated 19%)
  adding: dvs/0093.png (deflated 9%)
  adding: dvs/0004.png (deflated 50%)
  adding: dvs/0006.png (deflated 23%)
  adding: dvs/0159.png (deflated 24%)
  adding: dvs/0188.png (stored 0%)
  adding: dvs/0030.png (deflated 14%)
  adding: dvs/0130.png (stored 0%)
  adding: dvs/0132.png (stored 0%)
  adding: dvs/0009.png (deflated 0%)
  adding: dvs/0205.png (deflated 1%)
  adding: dvs/0162.png (deflated 8%)
  adding: dvs/0017.png (stored 0%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (stored 0%)
  adding: dvs/0170.png (stored 0%)
  adding: dvs/0035.png (deflated 19%)
  adding: dvs/0201.png (deflated 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (deflated 22%)
  adding: dvs/0196.png (stored 0%)
  adding: dvs/0147.png (deflated 12%)
  adding: dvs/0183.png (deflated 0%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0069.png (deflated 1%)
  adding: dvs/0148.png (deflated 16%)
  adding: dvs/0060.png (deflated 1%)
  adding: dvs/0003.png (deflated 56%)
  adding: dvs/0187.png (deflated 0%)
  adding: dvs/0029.png (deflated 17%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (deflated 7%)
  adding: dvs/0001.png (deflated 54%)
  adding: dvs/0200.png (deflated 0%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0135.png (stored 0%)
  adding: dvs/0080.png (deflated 5%)
  adding: dvs/0094.png (deflated 14%)
  adding: dvs/0090.png (deflated 14%)
  adding: dvs/0203.png (deflated 1%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (stored 0%)
  adding: dvs/0024.png (deflated 11%)
  adding: dvs/0061.png (deflated 3%)
  adding: dvs/0039.png (deflated 14%)
  adding: dvs/0101.png (stored 0%)
  adding: dvs/0152.png (deflated 24%)
  adding: dvs/0097.png (deflated 20%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (deflated 16%)
  adding: dvs/0070.png (stored 0%)
  adding: dvs/0129.png (deflated 0%)
  adding: dvs/0206.png (deflated 1%)
  adding: dvs/0037.png (deflated 20%)
  adding: dvs/0073.png (stored 0%)
  adding: dvs/0116.png (deflated 2%)
  adding: dvs/0185.png (stored 0%)
  adding: dvs/0021.png (deflated 1%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0015.png (stored 0%)
  adding: dvs/0166.png (stored 0%)
  adding: dvs/0146.png (deflated 15%)
  adding: dvs/0121.png (deflated 3%)
  adding: dvs/0027.png (deflated 12%)
  adding: dvs/0040.png (deflated 1%)
  adding: dvs/0074.png (stored 0%)
  adding: dvs/0149.png (deflated 16%)
  adding: dvs/0096.png (deflated 22%)
  adding: dvs/0068.png (deflated 1%)
  adding: dvs/0181.png (deflated 0%)
  adding: dvs/0180.png (deflated 2%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (deflated 1%)
  adding: dvs/0078.png (stored 0%)
  adding: dvs/0125.png (deflated 9%)
  adding: dvs/0127.png (deflated 5%)
  adding: dvs/0099.png (deflated 23%)
  adding: dvs/0194.png (stored 0%)
  adding: dvs/0008.png (deflated 12%)
  adding: dvs/0028.png (deflated 11%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (deflated 12%)
  adding: dvs/0118.png (deflated 3%)
  adding: dvs/0103.png (stored 0%)
  adding: dvs/0092.png (deflated 15%)
  adding: dvs/0012.png (stored 0%)
  adding: dvs/0133.png (stored 0%)
  adding: dvs/0165.png (stored 0%)
  adding: dvs/0031.png (deflated 12%)
  adding: dvs/0064.png (deflated 4%)
  adding: dvs/0155.png (deflated 21%)
  adding: dvs/0193.png (stored 0%)
  adding: dvs/0055.png (deflated 1%)
  adding: dvs/0195.png (stored 0%)
  adding: dvs/0144.png (deflated 13%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0016.png (stored 0%)
  adding: dvs/0202.png (deflated 0%)
  adding: dvs/0208.png (deflated 9%)
  adding: dvs/0114.png (stored 0%)
  adding: dvs/0107.png (stored 0%)
  adding: dvs/0123.png (deflated 5%)
  adding: dvs/0109.png (stored 0%)
  adding: dvs/0189.png (deflated 3%)
  adding: dvs/0025.png (deflated 7%)
  adding: dvs/0085.png (deflated 5%)
  adding: dvs/0058.png (deflated 0%)
  adding: dvs/0153.png (deflated 20%)
  adding: dvs/0139.png (deflated 4%)
  adding: dvs/0174.png (deflated 1%)
  adding: dvs/0192.png (stored 0%)
  adding: dvs/0169.png (stored 0%)
  adding: dvs/0098.png (deflated 17%)
  adding: dvs/0048.png (stored 0%)
  adding: dvs/0089.png (deflated 16%)
  adding: dvs/0122.png (deflated 1%)
  adding: dvs/0002.png (deflated 51%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (deflated 0%)
  adding: dvs/0176.png (deflated 0%)
  adding: dvs/0136.png (stored 0%)
  adding: dvs/0005.png (deflated 36%)
  adding: dvs/0023.png (deflated 8%)
  adding: dvs/0102.png (stored 0%)
  adding: dvs/0124.png (deflated 8%)
  adding: dvs/0204.png (deflated 0%)
  adding: dvs/0087.png (deflated 11%)
  adding: dvs/0179.png (deflated 1%)
  adding: dvs/0173.png (deflated 1%)
  adding: dvs/0186.png (stored 0%)
  adding: dvs/0131.png (stored 0%)
  adding: dvs/0119.png (deflated 1%)
  adding: dvs/0083.png (deflated 10%)
  adding: dvs/0019.png (deflated 1%)
  adding: dvs/0014.png (stored 0%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 18%)
  adding: aps/0140.png (deflated 17%)
  adding: aps/0104.png (deflated 19%)
  adding: aps/0160.png (deflated 17%)
  adding: aps/0105.png (deflated 19%)
  adding: aps/0199.png (deflated 16%)
  adding: aps/0134.png (deflated 19%)
  adding: aps/0077.png (deflated 16%)
  adding: aps/0011.png (deflated 37%)
  adding: aps/0026.png (deflated 16%)
  adding: aps/0154.png (deflated 16%)
  adding: aps/0128.png (deflated 19%)
  adding: aps/0171.png (deflated 19%)
  adding: aps/0108.png (deflated 18%)
  adding: aps/0145.png (deflated 17%)
  adding: aps/0120.png (deflated 18%)
  adding: aps/0163.png (deflated 19%)
  adding: aps/0084.png (deflated 16%)
  adding: aps/0066.png (deflated 19%)
  adding: aps/0010.png (deflated 18%)
  adding: aps/0191.png (deflated 40%)
  adding: aps/0007.png (deflated 18%)
  adding: aps/0071.png (deflated 36%)
  adding: aps/0053.png (deflated 20%)
  adding: aps/0161.png (deflated 26%)
  adding: aps/0062.png (deflated 18%)
  adding: aps/0082.png (deflated 17%)
  adding: aps/0197.png (deflated 17%)
  adding: aps/0143.png (deflated 16%)
  adding: aps/0184.png (deflated 18%)
  adding: aps/0178.png (deflated 18%)
  adding: aps/0054.png (deflated 19%)
  adding: aps/0022.png (deflated 16%)
  adding: aps/0045.png (deflated 18%)
  adding: aps/0086.png (deflated 17%)
  adding: aps/0117.png (deflated 19%)
  adding: aps/0052.png (deflated 18%)
  adding: aps/0126.png (deflated 19%)
  adding: aps/0150.png (deflated 17%)
  adding: aps/0042.png (deflated 19%)
  adding: aps/0112.png (deflated 18%)
  adding: aps/0168.png (deflated 18%)
  adding: aps/0075.png (deflated 17%)
  adding: aps/0036.png (deflated 16%)
  adding: aps/0207.png (deflated 16%)
  adding: aps/0095.png (deflated 16%)
  adding: aps/0065.png (deflated 19%)
  adding: aps/0057.png (deflated 19%)
  adding: aps/0033.png (deflated 16%)
  adding: aps/0182.png (deflated 18%)
  adding: aps/0091.png (deflated 16%)
  adding: aps/0067.png (deflated 19%)
  adding: aps/0081.png (deflated 16%)
  adding: aps/0047.png (deflated 19%)
  adding: aps/0151.png (deflated 16%)
  adding: aps/0056.png (deflated 19%)
  adding: aps/0142.png (deflated 16%)
  adding: aps/0044.png (deflated 19%)
  adding: aps/0020.png (deflated 16%)
  adding: aps/0106.png (deflated 18%)
  adding: aps/0072.png (deflated 36%)
  adding: aps/0113.png (deflated 19%)
  adding: aps/0043.png (deflated 19%)
  adding: aps/0157.png (deflated 17%)
  adding: aps/0013.png (deflated 23%)
  adding: aps/0158.png (deflated 17%)
  adding: aps/0034.png (deflated 16%)
  adding: aps/0138.png (deflated 17%)
  adding: aps/0100.png (deflated 16%)
  adding: aps/0175.png (deflated 19%)
  adding: aps/0167.png (deflated 19%)
  adding: aps/0041.png (deflated 23%)
  adding: aps/0177.png (deflated 19%)
  adding: aps/0032.png (deflated 16%)
  adding: aps/0093.png (deflated 16%)
  adding: aps/0004.png (deflated 18%)
  adding: aps/0006.png (deflated 18%)
  adding: aps/0159.png (deflated 16%)
  adding: aps/0188.png (deflated 18%)
  adding: aps/0030.png (deflated 16%)
  adding: aps/0130.png (deflated 18%)
  adding: aps/0132.png (deflated 36%)
  adding: aps/0009.png (deflated 18%)
  adding: aps/0205.png (deflated 16%)
  adding: aps/0162.png (deflated 20%)
  adding: aps/0017.png (deflated 16%)
  adding: aps/0051.png (deflated 19%)
  adding: aps/0190.png (deflated 18%)
  adding: aps/0170.png (deflated 19%)
  adding: aps/0035.png (deflated 16%)
  adding: aps/0201.png (deflated 17%)
  adding: aps/0018.png (deflated 17%)
  adding: aps/0156.png (deflated 16%)
  adding: aps/0196.png (deflated 18%)
  adding: aps/0147.png (deflated 16%)
  adding: aps/0183.png (deflated 18%)
  adding: aps/0198.png (deflated 17%)
  adding: aps/0069.png (deflated 19%)
  adding: aps/0148.png (deflated 16%)
  adding: aps/0060.png (deflated 19%)
  adding: aps/0003.png (deflated 19%)
  adding: aps/0187.png (deflated 19%)
  adding: aps/0029.png (deflated 16%)
  adding: aps/0115.png (deflated 19%)
  adding: aps/0141.png (deflated 16%)
  adding: aps/0001.png (deflated 20%)
  adding: aps/0200.png (deflated 16%)
  adding: aps/0046.png (deflated 19%)
  adding: aps/0135.png (deflated 19%)
  adding: aps/0080.png (deflated 17%)
  adding: aps/0094.png (deflated 16%)
  adding: aps/0090.png (deflated 16%)
  adding: aps/0203.png (deflated 16%)
  adding: aps/0049.png (deflated 19%)
  adding: aps/0164.png (deflated 20%)
  adding: aps/0024.png (deflated 17%)
  adding: aps/0061.png (deflated 18%)
  adding: aps/0039.png (deflated 16%)
  adding: aps/0101.png (deflated 26%)
  adding: aps/0152.png (deflated 16%)
  adding: aps/0097.png (deflated 16%)
  adding: aps/0059.png (deflated 19%)
  adding: aps/0038.png (deflated 16%)
  adding: aps/0070.png (deflated 19%)
  adding: aps/0129.png (deflated 18%)
  adding: aps/0206.png (deflated 16%)
  adding: aps/0037.png (deflated 16%)
  adding: aps/0073.png (deflated 24%)
  adding: aps/0116.png (deflated 19%)
  adding: aps/0185.png (deflated 18%)
  adding: aps/0021.png (deflated 16%)
  adding: aps/0137.png (deflated 16%)
  adding: aps/0015.png (deflated 18%)
  adding: aps/0166.png (deflated 19%)
  adding: aps/0146.png (deflated 16%)
  adding: aps/0121.png (deflated 18%)
  adding: aps/0027.png (deflated 16%)
  adding: aps/0040.png (deflated 16%)
  adding: aps/0074.png (deflated 19%)
  adding: aps/0149.png (deflated 17%)
  adding: aps/0096.png (deflated 16%)
  adding: aps/0068.png (deflated 19%)
  adding: aps/0181.png (deflated 18%)
  adding: aps/0180.png (deflated 19%)
  adding: aps/0076.png (deflated 17%)
  adding: aps/0079.png (deflated 16%)
  adding: aps/0078.png (deflated 17%)
  adding: aps/0125.png (deflated 19%)
  adding: aps/0127.png (deflated 18%)
  adding: aps/0099.png (deflated 17%)
  adding: aps/0194.png (deflated 20%)
  adding: aps/0008.png (deflated 19%)
  adding: aps/0028.png (deflated 16%)
  adding: aps/0050.png (deflated 19%)
  adding: aps/0088.png (deflated 16%)
  adding: aps/0118.png (deflated 19%)
  adding: aps/0103.png (deflated 21%)
  adding: aps/0092.png (deflated 16%)
  adding: aps/0012.png (deflated 36%)
  adding: aps/0133.png (deflated 25%)
  adding: aps/0165.png (deflated 19%)
  adding: aps/0031.png (deflated 16%)
  adding: aps/0064.png (deflated 18%)
  adding: aps/0155.png (deflated 16%)
  adding: aps/0193.png (deflated 24%)
  adding: aps/0055.png (deflated 19%)
  adding: aps/0195.png (deflated 18%)
  adding: aps/0144.png (deflated 16%)
  adding: aps/0110.png (deflated 18%)
  adding: aps/0016.png (deflated 17%)
  adding: aps/0202.png (deflated 16%)
  adding: aps/0208.png (deflated 16%)
  adding: aps/0114.png (deflated 18%)
  adding: aps/0107.png (deflated 19%)
  adding: aps/0123.png (deflated 19%)
  adding: aps/0109.png (deflated 18%)
  adding: aps/0189.png (deflated 19%)
  adding: aps/0025.png (deflated 16%)
  adding: aps/0085.png (deflated 16%)
  adding: aps/0058.png (deflated 18%)
  adding: aps/0153.png (deflated 16%)
  adding: aps/0139.png (deflated 17%)
  adding: aps/0174.png (deflated 19%)
  adding: aps/0192.png (deflated 35%)
  adding: aps/0169.png (deflated 18%)

'The chosen video file: /content/video/white_1hz.MOV'

FPS: 29.970617042115574
Frame count: 204
Duration: 6.81 sec
The Final v2e command:

'v2e -i /content/video/white_1hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/white_1hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/white_1hz.MOV
INFO:v2e:Input video frame rate 29.970617042115574Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/white_1hz.MOV has total 204 frames with total duration 6.77s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 204 frames 0 to 203
(From 0.0s to 6.766666666666667s, duration 6.766666666666667s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 203.0 frames with duration 6.77s and playback duration 6.77s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 203 from video input
INFO:v2e:Input video /content/video/white_1hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 204 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/204 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 204/204 [00:06<00:00, 30.70fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpsr5_wdxd
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 26 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/26 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 120
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/26 [00:33<13:51, 33.28s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 185
slomo-interp:   8% 2/26 [01:23<17:20, 43.37s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 99
slomo-interp: 100% 26/26 [13:01<00:00, 30.05s/ batch of 8 fr]
write-orig-avi: 100% 204/204 [00:00<00:00, 874.16fr/s]
write-slomo-vid: 100% 23071/23071 [00:54<00:00, 425.05fr/s]
INFO:v2ecore.slomo:Wrote 23071 frames and returning 23071 frame times.
Average upsampling factor=112.0
INFO:v2e:SloMo average upsampling factor=112.00; average DVS timestamp resolution=297.62us
INFO:v2e:*** Stage 3/3: emulating DVS events from 23071 frames
dvs:   0% 9/23071 [00:00<08:48, 43.60fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:  16% 3634/23071 [00:57<06:05, 53.14fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,641 at t=0.8810s
WARNING:v2ecore.emulator:no signal events generated for frame #3,650 at t=0.8828s
dvs:  16% 3650/23071 [00:57<05:05, 63.53fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,659 at t=0.8846s
dvs:  16% 3735/23071 [00:58<03:38, 88.67fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,738 at t=0.9003s
WARNING:v2ecore.emulator:no signal events generated for frame #3,739 at t=0.9005s
WARNING:v2ecore.emulator:no signal events generated for frame #3,743 at t=0.9013s
WARNING:v2ecore.emulator:no signal events generated for frame #3,745 at t=0.9017s
WARNING:v2ecore.emulator:no signal events generated for frame #3,747 at t=0.9021s
dvs:  16% 3759/23071 [00:58<04:37, 69.60fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,765 at t=0.9057s
dvs:  16% 3770/23071 [00:59<04:40, 68.88fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,779 at t=0.9084s
dvs:  16% 3781/23071 [00:59<04:09, 77.38fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,785 at t=0.9096s
dvs:  16% 3794/23071 [00:59<03:42, 86.62fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,796 at t=0.9118s
WARNING:v2ecore.emulator:no signal events generated for frame #3,797 at t=0.9120s
dvs:  17% 3817/23071 [00:59<03:19, 96.66fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,819 at t=0.9164s
WARNING:v2ecore.emulator:no signal events generated for frame #3,821 at t=0.9168s
dvs:  17% 3828/23071 [00:59<03:50, 83.43fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,830 at t=0.9186s
WARNING:v2ecore.emulator:no signal events generated for frame #3,831 at t=0.9188s
WARNING:v2ecore.emulator:no signal events generated for frame #3,834 at t=0.9193s
WARNING:v2ecore.emulator:no signal events generated for frame #3,835 at t=0.9195s
WARNING:v2ecore.emulator:no signal events generated for frame #3,837 at t=0.9199s
dvs:  17% 3838/23071 [00:59<03:47, 84.39fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,839 at t=0.9203s
WARNING:v2ecore.emulator:no signal events generated for frame #3,841 at t=0.9207s
WARNING:v2ecore.emulator:no signal events generated for frame #3,844 at t=0.9213s
WARNING:v2ecore.emulator:no signal events generated for frame #3,845 at t=0.9215s
WARNING:v2ecore.emulator:no signal events generated for frame #3,848 at t=0.9221s
dvs:  17% 3850/23071 [00:59<03:28, 92.39fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,855 at t=0.9235s
WARNING:v2ecore.emulator:no signal events generated for frame #3,857 at t=0.9239s
WARNING:v2ecore.emulator:no signal events generated for frame #3,858 at t=0.9241s
WARNING:v2ecore.emulator:no signal events generated for frame #3,860 at t=0.9245s
dvs:  17% 3899/23071 [01:00<03:36, 88.68fr/s] WARNING:v2ecore.emulator:no signal events generated for frame #3,906 at t=0.9336s
WARNING:v2ecore.emulator:no signal events generated for frame #3,908 at t=0.9340s
WARNING:v2ecore.emulator:no signal events generated for frame #3,909 at t=0.9342s
dvs:  17% 3910/23071 [01:00<03:24, 93.86fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,912 at t=0.9348s
WARNING:v2ecore.emulator:no signal events generated for frame #3,914 at t=0.9352s
WARNING:v2ecore.emulator:no signal events generated for frame #3,915 at t=0.9354s
dvs:  17% 3920/23071 [01:00<04:40, 68.27fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,921 at t=0.9366s
WARNING:v2ecore.emulator:no signal events generated for frame #3,924 at t=0.9372s
WARNING:v2ecore.emulator:no signal events generated for frame #3,927 at t=0.9378s
WARNING:v2ecore.emulator:no signal events generated for frame #3,928 at t=0.9380s
dvs:  17% 3930/23071 [01:00<04:22, 72.80fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,936 at t=0.9396s
dvs:  17% 3939/23071 [01:01<04:10, 76.35fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,942 at t=0.9408s
WARNING:v2ecore.emulator:no signal events generated for frame #3,945 at t=0.9414s
WARNING:v2ecore.emulator:no signal events generated for frame #3,946 at t=0.9416s
WARNING:v2ecore.emulator:no signal events generated for frame #3,948 at t=0.9420s
WARNING:v2ecore.emulator:no signal events generated for frame #3,952 at t=0.9428s
dvs:  17% 3954/23071 [01:01<03:32, 89.80fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,955 at t=0.9434s
WARNING:v2ecore.emulator:no signal events generated for frame #3,956 at t=0.9436s
WARNING:v2ecore.emulator:no signal events generated for frame #3,958 at t=0.9440s
WARNING:v2ecore.emulator:no signal events generated for frame #3,962 at t=0.9447s
WARNING:v2ecore.emulator:no signal events generated for frame #3,963 at t=0.9449s
dvs:  17% 3967/23071 [01:01<03:12, 99.30fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,969 at t=0.9461s
WARNING:v2ecore.emulator:no signal events generated for frame #3,970 at t=0.9463s
WARNING:v2ecore.emulator:no signal events generated for frame #3,974 at t=0.9471s
dvs:  17% 3978/23071 [01:01<03:10, 100.18fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #3,979 at t=0.9481s
WARNING:v2ecore.emulator:no signal events generated for frame #3,985 at t=0.9493s
WARNING:v2ecore.emulator:no signal events generated for frame #3,993 at t=0.9509s
WARNING:v2ecore.emulator:no signal events generated for frame #3,995 at t=0.9513s
WARNING:v2ecore.emulator:no signal events generated for frame #3,997 at t=0.9517s
dvs:  17% 4002/23071 [01:01<02:35, 122.74fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,006 at t=0.9535s
WARNING:v2ecore.emulator:no signal events generated for frame #4,009 at t=0.9541s
WARNING:v2ecore.emulator:no signal events generated for frame #4,014 at t=0.9551s
WARNING:v2ecore.emulator:no signal events generated for frame #4,016 at t=0.9555s
WARNING:v2ecore.emulator:no signal events generated for frame #4,018 at t=0.9559s
dvs:  17% 4018/23071 [01:01<02:34, 123.46fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,028 at t=0.9578s
dvs:  17% 4031/23071 [01:01<02:35, 122.28fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,039 at t=0.9600s
dvs:  18% 4044/23071 [01:01<03:08, 100.69fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,045 at t=0.9612s
WARNING:v2ecore.emulator:no signal events generated for frame #4,048 at t=0.9618s
WARNING:v2ecore.emulator:no signal events generated for frame #4,052 at t=0.9626s
dvs:  18% 4055/23071 [01:02<03:05, 102.68fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,064 at t=0.9650s
dvs:  30% 6978/23071 [01:51<06:44, 39.78fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,979 at t=1.9006s
dvs:  48% 11170/23071 [02:59<03:02, 65.22fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,177 at t=3.1754s
dvs:  49% 11236/23071 [03:00<02:23, 82.42fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,241 at t=3.1872s
WARNING:v2ecore.emulator:no signal events generated for frame #11,249 at t=3.1886s
WARNING:v2ecore.emulator:no signal events generated for frame #11,250 at t=3.1888s
dvs:  49% 11258/23071 [03:00<01:50, 107.13fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,268 at t=3.1921s
dvs:  49% 11269/23071 [03:00<01:51, 105.38fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #11,275 at t=3.1934s
dvs:  55% 12794/23071 [03:30<03:31, 48.57fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,799 at t=4.0363s
WARNING:v2ecore.emulator:no signal events generated for frame #12,801 at t=4.0367s
WARNING:v2ecore.emulator:no signal events generated for frame #12,806 at t=4.0376s
dvs:  56% 12818/23071 [03:30<02:46, 61.51fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,819 at t=4.0399s
WARNING:v2ecore.emulator:no signal events generated for frame #12,820 at t=4.0401s
WARNING:v2ecore.emulator:no signal events generated for frame #12,822 at t=4.0405s
WARNING:v2ecore.emulator:no signal events generated for frame #12,823 at t=4.0407s
WARNING:v2ecore.emulator:no signal events generated for frame #12,826 at t=4.0412s
dvs:  56% 12826/23071 [03:30<02:46, 61.39fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,828 at t=4.0416s
WARNING:v2ecore.emulator:no signal events generated for frame #12,833 at t=4.0425s
WARNING:v2ecore.emulator:no signal events generated for frame #12,839 at t=4.0436s
WARNING:v2ecore.emulator:no signal events generated for frame #12,841 at t=4.0439s
WARNING:v2ecore.emulator:no signal events generated for frame #12,846 at t=4.0448s
WARNING:v2ecore.emulator:no signal events generated for frame #12,847 at t=4.0450s
WARNING:v2ecore.emulator:no signal events generated for frame #12,849 at t=4.0454s
WARNING:v2ecore.emulator:no signal events generated for frame #12,850 at t=4.0456s
WARNING:v2ecore.emulator:no signal events generated for frame #12,851 at t=4.0457s
WARNING:v2ecore.emulator:no signal events generated for frame #12,852 at t=4.0459s
dvs:  56% 12852/23071 [03:31<01:37, 105.04fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #12,853 at t=4.0461s
WARNING:v2ecore.emulator:no signal events generated for frame #12,855 at t=4.0465s
WARNING:v2ecore.emulator:no signal events generated for frame #12,856 at t=4.0466s
WARNING:v2ecore.emulator:no signal events generated for frame #12,857 at t=4.0468s
WARNING:v2ecore.emulator:no signal events generated for frame #12,858 at t=4.0470s
WARNING:v2ecore.emulator:no signal events generated for frame #12,860 at t=4.0474s
dvs: 100% 23071/23071 [06:21<00:00, 60.52fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 202 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 204 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 23071 frames
INFO:v2e:generated total 23.41M events (11.61M on, 11.79M off)
INFO:v2e:Avg event rate for N=89960 px and total time =6.767 s
	Total: 3.46MHz (1.72MHz on, 1.74MHz off)
	Per pixel:  38.45Hz (19.08Hz on, 19.37Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 408 frames in 1.23ks (3s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 202 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 204 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 23071 frames
Total events: 23,407,223
  Written 5,000,000/23,407,223
  Written 10,000,000/23,407,223
  Written 15,000,000/23,407,223
  Written 20,000,000/23,407,223
  Written 23,407,223/23,407,223
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 204
Output folder: /content/v2e-output/aps
APS frames found: 204
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/204 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:06.80, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:06.80, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x5adc05f73840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x5adc05f7ca80] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x5adc0629e140] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5adc0629e140] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5adc0629e140] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  204 fps= 46 q=-1.0 Lsize=    3552kB time=00:00:06.70 bitrate=4343.1kbits/s speed=1.51x
video:3549kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.077175%
[libx264 @ 0x5adc0629e140] frame I:23    Avg QP:26.20  size: 39474
[libx264 @ 0x5adc0629e140] frame P:95    Avg QP:29.09  size: 20564
[libx264 @ 0x5adc0629e140] frame B:86    Avg QP:30.21  size:  8981
[libx264 @ 0x5adc0629e140] consecutive B-frames: 40.7%  6.9%  7.4% 45.1%
[libx264 @ 0x5adc0629e140] mb I  I16..4:  2.3% 52.2% 45.6%
[libx264 @ 0x5adc0629e140] mb P  I16..4:  8.0% 30.2% 28.2%  P16..4: 14.2%  2.8%  2.2%  0.0%  0.0%    skip:14.3%
[libx264 @ 0x5adc0629e140] mb B  I16..4:  7.1%  3.0%  6.6%  B16..8: 27.5%  5.2%  2.8%  direct: 3.3%  skip:44.5%  L0:40.4% L1:56.3% BI: 3.3%
[libx264 @ 0x5adc0629e140] 8x8 transform intra:43.0% inter:50.5%
[libx264 @ 0x5adc0629e140] coded y,uvDC,uvAC intra: 68.8% 46.5% 44.3% inter: 21.8% 6.3% 2.7%
[libx264 @ 0x5adc0629e140] i16 v,h,dc,p: 38% 14% 44%  4%
[libx264 @ 0x5adc0629e140] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 49% 10% 28%  2%  2%  3%  1%  3%  2%
[libx264 @ 0x5adc0629e140] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 12% 31%  6%  5%  5%  4%  5%  4%
[libx264 @ 0x5adc0629e140] i8c dc,h,v,p: 77%  6% 13%  4%
[libx264 @ 0x5adc0629e140] Weighted P-Frames: Y:24.2% UV:22.1%
[libx264 @ 0x5adc0629e140] ref P L0: 68.9% 13.0% 11.0%  6.5%  0.6%
[libx264 @ 0x5adc0629e140] ref B L0: 81.6% 15.6%  2.8%
[libx264 @ 0x5adc0629e140] ref B L1: 89.7% 10.3%
[libx264 @ 0x5adc0629e140] kb/s:4275.19
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (stored 0%)
  adding: dvs/0140.png (stored 0%)
  adding: dvs/0104.png (deflated 7%)
  adding: dvs/0160.png (deflated 0%)
  adding: dvs/0105.png (stored 0%)
  adding: dvs/0199.png (stored 0%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0077.png (stored 0%)
  adding: dvs/0011.png (stored 0%)
  adding: dvs/0026.png (stored 0%)
  adding: dvs/0154.png (stored 0%)
  adding: dvs/0128.png (stored 0%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0120.png (deflated 9%)
  adding: dvs/0163.png (deflated 1%)
  adding: dvs/0084.png (stored 0%)
  adding: dvs/0066.png (stored 0%)
  adding: dvs/0010.png (stored 0%)
  adding: dvs/0191.png (stored 0%)
  adding: dvs/0007.png (stored 0%)
  adding: dvs/0071.png (deflated 0%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (stored 0%)
  adding: dvs/0062.png (stored 0%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0197.png (deflated 70%)
  adding: dvs/0143.png (stored 0%)
  adding: dvs/0184.png (stored 0%)
  adding: dvs/0178.png (deflated 0%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (stored 0%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (stored 0%)
  adding: dvs/0126.png (stored 0%)
  adding: dvs/0150.png (deflated 9%)
  adding: dvs/0042.png (stored 0%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (deflated 5%)
  adding: dvs/0075.png (stored 0%)
  adding: dvs/0036.png (stored 0%)
  adding: dvs/0095.png (stored 0%)
  adding: dvs/0065.png (stored 0%)
  adding: dvs/0057.png (deflated 1%)
  adding: dvs/0033.png (stored 0%)
  adding: dvs/0182.png (stored 0%)
  adding: dvs/0091.png (stored 0%)
  adding: dvs/0067.png (stored 0%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0047.png (stored 0%)
  adding: dvs/0151.png (stored 0%)
  adding: dvs/0056.png (stored 0%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (stored 0%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0072.png (deflated 1%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (stored 0%)
  adding: dvs/0013.png (stored 0%)
  adding: dvs/0158.png (stored 0%)
  adding: dvs/0034.png (stored 0%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (deflated 1%)
  adding: dvs/0175.png (stored 0%)
  adding: dvs/0167.png (deflated 20%)
  adding: dvs/0041.png (deflated 0%)
  adding: dvs/0177.png (stored 0%)
  adding: dvs/0032.png (stored 0%)
  adding: dvs/0093.png (stored 0%)
  adding: dvs/0004.png (stored 0%)
  adding: dvs/0006.png (stored 0%)
  adding: dvs/0159.png (deflated 0%)
  adding: dvs/0188.png (stored 0%)
  adding: dvs/0030.png (stored 0%)
  adding: dvs/0130.png (stored 0%)
  adding: dvs/0132.png (stored 0%)
  adding: dvs/0009.png (stored 0%)
  adding: dvs/0162.png (deflated 8%)
  adding: dvs/0017.png (stored 0%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (stored 0%)
  adding: dvs/0170.png (deflated 0%)
  adding: dvs/0035.png (stored 0%)
  adding: dvs/0201.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (stored 0%)
  adding: dvs/0196.png (stored 0%)
  adding: dvs/0147.png (stored 0%)
  adding: dvs/0183.png (stored 0%)
  adding: dvs/0198.png (deflated 20%)
  adding: dvs/0069.png (stored 0%)
  adding: dvs/0148.png (deflated 10%)
  adding: dvs/0060.png (stored 0%)
  adding: dvs/0003.png (stored 0%)
  adding: dvs/0187.png (stored 0%)
  adding: dvs/0029.png (deflated 5%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0001.png (stored 0%)
  adding: dvs/0200.png (stored 0%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0135.png (deflated 0%)
  adding: dvs/0080.png (stored 0%)
  adding: dvs/0094.png (stored 0%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0203.png (stored 0%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (deflated 5%)
  adding: dvs/0024.png (stored 0%)
  adding: dvs/0061.png (stored 0%)
  adding: dvs/0039.png (stored 0%)
  adding: dvs/0101.png (deflated 10%)
  adding: dvs/0152.png (stored 0%)
  adding: dvs/0097.png (stored 0%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (stored 0%)
  adding: dvs/0070.png (stored 0%)
  adding: dvs/0129.png (stored 0%)
  adding: dvs/0037.png (stored 0%)
  adding: dvs/0073.png (stored 0%)
  adding: dvs/0116.png (stored 0%)
  adding: dvs/0185.png (stored 0%)
  adding: dvs/0021.png (stored 0%)
  adding: dvs/0137.png (stored 0%)
  adding: dvs/0015.png (stored 0%)
  adding: dvs/0166.png (stored 0%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0121.png (stored 0%)
  adding: dvs/0027.png (stored 0%)
  adding: dvs/0040.png (stored 0%)
  adding: dvs/0074.png (stored 0%)
  adding: dvs/0149.png (deflated 4%)
  adding: dvs/0096.png (stored 0%)
  adding: dvs/0068.png (stored 0%)
  adding: dvs/0181.png (stored 0%)
  adding: dvs/0180.png (deflated 0%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (stored 0%)
  adding: dvs/0078.png (stored 0%)
  adding: dvs/0125.png (stored 0%)
  adding: dvs/0127.png (stored 0%)
  adding: dvs/0099.png (stored 0%)
  adding: dvs/0194.png (stored 0%)
  adding: dvs/0008.png (stored 0%)
  adding: dvs/0028.png (deflated 1%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (deflated 9%)
  adding: dvs/0103.png (deflated 4%)
  adding: dvs/0092.png (stored 0%)
  adding: dvs/0012.png (stored 0%)
  adding: dvs/0133.png (stored 0%)
  adding: dvs/0165.png (deflated 7%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (stored 0%)
  adding: dvs/0155.png (stored 0%)
  adding: dvs/0193.png (stored 0%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (stored 0%)
  adding: dvs/0144.png (stored 0%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0016.png (deflated 13%)
  adding: dvs/0202.png (stored 0%)
  adding: dvs/0114.png (stored 0%)
  adding: dvs/0107.png (stored 0%)
  adding: dvs/0123.png (stored 0%)
  adding: dvs/0109.png (stored 0%)
  adding: dvs/0189.png (stored 0%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0058.png (stored 0%)
  adding: dvs/0153.png (stored 0%)
  adding: dvs/0139.png (stored 0%)
  adding: dvs/0174.png (stored 0%)
  adding: dvs/0192.png (deflated 2%)
  adding: dvs/0169.png (stored 0%)
  adding: dvs/0098.png (stored 0%)
  adding: dvs/0048.png (deflated 13%)
  adding: dvs/0089.png (deflated 0%)
  adding: dvs/0122.png (stored 0%)
  adding: dvs/0002.png (stored 0%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (stored 0%)
  adding: dvs/0176.png (stored 0%)
  adding: dvs/0136.png (stored 0%)
  adding: dvs/0005.png (stored 0%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (deflated 8%)
  adding: dvs/0124.png (stored 0%)
  adding: dvs/0204.png (stored 0%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0173.png (stored 0%)
  adding: dvs/0186.png (stored 0%)
  adding: dvs/0131.png (stored 0%)
  adding: dvs/0119.png (deflated 4%)
  adding: dvs/0083.png (stored 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (stored 0%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 31%)
  adding: aps/0140.png (deflated 19%)
  adding: aps/0104.png (deflated 17%)
  adding: aps/0160.png (deflated 16%)
  adding: aps/0105.png (deflated 17%)
  adding: aps/0199.png (deflated 19%)
  adding: aps/0134.png (deflated 17%)
  adding: aps/0077.png (deflated 25%)
  adding: aps/0011.png (deflated 17%)
  adding: aps/0026.png (deflated 18%)
  adding: aps/0154.png (deflated 24%)
  adding: aps/0128.png (deflated 17%)
  adding: aps/0171.png (deflated 18%)
  adding: aps/0108.png (deflated 22%)
  adding: aps/0145.png (deflated 18%)
  adding: aps/0120.png (deflated 19%)
  adding: aps/0163.png (deflated 16%)
  adding: aps/0084.png (deflated 19%)
  adding: aps/0066.png (deflated 17%)
  adding: aps/0010.png (deflated 17%)
  adding: aps/0191.png (deflated 16%)
  adding: aps/0007.png (deflated 17%)
  adding: aps/0071.png (deflated 17%)
  adding: aps/0053.png (deflated 19%)
  adding: aps/0161.png (deflated 16%)
  adding: aps/0062.png (deflated 29%)
  adding: aps/0082.png (deflated 18%)
  adding: aps/0197.png (deflated 23%)
  adding: aps/0143.png (deflated 19%)
  adding: aps/0184.png (deflated 31%)
  adding: aps/0178.png (deflated 18%)
  adding: aps/0054.png (deflated 19%)
  adding: aps/0022.png (deflated 19%)
  adding: aps/0045.png (deflated 16%)
  adding: aps/0086.png (deflated 18%)
  adding: aps/0117.png (deflated 18%)
  adding: aps/0052.png (deflated 19%)
  adding: aps/0126.png (deflated 17%)
  adding: aps/0150.png (deflated 19%)
  adding: aps/0042.png (deflated 16%)
  adding: aps/0112.png (deflated 19%)
  adding: aps/0168.png (deflated 19%)
  adding: aps/0075.png (deflated 16%)
  adding: aps/0036.png (deflated 17%)
  adding: aps/0095.png (deflated 19%)
  adding: aps/0065.png (deflated 19%)
  adding: aps/0057.png (deflated 19%)
  adding: aps/0033.png (deflated 31%)
  adding: aps/0182.png (deflated 37%)
  adding: aps/0091.png (deflated 19%)
  adding: aps/0067.png (deflated 17%)
  adding: aps/0081.png (deflated 19%)
  adding: aps/0047.png (deflated 26%)
  adding: aps/0151.png (deflated 19%)
  adding: aps/0056.png (deflated 19%)
  adding: aps/0142.png (deflated 19%)
  adding: aps/0044.png (deflated 16%)
  adding: aps/0020.png (deflated 19%)
  adding: aps/0106.png (deflated 16%)
  adding: aps/0072.png (deflated 17%)
  adding: aps/0113.png (deflated 19%)
  adding: aps/0043.png (deflated 17%)
  adding: aps/0157.png (deflated 16%)
  adding: aps/0013.png (deflated 17%)
  adding: aps/0158.png (deflated 17%)
  adding: aps/0034.png (deflated 23%)
  adding: aps/0138.png (deflated 20%)
  adding: aps/0100.png (deflated 16%)
  adding: aps/0175.png (deflated 19%)
  adding: aps/0167.png (deflated 24%)
  adding: aps/0041.png (deflated 16%)
  adding: aps/0177.png (deflated 19%)
  adding: aps/0032.png (deflated 32%)
  adding: aps/0093.png (deflated 36%)
  adding: aps/0004.png (deflated 21%)
  adding: aps/0006.png (deflated 19%)
  adding: aps/0159.png (deflated 17%)
  adding: aps/0188.png (deflated 16%)
  adding: aps/0030.png (deflated 19%)
  adding: aps/0130.png (deflated 16%)
  adding: aps/0132.png (deflated 17%)
  adding: aps/0009.png (deflated 17%)
  adding: aps/0162.png (deflated 17%)
  adding: aps/0017.png (deflated 25%)
  adding: aps/0051.png (deflated 18%)
  adding: aps/0190.png (deflated 16%)
  adding: aps/0170.png (deflated 18%)
  adding: aps/0035.png (deflated 18%)
  adding: aps/0201.png (deflated 19%)
  adding: aps/0018.png (deflated 20%)
  adding: aps/0156.png (deflated 17%)
  adding: aps/0196.png (deflated 16%)
  adding: aps/0147.png (deflated 18%)
  adding: aps/0183.png (deflated 34%)
  adding: aps/0198.png (deflated 23%)
  adding: aps/0069.png (deflated 16%)
  adding: aps/0148.png (deflated 19%)
  adding: aps/0060.png (deflated 18%)
  adding: aps/0003.png (deflated 34%)
  adding: aps/0187.png (deflated 17%)
  adding: aps/0029.png (deflated 18%)
  adding: aps/0115.png (deflated 18%)
  adding: aps/0141.png (deflated 19%)
  adding: aps/0001.png (deflated 19%)
  adding: aps/0200.png (deflated 19%)
  adding: aps/0046.png (deflated 16%)
  adding: aps/0135.png (deflated 17%)
  adding: aps/0080.png (deflated 20%)
  adding: aps/0094.png (deflated 21%)
  adding: aps/0090.png (deflated 19%)
  adding: aps/0203.png (deflated 18%)
  adding: aps/0049.png (deflated 19%)
  adding: aps/0164.png (deflated 16%)
  adding: aps/0024.png (deflated 19%)
  adding: aps/0061.png (deflated 21%)
  adding: aps/0039.png (deflated 17%)
  adding: aps/0101.png (deflated 16%)
  adding: aps/0152.png (deflated 36%)
  adding: aps/0097.png (deflated 18%)
  adding: aps/0059.png (deflated 18%)
  adding: aps/0038.png (deflated 17%)
  adding: aps/0070.png (deflated 17%)
  adding: aps/0129.png (deflated 17%)
  adding: aps/0037.png (deflated 17%)
  adding: aps/0073.png (deflated 16%)
  adding: aps/0116.png (deflated 18%)
  adding: aps/0185.png (deflated 18%)
  adding: aps/0021.png (deflated 19%)
  adding: aps/0137.png (deflated 26%)
  adding: aps/0015.png (deflated 16%)
  adding: aps/0166.png (deflated 17%)
  adding: aps/0146.png (deflated 18%)
  adding: aps/0121.png (deflated 19%)
  adding: aps/0027.png (deflated 18%)
  adding: aps/0040.png (deflated 16%)
  adding: aps/0074.png (deflated 17%)
  adding: aps/0149.png (deflated 18%)
  adding: aps/0096.png (deflated 17%)
  adding: aps/0068.png (deflated 16%)
  adding: aps/0181.png (deflated 19%)
  adding: aps/0180.png (deflated 19%)
  adding: aps/0076.png (deflated 16%)
  adding: aps/0079.png (deflated 20%)
  adding: aps/0078.png (deflated 20%)
  adding: aps/0125.png (deflated 19%)
  adding: aps/0127.png (deflated 17%)
  adding: aps/0099.png (deflated 16%)
  adding: aps/0194.png (deflated 17%)
  adding: aps/0008.png (deflated 17%)
  adding: aps/0028.png (deflated 18%)
  adding: aps/0050.png (deflated 19%)
  adding: aps/0088.png (deflated 18%)
  adding: aps/0118.png (deflated 18%)
  adding: aps/0103.png (deflated 17%)
  adding: aps/0092.png (deflated 39%)
  adding: aps/0012.png (deflated 16%)
  adding: aps/0133.png (deflated 16%)
  adding: aps/0165.png (deflated 17%)
  adding: aps/0031.png (deflated 19%)
  adding: aps/0064.png (deflated 20%)
  adding: aps/0155.png (deflated 18%)
  adding: aps/0193.png (deflated 17%)
  adding: aps/0055.png (deflated 18%)
  adding: aps/0195.png (deflated 16%)
  adding: aps/0144.png (deflated 18%)
  adding: aps/0110.png (deflated 19%)
  adding: aps/0016.png (deflated 17%)
  adding: aps/0202.png (deflated 19%)
  adding: aps/0114.png (deflated 18%)
  adding: aps/0107.png (deflated 24%)
  adding: aps/0123.png (deflated 31%)
  adding: aps/0109.png (deflated 19%)
  adding: aps/0189.png (deflated 16%)
  adding: aps/0025.png (deflated 19%)
  adding: aps/0085.png (deflated 18%)
  adding: aps/0058.png (deflated 18%)
  adding: aps/0153.png (deflated 36%)
  adding: aps/0139.png (deflated 19%)
  adding: aps/0174.png (deflated 19%)
  adding: aps/0192.png (deflated 17%)
  adding: aps/0169.png (deflated 19%)
  adding: aps/0098.png (deflated 17%)
  adding: aps/0048.png (deflated 24%)
  adding: aps/0089.png (deflated 18%)
  adding: aps/0122.png (deflated 36%)
  adding: aps/0002.png (deflated 36%)
  adding: aps/0111.png (deflated 18%)
  adding: aps/0172.png (deflated 19%)
  adding: aps/0176.png (deflated 18%)
  adding: aps/0136.png (deflated 17%)
  adding: aps/0005.png (deflated 20%)
  adding: aps/0023.png (deflated 19%)
  adding: aps/0102.png (deflated 17%)
  adding: aps/0124.png (deflated 24%)
  adding: aps/0204.png (deflated 18%)

'The chosen video file: /content/video/white_2hz.MOV'

FPS: 29.977628635346758
Frame count: 201
Duration: 6.71 sec
The Final v2e command:

'v2e -i /content/video/white_2hz.MOV -o /content/v2e-output --overwrite --unique_output_folder false --davis_output --dvs_h5 events.h5 --dvs_aedat2 None --dvs_text None --no_preview --dvs_exposure duration 0.033333 --input_frame_rate 30 --input_slowmotion_factor 1 --slomo_model /content/v2e/input/SuperSloMo39.ckpt --auto_timestamp_resolution true --pos_thres 0.2 --neg_thres 0.2 --sigma_thres 0.02 --cutoff_hz 0 --leak_rate_hz 0 --shot_noise_rate_hz 0 --dvs346'

INFO:v2e:torch device is cuda
INFO:v2e:No module named 'gooey': Gooey GUI builder not available, will use command line arguments.
Install with 'pip install Gooey if you want a no-arg GUI to invoke v2e'. See README
INFO:v2e:name 'Gooey' is not defined: Gooey package GUI not available, using command line arguments.
You can try to install with "pip install Gooey"
INFO:v2ecore.v2e_utils:using output folder /content/v2e-output
INFO:v2e:output_in_place==False so made output_folder=/content/v2e-output
INFO:v2ecore.v2e_args:
*** arguments:
auto_timestamp_resolution:	True
avi_frame_rate:	30
batch_size:	8
crop:	None
cs_lambda_pixels:	None
cs_tau_p_ms:	None
cutoff_hz:	0.0
ddd_output:	False
disable_slomo:	False
dvs1024:	False
dvs128:	False
dvs240:	False
dvs346:	True
dvs640:	False
dvs_aedat2:	None
dvs_aedat4:	None
dvs_emulator_seed:	0
dvs_exposure:	['duration', '0.033333']
dvs_h5:	events.h5
dvs_params:	None
dvs_text:	None
dvs_vid:	dvs-video.avi
dvs_vid_full_scale:	2
hdr:	False
input:	/content/video/white_2hz.MOV
input_frame_rate:	30.0
input_slowmotion_factor:	1.0
label_signal_noise:	False
leak_jitter_fraction:	0.1
leak_rate_hz:	0.0
neg_thres:	0.2
no_preview:	True
noise_rate_cov_decades:	0.1
output_folder:	/content/v2e-output
output_height:	None
output_in_place:	False
output_width:	None
overwrite:	True
photoreceptor_noise:	False
pos_thres:	0.2
record_single_pixel_states:	None
refractory_period:	0.0005
save_dvs_model_state:	False
scidvs:	False
shot_noise_rate_hz:	0.0
show_dvs_model_state:	None
sigma_thres:	0.02
skip_video_output:	False
slomo_model:	/content/v2e/input/SuperSloMo39.ckpt
slomo_stats_plot:	False
start_time:	None
stop_time:	None
synthetic_input:	None
timestamp_resolution:	None
unique_output_folder:	False
vid_orig:	video_orig.avi
vid_slomo:	video_slomo.avi

WARNING:v2ecore.v2e_args:
**** extra other arguments (please check if you are misspelling intended arguments):
--davis_output

INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 30.000300003000028
INFO:v2e:opening video input file /content/video/white_2hz.MOV
INFO:v2e:Input video frame rate 29.977628635346758Hz is overridden by command line argument --input_frame_rate=30.0
INFO:v2e:--auto_timestamp_resolution=True and timestamp_resolution is not set: source video will be automatically upsampled to limit maximum interframe motion to 1 pixel
INFO:v2ecore.slomo:CUDA available, running on GPU :-)
INFO:v2ecore.slomo:Using auto_upsample and upsampling_factor; setting minimum upsampling to 1
INFO:v2ecore.slomo:using automatic upsampling mode
INFO:v2e:Source video /content/video/white_2hz.MOV has total 201 frames with total duration 6.67s.
Source video is 30fps with slowmotion_factor 1 (frame interval 33.33ms),
Will convert 201 frames 0 to 200
(From 0.0s to 6.666666666666667s, duration 6.666666666666667s)
INFO:v2e:v2e DVS video will have constant-duration frames
at 30fps (accumulation time 33.33ms),
DVS video will have 200.0 frames with duration 6.67s and playback duration 6.67s

INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.2 / 0.2 +/- 0.02
INFO:v2ecore.emulator:opening event output dataset file /content/v2e-output/events.h5
WARNING:v2ecore.emulator:cannot get screen size for window placement: No enumerators available
INFO:v2e:processing frames 0 to 200 from video input
INFO:v2e:Input video /content/video/white_2hz.MOV has W=1920 x H=1080 frames each with 3 channels
INFO:v2e:*** Stage 1/3: Resizing 201 input frames to output size (with possible RGB to luma conversion)
rgb2luma:   0% 0/201 [00:00<?, ?fr/s]INFO:v2e:
Converting input frames from RGB color to luma
rgb2luma: 100% 201/201 [00:06<00:00, 32.13fr/s]
INFO:v2e:*** Stage 2/3: SloMo upsampling from /tmp/tmpyw_94ao_
INFO:v2ecore.slomo:loading SuperSloMo model from /content/v2e/input/SuperSloMo39.ckpt
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_orig.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.v2e_utils:opened /content/v2e-output/video_slomo.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.slomo:interpolating 25 batches of frames using batch_size=8 with auto_upsample=True and minimum upsampling_factor=1
slomo-interp:   0% 0/25 [00:00<?, ? batch of 8 fr/s]INFO:v2ecore.slomo:upsampled by factor 178
/usr/local/lib/python3.12/dist-packages/v2ecore/model.py:299: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  imgOut = torch.nn.functional.grid_sample(img, grid)
slomo-interp:   4% 1/25 [00:47<18:48, 47.02s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 169
slomo-interp:   8% 2/25 [01:32<17:40, 46.11s/ batch of 8 fr]INFO:v2ecore.slomo:upsampled by factor 176
slomo-interp: 100% 25/25 [19:39<00:00, 47.19s/ batch of 8 fr]
write-orig-avi: 100% 201/201 [00:00<00:00, 850.28fr/s]
write-slomo-vid: 100% 34616/34616 [01:22<00:00, 421.29fr/s]
INFO:v2ecore.slomo:Wrote 34616 frames and returning 34616 frame times.
Average upsampling factor=173.1
INFO:v2e:SloMo average upsampling factor=173.08; average DVS timestamp resolution=192.59us
INFO:v2e:*** Stage 3/3: emulating DVS events from 34616 frames
dvs:   0% 2/34616 [00:00<28:59, 19.89fr/s]INFO:v2ecore.renderer:opening DVS video output file /content/v2e-output/dvs-video.avi
INFO:v2ecore.v2e_utils:opened /content/v2e-output/dvs-video.avi with XVID https://www.fourcc.org/ codec, 30fps, and (346x260) size
INFO:v2ecore.renderer:opening DVS frame times file /content/v2e-output/dvs-video-frame_times.txt
dvs:  12% 4070/34616 [01:09<06:08, 82.87fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,079 at t=0.7799s
dvs:  13% 4442/34616 [01:14<06:46, 74.16fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #4,449 at t=0.8515s
dvs:  19% 6693/34616 [01:52<05:36, 83.03fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #6,695 at t=1.2794s
WARNING:v2ecore.emulator:no signal events generated for frame #6,699 at t=1.2801s
dvs:  21% 7192/34616 [01:59<07:20, 62.21fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #7,195 at t=1.3771s
dvs:  21% 7212/34616 [01:59<08:45, 52.11fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #7,218 at t=1.3819s
dvs:  21% 7226/34616 [02:00<08:52, 51.42fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #7,229 at t=1.3842s
dvs:  21% 7234/34616 [02:00<08:58, 50.81fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #7,239 at t=1.3863s
dvs:  21% 7250/34616 [02:00<08:28, 53.84fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #7,257 at t=1.3900s
dvs:  21% 7274/34616 [02:01<07:28, 60.94fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #7,277 at t=1.3942s
dvs:  27% 9180/34616 [02:34<06:22, 66.53fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,188 at t=1.7749s
dvs:  28% 9593/34616 [02:39<04:42, 88.46fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #9,603 at t=1.8535s
dvs:  44% 15085/34616 [04:18<04:13, 77.14fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #15,086 at t=2.9456s
dvs:  58% 19930/34616 [05:43<03:27, 70.83fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #19,938 at t=3.8788s
dvs:  69% 23746/34616 [06:56<03:14, 55.93fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #23,752 at t=4.6069s
dvs:  69% 23871/34616 [06:57<02:10, 82.62fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #23,877 at t=4.6300s
dvs:  80% 27842/34616 [08:05<02:10, 51.83fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #27,843 at t=5.3731s
dvs:  80% 27858/34616 [08:05<01:50, 61.02fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #27,859 at t=5.3762s
dvs:  81% 27875/34616 [08:06<01:36, 69.79fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #27,881 at t=5.3805s
WARNING:v2ecore.emulator:no signal events generated for frame #27,882 at t=5.3807s
WARNING:v2ecore.emulator:no signal events generated for frame #27,888 at t=5.3819s
dvs:  81% 27917/34616 [08:06<01:21, 82.37fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #27,923 at t=5.3888s
dvs:  81% 27926/34616 [08:06<01:21, 81.89fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #27,934 at t=5.3909s
dvs:  81% 27973/34616 [08:07<01:22, 80.62fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #27,975 at t=5.3990s
dvs:  88% 30290/34616 [08:48<01:09, 62.47fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #30,294 at t=5.8410s
dvs:  88% 30307/34616 [08:48<00:59, 72.23fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #30,309 at t=5.8437s
WARNING:v2ecore.emulator:no signal events generated for frame #30,314 at t=5.8447s
dvs:  88% 30316/34616 [08:49<00:56, 76.42fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #30,317 at t=5.8452s
WARNING:v2ecore.emulator:no signal events generated for frame #30,321 at t=5.8460s
WARNING:v2ecore.emulator:no signal events generated for frame #30,328 at t=5.8473s
dvs:  88% 30339/34616 [08:49<00:49, 86.04fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #30,342 at t=5.8499s
dvs:  92% 31698/34616 [09:14<00:52, 55.18fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #31,703 at t=6.1144s
dvs:  92% 31714/34616 [09:14<00:52, 55.30fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #31,722 at t=6.1181s
dvs:  92% 31722/34616 [09:14<00:51, 55.66fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #31,728 at t=6.1193s
dvs:  92% 31730/34616 [09:14<00:50, 56.84fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #31,737 at t=6.1210s
dvs:  92% 31746/34616 [09:15<00:41, 69.75fr/s]WARNING:v2ecore.emulator:no signal events generated for frame #31,751 at t=6.1238s
dvs: 100% 34616/34616 [10:06<00:00, 57.07fr/s]
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 200 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 201 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 34616 frames
INFO:v2e:generated total 45.65M events (22.73M on, 22.92M off)
INFO:v2e:Avg event rate for N=89960 px and total time =6.667 s
	Total: 6.85MHz (3.41MHz on, 3.44MHz off)
	Per pixel:  76.12Hz (37.91Hz on, 38.22Hz off)
INFO:v2e:generating desktop notification
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:103: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.12/dist-packages/plyer/platforms/linux/notification.py:107: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
INFO:v2e:could not show notification: No usable implementation found!
INFO:v2e:showing /content/v2e-output in desktop
/bin/sh: 1: xprop: not found
WARNING:v2e:Desktop 'None' not supported (neither DESKTOP_LAUNCH nor os.startfile could be used): could not open /content/v2e-output in desktop
INFO:v2e:done processing 402 frames in 1.88ks (4.67s/fr)
 **************** see output folder /content/v2e-output
INFO:v2ecore.renderer:Closing DVS video output file dvs-video.avi after writing 200 frames
INFO:v2ecore.slomo:closing original video AVI video_orig.avi after writing 201 frames
INFO:v2ecore.slomo:closing slomo video AVI video_slomo.avi after writing 34616 frames
Total events: 45,653,791
  Written 5,000,000/45,653,791
  Written 10,000,000/45,653,791
  Written 15,000,000/45,653,791
  Written 20,000,000/45,653,791
  Written 25,000,000/45,653,791
  Written 30,000,000/45,653,791
  Written 35,000,000/45,653,791
  Written 40,000,000/45,653,791
  Written 45,000,000/45,653,791
  Written 45,653,791/45,653,791
Saved: /content/v2e-output/events.csv
Detected FPS: 30.0
Saved frames: 201
Output folder: /content/v2e-output/aps
APS frames found: 201
Reading events and building frames (chunked)...

Processing chunks: 0it [00:00, ?it/s]

Saving DVS frames...

Saving DVS frames:   0%|          | 0/201 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/content/v2e-output/aps/%04d.png':
  Duration: 00:00:06.70, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Input #1, image2, from '/content/v2e-output/dvs/%04d.png':
  Duration: 00:00:06.70, start: 0.000000, bitrate: N/A
  Stream #1:0: Video: png, rgb24(pc), 346x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 (png) -> hstack:input0
  Stream #1:0 (png) -> hstack:input1
  hstack -> Stream #0:0 (libx264)
Press [q] to stop, [?] for help
[image2 @ 0x59bf0ca38840] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[image2 @ 0x59bf0ca412c0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[libx264 @ 0x59bf0cf47340] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x59bf0cf47340] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x59bf0cf47340] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/v2e-output/aps_dvs.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 692x260, q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  201 fps= 33 q=-1.0 Lsize=    4984kB time=00:00:06.60 bitrate=6185.8kbits/s speed=1.09x
video:4981kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.046285%
[libx264 @ 0x59bf0cf47340] frame I:31    Avg QP:26.77  size: 40148
[libx264 @ 0x59bf0cf47340] frame P:132   Avg QP:29.42  size: 23312
[libx264 @ 0x59bf0cf47340] frame B:38    Avg QP:31.73  size: 20487
[libx264 @ 0x59bf0cf47340] consecutive B-frames: 69.7% 12.9%  7.5% 10.0%
[libx264 @ 0x59bf0cf47340] mb I  I16..4:  2.5% 49.9% 47.5%
[libx264 @ 0x59bf0cf47340] mb P  I16..4:  7.4% 38.3% 32.4%  P16..4: 10.0%  1.5%  0.9%  0.0%  0.0%    skip: 9.6%
[libx264 @ 0x59bf0cf47340] mb B  I16..4: 13.3%  1.8% 18.5%  B16..8: 11.5%  4.4%  3.3%  direct: 6.5%  skip:40.6%  L0:52.2% L1:42.7% BI: 5.1%
[libx264 @ 0x59bf0cf47340] 8x8 transform intra:45.4% inter:60.6%
[libx264 @ 0x59bf0cf47340] coded y,uvDC,uvAC intra: 70.5% 47.0% 45.2% inter: 29.4% 7.3% 3.4%
[libx264 @ 0x59bf0cf47340] i16 v,h,dc,p: 36% 11% 48%  5%
[libx264 @ 0x59bf0cf47340] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 51% 10% 26%  2%  2%  3%  1%  3%  2%
[libx264 @ 0x59bf0cf47340] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 11% 30%  6%  5%  6%  5%  5%  4%
[libx264 @ 0x59bf0cf47340] i8c dc,h,v,p: 77%  5% 14%  4%
[libx264 @ 0x59bf0cf47340] Weighted P-Frames: Y:27.3% UV:22.0%
[libx264 @ 0x59bf0cf47340] ref P L0: 54.8% 24.3% 14.1%  5.2%  1.7%
[libx264 @ 0x59bf0cf47340] ref B L0: 86.9% 12.4%  0.7%
[libx264 @ 0x59bf0cf47340] ref B L1: 96.6%  3.4%
[libx264 @ 0x59bf0cf47340] kb/s:6089.92
/content/v2e-output
  adding: dvs/ (stored 0%)
  adding: dvs/0063.png (stored 0%)
  adding: dvs/0140.png (stored 0%)
  adding: dvs/0104.png (stored 0%)
  adding: dvs/0160.png (stored 0%)
  adding: dvs/0105.png (stored 0%)
  adding: dvs/0199.png (deflated 58%)
  adding: dvs/0134.png (stored 0%)
  adding: dvs/0077.png (stored 0%)
  adding: dvs/0011.png (stored 0%)
  adding: dvs/0026.png (stored 0%)
  adding: dvs/0154.png (stored 0%)
  adding: dvs/0128.png (stored 0%)
  adding: dvs/0171.png (stored 0%)
  adding: dvs/0108.png (stored 0%)
  adding: dvs/0145.png (stored 0%)
  adding: dvs/0120.png (stored 0%)
  adding: dvs/0163.png (stored 0%)
  adding: dvs/0084.png (stored 0%)
  adding: dvs/0066.png (stored 0%)
  adding: dvs/0010.png (stored 0%)
  adding: dvs/0191.png (stored 0%)
  adding: dvs/0007.png (stored 0%)
  adding: dvs/0071.png (stored 0%)
  adding: dvs/0053.png (stored 0%)
  adding: dvs/0161.png (stored 0%)
  adding: dvs/0062.png (stored 0%)
  adding: dvs/0082.png (stored 0%)
  adding: dvs/0197.png (deflated 75%)
  adding: dvs/0143.png (stored 0%)
  adding: dvs/0184.png (stored 0%)
  adding: dvs/0178.png (stored 0%)
  adding: dvs/0054.png (stored 0%)
  adding: dvs/0022.png (stored 0%)
  adding: dvs/0045.png (stored 0%)
  adding: dvs/0086.png (stored 0%)
  adding: dvs/0117.png (stored 0%)
  adding: dvs/0052.png (stored 0%)
  adding: dvs/0126.png (stored 0%)
  adding: dvs/0150.png (stored 0%)
  adding: dvs/0042.png (stored 0%)
  adding: dvs/0112.png (stored 0%)
  adding: dvs/0168.png (deflated 7%)
  adding: dvs/0075.png (stored 0%)
  adding: dvs/0036.png (stored 0%)
  adding: dvs/0095.png (stored 0%)
  adding: dvs/0065.png (stored 0%)
  adding: dvs/0057.png (stored 0%)
  adding: dvs/0033.png (stored 0%)
  adding: dvs/0182.png (deflated 65%)
  adding: dvs/0091.png (stored 0%)
  adding: dvs/0067.png (stored 0%)
  adding: dvs/0081.png (stored 0%)
  adding: dvs/0047.png (stored 0%)
  adding: dvs/0151.png (stored 0%)
  adding: dvs/0056.png (stored 0%)
  adding: dvs/0142.png (stored 0%)
  adding: dvs/0044.png (stored 0%)
  adding: dvs/0020.png (stored 0%)
  adding: dvs/0106.png (stored 0%)
  adding: dvs/0072.png (stored 0%)
  adding: dvs/0113.png (stored 0%)
  adding: dvs/0043.png (stored 0%)
  adding: dvs/0157.png (stored 0%)
  adding: dvs/0013.png (stored 0%)
  adding: dvs/0158.png (stored 0%)
  adding: dvs/0034.png (stored 0%)
  adding: dvs/0138.png (stored 0%)
  adding: dvs/0100.png (stored 0%)
  adding: dvs/0175.png (stored 0%)
  adding: dvs/0167.png (deflated 26%)
  adding: dvs/0041.png (stored 0%)
  adding: dvs/0177.png (stored 0%)
  adding: dvs/0032.png (stored 0%)
  adding: dvs/0093.png (stored 0%)
  adding: dvs/0004.png (stored 0%)
  adding: dvs/0006.png (stored 0%)
  adding: dvs/0159.png (stored 0%)
  adding: dvs/0188.png (stored 0%)
  adding: dvs/0030.png (stored 0%)
  adding: dvs/0130.png (stored 0%)
  adding: dvs/0132.png (stored 0%)
  adding: dvs/0009.png (stored 0%)
  adding: dvs/0162.png (stored 0%)
  adding: dvs/0017.png (stored 0%)
  adding: dvs/0051.png (stored 0%)
  adding: dvs/0190.png (stored 0%)
  adding: dvs/0170.png (stored 0%)
  adding: dvs/0035.png (stored 0%)
  adding: dvs/0201.png (stored 0%)
  adding: dvs/0018.png (stored 0%)
  adding: dvs/0156.png (stored 0%)
  adding: dvs/0196.png (stored 0%)
  adding: dvs/0147.png (stored 0%)
  adding: dvs/0183.png (deflated 21%)
  adding: dvs/0198.png (stored 0%)
  adding: dvs/0069.png (stored 0%)
  adding: dvs/0148.png (stored 0%)
  adding: dvs/0060.png (stored 0%)
  adding: dvs/0003.png (stored 0%)
  adding: dvs/0187.png (stored 0%)
  adding: dvs/0029.png (stored 0%)
  adding: dvs/0115.png (stored 0%)
  adding: dvs/0141.png (stored 0%)
  adding: dvs/0001.png (deflated 69%)
  adding: dvs/0200.png (stored 0%)
  adding: dvs/0046.png (stored 0%)
  adding: dvs/0135.png (stored 0%)
  adding: dvs/0080.png (stored 0%)
  adding: dvs/0094.png (stored 0%)
  adding: dvs/0090.png (stored 0%)
  adding: dvs/0049.png (stored 0%)
  adding: dvs/0164.png (stored 0%)
  adding: dvs/0024.png (stored 0%)
  adding: dvs/0061.png (stored 0%)
  adding: dvs/0039.png (stored 0%)
  adding: dvs/0101.png (stored 0%)
  adding: dvs/0152.png (deflated 1%)
  adding: dvs/0097.png (stored 0%)
  adding: dvs/0059.png (stored 0%)
  adding: dvs/0038.png (stored 0%)
  adding: dvs/0070.png (stored 0%)
  adding: dvs/0129.png (stored 0%)
  adding: dvs/0037.png (stored 0%)
  adding: dvs/0073.png (stored 0%)
  adding: dvs/0116.png (stored 0%)
  adding: dvs/0185.png (stored 0%)
  adding: dvs/0021.png (stored 0%)
  adding: dvs/0137.png (deflated 1%)
  adding: dvs/0015.png (stored 0%)
  adding: dvs/0166.png (stored 0%)
  adding: dvs/0146.png (stored 0%)
  adding: dvs/0121.png (stored 0%)
  adding: dvs/0027.png (stored 0%)
  adding: dvs/0040.png (stored 0%)
  adding: dvs/0074.png (stored 0%)
  adding: dvs/0149.png (stored 0%)
  adding: dvs/0096.png (stored 0%)
  adding: dvs/0068.png (stored 0%)
  adding: dvs/0181.png (stored 0%)
  adding: dvs/0180.png (stored 0%)
  adding: dvs/0076.png (stored 0%)
  adding: dvs/0079.png (stored 0%)
  adding: dvs/0078.png (deflated 3%)
  adding: dvs/0125.png (stored 0%)
  adding: dvs/0127.png (stored 0%)
  adding: dvs/0099.png (stored 0%)
  adding: dvs/0194.png (stored 0%)
  adding: dvs/0008.png (deflated 4%)
  adding: dvs/0028.png (stored 0%)
  adding: dvs/0050.png (stored 0%)
  adding: dvs/0088.png (stored 0%)
  adding: dvs/0118.png (stored 0%)
  adding: dvs/0103.png (stored 0%)
  adding: dvs/0092.png (stored 0%)
  adding: dvs/0012.png (stored 0%)
  adding: dvs/0133.png (stored 0%)
  adding: dvs/0165.png (stored 0%)
  adding: dvs/0031.png (stored 0%)
  adding: dvs/0064.png (stored 0%)
  adding: dvs/0155.png (stored 0%)
  adding: dvs/0193.png (stored 0%)
  adding: dvs/0055.png (stored 0%)
  adding: dvs/0195.png (stored 0%)
  adding: dvs/0144.png (stored 0%)
  adding: dvs/0110.png (stored 0%)
  adding: dvs/0016.png (deflated 15%)
  adding: dvs/0114.png (stored 0%)
  adding: dvs/0107.png (stored 0%)
  adding: dvs/0123.png (stored 0%)
  adding: dvs/0109.png (stored 0%)
  adding: dvs/0189.png (deflated 2%)
  adding: dvs/0025.png (stored 0%)
  adding: dvs/0085.png (stored 0%)
  adding: dvs/0058.png (stored 0%)
  adding: dvs/0153.png (stored 0%)
  adding: dvs/0139.png (stored 0%)
  adding: dvs/0174.png (stored 0%)
  adding: dvs/0192.png (stored 0%)
  adding: dvs/0169.png (stored 0%)
  adding: dvs/0098.png (stored 0%)
  adding: dvs/0048.png (stored 0%)
  adding: dvs/0089.png (stored 0%)
  adding: dvs/0122.png (stored 0%)
  adding: dvs/0002.png (deflated 9%)
  adding: dvs/0111.png (stored 0%)
  adding: dvs/0172.png (stored 0%)
  adding: dvs/0176.png (stored 0%)
  adding: dvs/0136.png (stored 0%)
  adding: dvs/0005.png (stored 0%)
  adding: dvs/0023.png (stored 0%)
  adding: dvs/0102.png (stored 0%)
  adding: dvs/0124.png (stored 0%)
  adding: dvs/0087.png (stored 0%)
  adding: dvs/0179.png (stored 0%)
  adding: dvs/0173.png (stored 0%)
  adding: dvs/0186.png (stored 0%)
  adding: dvs/0131.png (stored 0%)
  adding: dvs/0119.png (stored 0%)
  adding: dvs/0083.png (stored 0%)
  adding: dvs/0019.png (stored 0%)
  adding: dvs/0014.png (stored 0%)
  adding: events.csv (deflated 79%)
  adding: aps/ (stored 0%)
  adding: aps/0063.png (deflated 20%)
  adding: aps/0140.png (deflated 20%)
  adding: aps/0104.png (deflated 17%)
  adding: aps/0160.png (deflated 34%)
  adding: aps/0105.png (deflated 17%)
  adding: aps/0199.png (deflated 20%)
  adding: aps/0134.png (deflated 16%)
  adding: aps/0077.png (deflated 25%)
  adding: aps/0011.png (deflated 28%)
  adding: aps/0026.png (deflated 23%)
  adding: aps/0154.png (deflated 18%)
  adding: aps/0128.png (deflated 19%)
  adding: aps/0171.png (deflated 18%)
  adding: aps/0108.png (deflated 20%)
  adding: aps/0145.png (deflated 34%)
  adding: aps/0120.png (deflated 17%)
  adding: aps/0163.png (deflated 19%)
  adding: aps/0084.png (deflated 36%)
  adding: aps/0066.png (deflated 19%)
  adding: aps/0010.png (deflated 34%)
  adding: aps/0191.png (deflated 23%)
  adding: aps/0007.png (deflated 19%)
  adding: aps/0071.png (deflated 21%)
  adding: aps/0053.png (deflated 19%)
  adding: aps/0161.png (deflated 21%)
  adding: aps/0062.png (deflated 26%)
  adding: aps/0082.png (deflated 18%)
  adding: aps/0197.png (deflated 27%)
  adding: aps/0143.png (deflated 19%)
  adding: aps/0184.png (deflated 19%)
  adding: aps/0178.png (deflated 19%)
  adding: aps/0054.png (deflated 34%)
  adding: aps/0022.png (deflated 19%)
  adding: aps/0045.png (deflated 17%)
  adding: aps/0086.png (deflated 23%)
  adding: aps/0117.png (deflated 19%)
  adding: aps/0052.png (deflated 19%)
  adding: aps/0126.png (deflated 19%)
  adding: aps/0150.png (deflated 17%)
  adding: aps/0042.png (deflated 19%)
  adding: aps/0112.png (deflated 19%)
  adding: aps/0168.png (deflated 20%)
  adding: aps/0075.png (deflated 17%)
  adding: aps/0036.png (deflated 19%)
  adding: aps/0095.png (deflated 19%)
  adding: aps/0065.png (deflated 18%)
  adding: aps/0057.png (deflated 22%)
  adding: aps/0033.png (deflated 21%)
  adding: aps/0182.png (deflated 26%)
  adding: aps/0091.png (deflated 17%)
  adding: aps/0067.png (deflated 19%)
  adding: aps/0081.png (deflated 19%)
  adding: aps/0047.png (deflated 25%)
  adding: aps/0151.png (deflated 17%)
  adding: aps/0056.png (deflated 23%)
  adding: aps/0142.png (deflated 19%)
  adding: aps/0044.png (deflated 17%)
  adding: aps/0020.png (deflated 19%)
  adding: aps/0106.png (deflated 17%)
  adding: aps/0072.png (deflated 18%)
  adding: aps/0113.png (deflated 18%)
  adding: aps/0043.png (deflated 18%)
  adding: aps/0157.png (deflated 19%)
  adding: aps/0013.png (deflated 19%)
  adding: aps/0158.png (deflated 18%)
  adding: aps/0034.png (deflated 19%)
  adding: aps/0138.png (deflated 21%)
  adding: aps/0100.png (deflated 33%)
  adding: aps/0175.png (deflated 34%)
  adding: aps/0167.png (deflated 29%)
  adding: aps/0041.png (deflated 23%)
  adding: aps/0177.png (deflated 21%)
  adding: aps/0032.png (deflated 25%)
  adding: aps/0093.png (deflated 21%)
  adding: aps/0004.png (deflated 20%)
  adding: aps/0006.png (deflated 19%)
  adding: aps/0159.png (deflated 35%)
  adding: aps/0188.png (deflated 19%)
  adding: aps/0030.png (deflated 16%)
  adding: aps/0130.png (deflated 34%)
  adding: aps/0132.png (deflated 19%)
  adding: aps/0009.png (deflated 35%)
  adding: aps/0162.png (deflated 19%)
  adding: aps/0017.png (deflated 27%)
  adding: aps/0051.png (deflated 19%)
  adding: aps/0190.png (deflated 34%)
  adding: aps/0170.png (deflated 19%)
  adding: aps/0035.png (deflated 19%)
  adding: aps/0201.png (deflated 19%)
  adding: aps/0018.png (deflated 20%)
  adding: aps/0156.png (deflated 20%)
  adding: aps/0196.png (deflated 17%)
  adding: aps/0147.png (deflated 19%)
  adding: aps/0183.png (deflated 21%)
  adding: aps/0198.png (deflated 23%)
  adding: aps/0069.png (deflated 33%)
  adding: aps/0148.png (deflated 18%)
  adding: aps/0060.png (deflated 17%)
  adding: aps/0003.png (deflated 20%)
  adding: aps/0187.png (deflated 19%)
  adding: aps/0029.png (deflated 17%)
  adding: aps/0115.png (deflated 36%)
  adding: aps/0141.png (deflated 19%)
  adding: aps/0001.png (deflated 16%)
  adding: aps/0200.png (deflated 19%)
  adding: aps/0046.png (deflated 16%)
  adding: aps/0135.png (deflated 16%)
  adding: aps/0080.png (deflated 19%)
  adding: aps/0094.png (deflated 19%)
  adding: aps/0090.png (deflated 17%)
  adding: aps/0049.png (deflated 19%)
  adding: aps/0164.png (deflated 17%)
  adding: aps/0024.png (deflated 29%)
  adding: aps/0061.png (deflated 16%)
  adding: aps/0039.png (deflated 30%)
  adding: aps/0101.png (deflated 21%)
  adding: aps/0152.png (deflated 26%)
  adding: aps/0097.png (deflated 19%)
  adding: aps/0059.png (deflated 17%)
  adding: aps/0038.png (deflated 19%)
  adding: aps/0070.png (deflated 30%)
  adding: aps/0129.png (deflated 35%)
  adding: aps/0037.png (deflated 19%)
  adding: aps/0073.png (deflated 19%)
  adding: aps/0116.png (deflated 21%)
  adding: aps/0185.png (deflated 19%)
  adding: aps/0021.png (deflated 19%)
  adding: aps/0137.png (deflated 25%)
  adding: aps/0015.png (deflated 17%)
  adding: aps/0166.png (deflated 17%)
  adding: aps/0146.png (deflated 23%)
  adding: aps/0121.png (deflated 17%)
  adding: aps/0027.png (deflated 21%)
  adding: aps/0040.png (deflated 27%)
  adding: aps/0074.png (deflated 17%)
  adding: aps/0149.png (deflated 17%)
  adding: aps/0096.png (deflated 20%)
  adding: aps/0068.png (deflated 18%)
  adding: aps/0181.png (deflated 17%)
  adding: aps/0180.png (deflated 17%)
  adding: aps/0076.png (deflated 16%)
  adding: aps/0079.png (deflated 20%)
  adding: aps/0078.png (deflated 22%)
  adding: aps/0125.png (deflated 19%)
  adding: aps/0127.png (deflated 19%)
  adding: aps/0099.png (deflated 36%)
  adding: aps/0194.png (deflated 16%)
  adding: aps/0008.png (deflated 19%)
  adding: aps/0028.png (deflated 18%)
  adding: aps/0050.png (deflated 20%)
  adding: aps/0088.png (deflated 18%)
  adding: aps/0118.png (deflated 19%)
  adding: aps/0103.png (deflated 19%)
  adding: aps/0092.png (deflated 25%)
  adding: aps/0012.png (deflated 19%)
  adding: aps/0133.png (deflated 19%)
  adding: aps/0165.png (deflated 17%)
  adding: aps/0031.png (deflated 17%)
  adding: aps/0064.png (deflated 19%)
  adding: aps/0155.png (deflated 19%)
  adding: aps/0193.png (deflated 18%)
  adding: aps/0055.png (deflated 30%)
  adding: aps/0195.png (deflated 17%)
  adding: aps/0144.png (deflated 36%)
  adding: aps/0110.png (deflated 18%)
  adding: aps/0016.png (deflated 17%)
  adding: aps/0114.png (deflated 36%)
  adding: aps/0107.png (deflated 24%)
  adding: aps/0123.png (deflated 20%)
  adding: aps/0109.png (deflated 19%)
  adding: aps/0189.png (deflated 35%)
  adding: aps/0025.png (deflated 23%)
  adding: aps/0085.png (deflated 34%)
  adding: aps/0058.png (deflated 19%)
  adding: aps/0153.png (deflated 20%)
  adding: aps/0139.png (deflated 20%)
  adding: aps/0174.png (deflated 36%)
  adding: aps/0192.png (deflated 18%)
  adding: aps/0169.png (deflated 19%)
  adding: aps/0098.png (deflated 19%)
  adding: aps/0048.png (deflated 20%)
  adding: aps/0089.png (deflated 16%)
  adding: aps/0122.png (deflated 24%)
  adding: aps/0002.png (deflated 29%)
  adding: aps/0111.png (deflated 18%)
  adding: aps/0172.png (deflated 19%)
  adding: aps/0176.png (deflated 22%)
  adding: aps/0136.png (deflated 17%)
  adding: aps/0005.png (deflated 20%)
  adding: aps/0023.png (deflated 18%)
  adding: aps/0102.png (deflated 19%)
  adding: aps/0124.png (deflated 20%)
  adding: aps/0087.png (deflated 19%)
  adding: aps/0179.png (deflated 17%)
  adding: aps/0173.png (deflated 19%)
  adding: aps/0186.png (deflated 20%)
  adding: aps/0131.png (deflated 21%)
  adding: aps/0119.png (deflated 17%)
  adding: aps/0083.png (deflated 18%)

# Process GT

In [ ]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

from tqdm.notebook import tqdm

Mounted at /content/drive

In [ ]:
seq = 'tag'
initials = 'seya'


gt_path = f'/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/{initials}/clean/{seq}/gt.txt'

df = pd.read_csv(
    gt_path,
    header=None,
    names=["frame", "id", "x", "y", "w", "h", "conf", "class", "visibility"]
)
df

     frame  id       x       y      w      h  conf  class  visibility
0        1   1  231.85  114.81  16.30  18.89     1      1         1.0
1        2   1  213.44  119.66  16.53  18.82     1      1         1.0
2        3   1  193.98  122.17  13.88  18.48     1      1         1.0
3        4   1  174.92  120.41  14.88  17.58     1      1         1.0
4        5   1  156.92  115.42  14.70  18.18     1      1         1.0
..     ...  ..     ...     ...    ...    ...   ...    ...         ...
309    310   1  163.70  115.04  12.77  18.21     1      1         1.0
310    311   1  152.35  110.82  13.04  18.47     1      1         1.0
311    312   1  142.56  105.84  13.65  19.03     1      1         1.0
312    313   1  133.58  100.47  14.09  18.84     1      1         1.0
313    314   1  126.94   95.73  13.29  18.53     1      1         1.0

[314 rows x 9 columns]

In [ ]:
df_new = df[["x", "y", "w", "h"]]
df_new

          x       y      w      h
0    231.85  114.81  16.30  18.89
1    213.44  119.66  16.53  18.82
2    193.98  122.17  13.88  18.48
3    174.92  120.41  14.88  17.58
4    156.92  115.42  14.70  18.18
..      ...     ...    ...    ...
309  163.70  115.04  12.77  18.21
310  152.35  110.82  13.04  18.47
311  142.56  105.84  13.65  19.03
312  133.58  100.47  14.09  18.84
313  126.94   95.73  13.29  18.53

[314 rows x 4 columns]

In [ ]:
new_gt_path = f'/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/{initials}/clean/{seq}/groundtruth_rect.txt'
df_new.to_csv(new_gt_path, sep=",", header=False, index=False)

In [ ]:
initials = 'seya'
sequences = ['key_1:2hz', 'key_1hz', 'key_2hz', 'lamp_1:2hz', 'lamp_1hz', 'lamp_2hz',
             'repeater_1:2hz', 'repeater_1hz', 'repeater_2hz', 'soap_1:2hz',
             'soap_1hz', 'soap_2hz', 'white_1:2hz', 'white_1hz', 'white_2hz',
             'cleaner_1:2hz', 'cleaner_1hz', 'cleaner_2hz', 'knife_1:2hz', 'knife_1hz', 'knife_2hz',
             'longus_1:2hz', 'longus_1hz', 'longus_2hz', 'nonstop_1:2hz',
             'nonstop_1hz', 'nonstop_2hz', 'rexona_1:2hz', 'rexona_1hz', 'rexona_2hz']

for seq in tqdm(sequences):
    gt_path = f'/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/{initials}/flicker/{seq}/gt.txt'

    df = pd.read_csv(
        gt_path,
        header=None,
        names=["frame", "id", "x", "y", "w", "h", "conf", "class", "visibility"]
    )
    df_new = df[["x", "y", "w", "h"]]

    new_gt_path = f'/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/{initials}/flicker/{seq}/groundtruth_rect.txt'
    df_new.to_csv(new_gt_path, sep=",", header=False, index=False)

  0%|          | 0/30 [00:00<?, ?it/s]

# Video aps_dvs_gpt with gt

In [ ]:
import os
import shutil
import cv2
import numpy as np
from tqdm.notebook import tqdm

In [ ]:
def load_bboxes(path):
    bboxes = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                d = ',' if ',' in line else '\t'
                bboxes.append(list(map(float, line.split(d))))
    return bboxes

In [ ]:
initials = 'seya'
sequences = ['key_1:2hz', 'key_1hz', 'key_2hz', 'lamp_1:2hz', 'lamp_1hz', 'lamp_2hz',
             'repeater_1:2hz', 'repeater_1hz', 'repeater_2hz', 'soap_1:2hz',
             'soap_1hz', 'soap_2hz', 'white_1:2hz', 'white_1hz', 'white_2hz',
             'cleaner_1:2hz', 'cleaner_1hz', 'cleaner_2hz', 'knife_1:2hz', 'knife_1hz', 'knife_2hz',
             'longus_1:2hz', 'longus_1hz', 'longus_2hz', 'nonstop_1:2hz',
             'nonstop_1hz', 'nonstop_2hz', 'rexona_1:2hz', 'rexona_1hz', 'rexona_2hz']


for seq in tqdm(sequences):
    base = f'/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/{initials}/flicker/{seq}'
    tmp = f'/tmp/{seq}'
    os.makedirs(tmp, exist_ok=True)

    gt_boxes   = load_bboxes(f'{base}/groundtruth_rect.txt')
    aps_frames = sorted(os.listdir(f'{base}/aps'))
    dvs_frames = sorted(os.listdir(f'{base}/dvs'))
    gtp_frames = sorted(os.listdir(f'{base}/inter1_stack_3008'))
    n = min(len(aps_frames), len(dvs_frames), len(gtp_frames), len(gt_boxes))

    for i in tqdm(range(n)):
        aps_img = cv2.imread(f'{base}/aps/{aps_frames[i]}')
        dvs_img = cv2.imread(f'{base}/dvs/{dvs_frames[i]}')
        gtp_img = cv2.imread(f'{base}/inter1_stack_3008/{gtp_frames[i]}')

        labels = ['APS', 'GTP', 'DVS']
        for fr, label in zip([aps_img, gtp_img, dvs_img], labels):
            # draw GT bounding box in green
            x, y, w, h = [int(v) for v in gt_boxes[i]]
            if any([x, y, w, h]):
                cv2.rectangle(fr, (x, y), (x+w, y+h), (0, 255, 0), 1)

            # window label in top-left corner
            cv2.putText(fr, label, (10, 15), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1)

            # frame number at the bottom
            cv2.putText(fr, f'Frame: {i+1}', (10, fr.shape[0] - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.27, (255, 255, 255), 1)

        # stack frames horizontally and save
        cv2.imwrite(f'{tmp}/{i:04d}.png', np.hstack([aps_img, gtp_img, dvs_img]))

    # encode frames to mp4
    !ffmpeg -y -framerate 30 -i {tmp}/%04d.png -c:v libx264 -pix_fmt yuv420p {base}/aps_dvs_gtp.mp4
    shutil.rmtree(tmp)

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/217 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/key_1:2hz/%04d.png':
  Duration: 00:00:07.23, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x597a230b0980] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x597a230b0980] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x597a230b0980] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/key_1:2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  217 fps= 42 q=-1.0 Lsize=    2340kB time=00:00:07.13 bitrate=2686.9kbits/s speed=1.37x
video:2337kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.135123%
[libx264 @ 0x597a230b0980] frame I:8     Avg QP:25.53  size: 45547
[libx264 @ 0x597a230b0980] frame P:81    Avg QP:27.00  size: 16391
[libx264 @ 0x597a230b0980] frame B:128   Avg QP:28.44  size:  5468
[libx264 @ 0x597a230b0980] consecutive B-frames: 19.8%  3.7%  2.8% 73.7%
[libx264 @ 0x597a230b0980] mb I  I16..4: 14.4% 57.3% 28.3%
[libx264 @ 0x597a230b0980] mb P  I16..4:  9.8% 35.1% 12.8%  P16..4: 15.4%  3.4%  2.9%  0.0%  0.0%    skip:20.6%
[libx264 @ 0x597a230b0980] mb B  I16..4:  3.1%  1.5%  2.1%  B16..8: 24.6%  2.2%  1.0%  direct: 4.0%  skip:61.5%  L0:39.7% L1:56.4% BI: 3.9%
[libx264 @ 0x597a230b0980] 8x8 transform intra:55.2% inter:62.5%
[libx264 @ 0x597a230b0980] coded y,uvDC,uvAC intra: 57.8% 49.1% 40.0% inter: 12.4% 8.9% 1.8%
[libx264 @ 0x597a230b0980] i16 v,h,dc,p: 49% 17% 27%  7%
[libx264 @ 0x597a230b0980] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 42%  9% 32%  3%  2%  3%  2%  3%  3%
[libx264 @ 0x597a230b0980] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 35% 12% 30%  5%  4%  4%  4%  4%  3%
[libx264 @ 0x597a230b0980] i8c dc,h,v,p: 69%  9% 18%  4%
[libx264 @ 0x597a230b0980] Weighted P-Frames: Y:18.5% UV:16.0%
[libx264 @ 0x597a230b0980] ref P L0: 61.8% 17.9% 13.8%  5.7%  0.8%
[libx264 @ 0x597a230b0980] ref B L0: 80.8% 16.1%  3.1%
[libx264 @ 0x597a230b0980] ref B L1: 92.2%  7.8%
[libx264 @ 0x597a230b0980] kb/s:2645.48

  0%|          | 0/221 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/key_1hz/%04d.png':
  Duration: 00:00:07.37, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5794271d8180] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5794271d8180] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5794271d8180] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/key_1hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  221 fps= 24 q=-1.0 Lsize=    4893kB time=00:00:07.26 bitrate=5516.1kbits/s speed= 0.8x
video:4890kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.057213%
[libx264 @ 0x5794271d8180] frame I:16    Avg QP:25.69  size: 55422
[libx264 @ 0x5794271d8180] frame P:118   Avg QP:28.41  size: 26097
[libx264 @ 0x5794271d8180] frame B:87    Avg QP:29.12  size: 11962
[libx264 @ 0x5794271d8180] consecutive B-frames: 44.3%  5.4% 12.2% 38.0%
[libx264 @ 0x5794271d8180] mb I  I16..4: 15.6% 55.4% 29.1%
[libx264 @ 0x5794271d8180] mb P  I16..4: 11.6% 42.7% 21.0%  P16..4: 11.2%  2.0%  1.4%  0.0%  0.0%    skip:10.0%
[libx264 @ 0x5794271d8180] mb B  I16..4:  6.4%  4.2%  5.5%  B16..8: 20.4%  3.2%  1.8%  direct: 7.8%  skip:50.6%  L0:36.7% L1:57.2% BI: 6.1%
[libx264 @ 0x5794271d8180] 8x8 transform intra:52.9% inter:63.1%
[libx264 @ 0x5794271d8180] coded y,uvDC,uvAC intra: 63.1% 55.8% 45.7% inter: 21.0% 16.4% 3.2%
[libx264 @ 0x5794271d8180] i16 v,h,dc,p: 44% 18% 30%  7%
[libx264 @ 0x5794271d8180] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 42% 10% 30%  3%  3%  3%  3%  4%  3%
[libx264 @ 0x5794271d8180] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 10% 30%  6%  5%  5%  5%  5%  4%
[libx264 @ 0x5794271d8180] i8c dc,h,v,p: 67%  9% 19%  5%
[libx264 @ 0x5794271d8180] Weighted P-Frames: Y:19.5% UV:18.6%
[libx264 @ 0x5794271d8180] ref P L0: 57.3% 20.2% 11.9%  9.4%  1.2%
[libx264 @ 0x5794271d8180] ref B L0: 79.5% 15.0%  5.5%
[libx264 @ 0x5794271d8180] ref B L1: 91.8%  8.2%
[libx264 @ 0x5794271d8180] kb/s:5437.37

  0%|          | 0/207 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/key_2hz/%04d.png':
  Duration: 00:00:06.90, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5a6398e04880] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5a6398e04880] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5a6398e04880] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/key_2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  207 fps= 21 q=-1.0 Lsize=    6807kB time=00:00:06.80 bitrate=8199.9kbits/s speed=0.674x
video:6805kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.029579%
[libx264 @ 0x5a6398e04880] frame I:25    Avg QP:26.31  size: 49305
[libx264 @ 0x5a6398e04880] frame P:168   Avg QP:29.36  size: 31434
[libx264 @ 0x5a6398e04880] frame B:14    Avg QP:30.73  size: 32403
[libx264 @ 0x5a6398e04880] consecutive B-frames: 88.4%  6.8%  2.9%  1.9%
[libx264 @ 0x5a6398e04880] mb I  I16..4: 11.7% 59.6% 28.7%
[libx264 @ 0x5a6398e04880] mb P  I16..4:  9.9% 45.8% 23.2%  P16..4: 11.2%  2.0%  1.2%  0.0%  0.0%    skip: 6.7%
[libx264 @ 0x5a6398e04880] mb B  I16..4:  9.5% 15.4% 19.1%  B16..8: 10.9%  3.8%  1.5%  direct:18.2%  skip:21.5%  L0:42.4% L1:41.3% BI:16.3%
[libx264 @ 0x5a6398e04880] 8x8 transform intra:57.4% inter:82.3%
[libx264 @ 0x5a6398e04880] coded y,uvDC,uvAC intra: 70.3% 59.8% 50.2% inter: 43.1% 24.9% 5.8%
[libx264 @ 0x5a6398e04880] i16 v,h,dc,p: 38% 13% 38% 12%
[libx264 @ 0x5a6398e04880] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 39%  9% 29%  4%  3%  4%  3%  5%  4%
[libx264 @ 0x5a6398e04880] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 10% 29%  6%  5%  6%  5%  5%  4%
[libx264 @ 0x5a6398e04880] i8c dc,h,v,p: 65%  8% 21%  6%
[libx264 @ 0x5a6398e04880] Weighted P-Frames: Y:22.6% UV:14.3%
[libx264 @ 0x5a6398e04880] ref P L0: 45.3% 27.7% 15.5% 11.0%  0.5%
[libx264 @ 0x5a6398e04880] ref B L0: 69.4% 26.6%  4.0%
[libx264 @ 0x5a6398e04880] ref B L1: 99.5%  0.5%
[libx264 @ 0x5a6398e04880] kb/s:8077.91

  0%|          | 0/205 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/lamp_1:2hz/%04d.png':
  Duration: 00:00:06.83, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5979550b8fc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5979550b8fc0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5979550b8fc0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/lamp_1:2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  205 fps= 38 q=-1.0 Lsize=    2677kB time=00:00:06.73 bitrate=3256.7kbits/s speed=1.26x
video:2674kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.111796%
[libx264 @ 0x5979550b8fc0] frame I:9     Avg QP:25.77  size: 46507
[libx264 @ 0x5979550b8fc0] frame P:78    Avg QP:27.37  size: 19438
[libx264 @ 0x5979550b8fc0] frame B:118   Avg QP:28.59  size:  6802
[libx264 @ 0x5979550b8fc0] consecutive B-frames: 21.5%  2.9%  7.3% 68.3%
[libx264 @ 0x5979550b8fc0] mb I  I16..4:  8.9% 64.4% 26.7%
[libx264 @ 0x5979550b8fc0] mb P  I16..4:  9.5% 33.1% 16.8%  P16..4: 16.0%  3.6%  3.0%  0.0%  0.0%    skip:18.0%
[libx264 @ 0x5979550b8fc0] mb B  I16..4:  4.3%  1.7%  2.5%  B16..8: 25.5%  3.5%  1.6%  direct: 4.3%  skip:56.6%  L0:39.0% L1:56.6% BI: 4.4%
[libx264 @ 0x5979550b8fc0] 8x8 transform intra:51.4% inter:58.4%
[libx264 @ 0x5979550b8fc0] coded y,uvDC,uvAC intra: 58.8% 52.2% 43.3% inter: 14.8% 11.6% 3.0%
[libx264 @ 0x5979550b8fc0] i16 v,h,dc,p: 49% 19% 27%  6%
[libx264 @ 0x5979550b8fc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 42% 10% 30%  3%  2%  3%  2%  4%  3%
[libx264 @ 0x5979550b8fc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 33% 13% 30%  5%  4%  5%  4%  4%  3%
[libx264 @ 0x5979550b8fc0] i8c dc,h,v,p: 67% 10% 19%  4%
[libx264 @ 0x5979550b8fc0] Weighted P-Frames: Y:15.4% UV:12.8%
[libx264 @ 0x5979550b8fc0] ref P L0: 59.6% 20.0% 12.0%  6.6%  1.8%
[libx264 @ 0x5979550b8fc0] ref B L0: 79.9% 15.2%  4.8%
[libx264 @ 0x5979550b8fc0] ref B L1: 92.8%  7.2%
[libx264 @ 0x5979550b8fc0] kb/s:3204.69

  0%|          | 0/208 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/lamp_1hz/%04d.png':
  Duration: 00:00:06.93, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x59f6db5e4f00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x59f6db5e4f00] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x59f6db5e4f00] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/lamp_1hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  208 fps= 24 q=-1.0 Lsize=    4522kB time=00:00:06.83 bitrate=5421.5kbits/s speed=0.795x
video:4520kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.061299%
[libx264 @ 0x59f6db5e4f00] frame I:22    Avg QP:26.07  size: 57514
[libx264 @ 0x59f6db5e4f00] frame P:95    Avg QP:28.56  size: 26099
[libx264 @ 0x59f6db5e4f00] frame B:91    Avg QP:28.86  size:  9700
[libx264 @ 0x59f6db5e4f00] consecutive B-frames: 38.9%  2.9% 15.9% 42.3%
[libx264 @ 0x59f6db5e4f00] mb I  I16..4: 11.2% 54.9% 33.9%
[libx264 @ 0x59f6db5e4f00] mb P  I16..4: 12.7% 40.1% 21.1%  P16..4: 11.7%  2.3%  1.7%  0.0%  0.0%    skip:10.3%
[libx264 @ 0x59f6db5e4f00] mb B  I16..4:  6.7%  2.9%  4.2%  B16..8: 22.1%  4.1%  2.2%  direct: 7.9%  skip:49.9%  L0:35.8% L1:57.9% BI: 6.3%
[libx264 @ 0x59f6db5e4f00] 8x8 transform intra:50.4% inter:61.9%
[libx264 @ 0x59f6db5e4f00] coded y,uvDC,uvAC intra: 64.6% 57.7% 48.3% inter: 20.6% 17.1% 3.9%
[libx264 @ 0x59f6db5e4f00] i16 v,h,dc,p: 45% 19% 30%  6%
[libx264 @ 0x59f6db5e4f00] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 41% 11% 28%  3%  3%  4%  3%  4%  3%
[libx264 @ 0x59f6db5e4f00] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 12% 30%  6%  5%  5%  5%  5%  4%
[libx264 @ 0x59f6db5e4f00] i8c dc,h,v,p: 65% 11% 19%  5%
[libx264 @ 0x59f6db5e4f00] Weighted P-Frames: Y:17.9% UV:13.7%
[libx264 @ 0x59f6db5e4f00] ref P L0: 67.9% 15.4%  9.8%  6.1%  0.9%
[libx264 @ 0x59f6db5e4f00] ref B L0: 79.6% 14.4%  6.0%
[libx264 @ 0x59f6db5e4f00] ref B L1: 91.2%  8.8%
[libx264 @ 0x59f6db5e4f00] kb/s:5339.32

  0%|          | 0/220 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/lamp_2hz/%04d.png':
  Duration: 00:00:07.33, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x57ed93f09dc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x57ed93f09dc0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x57ed93f09dc0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/lamp_2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  220 fps= 22 q=-1.0 Lsize=    7386kB time=00:00:07.23 bitrate=8365.3kbits/s speed=0.724x
video:7384kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.032495%
[libx264 @ 0x57ed93f09dc0] frame I:31    Avg QP:26.52  size: 56307
[libx264 @ 0x57ed93f09dc0] frame P:151   Avg QP:29.29  size: 31788
[libx264 @ 0x57ed93f09dc0] frame B:38    Avg QP:30.22  size: 26712
[libx264 @ 0x57ed93f09dc0] consecutive B-frames: 72.3% 10.0% 12.3%  5.5%
[libx264 @ 0x57ed93f09dc0] mb I  I16..4: 13.1% 54.5% 32.5%
[libx264 @ 0x57ed93f09dc0] mb P  I16..4: 12.2% 45.4% 24.1%  P16..4:  9.7%  2.0%  1.1%  0.0%  0.0%    skip: 5.5%
[libx264 @ 0x57ed93f09dc0] mb B  I16..4:  9.7%  7.7% 15.2%  B16..8: 16.0%  5.3%  3.4%  direct:12.1%  skip:30.5%  L0:39.1% L1:48.8% BI:12.1%
[libx264 @ 0x57ed93f09dc0] 8x8 transform intra:53.0% inter:74.0%
[libx264 @ 0x57ed93f09dc0] coded y,uvDC,uvAC intra: 71.2% 59.7% 50.6% inter: 41.0% 24.6% 6.0%
[libx264 @ 0x57ed93f09dc0] i16 v,h,dc,p: 39% 16% 37%  9%
[libx264 @ 0x57ed93f09dc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 37% 12% 29%  4%  3%  4%  3%  4%  4%
[libx264 @ 0x57ed93f09dc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 11% 30%  6%  5%  6%  5%  5%  4%
[libx264 @ 0x57ed93f09dc0] i8c dc,h,v,p: 66% 10% 19%  5%
[libx264 @ 0x57ed93f09dc0] Weighted P-Frames: Y:14.6% UV:13.2%
[libx264 @ 0x57ed93f09dc0] ref P L0: 53.3% 25.1% 12.8%  8.2%  0.5%
[libx264 @ 0x57ed93f09dc0] ref B L0: 79.4% 17.3%  3.4%
[libx264 @ 0x57ed93f09dc0] ref B L1: 97.3%  2.7%
[libx264 @ 0x57ed93f09dc0] kb/s:8247.85

  0%|          | 0/207 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/repeater_1:2hz/%04d.png':
  Duration: 00:00:06.90, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x59e614bc85c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x59e614bc85c0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x59e614bc85c0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/repeater_1:2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  207 fps= 34 q=-1.0 Lsize=    2277kB time=00:00:06.80 bitrate=2743.5kbits/s speed=1.12x
video:2274kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.133671%
[libx264 @ 0x59e614bc85c0] frame I:7     Avg QP:24.85  size: 44279
[libx264 @ 0x59e614bc85c0] frame P:78    Avg QP:27.21  size: 18285
[libx264 @ 0x59e614bc85c0] frame B:122   Avg QP:28.48  size:  4852
[libx264 @ 0x59e614bc85c0] consecutive B-frames: 19.3%  3.9%  7.2% 69.6%
[libx264 @ 0x59e614bc85c0] mb I  I16..4: 10.1% 61.8% 28.2%
[libx264 @ 0x59e614bc85c0] mb P  I16..4:  9.5% 30.4% 13.9%  P16..4: 16.4%  4.0%  3.6%  0.0%  0.0%    skip:22.2%
[libx264 @ 0x59e614bc85c0] mb B  I16..4:  2.9%  1.3%  1.8%  B16..8: 26.0%  2.9%  1.2%  direct: 3.4%  skip:60.5%  L0:41.9% L1:54.2% BI: 3.9%
[libx264 @ 0x59e614bc85c0] 8x8 transform intra:52.7% inter:57.7%
[libx264 @ 0x59e614bc85c0] coded y,uvDC,uvAC intra: 59.2% 49.7% 40.6% inter: 12.7% 8.3% 2.3%
[libx264 @ 0x59e614bc85c0] i16 v,h,dc,p: 49% 17% 27%  6%
[libx264 @ 0x59e614bc85c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 39% 10% 35%  3%  2%  3%  2%  3%  3%
[libx264 @ 0x59e614bc85c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 33% 13% 31%  5%  4%  4%  4%  4%  3%
[libx264 @ 0x59e614bc85c0] i8c dc,h,v,p: 70%  9% 17%  4%
[libx264 @ 0x59e614bc85c0] Weighted P-Frames: Y:15.4% UV:15.4%
[libx264 @ 0x59e614bc85c0] ref P L0: 64.0% 17.7% 13.3%  4.8%  0.2%
[libx264 @ 0x59e614bc85c0] ref B L0: 80.3% 15.9%  3.8%
[libx264 @ 0x59e614bc85c0] ref B L1: 92.8%  7.2%
[libx264 @ 0x59e614bc85c0] kb/s:2699.32

  0%|          | 0/205 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/repeater_1hz/%04d.png':
  Duration: 00:00:06.83, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x56080277b3c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x56080277b3c0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x56080277b3c0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/repeater_1hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  205 fps= 31 q=-1.0 Lsize=    4217kB time=00:00:06.73 bitrate=5130.4kbits/s speed=1.03x
video:4214kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.064722%
[libx264 @ 0x56080277b3c0] frame I:19    Avg QP:25.95  size: 56295
[libx264 @ 0x56080277b3c0] frame P:94    Avg QP:28.50  size: 24583
[libx264 @ 0x56080277b3c0] frame B:92    Avg QP:28.79  size: 10155
[libx264 @ 0x56080277b3c0] consecutive B-frames: 37.6%  1.0% 20.5% 41.0%
[libx264 @ 0x56080277b3c0] mb I  I16..4: 10.5% 55.4% 34.1%
[libx264 @ 0x56080277b3c0] mb P  I16..4: 11.5% 40.9% 20.3%  P16..4: 12.1%  2.1%  1.7%  0.0%  0.0%    skip:11.5%
[libx264 @ 0x56080277b3c0] mb B  I16..4:  7.0%  3.9%  4.7%  B16..8: 22.1%  3.4%  1.8%  direct: 8.4%  skip:48.7%  L0:37.8% L1:56.5% BI: 5.7%
[libx264 @ 0x56080277b3c0] 8x8 transform intra:51.7% inter:62.1%
[libx264 @ 0x56080277b3c0] coded y,uvDC,uvAC intra: 63.3% 55.7% 45.8% inter: 19.9% 16.7% 3.5%
[libx264 @ 0x56080277b3c0] i16 v,h,dc,p: 48% 19% 26%  7%
[libx264 @ 0x56080277b3c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 40% 10% 31%  3%  3%  4%  3%  4%  3%
[libx264 @ 0x56080277b3c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 11% 30%  6%  5%  5%  5%  5%  4%
[libx264 @ 0x56080277b3c0] i8c dc,h,v,p: 68% 10% 18%  5%
[libx264 @ 0x56080277b3c0] Weighted P-Frames: Y:16.0% UV:14.9%
[libx264 @ 0x56080277b3c0] ref P L0: 67.6% 13.8% 10.4%  7.9%  0.2%
[libx264 @ 0x56080277b3c0] ref B L0: 75.7% 18.4%  5.9%
[libx264 @ 0x56080277b3c0] ref B L1: 91.3%  8.7%
[libx264 @ 0x56080277b3c0] kb/s:5051.31

  0%|          | 0/206 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/repeater_2hz/%04d.png':
  Duration: 00:00:06.87, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5a19b1ec9480] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5a19b1ec9480] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5a19b1ec9480] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/repeater_2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  206 fps= 18 q=-1.0 Lsize=    6695kB time=00:00:06.76 bitrate=8105.6kbits/s speed= 0.6x
video:6693kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.033982%
[libx264 @ 0x5a19b1ec9480] frame I:24    Avg QP:26.38  size: 52449
[libx264 @ 0x5a19b1ec9480] frame P:147   Avg QP:29.25  size: 31539
[libx264 @ 0x5a19b1ec9480] frame B:35    Avg QP:30.34  size: 27372
[libx264 @ 0x5a19b1ec9480] consecutive B-frames: 72.3%  9.7% 16.0%  1.9%
[libx264 @ 0x5a19b1ec9480] mb I  I16..4: 11.7% 57.4% 30.9%
[libx264 @ 0x5a19b1ec9480] mb P  I16..4: 12.0% 44.9% 24.1%  P16..4: 11.0%  1.8%  1.2%  0.0%  0.0%    skip: 4.9%
[libx264 @ 0x5a19b1ec9480] mb B  I16..4: 10.1%  8.1% 14.7%  B16..8: 16.2%  4.9%  2.9%  direct:12.1%  skip:31.1%  L0:41.7% L1:46.4% BI:11.9%
[libx264 @ 0x5a19b1ec9480] 8x8 transform intra:53.4% inter:76.7%
[libx264 @ 0x5a19b1ec9480] coded y,uvDC,uvAC intra: 70.2% 59.5% 50.2% inter: 41.6% 25.4% 5.3%
[libx264 @ 0x5a19b1ec9480] i16 v,h,dc,p: 38% 15% 37%  9%
[libx264 @ 0x5a19b1ec9480] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 38% 10% 29%  4%  3%  4%  3%  4%  4%
[libx264 @ 0x5a19b1ec9480] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 11% 29%  6%  5%  5%  5%  5%  4%
[libx264 @ 0x5a19b1ec9480] i8c dc,h,v,p: 66% 10% 19%  5%
[libx264 @ 0x5a19b1ec9480] Weighted P-Frames: Y:12.2% UV:10.2%
[libx264 @ 0x5a19b1ec9480] ref P L0: 51.3% 25.6% 10.4% 12.2%  0.5%
[libx264 @ 0x5a19b1ec9480] ref B L0: 77.6% 16.7%  5.7%
[libx264 @ 0x5a19b1ec9480] ref B L1: 99.9%  0.1%
[libx264 @ 0x5a19b1ec9480] kb/s:7984.09

  0%|          | 0/203 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/soap_1:2hz/%04d.png':
  Duration: 00:00:06.77, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5b4b7cb40300] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5b4b7cb40300] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5b4b7cb40300] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/soap_1:2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  203 fps= 39 q=-1.0 Lsize=    2545kB time=00:00:06.66 bitrate=3127.2kbits/s speed=1.28x
video:2542kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.117444%
[libx264 @ 0x5b4b7cb40300] frame I:9     Avg QP:25.29  size: 42057
[libx264 @ 0x5b4b7cb40300] frame P:75    Avg QP:26.96  size: 19701
[libx264 @ 0x5b4b7cb40300] frame B:119   Avg QP:28.58  size:  6271
[libx264 @ 0x5b4b7cb40300] consecutive B-frames: 20.2%  2.0%  8.9% 69.0%
[libx264 @ 0x5b4b7cb40300] mb I  I16..4: 11.0% 58.9% 30.1%
[libx264 @ 0x5b4b7cb40300] mb P  I16..4:  9.7% 33.8% 15.7%  P16..4: 14.8%  2.7%  2.1%  0.0%  0.0%    skip:21.2%
[libx264 @ 0x5b4b7cb40300] mb B  I16..4:  3.2%  1.4%  2.3%  B16..8: 19.9%  2.1%  1.0%  direct: 4.0%  skip:66.1%  L0:38.7% L1:56.6% BI: 4.6%
[libx264 @ 0x5b4b7cb40300] 8x8 transform intra:52.4% inter:66.4%
[libx264 @ 0x5b4b7cb40300] coded y,uvDC,uvAC intra: 59.0% 52.2% 42.3% inter: 12.3% 8.8% 1.9%
[libx264 @ 0x5b4b7cb40300] i16 v,h,dc,p: 48% 16% 29%  6%
[libx264 @ 0x5b4b7cb40300] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 41% 10% 32%  3%  2%  3%  2%  3%  3%
[libx264 @ 0x5b4b7cb40300] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 33% 11% 30%  5%  4%  5%  4%  4%  3%
[libx264 @ 0x5b4b7cb40300] i8c dc,h,v,p: 69%  9% 19%  4%
[libx264 @ 0x5b4b7cb40300] Weighted P-Frames: Y:24.0% UV:16.0%
[libx264 @ 0x5b4b7cb40300] ref P L0: 56.6% 23.2% 14.1%  5.2%  1.0%
[libx264 @ 0x5b4b7cb40300] ref B L0: 82.5% 15.3%  2.2%
[libx264 @ 0x5b4b7cb40300] ref B L1: 93.0%  7.0%
[libx264 @ 0x5b4b7cb40300] kb/s:3076.56

  0%|          | 0/206 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/soap_1hz/%04d.png':
  Duration: 00:00:06.87, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x55eb69c01580] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55eb69c01580] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x55eb69c01580] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/soap_1hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  206 fps= 21 q=-1.0 Lsize=    4902kB time=00:00:06.76 bitrate=5934.9kbits/s speed=0.698x
video:4900kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.054392%
[libx264 @ 0x55eb69c01580] frame I:20    Avg QP:25.88  size: 56419
[libx264 @ 0x55eb69c01580] frame P:112   Avg QP:28.71  size: 26738
[libx264 @ 0x55eb69c01580] frame B:74    Avg QP:29.33  size: 12074
[libx264 @ 0x55eb69c01580] consecutive B-frames: 48.1% 10.7%  4.4% 36.9%
[libx264 @ 0x55eb69c01580] mb I  I16..4: 14.7% 56.5% 28.8%
[libx264 @ 0x55eb69c01580] mb P  I16..4: 12.5% 40.4% 21.2%  P16..4: 12.4%  2.2%  1.6%  0.0%  0.0%    skip: 9.7%
[libx264 @ 0x55eb69c01580] mb B  I16..4:  6.9%  3.8%  5.4%  B16..8: 20.4%  3.8%  2.4%  direct: 8.0%  skip:49.2%  L0:39.2% L1:54.7% BI: 6.1%
[libx264 @ 0x55eb69c01580] 8x8 transform intra:51.6% inter:63.0%
[libx264 @ 0x55eb69c01580] coded y,uvDC,uvAC intra: 65.7% 57.7% 47.5% inter: 22.9% 18.6% 3.9%
[libx264 @ 0x55eb69c01580] i16 v,h,dc,p: 38% 16% 37%  8%
[libx264 @ 0x55eb69c01580] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 41% 10% 30%  3%  3%  4%  3%  4%  3%
[libx264 @ 0x55eb69c01580] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 33% 11% 29%  6%  4%  5%  4%  5%  4%
[libx264 @ 0x55eb69c01580] i8c dc,h,v,p: 66%  9% 20%  5%
[libx264 @ 0x55eb69c01580] Weighted P-Frames: Y:22.3% UV:19.6%
[libx264 @ 0x55eb69c01580] ref P L0: 58.6% 19.0% 13.2%  7.9%  1.3%
[libx264 @ 0x55eb69c01580] ref B L0: 83.5% 12.7%  3.8%
[libx264 @ 0x55eb69c01580] ref B L1: 91.1%  8.9%
[libx264 @ 0x55eb69c01580] kb/s:5844.52

  0%|          | 0/207 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/soap_2hz/%04d.png':
  Duration: 00:00:06.90, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5cbaefb65580] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5cbaefb65580] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5cbaefb65580] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/soap_2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  207 fps= 22 q=-1.0 Lsize=    6490kB time=00:00:06.80 bitrate=7818.5kbits/s speed=0.721x
video:6488kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.033611%
[libx264 @ 0x5cbaefb65580] frame I:28    Avg QP:25.97  size: 47891
[libx264 @ 0x5cbaefb65580] frame P:154   Avg QP:28.92  size: 29836
[libx264 @ 0x5cbaefb65580] frame B:25    Avg QP:30.70  size: 28288
[libx264 @ 0x5cbaefb65580] consecutive B-frames: 79.7% 10.6%  5.8%  3.9%
[libx264 @ 0x5cbaefb65580] mb I  I16..4: 15.0% 54.3% 30.6%
[libx264 @ 0x5cbaefb65580] mb P  I16..4: 12.8% 46.3% 21.7%  P16..4:  9.3%  1.8%  1.0%  0.0%  0.0%    skip: 7.1%
[libx264 @ 0x5cbaefb65580] mb B  I16..4:  8.6%  8.8% 14.4%  B16..8: 15.9%  5.4%  3.1%  direct:13.8%  skip:30.0%  L0:26.4% L1:58.4% BI:15.3%
[libx264 @ 0x5cbaefb65580] 8x8 transform intra:55.3% inter:73.8%
[libx264 @ 0x5cbaefb65580] coded y,uvDC,uvAC intra: 67.9% 58.7% 49.2% inter: 36.7% 23.8% 6.5%
[libx264 @ 0x5cbaefb65580] i16 v,h,dc,p: 36% 14% 40% 10%
[libx264 @ 0x5cbaefb65580] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 39% 10% 29%  4%  3%  4%  3%  4%  4%
[libx264 @ 0x5cbaefb65580] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 11% 28%  6%  4%  5%  4%  5%  4%
[libx264 @ 0x5cbaefb65580] i8c dc,h,v,p: 65% 10% 20%  6%
[libx264 @ 0x5cbaefb65580] Weighted P-Frames: Y:17.5% UV:11.0%
[libx264 @ 0x5cbaefb65580] ref P L0: 55.0% 27.8%  8.5%  7.4%  1.3%
[libx264 @ 0x5cbaefb65580] ref B L0: 80.8% 12.4%  6.8%
[libx264 @ 0x5cbaefb65580] ref B L1: 98.8%  1.2%
[libx264 @ 0x5cbaefb65580] kb/s:7701.91

  0%|          | 0/208 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/white_1:2hz/%04d.png':
  Duration: 00:00:06.93, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x574daf9d6a80] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x574daf9d6a80] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x574daf9d6a80] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/white_1:2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  208 fps= 41 q=-1.0 Lsize=    2340kB time=00:00:06.83 bitrate=2805.7kbits/s speed=1.35x
video:2337kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.132573%
[libx264 @ 0x574daf9d6a80] frame I:8     Avg QP:25.39  size: 48790
[libx264 @ 0x574daf9d6a80] frame P:74    Avg QP:26.89  size: 19154
[libx264 @ 0x574daf9d6a80] frame B:126   Avg QP:28.35  size:  4643
[libx264 @ 0x574daf9d6a80] consecutive B-frames: 17.8%  3.8%  1.4% 76.9%
[libx264 @ 0x574daf9d6a80] mb I  I16..4:  9.5% 60.6% 29.9%
[libx264 @ 0x574daf9d6a80] mb P  I16..4: 10.2% 33.9% 15.4%  P16..4: 13.9%  2.9%  2.8%  0.0%  0.0%    skip:21.0%
[libx264 @ 0x574daf9d6a80] mb B  I16..4:  3.0%  1.4%  1.6%  B16..8: 24.2%  2.5%  1.0%  direct: 3.0%  skip:63.3%  L0:39.4% L1:57.1% BI: 3.6%
[libx264 @ 0x574daf9d6a80] 8x8 transform intra:53.3% inter:54.4%
[libx264 @ 0x574daf9d6a80] coded y,uvDC,uvAC intra: 57.1% 48.0% 39.0% inter: 11.1% 8.2% 1.9%
[libx264 @ 0x574daf9d6a80] i16 v,h,dc,p: 51% 17% 26%  5%
[libx264 @ 0x574daf9d6a80] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 41% 10% 34%  2%  2%  3%  2%  3%  2%
[libx264 @ 0x574daf9d6a80] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 11% 32%  5%  4%  5%  4%  4%  3%
[libx264 @ 0x574daf9d6a80] i8c dc,h,v,p: 71%  8% 17%  4%
[libx264 @ 0x574daf9d6a80] Weighted P-Frames: Y:14.9% UV:14.9%
[libx264 @ 0x574daf9d6a80] ref P L0: 67.6% 15.2% 13.1%  3.9%  0.2%
[libx264 @ 0x574daf9d6a80] ref B L0: 79.6% 17.7%  2.7%
[libx264 @ 0x574daf9d6a80] ref B L1: 92.7%  7.3%
[libx264 @ 0x574daf9d6a80] kb/s:2760.81

  0%|          | 0/204 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/white_1hz/%04d.png':
  Duration: 00:00:06.80, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5c7092a54880] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5c7092a54880] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5c7092a54880] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/white_1hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  204 fps= 30 q=-1.0 Lsize=    4481kB time=00:00:06.70 bitrate=5478.4kbits/s speed=0.985x
video:4478kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.060300%
[libx264 @ 0x5c7092a54880] frame I:21    Avg QP:25.80  size: 52631
[libx264 @ 0x5c7092a54880] frame P:97    Avg QP:28.52  size: 26800
[libx264 @ 0x5c7092a54880] frame B:86    Avg QP:28.86  size: 10231
[libx264 @ 0x5c7092a54880] consecutive B-frames: 41.2%  2.9% 14.7% 41.2%
[libx264 @ 0x5c7092a54880] mb I  I16..4: 11.7% 54.2% 34.1%
[libx264 @ 0x5c7092a54880] mb P  I16..4: 12.6% 40.9% 21.4%  P16..4: 11.8%  2.4%  1.8%  0.0%  0.0%    skip: 9.1%
[libx264 @ 0x5c7092a54880] mb B  I16..4:  7.2%  3.3%  4.1%  B16..8: 23.5%  4.1%  2.2%  direct: 8.3%  skip:47.4%  L0:39.3% L1:55.1% BI: 5.6%
[libx264 @ 0x5c7092a54880] 8x8 transform intra:50.7% inter:60.5%
[libx264 @ 0x5c7092a54880] coded y,uvDC,uvAC intra: 65.2% 56.0% 46.7% inter: 22.1% 16.7% 3.5%
[libx264 @ 0x5c7092a54880] i16 v,h,dc,p: 44% 18% 31%  7%
[libx264 @ 0x5c7092a54880] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 40% 10% 30%  3%  3%  4%  3%  4%  3%
[libx264 @ 0x5c7092a54880] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 11% 30%  6%  4%  5%  4%  5%  4%
[libx264 @ 0x5c7092a54880] i8c dc,h,v,p: 67%  9% 19%  5%
[libx264 @ 0x5c7092a54880] Weighted P-Frames: Y:13.4% UV:11.3%
[libx264 @ 0x5c7092a54880] ref P L0: 65.5% 15.6%  9.1%  9.5%  0.4%
[libx264 @ 0x5c7092a54880] ref B L0: 80.1% 14.8%  5.1%
[libx264 @ 0x5c7092a54880] ref B L1: 91.4%  8.6%
[libx264 @ 0x5c7092a54880] kb/s:5393.79

  0%|          | 0/201 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/white_2hz/%04d.png':
  Duration: 00:00:06.70, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5c1f1843cac0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5c1f1843cac0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5c1f1843cac0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/white_2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  201 fps= 23 q=-1.0 Lsize=    6588kB time=00:00:06.60 bitrate=8177.4kbits/s speed=0.758x
video:6586kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.034830%
[libx264 @ 0x5c1f1843cac0] frame I:31    Avg QP:26.09  size: 50185
[libx264 @ 0x5c1f1843cac0] frame P:135   Avg QP:29.26  size: 32155
[libx264 @ 0x5c1f1843cac0] frame B:35    Avg QP:30.36  size: 24192
[libx264 @ 0x5c1f1843cac0] consecutive B-frames: 71.6% 12.9%  7.5%  8.0%
[libx264 @ 0x5c1f1843cac0] mb I  I16..4: 12.1% 55.2% 32.7%
[libx264 @ 0x5c1f1843cac0] mb P  I16..4: 11.5% 44.5% 24.0%  P16..4:  9.7%  1.7%  1.3%  0.0%  0.0%    skip: 7.3%
[libx264 @ 0x5c1f1843cac0] mb B  I16..4: 11.1%  5.4% 12.3%  B16..8: 15.1%  5.7%  3.4%  direct:11.1%  skip:35.9%  L0:52.1% L1:35.9% BI:12.0%
[libx264 @ 0x5c1f1843cac0] 8x8 transform intra:53.1% inter:70.2%
[libx264 @ 0x5c1f1843cac0] coded y,uvDC,uvAC intra: 71.0% 61.2% 52.7% inter: 34.5% 26.2% 6.0%
[libx264 @ 0x5c1f1843cac0] i16 v,h,dc,p: 37% 15% 39% 10%
[libx264 @ 0x5c1f1843cac0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 38% 11% 29%  4%  3%  4%  3%  4%  4%
[libx264 @ 0x5c1f1843cac0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 11% 29%  6%  5%  5%  5%  5%  4%
[libx264 @ 0x5c1f1843cac0] i8c dc,h,v,p: 66%  9% 19%  6%
[libx264 @ 0x5c1f1843cac0] Weighted P-Frames: Y:23.0% UV:18.5%
[libx264 @ 0x5c1f1843cac0] ref P L0: 50.3% 20.9% 17.8%  9.3%  1.6%
[libx264 @ 0x5c1f1843cac0] ref B L0: 82.6% 14.9%  2.5%
[libx264 @ 0x5c1f1843cac0] ref B L1: 97.2%  2.8%
[libx264 @ 0x5c1f1843cac0] kb/s:8051.83

  0%|          | 0/206 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/cleaner_1:2hz/%04d.png':
  Duration: 00:00:06.87, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5c15931fc480] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5c15931fc480] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5c15931fc480] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/cleaner_1:2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  206 fps= 37 q=-1.0 Lsize=    2651kB time=00:00:06.76 bitrate=3209.1kbits/s speed=1.21x
video:2648kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.114078%
[libx264 @ 0x5c15931fc480] frame I:8     Avg QP:26.60  size: 59990
[libx264 @ 0x5c15931fc480] frame P:76    Avg QP:27.31  size: 19589
[libx264 @ 0x5c15931fc480] frame B:122   Avg QP:28.51  size:  6081
[libx264 @ 0x5c15931fc480] consecutive B-frames: 20.4%  1.0%  2.9% 75.7%
[libx264 @ 0x5c15931fc480] mb I  I16..4: 14.0% 54.9% 31.1%
[libx264 @ 0x5c15931fc480] mb P  I16..4:  9.5% 33.7% 16.7%  P16..4: 16.0%  4.1%  3.0%  0.0%  0.0%    skip:16.9%
[libx264 @ 0x5c15931fc480] mb B  I16..4:  3.6%  1.6%  2.1%  B16..8: 25.1%  3.5%  1.5%  direct: 3.5%  skip:59.1%  L0:42.5% L1:53.4% BI: 4.1%
[libx264 @ 0x5c15931fc480] 8x8 transform intra:51.3% inter:58.7%
[libx264 @ 0x5c15931fc480] coded y,uvDC,uvAC intra: 61.3% 52.0% 42.4% inter: 13.8% 9.8% 2.9%
[libx264 @ 0x5c15931fc480] i16 v,h,dc,p: 46% 16% 32%  6%
[libx264 @ 0x5c15931fc480] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 41%  8% 34%  3%  2%  3%  2%  3%  3%
[libx264 @ 0x5c15931fc480] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 35% 11% 30%  5%  4%  5%  4%  4%  3%
[libx264 @ 0x5c15931fc480] i8c dc,h,v,p: 68%  8% 20%  4%
[libx264 @ 0x5c15931fc480] Weighted P-Frames: Y:30.3% UV:22.4%
[libx264 @ 0x5c15931fc480] ref P L0: 55.5% 22.3% 15.8%  5.6%  0.9%
[libx264 @ 0x5c15931fc480] ref B L0: 82.4% 14.5%  3.0%
[libx264 @ 0x5c15931fc480] ref B L1: 92.1%  7.9%
[libx264 @ 0x5c15931fc480] kb/s:3157.99

  0%|          | 0/207 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/cleaner_1hz/%04d.png':
  Duration: 00:00:06.90, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5d52dba4f5c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5d52dba4f5c0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5d52dba4f5c0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/cleaner_1hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  207 fps= 28 q=-1.0 Lsize=    4832kB time=00:00:06.80 bitrate=5821.0kbits/s speed=0.929x
video:4829kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.056966%
[libx264 @ 0x5d52dba4f5c0] frame I:19    Avg QP:26.24  size: 55382
[libx264 @ 0x5d52dba4f5c0] frame P:105   Avg QP:28.69  size: 26491
[libx264 @ 0x5d52dba4f5c0] frame B:83    Avg QP:29.20  size: 13380
[libx264 @ 0x5d52dba4f5c0] consecutive B-frames: 43.0%  8.7%  5.8% 42.5%
[libx264 @ 0x5d52dba4f5c0] mb I  I16..4:  9.0% 56.1% 34.8%
[libx264 @ 0x5d52dba4f5c0] mb P  I16..4: 10.4% 41.2% 22.4%  P16..4: 11.4%  2.5%  1.6%  0.0%  0.0%    skip:10.5%
[libx264 @ 0x5d52dba4f5c0] mb B  I16..4:  6.6%  4.5%  6.5%  B16..8: 20.7%  4.2%  2.1%  direct:10.0%  skip:45.3%  L0:34.3% L1:58.5% BI: 7.2%
[libx264 @ 0x5d52dba4f5c0] 8x8 transform intra:51.8% inter:65.0%
[libx264 @ 0x5d52dba4f5c0] coded y,uvDC,uvAC intra: 65.1% 57.9% 48.2% inter: 23.7% 20.4% 4.2%
[libx264 @ 0x5d52dba4f5c0] i16 v,h,dc,p: 44% 18% 31%  8%
[libx264 @ 0x5d52dba4f5c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 41%  9% 31%  3%  3%  4%  3%  4%  3%
[libx264 @ 0x5d52dba4f5c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 10% 30%  6%  5%  5%  5%  5%  4%
[libx264 @ 0x5d52dba4f5c0] i8c dc,h,v,p: 66%  9% 20%  5%
[libx264 @ 0x5d52dba4f5c0] Weighted P-Frames: Y:20.0% UV:16.2%
[libx264 @ 0x5d52dba4f5c0] ref P L0: 56.4% 15.6% 19.4%  8.1%  0.5%
[libx264 @ 0x5d52dba4f5c0] ref B L0: 80.9% 16.6%  2.5%
[libx264 @ 0x5d52dba4f5c0] ref B L1: 91.4%  8.6%
[libx264 @ 0x5d52dba4f5c0] kb/s:5732.58

  0%|          | 0/191 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/cleaner_2hz/%04d.png':
  Duration: 00:00:06.37, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5cb0ac8ad540] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5cb0ac8ad540] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5cb0ac8ad540] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/cleaner_2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  191 fps= 17 q=-1.0 Lsize=    6675kB time=00:00:06.26 bitrate=8725.2kbits/s speed=0.573x
video:6673kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.028758%
[libx264 @ 0x5cb0ac8ad540] frame I:31    Avg QP:26.68  size: 53307
[libx264 @ 0x5cb0ac8ad540] frame P:149   Avg QP:29.46  size: 31834
[libx264 @ 0x5cb0ac8ad540] frame B:11    Avg QP:30.73  size: 39674
[libx264 @ 0x5cb0ac8ad540] consecutive B-frames: 89.5%  7.3%  3.1%  0.0%
[libx264 @ 0x5cb0ac8ad540] mb I  I16..4: 12.1% 57.0% 30.9%
[libx264 @ 0x5cb0ac8ad540] mb P  I16..4:  9.1% 43.7% 25.0%  P16..4: 11.1%  2.4%  1.3%  0.0%  0.0%    skip: 7.5%
[libx264 @ 0x5cb0ac8ad540] mb B  I16..4: 11.8% 11.2% 23.7%  B16..8: 11.9%  3.9%  1.8%  direct:15.8%  skip:20.0%  L0:52.6% L1:35.1% BI:12.3%
[libx264 @ 0x5cb0ac8ad540] 8x8 transform intra:55.3% inter:86.6%
[libx264 @ 0x5cb0ac8ad540] coded y,uvDC,uvAC intra: 70.9% 61.9% 52.7% inter: 44.5% 26.9% 5.9%
[libx264 @ 0x5cb0ac8ad540] i16 v,h,dc,p: 37% 15% 36% 11%
[libx264 @ 0x5cb0ac8ad540] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 39%  8% 29%  4%  3%  5%  3%  5%  4%
[libx264 @ 0x5cb0ac8ad540] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32%  9% 28%  6%  5%  6%  5%  5%  4%
[libx264 @ 0x5cb0ac8ad540] i8c dc,h,v,p: 65%  9% 21%  6%
[libx264 @ 0x5cb0ac8ad540] Weighted P-Frames: Y:23.5% UV:18.1%
[libx264 @ 0x5cb0ac8ad540] ref P L0: 48.2% 22.9% 17.4% 10.4%  1.1%
[libx264 @ 0x5cb0ac8ad540] ref B L0: 81.8% 16.2%  2.0%
[libx264 @ 0x5cb0ac8ad540] kb/s:8584.90

  0%|          | 0/191 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/knife_1:2hz/%04d.png':
  Duration: 00:00:06.37, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x57890771cf00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x57890771cf00] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x57890771cf00] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/knife_1:2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  191 fps= 30 q=-1.0 Lsize=    2705kB time=00:00:06.26 bitrate=3535.4kbits/s speed=0.974x
video:2702kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.103848%
[libx264 @ 0x57890771cf00] frame I:5     Avg QP:26.38  size: 57958
[libx264 @ 0x57890771cf00] frame P:81    Avg QP:27.43  size: 20256
[libx264 @ 0x57890771cf00] frame B:105   Avg QP:28.73  size:  7956
[libx264 @ 0x57890771cf00] consecutive B-frames: 24.6%  5.2%  3.1% 67.0%
[libx264 @ 0x57890771cf00] mb I  I16..4: 14.9% 56.6% 28.5%
[libx264 @ 0x57890771cf00] mb P  I16..4:  9.7% 34.4% 17.2%  P16..4: 14.9%  3.0%  2.2%  0.0%  0.0%    skip:18.5%
[libx264 @ 0x57890771cf00] mb B  I16..4:  4.3%  1.8%  3.5%  B16..8: 23.0%  2.3%  1.0%  direct: 3.3%  skip:60.6%  L0:37.0% L1:59.0% BI: 3.9%
[libx264 @ 0x57890771cf00] 8x8 transform intra:50.3% inter:65.6%
[libx264 @ 0x57890771cf00] coded y,uvDC,uvAC intra: 60.7% 53.0% 42.6% inter: 14.2% 9.8% 2.2%
[libx264 @ 0x57890771cf00] i16 v,h,dc,p: 47% 15% 33%  6%
[libx264 @ 0x57890771cf00] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 42%  8% 33%  3%  2%  3%  2%  4%  3%
[libx264 @ 0x57890771cf00] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 35% 10% 29%  5%  4%  5%  4%  5%  3%
[libx264 @ 0x57890771cf00] i8c dc,h,v,p: 67%  8% 21%  4%
[libx264 @ 0x57890771cf00] Weighted P-Frames: Y:27.2% UV:22.2%
[libx264 @ 0x57890771cf00] ref P L0: 49.1% 26.1% 17.2%  6.5%  1.0%
[libx264 @ 0x57890771cf00] ref B L0: 81.2% 15.9%  2.9%
[libx264 @ 0x57890771cf00] ref B L1: 91.7%  8.3%
[libx264 @ 0x57890771cf00] kb/s:3475.41

  0%|          | 0/205 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/knife_1hz/%04d.png':
  Duration: 00:00:06.83, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5ad756683700] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5ad756683700] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5ad756683700] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/knife_1hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  205 fps= 28 q=-1.0 Lsize=    5065kB time=00:00:06.73 bitrate=6162.5kbits/s speed=0.909x
video:5063kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.051098%
[libx264 @ 0x5ad756683700] frame I:21    Avg QP:26.08  size: 55155
[libx264 @ 0x5ad756683700] frame P:114   Avg QP:28.88  size: 27431
[libx264 @ 0x5ad756683700] frame B:70    Avg QP:29.49  size: 12830
[libx264 @ 0x5ad756683700] consecutive B-frames: 51.2%  6.8%  8.8% 33.2%
[libx264 @ 0x5ad756683700] mb I  I16..4: 11.2% 55.9% 32.9%
[libx264 @ 0x5ad756683700] mb P  I16..4: 10.7% 40.2% 22.2%  P16..4: 12.1%  2.3%  1.6%  0.0%  0.0%    skip:10.9%
[libx264 @ 0x5ad756683700] mb B  I16..4:  6.8%  2.9%  5.7%  B16..8: 20.0%  4.1%  2.6%  direct: 8.2%  skip:49.6%  L0:37.6% L1:56.6% BI: 5.8%
[libx264 @ 0x5ad756683700] 8x8 transform intra:51.7% inter:63.8%
[libx264 @ 0x5ad756683700] coded y,uvDC,uvAC intra: 68.1% 59.5% 49.6% inter: 23.0% 19.8% 4.0%
[libx264 @ 0x5ad756683700] i16 v,h,dc,p: 37% 15% 39%  9%
[libx264 @ 0x5ad756683700] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 41%  9% 30%  3%  3%  4%  3%  4%  3%
[libx264 @ 0x5ad756683700] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 34% 10% 28%  6%  4%  5%  4%  5%  3%
[libx264 @ 0x5ad756683700] i8c dc,h,v,p: 65%  8% 21%  5%
[libx264 @ 0x5ad756683700] Weighted P-Frames: Y:18.4% UV:16.7%
[libx264 @ 0x5ad756683700] ref P L0: 56.6% 16.0% 18.5%  7.0%  1.9%
[libx264 @ 0x5ad756683700] ref B L0: 80.4% 16.0%  3.6%
[libx264 @ 0x5ad756683700] ref B L1: 90.7%  9.3%
[libx264 @ 0x5ad756683700] kb/s:6068.50

  0%|          | 0/209 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/knife_2hz/%04d.png':
  Duration: 00:00:06.97, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x55a4cd1a1dc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55a4cd1a1dc0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x55a4cd1a1dc0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/knife_2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  209 fps= 19 q=-1.0 Lsize=    6941kB time=00:00:06.86 bitrate=8281.0kbits/s speed=0.639x
video:6939kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.030919%
[libx264 @ 0x55a4cd1a1dc0] frame I:26    Avg QP:26.69  size: 53087
[libx264 @ 0x55a4cd1a1dc0] frame P:164   Avg QP:29.28  size: 30635
[libx264 @ 0x55a4cd1a1dc0] frame B:19    Avg QP:31.59  size: 36873
[libx264 @ 0x55a4cd1a1dc0] consecutive B-frames: 82.8% 14.4%  2.9%  0.0%
[libx264 @ 0x55a4cd1a1dc0] mb I  I16..4: 13.5% 55.1% 31.4%
[libx264 @ 0x55a4cd1a1dc0] mb P  I16..4: 10.6% 45.9% 24.4%  P16..4: 10.7%  1.9%  1.0%  0.0%  0.0%    skip: 5.5%
[libx264 @ 0x55a4cd1a1dc0] mb B  I16..4: 15.3%  8.4% 17.5%  B16..8: 11.6%  5.8%  3.0%  direct: 9.0%  skip:29.5%  L0:63.4% L1:25.7% BI:10.9%
[libx264 @ 0x55a4cd1a1dc0] 8x8 transform intra:54.8% inter:81.8%
[libx264 @ 0x55a4cd1a1dc0] coded y,uvDC,uvAC intra: 68.8% 61.2% 52.4% inter: 43.4% 27.2% 6.2%
[libx264 @ 0x55a4cd1a1dc0] i16 v,h,dc,p: 36% 15% 40% 10%
[libx264 @ 0x55a4cd1a1dc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 41%  9% 28%  4%  3%  4%  3%  5%  4%
[libx264 @ 0x55a4cd1a1dc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 34% 10% 27%  6%  5%  6%  4%  5%  4%
[libx264 @ 0x55a4cd1a1dc0] i8c dc,h,v,p: 64%  8% 21%  6%
[libx264 @ 0x55a4cd1a1dc0] Weighted P-Frames: Y:18.9% UV:12.2%
[libx264 @ 0x55a4cd1a1dc0] ref P L0: 45.3% 28.4% 15.0% 10.5%  0.8%
[libx264 @ 0x55a4cd1a1dc0] ref B L0: 75.9% 20.9%  3.1%
[libx264 @ 0x55a4cd1a1dc0] kb/s:8158.87

  0%|          | 0/193 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/longus_1:2hz/%04d.png':
  Duration: 00:00:06.43, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5a7961be3600] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5a7961be3600] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5a7961be3600] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/longus_1:2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  193 fps= 38 q=-1.0 Lsize=    2480kB time=00:00:06.33 bitrate=3207.4kbits/s speed=1.25x
video:2477kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.115800%
[libx264 @ 0x5a7961be3600] frame I:5     Avg QP:26.94  size: 57181
[libx264 @ 0x5a7961be3600] frame P:75    Avg QP:27.34  size: 18879
[libx264 @ 0x5a7961be3600] frame B:113   Avg QP:28.61  size:  7379
[libx264 @ 0x5a7961be3600] consecutive B-frames: 21.2%  1.0%  3.1% 74.6%
[libx264 @ 0x5a7961be3600] mb I  I16..4: 13.8% 56.4% 29.8%
[libx264 @ 0x5a7961be3600] mb P  I16..4:  9.3% 35.5% 15.8%  P16..4: 15.0%  3.2%  2.3%  0.0%  0.0%    skip:19.0%
[libx264 @ 0x5a7961be3600] mb B  I16..4:  4.5%  1.9%  2.8%  B16..8: 22.7%  2.5%  1.2%  direct: 4.1%  skip:60.4%  L0:36.8% L1:58.7% BI: 4.5%
[libx264 @ 0x5a7961be3600] 8x8 transform intra:51.9% inter:63.0%
[libx264 @ 0x5a7961be3600] coded y,uvDC,uvAC intra: 60.6% 52.0% 42.0% inter: 13.3% 9.8% 2.1%
[libx264 @ 0x5a7961be3600] i16 v,h,dc,p: 47% 14% 32%  7%
[libx264 @ 0x5a7961be3600] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 42%  8% 33%  3%  2%  3%  2%  3%  3%
[libx264 @ 0x5a7961be3600] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 36% 10% 29%  5%  4%  5%  4%  4%  3%
[libx264 @ 0x5a7961be3600] i8c dc,h,v,p: 68%  8% 21%  4%
[libx264 @ 0x5a7961be3600] Weighted P-Frames: Y:26.7% UV:21.3%
[libx264 @ 0x5a7961be3600] ref P L0: 55.4% 22.6% 15.6%  5.7%  0.6%
[libx264 @ 0x5a7961be3600] ref B L0: 82.1% 14.8%  3.1%
[libx264 @ 0x5a7961be3600] ref B L1: 92.3%  7.7%
[libx264 @ 0x5a7961be3600] kb/s:3153.07

  0%|          | 0/205 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/longus_1hz/%04d.png':
  Duration: 00:00:06.83, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x583419925fc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x583419925fc0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x583419925fc0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/longus_1hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  205 fps= 21 q=-1.0 Lsize=    4981kB time=00:00:06.73 bitrate=6060.3kbits/s speed=0.681x
video:4979kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.052588%
[libx264 @ 0x583419925fc0] frame I:21    Avg QP:26.24  size: 59451
[libx264 @ 0x583419925fc0] frame P:106   Avg QP:28.84  size: 26966
[libx264 @ 0x583419925fc0] frame B:78    Avg QP:29.46  size: 12699
[libx264 @ 0x583419925fc0] consecutive B-frames: 46.3%  3.9% 14.6% 35.1%
[libx264 @ 0x583419925fc0] mb I  I16..4: 10.4% 55.3% 34.3%
[libx264 @ 0x583419925fc0] mb P  I16..4: 10.1% 39.8% 22.0%  P16..4: 13.0%  2.4%  1.8%  0.0%  0.0%    skip:10.9%
[libx264 @ 0x583419925fc0] mb B  I16..4:  7.2%  3.6%  5.5%  B16..8: 21.0%  4.1%  2.3%  direct: 9.0%  skip:47.4%  L0:37.5% L1:56.6% BI: 5.9%
[libx264 @ 0x583419925fc0] 8x8 transform intra:51.5% inter:64.2%
[libx264 @ 0x583419925fc0] coded y,uvDC,uvAC intra: 68.3% 59.1% 49.4% inter: 22.8% 19.6% 3.6%
[libx264 @ 0x583419925fc0] i16 v,h,dc,p: 38% 15% 38%  9%
[libx264 @ 0x583419925fc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 39%  9% 32%  3%  3%  4%  3%  4%  3%
[libx264 @ 0x583419925fc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 10% 29%  6%  5%  5%  4%  5%  4%
[libx264 @ 0x583419925fc0] i8c dc,h,v,p: 66%  8% 21%  5%
[libx264 @ 0x583419925fc0] Weighted P-Frames: Y:33.0% UV:28.3%
[libx264 @ 0x583419925fc0] ref P L0: 54.3% 20.0% 19.0%  5.6%  1.0%
[libx264 @ 0x583419925fc0] ref B L0: 81.1% 17.3%  1.6%
[libx264 @ 0x583419925fc0] ref B L1: 91.2%  8.8%
[libx264 @ 0x583419925fc0] kb/s:5967.69

  0%|          | 0/206 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/longus_2hz/%04d.png':
  Duration: 00:00:06.87, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x57338f6802c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x57338f6802c0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x57338f6802c0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/longus_2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  206 fps= 19 q=-1.0 Lsize=    6876kB time=00:00:06.76 bitrate=8324.3kbits/s speed=0.622x
video:6874kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.029848%
[libx264 @ 0x57338f6802c0] frame I:27    Avg QP:26.55  size: 55437
[libx264 @ 0x57338f6802c0] frame P:165   Avg QP:29.45  size: 31102
[libx264 @ 0x57338f6802c0] frame B:14    Avg QP:31.07  size: 29255
[libx264 @ 0x57338f6802c0] consecutive B-frames: 86.9% 11.7%  1.5%  0.0%
[libx264 @ 0x57338f6802c0] mb I  I16..4: 13.2% 54.2% 32.6%
[libx264 @ 0x57338f6802c0] mb P  I16..4: 10.3% 45.3% 23.8%  P16..4: 10.7%  1.9%  1.1%  0.0%  0.0%    skip: 6.9%
[libx264 @ 0x57338f6802c0] mb B  I16..4: 13.2%  8.4% 16.5%  B16..8: 13.9%  4.9%  2.3%  direct: 9.5%  skip:31.4%  L0:77.7% L1:16.8% BI: 5.5%
[libx264 @ 0x57338f6802c0] 8x8 transform intra:55.5% inter:81.5%
[libx264 @ 0x57338f6802c0] coded y,uvDC,uvAC intra: 69.3% 60.3% 51.8% inter: 40.2% 28.3% 6.6%
[libx264 @ 0x57338f6802c0] i16 v,h,dc,p: 36% 14% 39% 11%
[libx264 @ 0x57338f6802c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 41%  9% 28%  4%  3%  4%  3%  5%  4%
[libx264 @ 0x57338f6802c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 33% 10% 28%  6%  5%  6%  5%  5%  4%
[libx264 @ 0x57338f6802c0] i8c dc,h,v,p: 65%  8% 20%  6%
[libx264 @ 0x57338f6802c0] Weighted P-Frames: Y:20.0% UV:10.9%
[libx264 @ 0x57338f6802c0] ref P L0: 43.4% 28.7% 15.3% 11.6%  1.0%
[libx264 @ 0x57338f6802c0] ref B L0: 83.3% 16.7%
[libx264 @ 0x57338f6802c0] kb/s:8199.88

  0%|          | 0/195 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/nonstop_1:2hz/%04d.png':
  Duration: 00:00:06.50, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x59117ed79240] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x59117ed79240] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x59117ed79240] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/nonstop_1:2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  195 fps= 38 q=-1.0 Lsize=    2417kB time=00:00:06.40 bitrate=3093.5kbits/s speed=1.23x
video:2414kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.121894%
[libx264 @ 0x59117ed79240] frame I:6     Avg QP:25.90  size: 49003
[libx264 @ 0x59117ed79240] frame P:71    Avg QP:27.31  size: 19352
[libx264 @ 0x59117ed79240] frame B:118   Avg QP:28.56  size:  6806
[libx264 @ 0x59117ed79240] consecutive B-frames: 18.5%  2.1%  1.5% 77.9%
[libx264 @ 0x59117ed79240] mb I  I16..4: 13.5% 53.1% 33.4%
[libx264 @ 0x59117ed79240] mb P  I16..4:  9.8% 35.3% 17.2%  P16..4: 15.2%  3.4%  2.9%  0.0%  0.0%    skip:16.2%
[libx264 @ 0x59117ed79240] mb B  I16..4:  4.2%  2.1%  2.6%  B16..8: 27.0%  4.0%  1.7%  direct: 3.8%  skip:54.6%  L0:39.1% L1:56.5% BI: 4.5%
[libx264 @ 0x59117ed79240] 8x8 transform intra:50.6% inter:52.7%
[libx264 @ 0x59117ed79240] coded y,uvDC,uvAC intra: 58.1% 50.9% 41.9% inter: 13.9% 10.9% 3.3%
[libx264 @ 0x59117ed79240] i16 v,h,dc,p: 48% 17% 29%  6%
[libx264 @ 0x59117ed79240] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 41%  8% 34%  3%  2%  3%  2%  3%  2%
[libx264 @ 0x59117ed79240] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 38% 11% 29%  5%  3%  4%  3%  4%  3%
[libx264 @ 0x59117ed79240] i8c dc,h,v,p: 67%  8% 21%  4%
[libx264 @ 0x59117ed79240] Weighted P-Frames: Y:14.1% UV:9.9%
[libx264 @ 0x59117ed79240] ref P L0: 60.0% 17.5% 14.6%  7.1%  0.9%
[libx264 @ 0x59117ed79240] ref B L0: 81.1% 15.3%  3.5%
[libx264 @ 0x59117ed79240] ref B L1: 91.6%  8.4%
[libx264 @ 0x59117ed79240] kb/s:3041.39

  0%|          | 0/218 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/nonstop_1hz/%04d.png':
  Duration: 00:00:07.27, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5bb72873f940] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5bb72873f940] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5bb72873f940] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/nonstop_1hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  218 fps= 25 q=-1.0 Lsize=    4786kB time=00:00:07.16 bitrate=5470.8kbits/s speed=0.838x
video:4783kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.059718%
[libx264 @ 0x5bb72873f940] frame I:17    Avg QP:26.14  size: 54674
[libx264 @ 0x5bb72873f940] frame P:107   Avg QP:28.58  size: 26585
[libx264 @ 0x5bb72873f940] frame B:94    Avg QP:29.25  size: 11950
[libx264 @ 0x5bb72873f940] consecutive B-frames: 39.4%  4.6% 13.8% 42.2%
[libx264 @ 0x5bb72873f940] mb I  I16..4: 12.9% 55.9% 31.2%
[libx264 @ 0x5bb72873f940] mb P  I16..4: 12.1% 40.8% 22.1%  P16..4: 10.9%  2.8%  1.7%  0.0%  0.0%    skip: 9.6%
[libx264 @ 0x5bb72873f940] mb B  I16..4:  6.5%  3.3%  5.3%  B16..8: 21.0%  4.6%  2.7%  direct: 7.6%  skip:49.0%  L0:33.5% L1:59.5% BI: 7.0%
[libx264 @ 0x5bb72873f940] 8x8 transform intra:50.5% inter:60.6%
[libx264 @ 0x5bb72873f940] coded y,uvDC,uvAC intra: 64.3% 56.8% 47.5% inter: 22.0% 17.6% 4.4%
[libx264 @ 0x5bb72873f940] i16 v,h,dc,p: 42% 16% 35%  7%
[libx264 @ 0x5bb72873f940] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 42%  9% 31%  3%  3%  4%  2%  4%  3%
[libx264 @ 0x5bb72873f940] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 34% 10% 29%  5%  4%  5%  4%  5%  3%
[libx264 @ 0x5bb72873f940] i8c dc,h,v,p: 66%  8% 21%  5%
[libx264 @ 0x5bb72873f940] Weighted P-Frames: Y:15.9% UV:13.1%
[libx264 @ 0x5bb72873f940] ref P L0: 64.8% 19.1% 11.7%  4.1%  0.4%
[libx264 @ 0x5bb72873f940] ref B L0: 85.0% 13.5%  1.5%
[libx264 @ 0x5bb72873f940] ref B L1: 91.6%  8.4%
[libx264 @ 0x5bb72873f940] kb/s:5391.57

  0%|          | 0/210 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/nonstop_2hz/%04d.png':
  Duration: 00:00:07.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5930e9595f00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5930e9595f00] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5930e9595f00] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/nonstop_2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  210 fps= 21 q=-1.0 Lsize=    6719kB time=00:00:06.90 bitrate=7977.0kbits/s speed=0.697x
video:6717kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.034560%
[libx264 @ 0x5930e9595f00] frame I:24    Avg QP:26.30  size: 45458
[libx264 @ 0x5930e9595f00] frame P:151   Avg QP:29.33  size: 31727
[libx264 @ 0x5930e9595f00] frame B:35    Avg QP:30.59  size: 28438
[libx264 @ 0x5930e9595f00] consecutive B-frames: 73.3% 10.5%  8.6%  7.6%
[libx264 @ 0x5930e9595f00] mb I  I16..4: 10.6% 59.2% 30.2%
[libx264 @ 0x5930e9595f00] mb P  I16..4: 11.7% 43.8% 24.8%  P16..4: 10.9%  2.1%  1.1%  0.0%  0.0%    skip: 5.6%
[libx264 @ 0x5930e9595f00] mb B  I16..4:  9.3%  7.8% 15.8%  B16..8: 15.9%  5.6%  3.3%  direct:12.9%  skip:29.5%  L0:42.0% L1:45.6% BI:12.4%
[libx264 @ 0x5930e9595f00] 8x8 transform intra:53.0% inter:77.1%
[libx264 @ 0x5930e9595f00] coded y,uvDC,uvAC intra: 70.1% 60.4% 51.5% inter: 42.1% 25.4% 6.3%
[libx264 @ 0x5930e9595f00] i16 v,h,dc,p: 37% 14% 39% 10%
[libx264 @ 0x5930e9595f00] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 39%  9% 29%  4%  3%  4%  3%  5%  4%
[libx264 @ 0x5930e9595f00] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 33% 10% 28%  6%  5%  5%  4%  5%  4%
[libx264 @ 0x5930e9595f00] i8c dc,h,v,p: 64%  9% 21%  6%
[libx264 @ 0x5930e9595f00] Weighted P-Frames: Y:8.6% UV:7.9%
[libx264 @ 0x5930e9595f00] ref P L0: 51.4% 28.0% 11.0%  9.4%  0.2%
[libx264 @ 0x5930e9595f00] ref B L0: 80.1% 15.9%  4.0%
[libx264 @ 0x5930e9595f00] ref B L1: 98.2%  1.8%
[libx264 @ 0x5930e9595f00] kb/s:7859.57

  0%|          | 0/198 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/rexona_1:2hz/%04d.png':
  Duration: 00:00:06.60, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5b845cc14940] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5b845cc14940] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5b845cc14940] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/rexona_1:2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  198 fps= 37 q=-1.0 Lsize=    2596kB time=00:00:06.50 bitrate=3272.0kbits/s speed=1.22x
video:2593kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.112406%
[libx264 @ 0x5b845cc14940] frame I:6     Avg QP:26.50  size: 60837
[libx264 @ 0x5b845cc14940] frame P:78    Avg QP:27.29  size: 19580
[libx264 @ 0x5b845cc14940] frame B:114   Avg QP:28.48  size:  6690
[libx264 @ 0x5b845cc14940] consecutive B-frames: 22.2%  2.0%  3.0% 72.7%
[libx264 @ 0x5b845cc14940] mb I  I16..4: 14.5% 55.4% 30.1%
[libx264 @ 0x5b845cc14940] mb P  I16..4:  9.6% 34.7% 15.9%  P16..4: 16.5%  3.4%  2.7%  0.0%  0.0%    skip:17.2%
[libx264 @ 0x5b845cc14940] mb B  I16..4:  4.0%  1.8%  2.5%  B16..8: 25.1%  2.7%  1.1%  direct: 3.4%  skip:59.4%  L0:38.3% L1:58.0% BI: 3.7%
[libx264 @ 0x5b845cc14940] 8x8 transform intra:51.9% inter:61.5%
[libx264 @ 0x5b845cc14940] coded y,uvDC,uvAC intra: 60.0% 52.6% 42.3% inter: 13.6% 10.7% 2.4%
[libx264 @ 0x5b845cc14940] i16 v,h,dc,p: 44% 14% 35%  7%
[libx264 @ 0x5b845cc14940] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 43%  8% 34%  3%  2%  3%  2%  3%  2%
[libx264 @ 0x5b845cc14940] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 35% 10% 30%  5%  4%  5%  4%  4%  3%
[libx264 @ 0x5b845cc14940] i8c dc,h,v,p: 69%  7% 19%  4%
[libx264 @ 0x5b845cc14940] Weighted P-Frames: Y:28.2% UV:25.6%
[libx264 @ 0x5b845cc14940] ref P L0: 58.6% 20.0% 15.1%  5.3%  1.0%
[libx264 @ 0x5b845cc14940] ref B L0: 82.2% 15.2%  2.6%
[libx264 @ 0x5b845cc14940] ref B L1: 91.9%  8.1%
[libx264 @ 0x5b845cc14940] kb/s:3218.02

  0%|          | 0/224 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/rexona_1hz/%04d.png':
  Duration: 00:00:07.47, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5be42bdaad40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5be42bdaad40] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5be42bdaad40] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/rexona_1hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  224 fps= 22 q=-1.0 Lsize=    5450kB time=00:00:07.36 bitrate=6060.0kbits/s speed=0.713x
video:5447kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.054238%
[libx264 @ 0x5be42bdaad40] frame I:21    Avg QP:26.20  size: 57041
[libx264 @ 0x5be42bdaad40] frame P:112   Avg QP:28.69  size: 27686
[libx264 @ 0x5be42bdaad40] frame B:91    Avg QP:29.46  size: 14043
[libx264 @ 0x5be42bdaad40] consecutive B-frames: 41.1% 11.6%  8.0% 39.3%
[libx264 @ 0x5be42bdaad40] mb I  I16..4: 12.2% 54.0% 33.7%
[libx264 @ 0x5be42bdaad40] mb P  I16..4: 10.5% 41.1% 23.1%  P16..4: 12.3%  2.5%  1.8%  0.0%  0.0%    skip: 8.7%
[libx264 @ 0x5be42bdaad40] mb B  I16..4:  8.1%  3.6%  5.9%  B16..8: 19.5%  4.6%  2.7%  direct: 8.9%  skip:46.7%  L0:37.5% L1:56.4% BI: 6.1%
[libx264 @ 0x5be42bdaad40] 8x8 transform intra:50.3% inter:61.1%
[libx264 @ 0x5be42bdaad40] coded y,uvDC,uvAC intra: 67.5% 58.9% 49.5% inter: 24.2% 20.6% 4.1%
[libx264 @ 0x5be42bdaad40] i16 v,h,dc,p: 39% 17% 36%  8%
[libx264 @ 0x5be42bdaad40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 41%  9% 30%  3%  3%  4%  3%  4%  3%
[libx264 @ 0x5be42bdaad40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 31% 10% 30%  6%  5%  5%  4%  5%  4%
[libx264 @ 0x5be42bdaad40] i8c dc,h,v,p: 67%  8% 20%  5%
[libx264 @ 0x5be42bdaad40] Weighted P-Frames: Y:25.0% UV:20.5%
[libx264 @ 0x5be42bdaad40] ref P L0: 53.2% 24.2% 13.5%  7.6%  1.5%
[libx264 @ 0x5be42bdaad40] ref B L0: 81.3% 14.0%  4.6%
[libx264 @ 0x5be42bdaad40] ref B L1: 89.4% 10.6%
[libx264 @ 0x5be42bdaad40] kb/s:5974.95

  0%|          | 0/222 [00:00<?, ?it/s]

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, image2, from '/tmp/rexona_2hz/%04d.png':
  Duration: 00:00:07.40, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1038x260, 30 fps, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5b33e7d5b540] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5b33e7d5b540] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x5b33e7d5b540] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/rexona_2hz/aps_dvs_gtp.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 1038x260, q=2-31, 30 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  222 fps= 23 q=-1.0 Lsize=    7326kB time=00:00:07.30 bitrate=8221.6kbits/s speed=0.77x
video:7324kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.031107%
[libx264 @ 0x5b33e7d5b540] frame I:29    Avg QP:26.39  size: 51797
[libx264 @ 0x5b33e7d5b540] frame P:169   Avg QP:29.36  size: 31169
[libx264 @ 0x5b33e7d5b540] frame B:24    Avg QP:30.97  size: 30398
[libx264 @ 0x5b33e7d5b540] consecutive B-frames: 80.6% 13.5%  4.1%  1.8%
[libx264 @ 0x5b33e7d5b540] mb I  I16..4: 11.4% 56.3% 32.3%
[libx264 @ 0x5b33e7d5b540] mb P  I16..4: 10.6% 44.8% 24.6%  P16..4: 10.7%  1.9%  1.1%  0.0%  0.0%    skip: 6.3%
[libx264 @ 0x5b33e7d5b540] mb B  I16..4: 10.6%  7.1% 14.4%  B16..8: 14.2%  5.5%  3.4%  direct:15.4%  skip:29.2%  L0:29.7% L1:55.6% BI:14.7%
[libx264 @ 0x5b33e7d5b540] 8x8 transform intra:54.5% inter:78.1%
[libx264 @ 0x5b33e7d5b540] coded y,uvDC,uvAC intra: 70.5% 60.7% 52.3% inter: 42.4% 24.6% 6.6%
[libx264 @ 0x5b33e7d5b540] i16 v,h,dc,p: 37% 15% 38% 10%
[libx264 @ 0x5b33e7d5b540] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 40%  9% 29%  4%  3%  4%  3%  5%  4%
[libx264 @ 0x5b33e7d5b540] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 10% 28%  6%  5%  6%  5%  5%  4%
[libx264 @ 0x5b33e7d5b540] i8c dc,h,v,p: 65%  8% 21%  6%
[libx264 @ 0x5b33e7d5b540] Weighted P-Frames: Y:10.7% UV:7.1%
[libx264 @ 0x5b33e7d5b540] ref P L0: 53.3% 29.9% 10.5%  6.1%  0.3%
[libx264 @ 0x5b33e7d5b540] ref B L0: 82.1% 11.9%  6.0%
[libx264 @ 0x5b33e7d5b540] ref B L1: 99.0%  1.0%
[libx264 @ 0x5b33e7d5b540] kb/s:8107.28

In [ ]:
from google.colab import files

for seq in sequences:
    path = f'/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/flicker/{seq}/aps_dvs_gtp.mp4'
    shutil.copy(path, f'/content/{seq}.mp4')
    files.download(f'/content/{seq}.mp4')

# Complex video

In [ ]:
import cv2
import numpy as np
import os
import shutil
from tqdm import tqdm

# Directories
base = '/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/clean/bracket'
dvs_dir    = f'{base}/dvs'
gtp_dirs   = [f'{base}/augmented/gtp_{i}' for i in range(1, 11)]
gt_path    = f'{base}/groundtruth_rect.txt'
output_mp4 = f'{base}/augmented/comparison.mp4'
tmp_dir    = '/tmp/comparison'

# Load ground truth bounding boxes (x,y,w,h)
gt_boxes = []
with open(gt_path, 'r') as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        vals = line.replace(',', ' ').split()
        gt_boxes.append([int(float(v)) for v in vals[:4]])

def draw_box(img, box, color):
    x, y, w, h = box
    cv2.rectangle(img, (x, y), (x + w, y + h), color, 2)
    return img

def add_label(img, text):
    cv2.putText(img, text, (5, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)
    cv2.putText(img, text, (5, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 0), 1)
    return img

def read_img(path):
    img = cv2.imread(path)
    if img is None:
        return None
    if img.ndim == 2:
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    return img

# Get sorted frame lists
dvs_frames = sorted(os.listdir(dvs_dir))
gtp_frames = [sorted(os.listdir(d)) for d in gtp_dirs]
n = min(len(dvs_frames), *[len(f) for f in gtp_frames], len(gt_boxes))

os.makedirs(tmp_dir, exist_ok=True)

for i in tqdm(range(n)):
    box = gt_boxes[i]

    # Read DVS, draw box and label, then scale to 2x2
    dvs = read_img(f'{dvs_dir}/{dvs_frames[i]}')
    H, W = dvs.shape[:2]
    draw_box(dvs, box, color=(0, 0, 255))
    add_label(dvs, 'DVS')
    dvs_big = cv2.resize(dvs, (W * 2, H * 2))

    # Read GTP frames, draw box and label on original size
    gtps = []
    for j, d in enumerate(gtp_dirs):
        img = read_img(f'{d}/{gtp_frames[j][i]}')
        if img is None:
            img = np.zeros((H, W, 3), dtype=np.uint8)
        img = cv2.resize(img, (W, H))
        draw_box(img, box, color=(0, 255, 0))
        add_label(img, f'gtp_{j+1}')
        gtps.append(img)

    # Build grid
    empty = np.zeros((H, W, 3), dtype=np.uint8)

    right_top = np.vstack([
        np.hstack([gtps[0], gtps[1]]),
        np.hstack([gtps[2], gtps[3]])
    ])
    row_top = np.hstack([dvs_big, right_top])
    row_mid = np.hstack([gtps[4], gtps[5], gtps[6], gtps[7]])
    row_bot = np.hstack([gtps[8], gtps[9], empty, empty])

    frame = np.vstack([row_top, row_mid, row_bot])
    cv2.imwrite(f'{tmp_dir}/{i:04d}.png', frame)

# Render video
os.system(f'ffmpeg -y -framerate 30 -i {tmp_dir}/%04d.png -c:v libx264 -pix_fmt yuv420p {output_mp4}')
shutil.rmtree(tmp_dir)
print(f'Done! Video saved: {output_mp4}')

100%|██████████| 270/270 [16:44<00:00,  3.72s/it]

Done! Video saved: /content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/clean/bracket/augmented/comparison.mp4

In [ ]:
import cv2
import numpy as np
import os
import shutil
from tqdm import tqdm

def draw_box(img, box, color):
    x, y, w, h = box
    cv2.rectangle(img, (x, y), (x + w, y + h), color, 2)
    return img

def add_label(img, text):
    cv2.putText(img, text, (5, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)
    cv2.putText(img, text, (5, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 0), 1)
    return img

def read_img(path):
    img = cv2.imread(path)
    if img is None:
        return None
    if img.ndim == 2:
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    return img

initials = 'seya'
sequences = ['clamp', 'lighter', 'ruler', 'spinner', 'tag', 'traumel']

for seq in sequences:
    print(f'\nProcessing: {seq}')
    base       = f'/content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/{initials}/clean/{seq}'
    dvs_dir    = f'{base}/dvs'
    gtp_dirs   = [f'{base}/augmented/gtp_{i}' for i in range(1, 11)]
    gt_path    = f'{base}/groundtruth_rect.txt'
    output_mp4 = f'{base}/augmented/comparison.mp4'
    tmp_dir    = f'/tmp/comparison_{seq}'

    # Load ground truth bounding boxes (x,y,w,h)
    gt_boxes = []
    with open(gt_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            vals = line.replace(',', ' ').split()
            gt_boxes.append([int(float(v)) for v in vals[:4]])

    # Get sorted frame lists
    dvs_frames = sorted(os.listdir(dvs_dir))
    gtp_frames = [sorted(os.listdir(d)) for d in gtp_dirs]
    n = min(len(dvs_frames), *[len(f) for f in gtp_frames], len(gt_boxes))

    os.makedirs(tmp_dir, exist_ok=True)

    for i in tqdm(range(n), desc=seq):
        box = gt_boxes[i]

        # Read DVS, draw box and label, then scale to 2x2
        dvs = read_img(f'{dvs_dir}/{dvs_frames[i]}')
        if dvs is None:
            print(f'Warning: skipping frame {i}, DVS not readable: {dvs_frames[i]}')
            continue
        H, W = dvs.shape[:2]
        draw_box(dvs, box, color=(0, 0, 255))
        add_label(dvs, 'DVS')
        dvs_big = cv2.resize(dvs, (W * 2, H * 2))

        # Read GTP frames, draw box and label on original size
        gtps = []
        for j, d in enumerate(gtp_dirs):
            img = read_img(f'{d}/{gtp_frames[j][i]}')
            if img is None:
                img = np.zeros((H, W, 3), dtype=np.uint8)
            img = cv2.resize(img, (W, H))
            draw_box(img, box, color=(0, 255, 0))
            add_label(img, f'gtp_{j+1}')
            gtps.append(img)

        # Build grid
        empty = np.zeros((H, W, 3), dtype=np.uint8)

        right_top = np.vstack([
            np.hstack([gtps[0], gtps[1]]),
            np.hstack([gtps[2], gtps[3]])
        ])
        row_top = np.hstack([dvs_big, right_top])
        row_mid = np.hstack([gtps[4], gtps[5], gtps[6], gtps[7]])
        row_bot = np.hstack([gtps[8], gtps[9], empty, empty])

        frame = np.vstack([row_top, row_mid, row_bot])
        cv2.imwrite(f'{tmp_dir}/{i:04d}.png', frame)

    # Render video
    os.system(f'ffmpeg -y -framerate 30 -i {tmp_dir}/%04d.png -c:v libx264 -pix_fmt yuv420p {output_mp4}')
    shutil.rmtree(tmp_dir)
    print(f'Done: {output_mp4}')

Processing: clamp

clamp: 100%|██████████| 378/378 [28:45<00:00,  4.56s/it]

Done: /content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/clean/clamp/augmented/comparison.mp4

Processing: lighter

lighter: 100%|██████████| 326/326 [23:36<00:00,  4.35s/it]

Done: /content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/clean/lighter/augmented/comparison.mp4

Processing: ruler

ruler: 100%|██████████| 374/374 [26:08<00:00,  4.19s/it]

Done: /content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/clean/ruler/augmented/comparison.mp4

Processing: spinner

spinner: 100%|██████████| 360/360 [27:06<00:00,  4.52s/it]

Done: /content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/clean/spinner/augmented/comparison.mp4

Processing: tag

tag: 100%|██████████| 314/314 [26:14<00:00,  5.01s/it]

Done: /content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/clean/tag/augmented/comparison.mp4

Processing: traumel

traumel: 100%|██████████| 312/312 [25:09<00:00,  4.84s/it]

Done: /content/drive/MyDrive/Diploma_project/Datasets/Illumination_custom/seya/clean/traumel/augmented/comparison.mp4